-- Nebraska glamping web research (May 2026).
-- Skips properties already well-represented in Sage (e.g. Kimberly Creek Retreat, Slattery Vintage Estates,
-- Tallgrass Retreat / Ferncrest Elkhorn River rows).
-- discovery_source = web_research_2026_05_ne. research_status = in_progress.
-- Applied to production via Supabase migration add_nebraska_glamping_web_research_2026_05_18.

INSERT INTO public.all_glamping_properties (
  research_status,
  is_glamping_property,
  is_open,
  property_name,
  site_name,
  slug,
  property_type,
  unit_type,
  source,
  discovery_source,
  country,
  state,
  city,
  address,
  lat,
  lon,
  url,
  description,
  notes,
  date_added,
  date_updated,
  land_operator_category
) VALUES
(
  'in_progress',
  'Yes',
  'Yes',
  'Spring Ranch Campground',
  'Yurt',
  'spring-ranch-campground-fairfield-ne',
  'Glamping Resort',
  'Yurt',
  'Sage',
  'web_research_2026_05_ne',
  'United States',
  'NE',
  'Fairfield',
  '30551 Road D, Fairfield, NE 68938',
  40.432,
  -98.146,
  'https://www.springranchcampground.com/',
  $$Private glamping ranch near Fairfield on ~240 acres along the Little Blue River / Oregon Trail corridor: luxury yurts, Conestoga-style wagons with private baths, and a cabin; pond swimming, zipline, hiking, and optional chef-prepared meals (no on-site Wi-Fi per operator). Verify seasonal rates, inventory, and cell coverage notes with the host.$$,
  $$Sources: springranchcampground.com + regional directory address (May 2026 web research). Phone often listed as 402-726-2282.$$,
  '2026-05-18',
  '2026-05-18',
  'private_commercial'
),
(
  'in_progress',
  'Yes',
  'Yes',
  'Platte River State Park (Glamping Cabins)',
  'Cabin',
  'platte-river-state-park-glamping-cabins-louisville-ne',
  'Glamping',
  'Cabin',
  'Sage',
  'web_research_2026_05_ne',
  'United States',
  'NE',
  'Louisville',
  '14421 346th St, Louisville, NE 68037',
  41.039,
  -96.265,
  'https://outdoornebraska.gov/location/platte-river/',
  $$Nebraska Game and Parks glamping cabin loop at Platte River State Park between Lincoln and Omaha: small modern cabins marketed as upscale glamping with full bath, kitchenette, outdoor fire feature, and stargazing-oriented bedding (public materials cite a multi-night minimum and reservation fees). Confirm current nightly rates, pet rules, and exact cabin count via ReserveAmerica / NGPC.$$,
  $$Sources: outdoornebraska.gov Platte River location + regional news/travel summaries (May 2026 web research). Park office often listed as 402-234-2217.$$,
  '2026-05-18',
  '2026-05-18',
  'state_park'
),
(
  'in_progress',
  'Yes',
  'Yes',
  'Ashland Glamping',
  'Geodesic Dome',
  'ashland-glamping-ashland-ne',
  'Glamping Resort',
  'Geodesic Dome',
  'Sage',
  'web_research_2026_05_ne',
  'United States',
  'NE',
  'Ashland',
  '30199 E Park Hwy, Ashland, NE 68003',
  41.019,
  -96.918,
  'https://www.ashlandglamping.com/',
  $$Lakeside glamping on ~63 acres between Omaha and Lincoln: contemporary domes, safari tents, and canvas-wall tents with full kitchens, baths, climate control, patios, and outdoor fire/BBQ amenities (separate operator from nearby Kimberly Creek Retreat). Verify minimum age, pet policy, and live booking inventory on the official site.$$,
  $$Sources: ashlandglamping.com marketing pages + contact listing (May 2026 web research). Text contact sometimes listed as 402-867-1080.$$,
  '2026-05-18',
  '2026-05-18',
  'private_commercial'
);
