-- Landscape hotels similar to Ambiente Sedona (May 2026 web research).
-- Sources: Ambiente Sedona operator site, Room + Wild "25 Landscape Hotels to Visit in 2025"
--   (roomandwild.com/blog/25-landscape-hotels-to-visit-in-2025), and operator websites.
-- Skips properties already in Sage (e.g. Amangiri, Ambiente, Post Ranch Inn, Cuixmala, Fogo Island Inn).
-- discovery_source = web_research_2026_05_landscape_hotels. research_status = in_progress.

INSERT INTO public.all_glamping_properties (
  research_status,
  is_glamping_property,
  is_open,
  property_name,
  site_name,
  slug,
  property_type,
  unit_type,
  source,
  discovery_source,
  country,
  state,
  city,
  address,
  lat,
  lon,
  url,
  description,
  notes,
  date_added,
  date_updated,
  land_operator_category
) VALUES
(
  'in_progress',
  'Yes',
  'Yes',
  'Civana Carefree Resort & Spa',
  'Suite',
  'civana-carefree-resort-spa-carefree-az',
  'Landscape Hotel',
  'Suite',
  'Sage',
  'web_research_2026_05_landscape_hotels',
  'United States',
  'AZ',
  'Carefree',
  '48000 N 68th St, Carefree, AZ 85377',
  33.822,
  -111.918,
  'https://www.civanaresort.com/',
  $$Sonoran-desert wellness resort on ~20 acres in Carefree: design-forward casitas and suites with desert gardens, pools, and spa programming positioned as a nature-integrated luxury retreat (successor branding to the former Boulders Resort). Comparable to Ambiente for high-ADR desert hospitality with strong landscape and wellness positioning.$$,
  $$Sources: civanaresort.com + Room + Wild landscape hotel list (May 2026). Verify unit count, ADR, and adults-only policies with operator.$$,
  '2026-05-18',
  '2026-05-18',
  'private_commercial'
),
(
  'in_progress',
  'Yes',
  'Yes',
  'Miraval Arizona Resort & Spa',
  'Suite',
  'miraval-arizona-resort-spa-tucson-az',
  'Landscape Hotel',
  'Suite',
  'Sage',
  'web_research_2026_05_landscape_hotels',
  'United States',
  'AZ',
  'Tucson',
  '5000 E Via Este Rd, Tucson, AZ 85718',
  32.279,
  -110.872,
  'https://www.miravalresorts.com/arizona',
  $$Hyatt-owned destination wellness resort in the Catalina foothills outside Tucson: casita-style accommodations, extensive spa and mindfulness programming, and Sonoran-desert trails—landscape-forward luxury with a holistic-retreat operating model similar in guest intent to Ambiente Sedona.$$,
  $$Sources: miravalresorts.com/arizona + industry comps (May 2026 web research). Distinct from Miraval Austin / Berkshares if cataloguing siblings.$$,
  '2026-05-18',
  '2026-05-18',
  'private_commercial'
),
(
  'in_progress',
  'Yes',
  'Yes',
  'Sanctuary Camelback Mountain, A Gurney''s Resort',
  'Suite',
  'sanctuary-camelback-mountain-paradise-valley-az',
  'Landscape Hotel',
  'Suite',
  'Sage',
  'web_research_2026_05_landscape_hotels',
  'United States',
  'AZ',
  'Paradise Valley',
  '5700 E McDonald Dr, Paradise Valley, AZ 85253',
  33.516,
  -111.942,
  'https://gurneys.com/sanctuary-camelback/',
  $$Iconic Paradise Valley resort on Camelback Mountain with casitas and spa villas oriented to desert-mountain views, pools, and fine dining—luxury outdoor-hospitality positioning aligned with Arizona red-rock/desert comp set including Ambiente and Enchantment.$$,
  $$Sources: gurneys.com/sanctuary-camelback + regional press (May 2026 web research). Formerly Sanctuary on Camelback; confirm Gurney''s branding on collateral.$$,
  '2026-05-18',
  '2026-05-18',
  'private_commercial'
),
(
  'in_progress',
  'Yes',
  'Yes',
  'Amangani',
  'Suite',
  'amangani-jackson-wy',
  'Landscape Hotel',
  'Suite',
  'Sage',
  'web_research_2026_05_landscape_hotels',
  'United States',
  'WY',
  'Jackson',
  '6835 N Cache St, Jackson, WY 83001',
  43.479,
  -110.762,
  'https://www.aman.com/resorts/amangani',
  $$Aman resort on a butte above Jackson Hole with low-profile pavilions and suites framed by Teton views—benchmark landscape-integrated luxury lodge architecture (material palette, siting, and view corridors) often cited alongside Amangiri and Ambiente in design-led desert/mountain comps.$$,
  $$Sources: aman.com/resorts/amangani + Room + Wild North America landscape curation (May 2026). Sister property Amangiri already in Sage.$$,
  '2026-05-18',
  '2026-05-18',
  'private_commercial'
),
(
  'in_progress',
  'Yes',
  'Yes',
  'AWOL Kennebunkport',
  'Cabin',
  'awol-kennebunkport-me',
  'Landscape Hotel',
  'Cabin',
  'Sage',
  'web_research_2026_05_landscape_hotels',
  'United States',
  'ME',
  'Kennebunkport',
  '140 North St, Kennebunkport, ME 04043',
  43.362,
  -70.477,
  'https://www.larkhotels.com/hotels/awol-kennebunkport',
  $$Lark Hotels boutique woodland retreat minutes from Dock Square: cabin studios and suites with Japanese soaking tubs, fireplaces, and pine-birch setting—Room + Wild "Good List" landscape hotel emphasizing architecture nested in nature rather than a central lodge mass.$$,
  $$Sources: larkhotels.com/awol-kennebunkport + Room + Wild 25 Landscape Hotels (May 2026 web research).$$,
  '2026-05-18',
  '2026-05-18',
  'private_commercial'
),
(
  'in_progress',
  'Yes',
  'Yes',
  'Rancho La Puerta',
  'Casita',
  'rancho-la-puerta-tecate-mx',
  'Landscape Hotel',
  'Casita',
  'Sage',
  'web_research_2026_05_landscape_hotels',
  'Mexico',
  'Baja California',
  'Tecate',
  'Rancho La Puerta, Tecate, Baja California, Mexico',
  32.557,
  -116.628,
  'https://www.rancholapuerta.com/',
  $$Historic all-inclusive wellness eco-village at the base of Mount Kuchumaa (~4,000 acres): 87 individually designed casitas integrated into chaparral, organic gardens, and spa/wellness campus—Room + Wild landscape hotel for dispersed, nature-embedded architecture and conservation ethos comparable to Ambiente''s land-first design narrative.$$,
  $$Sources: rancholapuerta.com + Room + Wild 25 Landscape Hotels (May 2026 web research). Coordinates approximate to Tecate property.$$,
  '2026-05-18',
  '2026-05-18',
  'private_commercial'
),
(
  'in_progress',
  'Yes',
  'Yes',
  'Loire Valley Lodges',
  'Lodge',
  'loire-valley-lodges-esvres-fr',
  'Landscape Hotel',
  'Lodge',
  'Sage',
  'web_research_2026_05_landscape_hotels',
  'France',
  'Centre-Val de Loire',
  'Esvres',
  'Chem. de la Haye, 37310 Esvres, France',
  47.283,
  0.967,
  'https://www.loirevalleylodges.com/',
  $$Adults-only forest hotel on 300+ private acres near Tours: 18 artist-designed stilt lodges with floor-to-ceiling glass, private terraces, jacuzzis/saunas, and forest-bathing programming—European peer to Ambiente''s glass pavilion + landscape immersion model per Room + Wild.$$,
  $$Sources: loirevalleylodges.com + Room + Wild 25 Landscape Hotels (May 2026 web research).$$,
  '2026-05-18',
  '2026-05-18',
  'private_commercial'
),
(
  'in_progress',
  'Yes',
  'Yes',
  'The Tawny',
  'Treehouse',
  'the-tawny-consall-gb',
  'Landscape Hotel',
  'Treehouse',
  'Sage',
  'web_research_2026_05_landscape_hotels',
  'United Kingdom',
  'Staffordshire',
  'Consall',
  'Consall Forge, Consall, Staffordshire ST9 0AF, United Kingdom',
  53.003,
  -2.196,
  'https://www.thetawny.co.uk/',
  $$Destination landscape hotel on ~70 acres of Staffordshire lakes and woodland: Wildwood Huts, Hillside Treehouses, Glade Huts, and Boathouses with outdoor spa baths—Room + Wild feature property for scattered, view-oriented accommodations integrated into rolling countryside.$$,
  $$Sources: thetawny.co.uk + Room + Wild 25 Landscape Hotels (May 2026 web research).$$,
  '2026-05-18',
  '2026-05-18',
  'private_commercial'
),
(
  'in_progress',
  'Yes',
  'Yes',
  'Oasyhotel',
  'Lodge',
  'oasyhotel-san-marcello-piteglio-it',
  'Landscape Hotel',
  'Lodge',
  'Sage',
  'web_research_2026_05_landscape_hotels',
  'Italy',
  'Tuscany',
  'San Marcello Piteglio',
  'Via Ximenes 662, 51028 San Marcello Piteglio PT, Italy',
  44.058,
  10.844,
  'https://www.oasyhotel.com/en',
  $$Sixteen lodges inside Italy''s WWF-affiliated Oasi Dynamo Nature Reserve in the Tuscan Apennines: biophilic architecture, farm-to-table dining, and biodiversity conservation—Room + Wild landscape hotel pairing luxury lodging with protected-habitat stewardship (parallel to Ambiente''s environmental positioning).$$,
  $$Sources: oasyhotel.com + Room + Wild 25 Landscape Hotels (May 2026 web research).$$,
  '2026-05-18',
  '2026-05-18',
  'private_commercial'
),
(
  'in_progress',
  'Yes',
  'Yes',
  'La Manigua Lodge',
  'Lodge',
  'la-manigua-lodge-la-macarena-co',
  'Landscape Hotel',
  'Lodge',
  'Sage',
  'web_research_2026_05_landscape_hotels',
  'Colombia',
  'Meta',
  'La Macarena',
  'La Macarena, Meta, Colombia (Orinoquía region)',
  2.183,
  -73.787,
  'https://www.lamanigua.com/',
  $$Remote jungle lodge on stilts in Colombia''s Orinoquía near Caño Cristales: eco-conscious elevated structures minimizing flood impact, guided river/jungle experiences, and conservation-focused hospitality per Room + Wild landscape hotel list.$$,
  $$Sources: lamanigua.com + Room + Wild 25 Landscape Hotels (May 2026 web research). Coordinates approximate to La Macarena corridor; confirm access logistics with operator.$$,
  '2026-05-18',
  '2026-05-18',
  'private_commercial'
),
(
  'in_progress',
  'Yes',
  'Yes',
  'The Newt in Somerset',
  'Room',
  'the-newt-in-somerset-castle-cary-gb',
  'Landscape Hotel',
  'Room',
  'Sage',
  'web_research_2026_05_landscape_hotels',
  'United Kingdom',
  'Somerset',
  'Castle Cary',
  'Hadspen House, Hadspen, Somerset BA7 7NG, United Kingdom',
  51.040,
  -2.420,
  'https://www.thenewtinsomerset.com/',
  $$Georgian estate hotel in Somerset with walled gardens, orchards, cyder press, and farm-to-table dining—Room + Wild landscape hotel where restored architecture and extensive grounds foreground agrarian landscape and low-profile luxury.$$,
  $$Sources: thenewtinsomerset.com + Room + Wild 25 Landscape Hotels (May 2026 web research).$$,
  '2026-05-18',
  '2026-05-18',
  'private_commercial'
),
(
  'in_progress',
  'Yes',
  'Yes',
  'Manshausen Island Resort',
  'Cabin',
  'manshausen-island-resort-steigen-no',
  'Landscape Hotel',
  'Cabin',
  'Sage',
  'web_research_2026_05_landscape_hotels',
  'Norway',
  'Nordland',
  'Steigen',
  'Manshausen, 8294 Steigen, Norway',
  67.982,
  15.015,
  'https://www.manshausen.com/',
  $$Polar explorer Børge Ousland''s archipelago resort in Nordland with minimalist sea cabins and Sea Towers on the Steigen coastline—Room + Wild water chapter landscape hotel with floor-to-ceiling glazing and fjord immersion comparable to Ambiente''s view-forward pavilion design.$$,
  $$Sources: manshausen.com + Room + Wild 25 Landscape Hotels (May 2026 web research).$$,
  '2026-05-18',
  '2026-05-18',
  'private_commercial'
),
(
  'in_progress',
  'Yes',
  'Yes',
  'Seehof Nature Retreat',
  'Suite',
  'seehof-nature-retreat-naz-sciaves-it',
  'Landscape Hotel',
  'Suite',
  'Sage',
  'web_research_2026_05_landscape_hotels',
  'Italy',
  'South Tyrol',
  'Naz-Sciaves',
  'Via Monte Sole 12, 39010 Naz-Sciaves BZ, Italy',
  46.750,
  11.750,
  'https://www.seehof.com/en/',
  $$Adults-only alpine wellness hotel in the Isarco Valley with lake-facing suites, PrimaVera spa (Finnish sauna on a private lake), and wood-stone architecture blending Mediterranean and Alpine landscape themes—Room + Wild sky chapter landscape retreat.$$,
  $$Sources: seehof.com + Room + Wild 25 Landscape Hotels (May 2026 web research).$$,
  '2026-05-18',
  '2026-05-18',
  'private_commercial'
),
(
  'in_progress',
  'Yes',
  'Yes',
  'Gundari',
  'Suite',
  'gundari-folegandros-gr',
  'Landscape Hotel',
  'Suite',
  'Sage',
  'web_research_2026_05_landscape_hotels',
  'Greece',
  'South Aegean',
  'Folegandros',
  'Folegandros 840 11, Greece',
  36.624,
  24.915,
  'https://www.gundari.com/',
  $$Cliffside luxury landscape hotel on Folegandros with Block722-designed suites and cave villas, subterranean spa, and Aegean views—Room + Wild feature for Cycladic siting and bioclimatic architecture integrated into rugged island topography.$$,
  $$Sources: gundari.com + Room + Wild 25 Landscape Hotels (May 2026 web research).$$,
  '2026-05-18',
  '2026-05-18',
  'private_commercial'
);
