-- Vermont glamping web research — supplemental batch (May 2026).
-- Tavily/Firecrawl pass for under-represented VT private commercial operators.
-- Skips rows already in Sage VT (Moose Meadow, Mount Snow Yurt, Lilla Rustica, Little River SP,
-- Yurt in Putney / Vermont Retreat, May 2026 batch).
-- discovery_source = web_research_2026_05_vt_2. research_status = in_progress.

-- Align existing published VT commercial rows with market-overview cohort (is_glamping_property = Yes).
UPDATE public.all_glamping_properties
SET
  is_glamping_property = 'Yes',
  land_operator_category = COALESCE(land_operator_category, 'private_commercial'),
  date_updated = '2026-05-19'
WHERE state = 'VT'
  AND research_status = 'published'
  AND (land_operator_category IS NULL OR land_operator_category = 'private_commercial')
  AND COALESCE(is_glamping_property, '') <> 'Yes';

INSERT INTO public.all_glamping_properties (
  research_status,
  is_glamping_property,
  is_open,
  property_name,
  site_name,
  slug,
  property_type,
  unit_type,
  source,
  discovery_source,
  country,
  state,
  city,
  address,
  lat,
  lon,
  url,
  description,
  notes,
  date_added,
  date_updated,
  land_operator_category,
  property_total_sites,
  quantity_of_units
) VALUES
(
  'in_progress',
  'Yes',
  'Yes',
  'Highwood Retreat',
  'East Camp',
  'highwood-retreat-east-camp-springfield-vt',
  'Glamping Resort',
  'Safari Tent',
  'Sage',
  'web_research_2026_05_vt_2',
  'United States',
  'VT',
  'Springfield',
  '237 Randall Hill Rd, Springfield, VT 05156',
  43.298,
  -72.478,
  'https://highwoodretreat.com/camps',
  $$Year-round luxury safari tent camp on 160 private acres in southern Vermont (Green Mountains foothills): hand-crafted canvas camps with plush bedding, spa robes, wood-burning stove, private deck, fire pit, and nearby composting-toilet bathhouse; seasonal cedar outdoor shower May–Oct. East Camp is one of three on-property tents (West Camp open; South Camp opening May 2026). Book via ResNexus; no in-tent cooking—cooler, kettle, and fire-pit cooking welcome.$$,
  $$Sources: highwoodretreat.com camps + contact (May 2026 Firecrawl). property_total_sites=3 safari tents.$$,
  '2026-05-19',
  '2026-05-19',
  'private_commercial',
  3,
  1
),
(
  'in_progress',
  'Yes',
  'Yes',
  'Highwood Retreat',
  'West Camp',
  'highwood-retreat-west-camp-springfield-vt',
  'Glamping Resort',
  'Safari Tent',
  'Sage',
  'web_research_2026_05_vt_2',
  'United States',
  'VT',
  'Springfield',
  '237 Randall Hill Rd, Springfield, VT 05156',
  43.298,
  -72.478,
  'https://highwoodretreat.com/camps',
  $$West Camp safari tent lofted into the treeline with en-suite composting toilet and safari-style sink, luxury linens, wood stove, private deck, fire pit, and seasonal outdoor shower (May–Oct). Same 160-acre Highwood Retreat property as East Camp; off-grid battery power with guest water service.$$,
  $$Sources: highwoodretreat.com West Camp gallery (May 2026 Firecrawl).$$,
  '2026-05-19',
  '2026-05-19',
  'private_commercial',
  3,
  1
),
(
  'in_progress',
  'Yes',
  'Yes',
  'Highwood Retreat',
  'South Camp',
  'highwood-retreat-south-camp-springfield-vt',
  'Glamping Resort',
  'Safari Tent',
  'Sage',
  'web_research_2026_05_vt_2',
  'United States',
  'VT',
  'Springfield',
  '237 Randall Hill Rd, Springfield, VT 05156',
  43.298,
  -72.478,
  'https://highwoodretreat.com/camps',
  $$Third safari tent at Highwood Retreat (South Camp) — operator listed as opening May 2026 with amenities matching East/West camps. Verify inventory and rates on ResNexus before publishing.$$,
  $$Sources: highwoodretreat.com camps page “Coming May 2026” (May 2026 Firecrawl).$$,
  '2026-05-19',
  '2026-05-19',
  'private_commercial',
  3,
  1
),
(
  'in_progress',
  'Yes',
  'Yes',
  'Stone City Treehouse',
  'The Treehouse',
  'stone-city-treehouse-hardwick-vt',
  'Glamping Resort',
  'Treehouse',
  'Sage',
  'web_research_2026_05_vt_2',
  'United States',
  'VT',
  'Hardwick',
  'Hardwick, VT 05843',
  44.501,
  -72.368,
  'https://www.stonecitytreehouse.com/treehouse-and-glamping-experiences-at-stone-city',
  $$Northern Vermont micro-retreat near Hardwick: elevated treehouse in the forest canopy with propane stove, outdoor fire pit, mini-fridge, shared modern bath access, wood-fired sauna bookings, kayaks/bikes/snowshoes, and dog-friendly policy (fee). Year-round for 2 guests; operator publishes direct booking from ~$252–$336/night inclusive.$$,
  $$Sources: stonecitytreehouse.com stays page (May 2026 Firecrawl). Phone 802-472-8024. Also lists Hipcamp/Airbnb but primary site is operator-owned.$$,
  '2026-05-19',
  '2026-05-19',
  'private_commercial',
  3,
  1
),
(
  'in_progress',
  'Yes',
  'Yes',
  'Stone City Treehouse',
  'The Pebble Tent',
  'stone-city-pebble-tent-hardwick-vt',
  'Glamping Resort',
  'Bell Tent',
  'Sage',
  'web_research_2026_05_vt_2',
  'United States',
  'VT',
  'Hardwick',
  'Hardwick, VT 05843',
  44.501,
  -72.368,
  'https://www.stonecitytreehouse.com/treehouse-and-glamping-experiences-at-stone-city',
  $$Canvas bell tent (“Pebble Tent”) on platform at Stone City — seasonal May–October glamping for up to four with shared bath/sauna access and forest-spa amenities per property standards. Published direct rates ~$173–$238/night inclusive.$$,
  $$Sources: stonecitytreehouse.com (May 2026 Firecrawl).$$,
  '2026-05-19',
  '2026-05-19',
  'private_commercial',
  3,
  1
),
(
  'in_progress',
  'Yes',
  'Yes',
  'Stone City Treehouse',
  'The Bedrock House',
  'stone-city-bedrock-house-hardwick-vt',
  'Glamping Resort',
  'Cabin',
  'Sage',
  'web_research_2026_05_vt_2',
  'United States',
  'VT',
  'Hardwick',
  'Hardwick, VT 05843',
  44.501,
  -72.368,
  'https://www.stonecitytreehouse.com/treehouse-and-glamping-experiences-at-stone-city',
  $$Streamside “Bedrock House” cabin at Stone City — cozy insulated retreat sleeping up to six on a limited inventory schedule; shares forest spa, sauna, and recreation amenities with treehouse and bell tent. From ~$420/night inclusive per operator.$$,
  $$Sources: stonecitytreehouse.com (May 2026 Firecrawl).$$,
  '2026-05-19',
  '2026-05-19',
  'private_commercial',
  3,
  1
),
(
  'in_progress',
  'Yes',
  'Yes',
  'Vermont Tree Cabin',
  'Treehouse at Walker Pond',
  'vermont-tree-cabin-treehouse-coventry-vt',
  'Glamping Resort',
  'Treehouse',
  'Sage',
  'web_research_2026_05_vt_2',
  'United States',
  'VT',
  'Coventry',
  'Coventry, VT',
  44.365,
  -72.265,
  'https://vermonttreecabin.com/treehouse-walker-pond/',
  $$Two-story treehouse on Walker Pond (Coventry): private pond views, cedar soaking tub, full kitchen, and Adirondack-style finishes; bookable alongside Osprey Cabin on the same homestead. Operator contact (802) 535-2865 / vermonttreecabin.com.$$,
  $$Sources: vermonttreecabin.com home + contact (May 2026 Firecrawl). property_total_sites=2.$$,
  '2026-05-19',
  '2026-05-19',
  'private_commercial',
  2,
  1
),
(
  'in_progress',
  'Yes',
  'Yes',
  'Vermont Tree Cabin',
  'Osprey Cabin',
  'vermont-tree-cabin-osprey-cabin-coventry-vt',
  'Glamping Resort',
  'Cabin',
  'Sage',
  'web_research_2026_05_vt_2',
  'United States',
  'VT',
  'Coventry',
  'Coventry, VT',
  44.365,
  -72.265,
  'https://vermonttreecabin.com/reservations/osprey-cabin/',
  $$Modern tiny “Osprey Cabin” with patio cedar soaking tub and contemporary kitchen/bath — companion stay to the Walker Pond treehouse at Vermont Tree Cabin property.$$,
  $$Sources: vermonttreecabin.com (May 2026 Firecrawl).$$,
  '2026-05-19',
  '2026-05-19',
  'private_commercial',
  2,
  1
),
(
  'in_progress',
  'Yes',
  'Yes',
  'Maple Mountain Homestead',
  'Cassiopeia''s Hideaway Geodome',
  'maple-mountain-homestead-geodome-milton-vt',
  'Glamping',
  'Geodesic Dome',
  'Sage',
  'web_research_2026_05_vt_2',
  'United States',
  'VT',
  'Milton',
  '26 Shotwell Rd, Milton, VT 05468',
  44.623,
  -73.132,
  'https://www.maplemountainhomestead.com/',
  $$Off-grid geodesic dome farm stay (“Cassiopeia’s Hideaway”) on a 12.5-acre regenerative homestead in Milton: wooded private setting, permaculture gardens, and farm products; book via operator site/Airbnb hub link. Single-unit glamping inventory on working farm.$$,
  $$Sources: maplemountainhomestead.com + mailing address on homestead share page (May 2026 Firecrawl).$$,
  '2026-05-19',
  '2026-05-19',
  'private_commercial',
  1,
  1
),
(
  'in_progress',
  'Yes',
  'Yes',
  'Quarry Brook',
  'Geodesic Dome',
  'quarry-brook-geodesic-dome-putney-vt',
  'Glamping',
  'Geodesic Dome',
  'Sage',
  'web_research_2026_05_vt_2',
  'United States',
  'VT',
  'Putney',
  'Putney, VT 05346',
  42.975,
  -72.522,
  'https://www.quarrybrook.com/geodesic-dome',
  $$Working-homestead glamping dome on ~20 secluded acres near Putney: furnished queen bed, wood stove, fire pit, propane cook station, sawdust-composting outhouse, trails, and abandoned quarry swimming; reservations via Hipcamp with property site quarrybrook.com. Distinct from nearby “Yurt in Putney” / Vermont Retreat row.$$,
  $$Sources: quarrybrook.com geodesic-dome + location pages (May 2026 Firecrawl). ~5 mi from downtown Putney.$$,
  '2026-05-19',
  '2026-05-19',
  'private_commercial',
  1,
  1
),
(
  'in_progress',
  'Yes',
  'Yes',
  'Treehouse Lodge',
  'Treehouse',
  'treehouse-lodge-peru-vt',
  'Glamping Resort',
  'Treehouse',
  'Sage',
  'web_research_2026_05_vt_2',
  'United States',
  'VT',
  'Peru',
  '456 Treehouse Rd, Peru, VT 05152',
  43.216,
  -72.878,
  'https://resources.sageoutdooradvisory.com/en/property/treehouse-lodge',
  $$Multi-treehouse glamping lodge in the Green Mountains (Peru, VT — town name, not country): forested retreat with multiple elevated treehouses and modern amenities per regional listings. Verify operator website/URL and unit count before publishing (public Sage property card lists phone (802) 824-3911).$$,
  $$Sources: Sage resources property card + Peru VT addressing (May 2026 Firecrawl). Confirm book-direct URL is not the Amazon Treehouse Lodge domain.$$,
  '2026-05-19',
  '2026-05-19',
  'private_commercial',
  3,
  1
);
