-- Arkansas glamping web research (May 2026).
-- Adds properties not already represented in Sage AR rows (existing in_progress rows include
-- Eureka Springs Treehouses, Shire Haven, The Compton).
-- discovery_source = web_research_2026_05_ar. research_status = in_progress.
-- Applied to production via Supabase migration add_arkansas_glamping_web_research_2026_05_18.

INSERT INTO public.all_glamping_properties (
  research_status,
  is_glamping_property,
  is_open,
  property_name,
  site_name,
  slug,
  property_type,
  unit_type,
  source,
  discovery_source,
  country,
  state,
  city,
  address,
  lat,
  lon,
  url,
  description,
  notes,
  date_added,
  date_updated,
  land_operator_category
) VALUES
(
  'in_progress',
  'Yes',
  'Yes',
  'Ouachita Wilde',
  'Safari Tent',
  'ouachita-wilde-mena-ar',
  'Glamping Resort',
  'Safari Tent',
  'Sage',
  'web_research_2026_05_ar',
  'United States',
  'AR',
  'Mena',
  '185 Polk County Road 167, Mena, AR 71953',
  34.575,
  -94.208,
  'https://www.ouachitawilde.com/',
  $$Private Ouachita Mountains glamping on wooded acreage near Mena: safari-wall tents and a separate geodome with climate control, plush bedding, private decks, and a shared luxury bathhouse (tankless hot water) per operator copy. Pet-friendly positioning cited in third-party listings; verify rates, site count, and rules on the official site.$$,
  $$Sources: ouachitawilde.com + regional directory address (May 2026 web research). Phone often listed as 479-243-8500.$$,
  '2026-05-18',
  '2026-05-18',
  'private_commercial'
),
(
  'in_progress',
  'Yes',
  'Yes',
  'Starlight Haven at Hot Springs',
  'Geodesic Dome',
  'starlight-haven-hot-springs-hot-springs-ar',
  'Glamping Resort',
  'Geodesic Dome',
  'Sage',
  'web_research_2026_05_ar',
  'United States',
  'AR',
  'Hot Springs',
  '148 Jubilee Trail, Hot Springs, AR 71913',
  34.502,
  -93.054,
  'https://www.visitstarlight.com/hot-springs/',
  $$Starlight Haven Arkansas location in the Ouachita foothills minutes from downtown Hot Springs and Hot Springs National Park: domes, treehouses, and a luxury glamping tent suite with private hot tubs, kitchenettes on select units, and clubhouse amenities per marketing site. Operator also runs a separate Weiss Lake, AL resort; use the Hot Springs URL for AR inventory.$$,
  $$Sources: visitstarlight.com Hot Springs section + Arkansas.com listing address (May 2026 web research). Phone often listed as 501-538-3394.$$,
  '2026-05-18',
  '2026-05-18',
  'private_commercial'
),
(
  'in_progress',
  'Yes',
  'Yes',
  'Eureka Yurts and Cabins',
  'Yurt',
  'eureka-yurts-and-cabins-eureka-springs-ar',
  'Glamping Resort',
  'Yurt',
  'Sage',
  'web_research_2026_05_ar',
  'United States',
  'AR',
  'Eureka Springs',
  '191 Bear Ridge Rd, Eureka Springs, AR 72631',
  36.395,
  -93.782,
  'https://eurekayurts.com/',
  $$Two large western red cedar yurts (~475 sq ft each) on 32 acres in Eureka Springs West: full kitchens, private baths, hot tubs, climate control, and oversized decks (hosts note proximity to Leatherwood bike trails and Beaver Lake). Future cabin build mentioned on operator blog; confirm live calendar and minimum-night policy.$$,
  $$Sources: eurekayurts.com + published directions address (May 2026 web research).$$,
  '2026-05-18',
  '2026-05-18',
  'private_commercial'
);
