-- The Sky Retreat at Westwater (Grand County OAO approved Dec 2021; Westwater / I-70 corridor).
-- May 2026 web research: no public booking site or operator website found; treat as proposed pipeline.
-- discovery_source = web_research_2026_05_sky_retreat_westwater

INSERT INTO public.all_glamping_properties (
  research_status,
  is_glamping_property,
  is_open,
  property_name,
  site_name,
  slug,
  property_type,
  unit_type,
  source,
  discovery_source,
  country,
  state,
  city,
  address,
  lat,
  lon,
  url,
  property_total_sites,
  description,
  notes,
  date_added,
  date_updated,
  land_operator_category,
  glamping_service_tier,
  glamping_service_tier_source,
  glamping_service_tier_notes
) VALUES (
  'in_progress',
  'Yes',
  'Proposed Development',
  'The Sky Retreat at Westwater',
  NULL,
  'sky-retreat-at-westwater-moab-ut',
  'Glamping Resort',
  'Cabin',
  'Sage',
  'web_research_2026_05_sky_retreat_westwater',
  'United States',
  'UT',
  'Moab',
  'Parcel 04-0025-0105, Section 16 T20S R25E (Westwater area, near I-70 & Westwater Canyon)',
  38.968,
  -109.138,
  'https://www.grandcountyutah.net/CivicAlerts.asp?AID=286&ARC=467',
  16,
  $$Grand County–approved off-grid astronomy retreat on a 40-acre parcel in the Westwater area (northeast Grand County, near Westwater Canyon and Interstate 70): up to 16 permanent or semi-permanent guest cabins, a communal kitchen/common building, two bathhouses, two stargazing observation areas, and two employee residences. OAO-Campground overlay approved by the County Commission 4–3 in December 2021 (applicant TBE, LLC; founders Mike Toomey & Andy Fasig). Designed for dark-sky education and outreach with minimal light pollution; ~90+ minutes from Moab, closer to Fruita, Colorado. No public reservations URL verified as of May 2026—confirm construction and opening before publishing rates.$$,
  $$Sources: Grand County Planning public hearing notice (Oct 2021, parcel 04-0025-0105); County Commission agenda Dec 7, 2021; Moab Times-Independent (Dec 30, 2021) county approval coverage. Market city Moab; physical site Westwater / I-70 corridor. Coordinates approximate (Section 16 vicinity). May 2026 Firecrawl research—no operating website or OTA listing found.$$,
  '2026-05-19',
  '2026-05-19',
  'private_commercial',
  'upscale',
  'manual',
  '16-cabin dark-sky astronomy retreat; county OAO approved 2021; remote Westwater footprint (May 2026 web research).'
);
