-- USA luxury glamping under construction / proposed (May 2026 web research).
-- discovery_source = web_research_2026_05_usa_luxury_upcoming
-- research_status = in_progress; is_open = Under Construction | Proposed Development

-- Bel Air Asheville (Cloud Dome) was filed as operating; still pre-opening per 2023–2025 entitlements press.
UPDATE public.all_glamping_properties
SET
  is_open = 'Proposed Development',
  research_status = 'in_progress',
  discovery_source = 'web_research_2026_05_usa_luxury_upcoming',
  glamping_service_tier = 'luxury',
  glamping_service_tier_source = 'manual',
  glamping_service_tier_notes = 'Bel Air Resorts Group Cloud Dome plan; $375–$875 ADR reference from Mont-Tremblant sister property (May 2026 web research).',
  description = $$Miami-based Bel Air Resorts Group proposes 89 commercial glamping units on 104 acres near Black Mountain (Cloud Dome tents, salt-water/steam/massage pods, farm, trails, pickleball). Board of Adjustments review cited in regional press; treat as proposed until construction and bookings are verified.$$,
  notes = $$Sources: Citizen Times / Modern Campground (Nov 2023–2024); prior Sage row misclassified is_open=Yes (May 2026 web research).$$,
  date_updated = '2026-05-19'
WHERE id = 11583;

INSERT INTO public.all_glamping_properties (
  research_status,
  is_glamping_property,
  is_open,
  property_name,
  site_name,
  slug,
  property_type,
  unit_type,
  source,
  discovery_source,
  country,
  state,
  city,
  address,
  lat,
  lon,
  url,
  description,
  notes,
  date_added,
  date_updated,
  land_operator_category,
  glamping_service_tier,
  glamping_service_tier_source,
  glamping_service_tier_notes
) VALUES
(
  'in_progress',
  'Yes',
  'Under Construction',
  'Entrada Moab',
  NULL,
  'entrada-moab-moab-ut',
  'Glamping Resort',
  'Safari Tent',
  'Sage',
  'web_research_2026_05_usa_luxury_upcoming',
  'United States',
  'UT',
  'Moab',
  '544-acre parcel at US-191 & UT-313 corridor (Grand County overnight accommodations overlay)',
  38.614,
  -109.552,
  'https://www.moabtimes.com/articles/county-approves-glamping-eco-resort/',
  $$Grand County–approved luxury eco-retreat on ~544 acres at the Hwy 191 / 313 junction: 16 tent sites, activity center with spa, two swimming pools, panoramic deck, trails, on-site/off-site employee housing, and a conservation easement on 136 acres. First overnight overlay approved since mid-2022; verify construction progress and opening before publishing rates.$$,
  $$Sources: Moab Times-Independent (Jan 2024 county approval); Modern Campground Utah proposal coverage (May 2026 web research). Coordinates approximate (north Moab corridor).$$,
  '2026-05-19',
  '2026-05-19',
  'private_commercial',
  'luxury',
  'manual',
  'County-approved luxury eco-resort; spa, pools, limited tent inventory (May 2026 web research).'
),
(
  'in_progress',
  'Yes',
  'Proposed Development',
  'Six Senses Camp Korongo',
  NULL,
  'six-senses-camp-korongo-kanab-ut',
  'Glamping Resort',
  'Safari Tent',
  'Sage',
  'web_research_2026_05_usa_luxury_upcoming',
  'United States',
  'UT',
  'Kanab',
  '480-acre canyon forest site near Kanab (southern Utah)',
  37.048,
  -112.526,
  'https://www.sixsenses.com/en/corporate/media-center/press-releases/2026/six-senses-camo-korongo-announcement/',
  $$IHG-signed Six Senses desert sanctuary (Canyon Global Partners): 41 luxury tented pavilions, 12 branded residences, Six Senses Spa, and nature-integrated design by Luxury Frontiers near Zion/Bryce/Grand Canyon gateways. Anticipated opening 2029; proposed pipeline only until ground-breaking is confirmed.$$,
  $$Sources: IHG / Six Senses press release (Jan 2026); Modern Campground (May 2026 web research). Coordinates approximate (Kanab area).$$,
  '2026-05-19',
  '2026-05-19',
  'private_commercial',
  'luxury',
  'manual',
  'Six Senses / IHG luxury tented pavilions + branded residences (May 2026 web research).'
),
(
  'in_progress',
  'Yes',
  'Proposed Development',
  'The Grange Campground',
  NULL,
  'the-grange-campground-napa-ca',
  'Glamping Resort',
  'Safari Tent',
  'Sage',
  'web_research_2026_05_usa_luxury_upcoming',
  'United States',
  'CA',
  'Napa',
  '12.5-acre Silverado Trail / Milliken Creek area parcel (proposed)',
  38.297,
  -122.275,
  'https://www.cbsnews.com/sanfrancisco/news/proposed-glamping-site-in-napa-sparks-debate-between-residents-developers/',
  $$Auto Camp–affiliated luxury glamping resort proposed on ~12.5 acres in Napa: up to 100 high-end camping trailers and tents, pool, and permanent support structures near Milliken Creek. Facing CEQA review and strong resident opposition over fire, traffic, and habitat; treat as proposed until entitlements and construction are verified.$$,
  $$Sources: CBS SF / ABC7 / Modern Campground (2024–2026); distinct from operating Wildhaven Lake Berryessa pipeline (May 2026 web research).$$,
  '2026-05-19',
  '2026-05-19',
  'private_commercial',
  'luxury',
  'manual',
  'Proposed Auto Camp luxury trailer/tent resort; high-end positioning in local press (May 2026 web research).'
),
(
  'in_progress',
  'Yes',
  'Proposed Development',
  'Caterpillar Hill Glampground',
  NULL,
  'caterpillar-hill-glampground-sedgwick-me',
  'Glamping Resort',
  'Geodesic Dome',
  'Sage',
  'web_research_2026_05_usa_luxury_upcoming',
  'United States',
  'ME',
  'Sedgwick',
  'Caterpillar Hill (former mini-golf / driving range parcel)',
  44.352,
  -68.616,
  'https://penobscotbaypress.com/category/islandadvantages/latestnews-islandadvantages',
  $$Deer Isle operator Caleb Scott proposes a 48-site luxury glampground on Caterpillar Hill in Sedgwick: geodesic domes, small cabins, and tent areas on a former recreation parcel. Regional coverage cites $300–$500/night positioning amid local backlash over precedent and character; verify permits and construction timeline.$$,
  $$Sources: Bangor Daily News / Penobscot Bay Press / Modern Campground Maine glamping coverage (2025–2026) (May 2026 web research).$$,
  '2026-05-19',
  '2026-05-19',
  'private_commercial',
  'luxury',
  'manual',
  'Maine luxury glampground press cites $300–$500 ADR band (May 2026 web research).'
);
