-- Kansas glamping web research (May 2026).
-- discovery_source = web_research_2026_05_ks. research_status = in_progress.
-- Applied to production via Supabase migration add_kansas_glamping_web_research_2026_05_18.

INSERT INTO public.all_glamping_properties (
  research_status,
  is_glamping_property,
  is_open,
  property_name,
  site_name,
  slug,
  property_type,
  unit_type,
  source,
  discovery_source,
  country,
  state,
  city,
  address,
  lat,
  lon,
  url,
  description,
  notes,
  date_added,
  date_updated,
  land_operator_category
) VALUES
(
  'in_progress',
  'Yes',
  'Yes',
  'Saddle Ridge Retreats',
  'Geodesic Dome',
  'saddle-ridge-retreats-lawrence-ks',
  'Glamping Resort',
  'Geodesic Dome',
  'Sage',
  'web_research_2026_05_ks',
  'United States',
  'KS',
  'Lawrence',
  '1972 E 1600 Rd, Lawrence, KS 66044',
  38.954,
  -95.238,
  'https://pinecliffresort.net/campgrounds-rv-parks/saddle-ridge-retreats',
  $$Private ranch glamping near Lawrence: furnished ~16 ft dome tents (marketing: in-unit toilet, sink, hot shower, portable A/C, generator power) plus a silo cabin; horseback riding, stocked pond fishing, trails, and farm animals on ~90 acres. Verify current inventory, rates, and booking links with the host.$$,
  $$Sources: Pine Cliff Resort / Saddle Ridge marketing page + regional listings (May 2026 web research). Phone cited on directory listings: 913-972-6212.$$,
  '2026-05-18',
  '2026-05-18',
  'private_commercial'
),
(
  'in_progress',
  'Yes',
  'Yes',
  'Eisenhower State Park (Yurts)',
  'Yurt',
  'eisenhower-state-park-yurts-osage-city-ks',
  'Glamping',
  'Yurt',
  'Sage',
  'web_research_2026_05_ks',
  'United States',
  'KS',
  'Osage City',
  NULL,
  38.436,
  -95.761,
  'https://ksoutdoors.com/State-Parks/Locations/Eisenhower/',
  $$Kansas state park yurt rentals on Melvern Lake (KDWP): reservable yurt sites such as Camp Colt and Camp Gaillard with access to tallgrass prairie, trails, and lake recreation. Confirm nightly fees, minimum stays, and which yurt(s) are offered via CampIt KS.$$,
  $$Sources: ksoutdoors.com Eisenhower State Park + KDWP yurt area pages (May 2026 web research). Coordinates approximate (park).$$,
  '2026-05-18',
  '2026-05-18',
  'state_park'
),
(
  'in_progress',
  'Yes',
  'Yes',
  'Lovewell State Park (Lookout Yurt)',
  'Yurt',
  'lovewell-state-park-lookout-yurt-courtland-ks',
  'Glamping',
  'Yurt',
  'Sage',
  'web_research_2026_05_ks',
  'United States',
  'KS',
  'Courtland',
  NULL,
  39.889,
  -97.643,
  'https://ksoutdoors.com/State-Parks/Locations/Lovewell/',
  $$Kansas state park rental yurt (Lookout Yurt / cabin-style lodging) at Lovewell Reservoir with access to boating, fishing, and trails in north-central Kansas. Verify reservation path, seasonal availability, and amenities with KDWP.$$,
  $$Sources: ksoutdoors.com Lovewell State Park + KDWP Lookout Yurt cabin page (May 2026 web research).$$,
  '2026-05-18',
  '2026-05-18',
  'state_park'
),
(
  'in_progress',
  'Yes',
  'Yes',
  'Glamping the Flint Hills (Equine Estates Rustic Ranch)',
  'Bell Tent',
  'glamping-the-flint-hills-equine-estates-junction-city-ks',
  'Glamping Resort',
  'Bell Tent',
  'Sage',
  'web_research_2026_05_ks',
  'United States',
  'KS',
  'Junction City',
  NULL,
  39.045,
  -96.831,
  'https://www.hipcamp.com/en-US/land/kansas-equine-estates-rustic-ranch-9mxhqlx8',
  $$Flint Hills ranch stay minutes from I-70: marketing lists glamping bell tents and rent-a-tents alongside RV/tent sites on ~80 acres (host-operated Hipcamp property). Confirm exact unit counts, bath facilities, and pricing on the live listing.$$,
  $$Sources: Hipcamp listing + host description (May 2026 web research). Consider replacing url with operator-owned site if one exists.$$,
  '2026-05-18',
  '2026-05-18',
  'private_commercial'
),
(
  'in_progress',
  'Yes',
  'Yes',
  'Sunset Ridge Campground (Milford State Park)',
  'Cabin',
  'sunset-ridge-campground-milford-state-park-ks',
  'Glamping',
  'Cabin',
  'Sage',
  'web_research_2026_05_ks',
  'United States',
  'KS',
  'Milford',
  NULL,
  39.179,
  -96.909,
  'https://ksoutdoors.com/State-Parks/Locations/Milford/Areas/Sunset-Ridge-Cabins-Campground/Sunset-Ridge-Campground',
  $$KDWP-operated cabins and campground at Milford Lake: marketing highlights furnished cabins (named units such as Appaloosa/Morgan in directory copy) plus RV/tent camping, lake access, and modern restrooms. Treat as in_progress until official cabin map, ADR, and glamping-specific SKUs are confirmed.$$,
  $$Sources: ksoutdoors.com Milford State Park Sunset Ridge area + regional campground summaries (May 2026 web research). Phone sometimes listed as 785-238-3014.$$,
  '2026-05-18',
  '2026-05-18',
  'state_park'
);
