-- Tin Roof Cabin Resort (Grand County OAO approved 2022; La Sal Mountains / Gateway corridor).
-- May 2026 web research: no public booking site or operator website found; treat as proposed pipeline.
-- discovery_source = web_research_2026_05_tin_roof_moab

INSERT INTO public.all_glamping_properties (
  research_status,
  is_glamping_property,
  is_open,
  property_name,
  site_name,
  slug,
  property_type,
  unit_type,
  source,
  discovery_source,
  country,
  state,
  city,
  address,
  lat,
  lon,
  url,
  property_total_sites,
  description,
  notes,
  date_added,
  date_updated,
  land_operator_category,
  glamping_service_tier,
  glamping_service_tier_source,
  glamping_service_tier_notes
) VALUES (
  'in_progress',
  'Yes',
  'Proposed Development',
  'Tin Roof Cabin Resort',
  NULL,
  'tin-roof-cabin-resort-moab-ut',
  'Glamping Resort',
  'Cabin',
  'Sage',
  'web_research_2026_05_tin_roof_moab',
  'United States',
  'UT',
  'Moab',
  '7495 E Gateway Rd, Parcel 04-0025-0059 (La Sal Mountains, ~1 mi NNW of Hidden Lake)',
  38.6965,
  -109.3502,
  'https://www.grandcountyutah.net/CivicAlerts.asp?AID=310&ARC=519',
  12,
  $$Grand County–approved seasonal cabin resort on 17.25 acres within the 373-acre Taylor Ranch (La Sal Mountains northeast of Moab): 12 rustic territorial-design guest cabins (~336 sq ft each with bed, bath, kitchenette, and covered porch), grid-tied solar, hauled potable water, and engineered septic. Remote OAO-Campground overlay approved by the County Commission (4–2) after February 2022 hearings; designed for La Sal recreation away from Moab crowds. No public reservations URL verified as of May 2026—confirm construction and opening before publishing rates.$$,
  $$Sources: Grand County Planning staff report & Civic Alert (Feb 2022, parcel 04-0025-0059, owner Jick Taylor / rep Tim Keogh); Moab Times-Independent Entrada Moab coverage noting 12-unit approval (Jan 2024). Market city Moab; physical access via Gateway / Castle Valley (Hwy 128). Coordinates approximate (Hidden Lake area). May 2026 Firecrawl research—no operating website or OTA listing found.$$,
  '2026-05-19',
  '2026-05-19',
  'private_commercial',
  'midscale',
  'manual',
  '12 seasonal rustic cabins; county OAO approved 2022; remote La Sal footprint (May 2026 web research).'
);
