-- Nevada glamping web research (May 2026).
-- Skips properties already in Sage for NV (e.g. Mustang Monument, Vegas Glamping, Lake Mead RV Village,
-- Retreat on Charleston Peak, Sandy Valley Ranch).
-- discovery_source = web_research_2026_05_nv. research_status = in_progress.
-- Applied to production via Supabase migration add_nevada_glamping_web_research_2026_05_18.

INSERT INTO public.all_glamping_properties (
  research_status,
  is_glamping_property,
  is_open,
  property_name,
  site_name,
  slug,
  property_type,
  unit_type,
  source,
  discovery_source,
  country,
  state,
  city,
  address,
  lat,
  lon,
  url,
  description,
  notes,
  date_added,
  date_updated,
  land_operator_category
) VALUES
(
  'in_progress',
  'Yes',
  'Yes',
  'Ruby 360 Lodge (Yurts)',
  'Yurt',
  'ruby-360-lodge-yurts-lamoille-nv',
  'Glamping Resort',
  'Yurt',
  'Sage',
  'web_research_2026_05_nv',
  'United States',
  'NV',
  'Lamoille',
  '301 N Mountain View Dr, Lamoille, NV 89828',
  40.725,
  -115.903,
  'https://ruby360lodge.com/yurts/',
  $$Ruby Mountains all-inclusive lodge also books two furnished yurt experiences: a drive-access yurt near Conrad Creek (~7,000 ft) and a high-alpine yurt requiring a strenuous hike (~10,000 ft ridge), each with solar power, kitchen, and fireplace per operator copy. Often packaged with lodge dining/adventures; verify nightly yurt rates vs. packages, access rules, and seasonal closures.$$,
  $$Sources: ruby360lodge.com yurts page + Travel Nevada listings (May 2026 web research). Phone often listed as 775-753-6867.$$,
  '2026-05-18',
  '2026-05-18',
  'private_commercial'
),
(
  'in_progress',
  'Yes',
  'Yes',
  'Schellraiser',
  'Bell Tent',
  'schellraiser-glamping-mcgill-nv',
  'Glamping Resort',
  'Bell Tent',
  'Sage',
  'web_research_2026_05_nv',
  'United States',
  'NV',
  'McGill',
  NULL,
  38.059,
  -114.782,
  'https://www.schellraiser.com/',
  $$Private ~80-acre campground near Ely / McGill marketing furnished solar bell tents (13 ft and 16 ft layouts), plus small A-frame cabin inventory (Fort Lulu), shared shower/restroom amenities, and dark-sky positioning; also hosts the annual Schellraiser festival. Confirm public booking calendar, exact driving directions, and winter access.$$,
  $$Sources: schellraiser.com product pages + Ely area visitor coverage (May 2026 web research).$$,
  '2026-05-18',
  '2026-05-18',
  'private_commercial'
),
(
  'in_progress',
  'Yes',
  'Yes',
  'Walker River Resort',
  'Cabin',
  'walker-river-resort-smith-valley-nv',
  'Glamping Resort',
  'Cabin',
  'Sage',
  'web_research_2026_05_nv',
  'United States',
  'NV',
  'Smith Valley',
  '700 Hudson Way, Smith Valley, NV 89430',
  38.768,
  -119.373,
  'https://wrresort.com/',
  $$Ranch-style resort on the West Walker River (historic Hudson townsite): furnished river-area cottages with full kitchens, A/C, and patios plus large RV park, pool/hot tub, sporting clays, OHV access, and fly fishing. Two-night minimum commonly cited for RV; verify cottage policies, rates, and office hours.$$,
  $$Sources: wrresort.com + contact listings (May 2026 web research). Phone often listed as 775-465-2573.$$,
  '2026-05-18',
  '2026-05-18',
  'private_commercial'
);
