-- Haven Yurts (Fredericksburg TX): 4 Guesty yurt inventory rows.
-- Sources: havenyurts.com/yurts, porchlighthospitality.com/haven-yurts, Guesty bookings (May 2026).
-- Enriches stub row id 11570 (property_id 3d46b9f5-61ab-4ea3-9f17-f16425f71e74) + 3 sibling rows.
-- discovery_source = web_research_havenyurts_guesty_2026_05

UPDATE public.all_glamping_properties SET
  property_id = '3d46b9f5-61ab-4ea3-9f17-f16425f71e74'::uuid,
  site_name = 'Pinot Noir',
  slug = 'haven-yurts-fredericksburg-tx',
  property_type = 'Glamping',
  unit_type = 'Yurt',
  source = 'Sage',
  discovery_source = 'web_research_havenyurts_guesty_2026_05',
  country = 'United States',
  address = '11594 E US Highway 290',
  zip_code = '78624',
  lat = 30.22348,
  lon = -98.78221,
  url = 'https://www.havenyurts.com/yurts',
  phone_number = '+1-833-428-4371',
  research_status = 'in_progress',
  is_glamping_property = 'Yes',
  is_open = 'Yes',
  property_total_sites = 4,
  quantity_of_units = 1,
  unit_capacity = '2',
  unit_sq_ft = 490,
  unit_bed = '1 King',
  unit_wifi = 'Yes',
  unit_pets = 'No',
  unit_shower = 'Yes',
  unit_private_bathroom = 'Yes',
  unit_kitchenette = 'Yes',
  unit_mini_fridge = 'Yes',
  unit_air_conditioning = 'Yes',
  unit_gas_fireplace = 'Yes',
  unit_patio = 'Yes',
  unit_campfires = 'Yes',
  property_family_friendly = 'No',
  property_remote_work_friendly = 'Yes',
  setting_field = 'Yes',
  setting_farm = 'Yes',
  activities_scenic_drives = 'Yes',
  activities_hiking = 'Yes',
  activities_wildlife_watching = 'Yes',
  land_operator_category = 'private_commercial',
  glamping_service_tier = 'luxury',
  date_updated = '2026-05-20',
  description = $$Haven Yurts — four custom luxury yurts on a private gated property along US-290 in Texas Wine Country near Fredericksburg (havenyurts.com / Porch Light Hospitality). Each 490 sq ft yurt sleeps 2 with king bed, stargazing dome, walk-in shower, kitchenette, electric fireplace, and smart TV; shared outdoor fire pit, grill, and covered patio. Book individually or reserve all four for up to 8 guests.$$,
  unit_description = $$Pinot Noir (Yurt #1): modern olive/black tones, stargazing dome, king bed, private bath, kitchenette, electric fireplace. Guesty: 6488ad9511e9b2003790fe44.$$,
  notes = COALESCE(notes, '') || E'\n\nGuesty enrichment (May 2026): 4 wine-named yurts. Sample 2026-06-15→16: $85 fees ($75 cleaning + $10 processing), ~$22 tax; base nightly re-quote in Guesty. 4-yurt bundle from ~$735/night on calendar search. No pets per house rules.',
  amenities_raw = 'Stargazing dome; king bed; high-end linens; A/C & heat; Wi-Fi; smart TV; electric fireplace; kitchenette; Caliche Coffee; walk-in shower; spa robes; Public Goods bath products; shared propane fire pit & grill.'
WHERE id = 11570;

INSERT INTO public.all_glamping_properties (
  property_id, research_status, is_glamping_property, is_open,
  property_name, site_name, slug, property_type, unit_type,
  source, discovery_source, country, state, city,
  address, zip_code, lat, lon, url, phone_number,
  description, unit_description, notes,
  date_added, date_updated, land_operator_category,
  property_total_sites, quantity_of_units, unit_capacity, unit_sq_ft, unit_bed,
  unit_wifi, unit_pets, unit_shower, unit_private_bathroom,
  unit_kitchenette, unit_mini_fridge, unit_air_conditioning, unit_gas_fireplace, unit_patio, unit_campfires,
  property_family_friendly, property_remote_work_friendly,
  setting_field, setting_farm, activities_scenic_drives, activities_hiking, activities_wildlife_watching,
  glamping_service_tier, amenities_raw
) VALUES
(
  '3d46b9f5-61ab-4ea3-9f17-f16425f71e74'::uuid,
  'in_progress', 'Yes', 'Yes',
  'Haven Yurts', 'Malbec',
  'haven-yurts-fredericksburg-tx', 'Glamping', 'Yurt',
  'Sage', 'web_research_havenyurts_guesty_2026_05', 'United States', 'TX', 'Fredericksburg',
  '11594 E US Highway 290', '78624', 30.22348, -98.78221,
  'https://porchlighthospitality.guestybookings.com/properties/6488ae8e8385340043398e3a?propertyType=YURT',
  '+1-833-428-4371',
  $$Sibling site — Haven Yurts (Fredericksburg TX). See anchor row id 11570 (Pinot Noir).$$,
  $$Malbec (Yurt #2): organic neutral hues with hunter green accents; king bed, stargazing dome, walk-in shower, kitchenette, fireplace.$$,
  $$Guesty 6488ae8e8385340043398e3a; re-quote ADR in engine.$$,
  '2026-05-20', '2026-05-20', 'private_commercial',
  4, 1, '2', 490, '1 King',
  'Yes', 'No', 'Yes', 'Yes',
  'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes',
  'No', 'Yes',
  'Yes', 'Yes', 'Yes', 'Yes', 'Yes',
  'luxury', 'Stargazing dome; king bed; kitchenette; electric fireplace; shared outdoor fire pit.'
),
(
  '3d46b9f5-61ab-4ea3-9f17-f16425f71e74'::uuid,
  'in_progress', 'Yes', 'Yes',
  'Haven Yurts', 'Riesling',
  'haven-yurts-fredericksburg-tx', 'Glamping', 'Yurt',
  'Sage', 'web_research_havenyurts_guesty_2026_05', 'United States', 'TX', 'Fredericksburg',
  '11594 E US Highway 290', '78624', 30.22348, -98.78221,
  'https://porchlighthospitality.guestybookings.com/properties/6488afb3a7d93d0036132af8?propertyType=YURT',
  '+1-833-428-4371',
  $$Sibling site — Haven Yurts (Fredericksburg TX).$$,
  $$Riesling (Yurt #3): coastal blue and champagne bronze tones; king bed, stargazing dome, sunset views, kitchenette, fireplace.$$,
  $$Guesty 6488afb3a7d93d0036132af8; re-quote ADR in engine.$$,
  '2026-05-20', '2026-05-20', 'private_commercial',
  4, 1, '2', 490, '1 King',
  'Yes', 'No', 'Yes', 'Yes',
  'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes',
  'No', 'Yes',
  'Yes', 'Yes', 'Yes', 'Yes', 'Yes',
  'luxury', 'Coastal-toned interior; stargazing dome; walk-in shower; shared fire pit & grill.'
),
(
  '3d46b9f5-61ab-4ea3-9f17-f16425f71e74'::uuid,
  'in_progress', 'Yes', 'Yes',
  'Haven Yurts', 'Moscato',
  'haven-yurts-fredericksburg-tx', 'Glamping', 'Yurt',
  'Sage', 'web_research_havenyurts_guesty_2026_05', 'United States', 'TX', 'Fredericksburg',
  '11594 E US Highway 290', '78624', 30.22348, -98.78221,
  'https://porchlighthospitality.guestybookings.com/properties/6488b0cda7d93d0036133a1b?propertyType=YURT',
  '+1-833-428-4371',
  $$Sibling site — Haven Yurts (Fredericksburg TX).$$,
  $$Moscato (Yurt #4): "Pink Palace" blush and champagne bronze boho-chic; abundant natural light; king bed, stargazing dome, kitchenette, fireplace.$$,
  $$Guesty 6488b0cda7d93d0036133a1b; re-quote ADR in engine.$$,
  '2026-05-20', '2026-05-20', 'private_commercial',
  4, 1, '2', 490, '1 King',
  'Yes', 'No', 'Yes', 'Yes',
  'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes',
  'No', 'Yes',
  'Yes', 'Yes', 'Yes', 'Yes', 'Yes',
  'luxury', 'Pink/blush interior; stargazing dome; private bath; shared outdoor amenities.'
);
