-- Sorrel River Ranch Resort & Spa (Moab UT): 9 accommodations inventory rows.
-- Sources: sorrelriver.com/accommodations/, Synxis hotel 76589 (May 2026).
-- Enriches existing stub row id 7 (property_id 30d9e8b4-d55f-4122-8ed3-bd709cb4de11) + 8 new site rows.
-- discovery_source = web_research_sorrelriver_accommodations_synxis_2026_05

UPDATE public.all_glamping_properties SET
  property_id = '30d9e8b4-d55f-4122-8ed3-bd709cb4de11'::uuid,
  site_name = 'Studio King Mesa View',
  slug = 'sorrel-river-ranch-resort-spa',
  property_type = 'Glamping',
  unit_type = 'Cabin',
  source = 'Sage',
  discovery_source = 'web_research_sorrelriver_accommodations_synxis_2026_05',
  country = 'United States',
  address = 'Mile 17, Highway 128',
  zip_code = '84532',
  lat = 38.6494,
  lon = -109.4877,
  url = 'https://www.sorrelriver.com/accommodations/',
  phone_number = '+1-435-259-4642',
  research_status = 'in_progress',
  is_glamping_property = 'Yes',
  is_open = 'Yes',
  property_total_sites = 9,
  quantity_of_units = 1,
  unit_capacity = '2',
  unit_sq_ft = 400,
  unit_bed = '1 King',
  unit_wifi = 'Yes',
  unit_pets = 'Yes',
  unit_shower = 'Yes',
  unit_private_bathroom = 'Yes',
  unit_kitchenette = 'Yes',
  unit_mini_fridge = 'Yes',
  unit_bathtub = 'Yes',
  unit_patio = 'Yes',
  setting_desert = 'Yes',
  setting_canyon = 'Yes',
  setting_ranch = 'Yes',
  river_stream_or_creek = 'Yes',
  activities_horseback_riding = 'Yes',
  activities_hiking = 'Yes',
  activities_biking = 'Yes',
  land_operator_category = 'private_commercial',
  glamping_service_tier = 'luxury',
  date_updated = '2026-05-20',
  description = $$Sorrel River Ranch Resort & Spa — 240-acre luxury ranch on the Colorado River near Moab UT (Mile 17, UT-128). Custom-built cabins and suites with handcrafted furnishings, private decks, mesa and river views; resort pool, spa, restaurant, fitness, and on-site experiences (sorrelriver.com / Synxis hotel 76589). Pet-friendly dogs ($75/night).$$,
  unit_description = $$Studio King Mesa View: 1 king, 400 sq ft, mesa-view private deck, tub/shower combo, kitchenette, TV/Wi-Fi, C.O. Bigelow amenities, bathrobes.$$,
  notes = COALESCE(notes, '') || E'\n\nAccommodations enrichment (May 2026): 9 bookable types on /accommodations/. Synxis sample dates unavailable — ADR $700 retained from prior research; re-quote per room in be.synxis.com.',
  amenities_raw = 'Private deck; TV & Wi-Fi; kitchenette; mini-fridge; coffee; bottled water; bathrobes; C.O. Bigelow; pets $75/night.'
WHERE id = 7;

INSERT INTO public.all_glamping_properties (
  property_id, research_status, is_glamping_property, is_open,
  property_name, site_name, slug, property_type, unit_type,
  source, discovery_source, country, state, city,
  address, zip_code, lat, lon, url, phone_number,
  description, unit_description, notes,
  date_added, date_updated, land_operator_category,
  property_total_sites, quantity_of_units, unit_capacity, unit_sq_ft, unit_bed,
  rate_avg_retail_daily_rate, rate_summer_weekday, rate_summer_weekend,
  rate_unit_rates_by_year,
  unit_wifi, unit_pets, unit_shower, unit_private_bathroom,
  unit_kitchenette, unit_mini_fridge, unit_bathtub, unit_hot_tub, unit_patio,
  setting_desert, setting_canyon, setting_ranch, river_stream_or_creek,
  activities_horseback_riding, activities_hiking, activities_biking,
  glamping_service_tier, amenities_raw
) VALUES
(
  '30d9e8b4-d55f-4122-8ed3-bd709cb4de11'::uuid,
  'in_progress', 'Yes', 'Yes',
  'Sorrel River Ranch Resort & Spa', 'Studio Queen River View',
  'sorrel-river-ranch-resort-spa', 'Glamping', 'Cabin',
  'Sage', 'web_research_sorrelriver_accommodations_synxis_2026_05', 'United States', 'UT', 'Moab',
  'Mile 17, Highway 128', '84532', 38.6494, -109.4877,
  'https://www.sorrelriver.com/accommodations/',
  '+1-435-259-4642',
  $$Sibling site — Sorrel River Ranch (Moab UT). See anchor row id 7 (Studio King Mesa View).$$,
  $$Studio Queen River View: 1 queen, 360 sq ft, private deck on Colorado River, kitchenette, spa bath amenities.$$,
  $$Accommodations page; Synxis re-quote ADR (property placeholder $700).$$,
  '2026-05-20', '2026-05-20', 'private_commercial',
  9, 1, '2', 360, '1 Queen',
  700, 700, 700,
  '{"2026":{"placeholder":{"base_nightly":700,"note":"Property ADR until Synxis per-room quote"}}}'::jsonb,
  'Yes', 'Yes', 'Yes', 'Yes',
  'Yes', 'Yes', 'Yes', NULL, 'Yes',
  'Yes', 'Yes', 'Yes', 'Yes',
  'Yes', 'Yes', 'Yes',
  'luxury', 'River-view deck; kitchenette; Wi-Fi; pets $75/night.'
),
(
  '30d9e8b4-d55f-4122-8ed3-bd709cb4de11'::uuid,
  'in_progress', 'Yes', 'Yes',
  'Sorrel River Ranch Resort & Spa', 'River Studio Double Queen',
  'sorrel-river-ranch-resort-spa', 'Glamping', 'Cabin',
  'Sage', 'web_research_sorrelriver_accommodations_synxis_2026_05', 'United States', 'UT', 'Moab',
  'Mile 17, Highway 128', '84532', 38.6494, -109.4877,
  'https://www.sorrelriver.com/accommodations/',
  '+1-435-259-4642',
  $$Sibling site — Sorrel River Ranch (Moab UT).$$,
  $$River Studio Double Queen: 2 queen beds, 560 sq ft, riverfront deck, kitchenette, rustic-modern studio.$$,
  $$Sleeps 4; river view filter tag on accommodations page.$$,
  '2026-05-20', '2026-05-20', 'private_commercial',
  9, 1, '4', 560, '2 Queen',
  700, 700, 700,
  '{"2026":{"placeholder":{"base_nightly":700,"note":"Property ADR until Synxis per-room quote"}}}'::jsonb,
  'Yes', 'Yes', 'Yes', 'Yes',
  'Yes', 'Yes', NULL, NULL, 'Yes',
  'Yes', 'Yes', 'Yes', 'Yes',
  'Yes', 'Yes', 'Yes',
  'luxury', 'Double queen; river deck; kitchenette; Wi-Fi.'
),
(
  '30d9e8b4-d55f-4122-8ed3-bd709cb4de11'::uuid,
  'in_progress', 'Yes', 'Yes',
  'Sorrel River Ranch Resort & Spa', 'Mesa Studio Double Queen',
  'sorrel-river-ranch-resort-spa', 'Glamping', 'Cabin',
  'Sage', 'web_research_sorrelriver_accommodations_synxis_2026_05', 'United States', 'UT', 'Moab',
  'Mile 17, Highway 128', '84532', 38.6494, -109.4877,
  'https://www.sorrelriver.com/accommodations/',
  '+1-435-259-4642',
  $$Sibling site — Sorrel River Ranch (Moab UT).$$,
  $$Mesa Studio Double Queen: 2 queen beds, 475 sq ft, private porch with mesa views, kitchenette.$$,
  $$Sleeps 4; mesa view tag.$$,
  '2026-05-20', '2026-05-20', 'private_commercial',
  9, 1, '4', 475, '2 Queen',
  700, 700, 700,
  '{"2026":{"placeholder":{"base_nightly":700,"note":"Property ADR until Synxis per-room quote"}}}'::jsonb,
  'Yes', 'Yes', 'Yes', 'Yes',
  'Yes', 'Yes', NULL, NULL, 'Yes',
  'Yes', 'Yes', 'Yes', 'Yes',
  'Yes', 'Yes', 'Yes',
  'luxury', 'Mesa porch; double queen; kitchenette.'
),
(
  '30d9e8b4-d55f-4122-8ed3-bd709cb4de11'::uuid,
  'in_progress', 'Yes', 'Yes',
  'Sorrel River Ranch Resort & Spa', 'River View Studio King',
  'sorrel-river-ranch-resort-spa', 'Glamping', 'Cabin',
  'Sage', 'web_research_sorrelriver_accommodations_synxis_2026_05', 'United States', 'UT', 'Moab',
  'Mile 17, Highway 128', '84532', 38.6494, -109.4877,
  'https://www.sorrelriver.com/accommodations/',
  '+1-435-259-4642',
  $$Sibling site — Sorrel River Ranch (Moab UT).$$,
  $$River View Studio King: 1 king, 560 sq ft, Colorado River deck, Jacuzzi tub, walk-in shower, handcrafted rustic furnishings.$$,
  $$Sleeps 2; premium river studio tier.$$,
  '2026-05-20', '2026-05-20', 'private_commercial',
  9, 1, '2', 560, '1 King',
  700, 700, 700,
  '{"2026":{"placeholder":{"base_nightly":700,"note":"Property ADR until Synxis per-room quote"}}}'::jsonb,
  'Yes', 'Yes', 'Yes', 'Yes',
  'Yes', 'Yes', 'Yes', 'Yes', 'Yes',
  'Yes', 'Yes', 'Yes', 'Yes',
  'Yes', 'Yes', 'Yes',
  'luxury', 'Jacuzzi tub; river deck; walk-in shower.'
),
(
  '30d9e8b4-d55f-4122-8ed3-bd709cb4de11'::uuid,
  'in_progress', 'Yes', 'Yes',
  'Sorrel River Ranch Resort & Spa', 'Balcony Studio King',
  'sorrel-river-ranch-resort-spa', 'Glamping', 'Cabin',
  'Sage', 'web_research_sorrelriver_accommodations_synxis_2026_05', 'United States', 'UT', 'Moab',
  'Mile 17, Highway 128', '84532', 38.6494, -109.4877,
  'https://www.sorrelriver.com/accommodations/',
  '+1-435-259-4642',
  $$Sibling site — Sorrel River Ranch (Moab UT).$$,
  $$Balcony Studio King: 1 king, 400–600 sq ft, private river balcony, soaking tub, upgraded amenities, kitchenette.$$,
  $$Sleeps 2; balcony + river view tags.$$,
  '2026-05-20', '2026-05-20', 'private_commercial',
  9, 1, '2', 500, '1 King',
  700, 700, 700,
  '{"2026":{"placeholder":{"base_nightly":700,"note":"Property ADR until Synxis per-room quote"}}}'::jsonb,
  'Yes', 'Yes', 'Yes', 'Yes',
  'Yes', 'Yes', 'Yes', 'Yes', 'Yes',
  'Yes', 'Yes', 'Yes', 'Yes',
  'Yes', 'Yes', 'Yes',
  'luxury', 'River balcony; soaking tub; couples retreat.'
),
(
  '30d9e8b4-d55f-4122-8ed3-bd709cb4de11'::uuid,
  'in_progress', 'Yes', 'Yes',
  'Sorrel River Ranch Resort & Spa', 'Mesa View Family Suite',
  'sorrel-river-ranch-resort-spa', 'Glamping', 'Cabin',
  'Sage', 'web_research_sorrelriver_accommodations_synxis_2026_05', 'United States', 'UT', 'Moab',
  'Mile 17, Highway 128', '84532', 38.6494, -109.4877,
  'https://www.sorrelriver.com/accommodations/',
  '+1-435-259-4642',
  $$Sibling site — Sorrel River Ranch (Moab UT).$$,
  $$Mesa View Family Suite: 1,000 sq ft, 2 bedrooms (1 king + 2 queens), living area, mesa patio, kitchenette, 2 full baths.$$,
  $$Sleeps 6; family/small group.$$,
  '2026-05-20', '2026-05-20', 'private_commercial',
  9, 1, '6', 1000, '1 King + 2 Queen',
  700, 700, 700,
  '{"2026":{"placeholder":{"base_nightly":700,"note":"Property ADR until Synxis per-room quote; suite likely higher"}}}'::jsonb,
  'Yes', 'Yes', 'Yes', 'Yes',
  'Yes', 'Yes', 'Yes', NULL, 'Yes',
  'Yes', 'Yes', 'Yes', 'Yes',
  'Yes', 'Yes', 'Yes',
  'luxury', 'Two-bedroom suite; mesa patio; dual bathrooms.'
),
(
  '30d9e8b4-d55f-4122-8ed3-bd709cb4de11'::uuid,
  'in_progress', 'Yes', 'Yes',
  'Sorrel River Ranch Resort & Spa', 'River View Family Suite',
  'sorrel-river-ranch-resort-spa', 'Glamping', 'Cabin',
  'Sage', 'web_research_sorrelriver_accommodations_synxis_2026_05', 'United States', 'UT', 'Moab',
  'Mile 17, Highway 128', '84532', 38.6494, -109.4877,
  'https://www.sorrelriver.com/accommodations/',
  '+1-435-259-4642',
  $$Sibling site — Sorrel River Ranch (Moab UT).$$,
  $$River View Family Suite: 1,000 sq ft, 2 bedrooms (1 king + 2 queens), Colorado River patio, kitchenette, 2 full baths.$$,
  $$Sleeps 6; river-view family suite.$$,
  '2026-05-20', '2026-05-20', 'private_commercial',
  9, 1, '6', 1000, '1 King + 2 Queen',
  700, 700, 700,
  '{"2026":{"placeholder":{"base_nightly":700,"note":"Property ADR until Synxis per-room quote; suite likely higher"}}}'::jsonb,
  'Yes', 'Yes', 'Yes', 'Yes',
  'Yes', 'Yes', 'Yes', NULL, 'Yes',
  'Yes', 'Yes', 'Yes', 'Yes',
  'Yes', 'Yes', 'Yes',
  'luxury', 'Two-bedroom suite; river patio; dual bathrooms.'
),
(
  '30d9e8b4-d55f-4122-8ed3-bd709cb4de11'::uuid,
  'in_progress', 'Yes', 'Yes',
  'Sorrel River Ranch Resort & Spa', 'Ranch House Estate',
  'sorrel-river-ranch-resort-spa', 'Glamping', 'Cabin',
  'Sage', 'web_research_sorrelriver_accommodations_synxis_2026_05', 'United States', 'UT', 'Moab',
  'Mile 17, Highway 128', '84532', 38.6494, -109.4877,
  'https://www.sorrelriver.com/accommodations/ranch-house/',
  '+1-435-259-4642',
  $$Sibling site — Sorrel River Ranch (Moab UT).$$,
  $$Ranch House Estate: 5,500 sq ft whole-home luxury lodging for groups; ranch and Colorado River views; outdoor gas grill, private deck, full kitchen, sauna (per accommodations overview / ranch-house page).$$,
  $$Sleeps 12; book via Synxis or direct; whole-home ADR expected above studio tier — re-quote.$$,
  '2026-05-20', '2026-05-20', 'private_commercial',
  9, 1, '12', 5500, 'Multi-bedroom estate',
  700, 700, 700,
  '{"2026":{"placeholder":{"base_nightly":700,"note":"Stub uses property ADR; estate whole-home pricing likely much higher"}}}'::jsonb,
  'Yes', 'Yes', 'Yes', 'Yes',
  'Yes', 'Yes', 'Yes', 'Yes', 'Yes',
  'Yes', 'Yes', 'Yes', 'Yes',
  'Yes', 'Yes', 'Yes',
  'luxury', 'Whole-home estate; sauna; full kitchen; grill; sleeps 12.'
);
