-- Proposed-stage glamping resorts (May 2026 web research).
-- Public announcements: planning/rezoning, land use approvals, exclusive negotiations, or
-- county/city permits — not yet operating and not confirmed under active construction.
-- discovery_source = web_research_2026_05_proposed. research_status = in_progress. is_open = Proposed Development.
-- Applied to production via Supabase migration add_proposed_glamping_web_research_2026_05_18.

-- Align existing misclassified rows discovered during research
UPDATE public.all_glamping_properties
SET
  property_name = 'The Haven of Cadillac',
  slug = 'the-haven-of-cadillac-clam-lake-mi',
  is_open = 'Proposed Development',
  research_status = 'in_progress',
  discovery_source = 'web_research_2026_05_proposed',
  property_type = 'Glamping Resort',
  unit_type = 'Geodesic Dome',
  country = 'United States',
  state = 'MI',
  city = 'Cadillac',
  address = '70-acre parcel adjacent to Evergreen Golf Course, Clam Lake Township (PUD overlay pending)',
  lat = 44.1993902,
  lon = -85.3958517,
  url = 'https://thehavenofcadillac.com/',
  description = $$Beauvista Partners (Shelby & Ben Hastings) luxury glamping PUD on ~70 acres near Cadillac: Phase 1 targets 15–20 eco-domes/mini cabins on a wooded parcel beside Evergreen Golf Course; master plan allows up to 64 glamping units and future upscale RV phases. Township planning commission reviewed a PUD overlay in 2025; developers publicly cited spring 2026 construction start and Memorial Day 2027 opening if approvals finalize—treat as proposed until ground-breaking is verified.$$,
  notes = $$Sources: moderncampground.com (Jul 2025), cadillacnews.com, thehavenofcadillac.com (May 2026 web research). Coordinates: Clam Lake Township centroid.$$,
  date_updated = '2026-05-18',
  land_operator_category = 'private_commercial'
WHERE id = 11467;

UPDATE public.all_glamping_properties
SET
  property_name = 'Wildhaven Lake Berryessa',
  slug = 'wildhaven-lake-berryessa-spanish-flat-ca',
  is_open = 'Proposed Development',
  research_status = 'in_progress',
  discovery_source = 'web_research_2026_05_proposed',
  city = 'Lake Berryessa',
  state = 'CA',
  country = 'United States',
  address = 'Spanish Flat area, Lake Berryessa (Napa County redevelopment parcel)',
  lat = 38.512,
  lon = -122.199,
  url = 'https://www.pressdemocrat.com/2026/05/08/margaritaville-resort-in-doubt-as-napa-county-considers-glamping-project-for-lake-berryessa/',
  description = $$Napa County entered a 28-month exclusive negotiation (May 2026) with Wildhaven Napa LLC for a year-round glamping resort at Spanish Flat on Lake Berryessa: 60 glamping tents, 40 cabins, central lodge/restaurant, day-use area, and marina (75 slips, rentals, launch). Negotiation does not commit the county or developer; project competes with stalled Margaritaville/Steele Canyon concepts. Distinct from operating Wildhaven Sonoma/Yosemite properties.$$,
  notes = $$Sources: Press Democrat / Napa County Board action May 2026 (May 2026 web research). Prior row conflated Russian River wine-country copy; corrected to Berryessa pipeline. Coordinates approximate (Spanish Flat).$$,
  date_updated = '2026-05-18',
  land_operator_category = 'private_commercial'
WHERE id = 11799;

INSERT INTO public.all_glamping_properties (
  research_status,
  is_glamping_property,
  is_open,
  property_name,
  site_name,
  slug,
  property_type,
  unit_type,
  source,
  discovery_source,
  country,
  state,
  city,
  address,
  lat,
  lon,
  url,
  description,
  notes,
  date_added,
  date_updated,
  land_operator_category
) VALUES
(
  'in_progress',
  'Yes',
  'Proposed Development',
  'Under Canvas Lanesborough',
  NULL,
  'under-canvas-lanesborough-ma',
  'Glamping Resort',
  'Safari Tent',
  'Sage',
  'web_research_2026_05_proposed',
  'United States',
  'MA',
  'Lanesborough',
  '775 Williamstown Rd (former Donnybrook Country Club), Lanesborough, MA',
  42.518,
  -73.245,
  'https://www.berkshireeagle.com/business/lanesborough-glamping-resort-gets-two-oks/article_502641d9-9018-4874-8111-0adc438aee74.html',
  $$Under Canvas seasonal glamping on 160 acres at the closed Donnybrook Country Club: phased plan for up to 94 platform tents (seasonal hard-wall tents on decks), communal lodge/kitchen, reuse of golf buildings; Conservation Commission and ZBA approvals reported early 2025 with Board of Health septic and state DEP water/stormwater reviews still outstanding. Marketing cites $400–$600 ADR and 180-day seasonal cap—no public opening date; treat as proposed pre-construction.$$,
  $$Sources: Berkshire Eagle (2025), Under Canvas entitlements quotes (May 2026 web research).$$,
  '2026-05-18',
  '2026-05-18',
  'private_commercial'
),
(
  'in_progress',
  'Yes',
  'Proposed Development',
  'Notch Road Glamping Resort',
  NULL,
  'notch-road-glamping-resort-north-adams-ma',
  'Glamping Resort',
  'Safari Tent',
  'Sage',
  'web_research_2026_05_proposed',
  'United States',
  'MA',
  'North Adams',
  'Notch Road, North Adams, MA (145-acre parcel; 196 Marine LLC / Benjamin Crespi)',
  42.701,
  -73.110,
  'https://moderncampground.com/usa/massachusetts/north-adams-planning-board-approves-revised-glamping-resort-on-notch-road/',
  $$Revised wellness-focused glamping resort approved by North Adams Planning Board (Oct 2025, 5–2): 49 NKN-Softshell luxury tents in two clusters on 145 acres with sewer tie-in, spa/wellness center, natural pool, and lower-impact programming vs. earlier recreation-heavy plan. Developer 196 Marine LLC (Benjamin Crespi) cites 20–25 FTE jobs; neighborhood appeals on traffic/noise noted. Special permit granted with event/noise conditions—verify building permits and construction start before reclassifying to Under Construction.$$,
  $$Sources: iBerkshires / Modern Campground (Oct 2025) (May 2026 web research). Coordinates approximate (North Adams).$$,
  '2026-05-18',
  '2026-05-18',
  'private_commercial'
),
(
  'in_progress',
  'Yes',
  'Proposed Development',
  'Emmanuel Church Road Glamping Retreat',
  NULL,
  'emmanuel-church-road-glamping-retreat-amherst-va',
  'Glamping Resort',
  'Safari Tent',
  'Sage',
  'web_research_2026_05_proposed',
  'United States',
  'VA',
  'Amherst',
  '480 Emmanuel Church Rd, Amherst, VA',
  37.62,
  -79.12,
  'https://newsadvance.com/news/community/new-era-progress/article_c18f05a0-f1f4-4d84-9038-1165417dd232.html',
  $$Northern Amherst County glamping retreat campground granted a special use permit (April 2026): 14 canvas tents, shared bathhouse, pavilion, office, centralized parking, fire pit/gathering area, and recreational amenities on wooded acreage. Applicant team cited in local press includes principals from the region’s outdoor-hospitality market; verify operator brand, tent specs, and construction timeline before publishing rates.$$,
  $$Sources: Lynchburg News & Advance / New Era-Progress (Apr 2026) (May 2026 web research). Coordinates approximate (northern Amherst County).$$,
  '2026-05-18',
  '2026-05-18',
  'private_commercial'
),
(
  'in_progress',
  'Yes',
  'Proposed Development',
  'Rockdale Glamping Retreat',
  NULL,
  'rockdale-glamping-retreat-conyers-ga',
  'Glamping Resort',
  'Glamping Tent',
  'Sage',
  'web_research_2026_05_proposed',
  'United States',
  'GA',
  'Conyers',
  '3601 GA Highway 212 SE, Conyers, GA',
  33.667,
  -84.007,
  'https://moderncampground.com/usa/georgia/rockdale-county-glamping-proposal-advances-despite-residential-moratorium/',
  $$Three-site glamping camp proposed on a 20-acre wooded parcel in Rockdale County: each site for up to four guests (12 total) with one vehicle per site, outdoor fireplaces, and use of an on-site lake. Board granted a moratorium exemption (June 2025) to advance public review despite staff recommending denial amid county residential moratorium; final entitlements and construction timeline not announced.$$,
  $$Sources: Rockdale Newton Citizen / Modern Campground (Jun 2025) (May 2026 web research). Applicant Che Tuma; owner Timothy Glenn.$$,
  '2026-05-18',
  '2026-05-18',
  'private_commercial'
),
(
  'in_progress',
  'Yes',
  'Proposed Development',
  'Under Canvas Mancos',
  NULL,
  'under-canvas-mancos-co',
  'Glamping Resort',
  'Safari Tent',
  'Sage',
  'web_research_2026_05_proposed',
  'United States',
  'CO',
  'Mancos',
  '12695 Road 40, north of Mancos, CO (346-acre parcel; ~75 tents proposed)',
  37.344,
  -108.289,
  'https://www.the-journal.com/articles/glamping-tent-development-proposed-for-outside-mancos/',
  $$Under Canvas special/high-impact use permit for ag-residential land north of Mancos near Mesa Verde: application cites 346 acres with concentrated tent development (~75 units in later reporting). Montezuma County Planning & Zoning recommended denial (Mar 2025, 3–2) after strong public opposition; final decision rests with Board of County Commissioners. Treat as proposed pipeline until county approval and construction are confirmed.$$,
  $$Sources: The Journal / Durango Herald / Modern Campground (Mar 2025) (May 2026 web research).$$,
  '2026-05-18',
  '2026-05-18',
  'private_commercial'
),
(
  'in_progress',
  'Yes',
  'Proposed Development',
  'Columbia Wetlands Glamping Resort',
  NULL,
  'columbia-wetlands-glamping-resort-wilmer-bc',
  'Glamping Resort',
  'Glamping Tent',
  'Sage',
  'web_research_2026_05_proposed',
  'Canada',
  'BC',
  'Wilmer',
  'Westside Road area, Wilmer, BC (42.5-acre parcel; RDEK review)',
  50.733,
  -116.033,
  'https://moderncampground.com/canada/british-columbia/nature-based-glamping-development-proposed-along-columbia-wetlands-buffer-zone/',
  $$Private developer (Haworth Development Consulting) seeks RDEK zoning/ OCP amendments for a phased 90-unit nature-based glamping campground on 42.5 acres near Wilmer: car-free interior, platform tents/cottages/prospector tents, 20 m Columbia Wetlands buffer, on-site wells/septic, no guest RVs. Application presented Apr 2025; still under regional review as of web research—proposed only.$$,
  $$Sources: Columbia Valley Pioneer / Modern Campground (Apr 2025) (May 2026 web research).$$,
  '2026-05-18',
  '2026-05-18',
  'private_commercial'
),
(
  'in_progress',
  'Yes',
  'Proposed Development',
  'Marmora Retreat (expansion)',
  NULL,
  'marmora-retreat-expansion-marmora-on',
  'Glamping Resort',
  'Geodesic Dome',
  'Sage',
  'web_research_2026_05_proposed',
  'Canada',
  'ON',
  'Marmora',
  'Marble Point Rd, Marmora and Lake, ON (39-acre resort parcel)',
  44.484,
  -77.689,
  'https://www.quintenews.com/2025/04/03/354374/',
  $$Existing Marmora Retreat (farmhouse + glamping dome on 39 acres) received unanimous council approval (Mar 2025) to rezone from Marginal Agriculture to RRC-5 for two additional glamping domes and an outdoor event space (up to 100 people), with wetland/setback protections on Crowe River shoreline. Expansion requires septic/building permits—proposed development phase until new units open.$$,
  $$Sources: Quinte News / Hastings County planning (Apr 2025) (May 2026 web research).$$,
  '2026-05-18',
  '2026-05-18',
  'private_commercial'
);
