-- USA upcoming / under-construction glamping (May 2026 web research).
-- Applied to production via Supabase migration add_usa_upcoming_glamping_web_research_2026_05_16.
-- Rows use discovery_source = 'web_research_2026_05_usa'. Do not re-run on prod without deduping.

INSERT INTO public.all_glamping_properties (
  research_status,
  is_glamping_property,
  is_open,
  property_name,
  site_name,
  slug,
  property_type,
  unit_type,
  source,
  discovery_source,
  country,
  state,
  city,
  address,
  lat,
  lon,
  url,
  description,
  notes,
  date_added,
  date_updated,
  land_operator_category
) VALUES
(
  'in_progress',
  'Yes',
  'Under Construction',
  'Terranova Nirvana',
  NULL,
  'terranova-nirvana-page-az',
  'Glamping Resort',
  'Geodesic Dome',
  'Sage',
  'web_research_2026_05_usa',
  'USA',
  'AZ',
  'Page',
  NULL,
  36.914,
  -111.456,
  'https://terranovanirvana.com/',
  $$Page-area luxury dome resort (marketing: mirror/wellness glamping domes, spa-tech amenities, coffee shop and amphitheater). Public site states “Opening 2026”; verify exact address and booking before publishing.$$,
  $$Source: terranovanirvana.com + regional travel press (May 2026 web research). Coordinates are city-center approximate.$$,
  '2026-05-16',
  '2026-05-16',
  'private_commercial'
),
(
  'in_progress',
  'Yes',
  'Under Construction',
  'Tallgrass Retreat (Ferncrest Elkhorn River)',
  NULL,
  'tallgrass-retreat-ferncrest-elkhorn-river-neligh-ne',
  'Glamping Resort',
  'Geodesic Dome',
  'Sage',
  'web_research_2026_05_usa',
  'USA',
  'NE',
  'Neligh',
  'Elkhorn River / Cowboy Trail corridor (under construction)',
  42.128,
  -98.030,
  'https://tallgrassretreat.com/',
  $$Ferncrest-network dome glampground on the Elkhorn River outside Neligh: climate-controlled domes, bathhouse, sauna/cold plunge, camp store, Cowboy Trail access. Marketing cites first guests summer 2026.$$,
  $$Source: tallgrassretreat.com operator narrative (May 2026 web research). Distinct from Ferncrest Chambers Creek (Grandview, TX) already in Sage.$$,
  '2026-05-16',
  '2026-05-16',
  'private_commercial'
),
(
  'in_progress',
  'Yes',
  'Under Construction',
  'Echo Valley Micro-Resort',
  NULL,
  'echo-valley-micro-resort-dry-fork-va',
  'Glamping Resort',
  'Geodesic Dome',
  'Sage',
  'web_research_2026_05_usa',
  'USA',
  'VA',
  'Dry Fork',
  'Pittsylvania County (Echo Valley / Carter homestead area)',
  36.895,
  -79.371,
  'https://www.echovalleymicroresort.com/',
  $$Nature-first micro-resort on ~42 acres in Pittsylvania County: phased events then boutique glamping in geodesic domes, future wellness building. Press and county coverage cite rezoning approval and a spring 2026 target; treat as pre-opening until verified.$$,
  $$Source: echovalleymicroresort.com + Cardinal News / local TV (May 2026 web research).$$,
  '2026-05-16',
  '2026-05-16',
  'private_commercial'
),
(
  'in_progress',
  'Yes',
  'Under Construction',
  'Luxe Den Resorts',
  NULL,
  'luxe-den-resorts-twin-falls-id',
  'Glamping Resort',
  'Geodesic Dome',
  'Sage',
  'web_research_2026_05_usa',
  'USA',
  'ID',
  'Twin Falls',
  NULL,
  42.563,
  -114.461,
  'https://luxedenresorts.com/',
  $$Planned Nordic-inspired glass/geodesic dome micro-resort near Twin Falls / Snake River country (dark-sky positioning, riverside wellness, saunas). Official timeline: VIP phase → construction late 2026 → grand opening summer 2027.$$,
  $$Source: luxedenresorts.com (May 2026 web research).$$,
  '2026-05-16',
  '2026-05-16',
  'private_commercial'
),
(
  'in_progress',
  'Yes',
  'Under Construction',
  'Dwell RV Resort & Casita Cabins',
  'Casita Cabins',
  'dwell-rv-resort-casita-cabins-lake-havasu-city-az',
  'Glamping Resort',
  'Tiny Home',
  'Sage',
  'web_research_2026_05_usa',
  'USA',
  'AZ',
  'Lake Havasu City',
  'Near Topock Bay / Lake Havasu corridor',
  34.474,
  -114.344,
  'https://dwelllakehavasu.com/',
  $$New-build desert resort positioning 20 high-finish “Casita Cabins” (park-model style) alongside RV sites—marketed as a non-tent glamping alternative with full bath, kitchenette, pool/clubhouse amenities. Trade press reports reservations targeting May 2026 and a summer 2026 opening push.$$,
  $$Source: dwelllakehavasu.com + Modern Campground interview (May 2026 web research). Row focuses on the cabin/glamping product.$$,
  '2026-05-16',
  '2026-05-16',
  'private_commercial'
),
(
  'in_progress',
  'Yes',
  'Under Construction',
  'Prospect and Refuge',
  NULL,
  'prospect-and-refuge-chattanooga-tn',
  'Glamping Resort',
  'Safari Tent',
  'Sage',
  'web_research_2026_05_usa',
  'USA',
  'TN',
  'Chattanooga',
  'Tennessee River Gorge (pre-opening; exact parcel TBD)',
  35.220,
  -85.321,
  'https://www.prospectandrefugeresorts.com/',
  $$Boutique glamping marketed for the Tennessee River Gorge near Chattanooga (luxury tents + resort-style positioning). Public landing page still frames a 2025 opening as “coming soon”; verify operational status, exact location, and inventory.$$,
  $$Source: prospectandrefugeresorts.com (May 2026 web research). Coordinates approximate (Prentiss-Cooper / gorge area).$$,
  '2026-05-16',
  '2026-05-16',
  'private_commercial'
);
