-- Vermont glamping web research (May 2026).
-- Adds properties not already in Sage VT sample (existing rows include Treehouse Lodge Peru,
-- Yurt Village at Green Mountain NF, Moose Meadow Lodge, Vermont Retreat / Yurt in Putney).
-- discovery_source = web_research_2026_05_vt. research_status = in_progress.
-- Applied to production via Supabase migration add_vermont_glamping_web_research_2026_05_18.

INSERT INTO public.all_glamping_properties (
  research_status,
  is_glamping_property,
  is_open,
  property_name,
  site_name,
  slug,
  property_type,
  unit_type,
  source,
  discovery_source,
  country,
  state,
  city,
  address,
  lat,
  lon,
  url,
  description,
  notes,
  date_added,
  date_updated,
  land_operator_category
) VALUES
(
  'in_progress',
  'Yes',
  'Yes',
  'Mount Snow Yurt',
  'Yurt',
  'mount-snow-yurt-dover-vt',
  'Glamping Resort',
  'Yurt',
  'Sage',
  'web_research_2026_05_vt',
  'United States',
  'VT',
  'Dover',
  '60 Ellis Brook Rd, Dover, VT 05356',
  42.944,
  -72.803,
  'https://mountsnowyurt.com/',
  $$Luxury yurt-shaped cabin near Mount Snow: creek-side setting with private hot tub, cedar sauna, wood stove, chef kitchen, Starlink Wi-Fi, EV charger, and high-end entertainment (marketing compares to canvas glamping but emphasizes insulated solid build). Sleeps up to 8 in flexible bedroom/loft layout; pet fee applies. Verify pricing, damage deposit, and exterior camera disclosure on the booking site.$$,
  $$Sources: mountsnowyurt.com FAQ + amenities (May 2026 web research).$$,
  '2026-05-18',
  '2026-05-18',
  'private_commercial'
),
(
  'in_progress',
  'Yes',
  'Yes',
  'Lilla Rustica Treehouse',
  'Treehouse',
  'lilla-rustica-treehouse-moretown-vt',
  'Glamping Resort',
  'Treehouse',
  'Sage',
  'web_research_2026_05_vt',
  'United States',
  'VT',
  'Moretown',
  'Moretown, VT 05660',
  44.252,
  -72.905,
  'https://www.treehouserentals.com/property/cozy-warm-treehouse-with-amazing-views-winter-paradise-hike-from-cabin/HA-3212044380',
  $$Elevated treehouse near Camel's Hump views (built by Vermont's Tree House Guys): two queen sleeping areas, propane fireplace, internet, small fridge, and ramp access; outdoor privy and limited water with spring water provided (no shower on-site per listing). Managed via TreeHouseRentals/VRBO channel; confirm child policy and pet rules before publishing.$$,
  $$Sources: TreeHouseRentals listing copy + independent design coverage (May 2026 web research). Street address withheld on public listing; city/ZIP only.$$,
  '2026-05-18',
  '2026-05-18',
  'private_commercial'
),
(
  'in_progress',
  'Yes',
  'Yes',
  'Little River State Park (Cabins)',
  'Cabin',
  'little-river-state-park-cabins-waterbury-vt',
  'Glamping',
  'Cabin',
  'Sage',
  'web_research_2026_05_vt',
  'United States',
  'VT',
  'Waterbury',
  '3444 Little River Rd, Waterbury, VT 05676',
  44.389,
  -72.722,
  'https://www.vtstateparks.com/parks/little-river',
  $$Vermont State Parks rental cabins at Little River on Waterbury Reservoir: five one-room cabins with bunks/futon-style sleeping, porch, picnic table, and fire ring; bathhouses with showers a short walk (seasonal camping loop). Popular boating, swimming, and trail access; verify reservation window, pet rules (Bear cabin pet-friendly), and resident vs. non-resident fees.$$,
  $$Sources: vtstateparks.com Little River park page (May 2026 web research).$$,
  '2026-05-18',
  '2026-05-18',
  'state_park'
);
