-- Canada glamping pipeline + new inventory (May 2026 web research).
-- Applied to production via Supabase migration add_canada_upcoming_glamping_web_research_2026_05_16.
-- Rows tagged discovery_source = 'web_research_2026_05' for audit.

INSERT INTO public.all_glamping_properties (
  research_status,
  is_glamping_property,
  is_open,
  property_name,
  site_name,
  slug,
  property_type,
  unit_type,
  source,
  discovery_source,
  country,
  state,
  city,
  address,
  zip_code,
  lat,
  lon,
  url,
  phone_number,
  description,
  notes,
  date_added,
  date_updated,
  land_operator_category
) VALUES
(
  'in_progress',
  'Yes',
  'Under Construction',
  'TK Glamping and Wellness',
  NULL,
  'tk-glamping-wellness-vernon',
  'Glamping Resort',
  'Safari Tent',
  'Sage',
  'web_research_2026_05',
  'Canada',
  'BC',
  'Vernon',
  NULL,
  NULL,
  50.267,
  -119.272,
  'https://whale-goose-jny9.squarespace.com/',
  NULL,
  $$Adults-only North Okanagan glamping on Syilx territory: hard-wall rustic tents with private bathrooms, wellness programming, and regional activities. Public materials cite an inaugural operating season beginning spring 2026 (weather-dependent).$$,
  $$Source: TK Glamping Squarespace site + regional tourism coverage (May 2026 web research). Verify opening dates, rates, and exact street address before publishing.$$,
  '2026-05-16',
  '2026-05-16',
  'private_commercial'
),
(
  'in_progress',
  'Yes',
  'Under Construction',
  'Miners Camp (proposed)',
  NULL,
  'miners-camp-canmore-proposed',
  'Glamping Resort',
  'Wall Tent',
  'Sage',
  'web_research_2026_05',
  'Canada',
  'AB',
  'Canmore',
  'Staircase Lands / Quarry Lake area (proposed)',
  NULL,
  51.074,
  -115.359,
  'https://www.cbc.ca/news/canada/calgary/glamping-quarry-lake-canmore-9.7139278',
  NULL,
  $$Proposed seasonal glamping campground (Summit Projects) near Quarry Lake: wall tents on platforms, services building, phased rollout reported in local/national press. Not approved/operating as of web research (May 2026).$$,
  $$Source: CBC / CTV / Global / trade press on Quarry Lake “Miners Camp” proposal. Coordinates approximate (Canmore).$$,
  '2026-05-16',
  '2026-05-16',
  'private_commercial'
),
(
  'in_progress',
  'Yes',
  'Under Construction',
  'New Harbour Hill',
  NULL,
  'new-harbour-hill-ns',
  'Glamping Resort',
  'Glamping Tent',
  'Sage',
  'web_research_2026_05',
  'Canada',
  'NS',
  'Mahone Bay',
  NULL,
  NULL,
  44.448,
  -64.382,
  'https://www.newharbourhill.ca/',
  NULL,
  $$South Shore Nova Scotia glamping project (panoramic Mahone Bay views) marketed as a future destination; treat as pre-opening until bookings and opening are verified.$$,
  $$Source: project website + Atlantic Canada press (May 2026 web research).$$,
  '2026-05-16',
  '2026-05-16',
  'private_commercial'
),
(
  'in_progress',
  'Yes',
  'Under Construction',
  'Elation Glamping',
  NULL,
  'elation-glamping-shepody-nb',
  'Glamping Resort',
  'Bell Tent',
  'Sage',
  'web_research_2026_05',
  'Canada',
  'NB',
  'Shepody',
  NULL,
  NULL,
  45.72,
  -64.95,
  'https://sites.google.com/view/www-elationglamping-com/home',
  NULL,
  $$Ocean-view glamping development on a rural Shepody Bay parcel (marketing site describes future furnished bell tents and amenities). Pre-opening.$$,
  $$Source: developer Google Sites (May 2026 web research). City uses local placename; coordinates approximate.$$,
  '2026-05-16',
  '2026-05-16',
  'private_commercial'
),
(
  'in_progress',
  'Yes',
  'Under Construction',
  'The Timber Walk',
  NULL,
  'the-timber-walk-lower-greenwich-nb',
  'Glamping Resort',
  'Bell Tent',
  'Sage',
  'web_research_2026_05',
  'Canada',
  'NB',
  'Lower Greenwich',
  NULL,
  NULL,
  45.26,
  -66.12,
  'https://www.thetimberwalk.ca/',
  NULL,
  $$Lower Saint John River valley forest retreat (modern cabins + furnished bell tents, boardwalks, shower house) marketed as under development—pre-opening.$$,
  $$Source: thetimberwalk.ca (May 2026 web research). Coordinates approximate (Grand Bay–Westfield / Lower Greenwich area).$$,
  '2026-05-16',
  '2026-05-16',
  'private_commercial'
),
(
  'in_progress',
  'Yes',
  'Under Construction',
  'Natura Wilderness Resort',
  NULL,
  'natura-wilderness-resort-newport-corner-ns',
  'Glamping Resort',
  'Safari Tent',
  'Sage',
  'web_research_2026_05',
  'Canada',
  'NS',
  'Newport Station',
  'Newport Corner / West Hants (planned)',
  NULL,
  44.92,
  -64.08,
  'https://www.saltwire.com/atlantic-canada/luxury-camping-experience-in-the-works-for-newport-corner-294082',
  NULL,
  $$Long-running proposal for canvas “glamping” campsites on a large West Hants parcel; status should be verified with the developer/municipality before treating as imminent.$$,
  $$Source: SaltWire / regional news (May 2026 web research). URL is a news article because a stable public resort site was not confirmed.$$,
  '2026-05-16',
  '2026-05-16',
  'private_commercial'
),
(
  'in_progress',
  'Yes',
  'Yes',
  'Waters Edge Eco Lodge',
  'Tipi Village',
  'waters-edge-eco-lodge-tipi-village-sk',
  'Wilderness Resort',
  'Tipi',
  'Sage',
  'web_research_2026_05',
  'Canada',
  'SK',
  'Meadow Lake',
  'Greig Lake, Meadow Lake Provincial Park',
  'S0M 2H0',
  54.116,
  -109.616,
  'https://watersedgeecolodge.ca/',
  '+1-306-234-7900',
  $$Waterhen Lake First Nation–operated lodge on Greig Lake with a bookable tipi village (electrically equipped tipis on platforms) marketed as Indigenous-led eco/cultural tourism.$$,
  $$Source: Waters Edge Eco Lodge official site + Saskatchewan news coverage (May 2026 web research).$$,
  '2026-05-16',
  '2026-05-16',
  'other_public'
),
(
  'in_progress',
  'Yes',
  'Yes',
  'Seal Bay Glamping Retreat',
  NULL,
  'seal-bay-glamping-retreat-powell-river-bc',
  'Glamping Resort',
  'Geodesic Dome',
  'Sage',
  'web_research_2026_05',
  'Canada',
  'BC',
  'Powell River',
  '8139 Emmonds Rd',
  NULL,
  49.952,
  -124.428,
  'https://sealbayglamping.ca/',
  NULL,
  $$qathet-area coastal glamping near Lund/Powell River on Tla’amin territory: forested property with beach access; marketing site lists accommodations and “Spassel” product as coming soon.$$,
  $$Source: sealbayglamping.ca (May 2026 web research).$$,
  '2026-05-16',
  '2026-05-16',
  'private_commercial'
);
