-- Glamping.com North America directory audit (May 2026).
-- Adds 52 properties missing from all_glamping_properties vs glamping.com sitemap (135 NA listings).
-- Reclassifies existing Glamping.com-listed rows where is_glamping_property = 'No'.
-- discovery_source = glamping_com_north_america_2026_05. Safe to re-run (WHERE NOT EXISTS guards).

-- Reclassify existing North America Glamping.com listings flagged as non-glamping.
UPDATE public.all_glamping_properties
SET
  is_glamping_property = 'Yes',
  research_status = CASE WHEN research_status = 'rejected' THEN 'published' ELSE research_status END,
  property_type = COALESCE(NULLIF(trim(property_type), ''), 'Glamping Resort'),
  date_updated = '2026-05-26',
  notes = COALESCE(notes, '') || E'\n\nGlamping.com North America directory audit (May 2026): confirmed glamping inventory.'
WHERE property_name IN (
  'Verde Ranch Resort',
  'American Safari Camp',
  'Gateway Canyons Resort & Spa',
  'Headwaters Jupiter',
  'Norwegian Wood Ranch',
  'The Eagle''s Nest',
  'Moonbeam Bungalows',
  'Shawnee Inn & Golf Resort',
  'Flying Flags RV Resort & Campground'
)
  AND is_glamping_property <> 'Yes';

INSERT INTO public.all_glamping_properties (
  research_status,
  is_glamping_property,
  is_open,
  property_name,
  slug,
  property_type,
  unit_type,
  source,
  discovery_source,
  country,
  state,
  city,
  lat,
  lon,
  url,
  description,
  notes,
  date_added,
  date_updated,
  land_operator_category
)
SELECT
  v.research_status,
  v.is_glamping_property,
  v.is_open,
  v.property_name,
  v.slug,
  v.property_type,
  v.unit_type,
  v.source,
  v.discovery_source,
  v.country,
  v.state,
  v.city,
  v.lat,
  v.lon,
  v.url,
  v.description,
  v.notes,
  v.date_added,
  v.date_updated,
  v.land_operator_category
FROM (
  VALUES
  ('published', 'Yes', 'Yes', 'Wildcoast Adventures', 'wildcoast-adventures-quathiaski-cove-bc', 'Glamping Resort', 'Mixed', 'Sage', 'glamping_com_north_america_2026_05', 'Canada', 'BC', 'Quathiaski Cove', NULL::numeric, NULL::numeric, 'https://www.wildcoast.ca/', $$Wildcoast Adventures — North American glamping property featured in the Glamping.com collection (Quathiaski Cove, BC).$$, $$Sources: Glamping.com North America directory audit (May 2026). Listing: https://www.glamping.com/destination/north-america/british-columbia/quathiaski-cove/wildcoast-adventures/$$, '2026-05-26', '2026-05-26', 'private_commercial', 'https://www.glamping.com/destination/north-america/british-columbia/quathiaski-cove/wildcoast-adventures/'),
  ('published', 'Yes', 'Yes', 'The Flow Wilderness Retreat', 'the-flow-wilderness-retreat-surge-narrows-bc', 'Glamping Resort', 'Mixed', 'Sage', 'glamping_com_north_america_2026_05', 'Canada', 'BC', 'Surge Narrows', NULL::numeric, NULL::numeric, 'https://www.theflow.ca/', $$The Flow Wilderness Retreat — North American glamping property featured in the Glamping.com collection (Surge Narrows, BC).$$, $$Sources: Glamping.com North America directory audit (May 2026). Listing: https://www.glamping.com/destination/north-america/british-columbia/surge-narrows/the-flow-wilderness-retreat/$$, '2026-05-26', '2026-05-26', 'private_commercial', 'https://www.glamping.com/destination/north-america/british-columbia/surge-narrows/the-flow-wilderness-retreat/'),
  ('published', 'Yes', 'Yes', 'Spirit of the West Adventures', 'spirit-of-the-west-adventures-swanson-island-bc', 'Glamping Resort', 'Mixed', 'Sage', 'glamping_com_north_america_2026_05', 'Canada', 'BC', 'Swanson Island', NULL::numeric, NULL::numeric, 'https://www.glamping.com/destination/north-america/british-columbia/swanson-island/spirit-of-the-west-adventures/', $$Spirit of the West Adventures — North American glamping property featured in the Glamping.com collection (Swanson Island, BC).$$, $$Sources: Glamping.com North America directory audit (May 2026). Listing: https://www.glamping.com/destination/north-america/british-columbia/swanson-island/spirit-of-the-west-adventures/$$, '2026-05-26', '2026-05-26', 'private_commercial', 'https://www.glamping.com/destination/north-america/british-columbia/swanson-island/spirit-of-the-west-adventures/'),
  ('published', 'Yes', 'Yes', 'Sierra Mountain Lodge', 'sierra-mountain-lodge-ahwahnee-ca', 'Glamping Resort', 'Mixed', 'Sage', 'glamping_com_north_america_2026_05', 'United States', 'CA', 'Ahwahnee', NULL::numeric, NULL::numeric, 'https://www.sierramountainlodge.com/', $$Sierra Mountain Lodge — North American glamping property featured in the Glamping.com collection (Ahwahnee, CA).$$, $$Sources: Glamping.com North America directory audit (May 2026). Listing: https://www.glamping.com/destination/north-america/california/ahwahnee/sierra-mountain-lodge/$$, '2026-05-26', '2026-05-26', 'private_commercial', 'https://www.glamping.com/destination/north-america/california/ahwahnee/sierra-mountain-lodge/'),
  ('published', 'Yes', 'Yes', 'Luxe RV', 'luxe-rv-chatsworth-ca', 'Glamping Resort', 'Mixed', 'Sage', 'glamping_com_north_america_2026_05', 'United States', 'CA', 'Chatsworth', NULL::numeric, NULL::numeric, 'https://www.glamping.com/destination/north-america/california/chatsworth/luxe-rv/', $$Luxe RV — North American glamping property featured in the Glamping.com collection (Chatsworth, CA).$$, $$Sources: Glamping.com North America directory audit (May 2026). Listing: https://www.glamping.com/destination/north-america/california/chatsworth/luxe-rv/$$, '2026-05-26', '2026-05-26', 'private_commercial', 'https://www.glamping.com/destination/north-america/california/chatsworth/luxe-rv/'),
  ('published', 'Yes', 'Yes', 'Sorensen''s Resort', 'sorensen-s-resort-hope-valley-ca', 'Glamping Resort', 'Mixed', 'Sage', 'glamping_com_north_america_2026_05', 'United States', 'CA', 'Hope Valley', NULL::numeric, NULL::numeric, 'https://www.sorensensresort.com/', $$Sorensen's Resort — North American glamping property featured in the Glamping.com collection (Hope Valley, CA).$$, $$Sources: Glamping.com North America directory audit (May 2026). Listing: https://www.glamping.com/destination/north-america/california/hope-valley/sorensens-resort/$$, '2026-05-26', '2026-05-26', 'private_commercial', 'https://www.glamping.com/destination/north-america/california/hope-valley/sorensens-resort/'),
  ('published', 'Yes', 'Yes', 'Pine Mountain Camp', 'pine-mountain-camp-lake-arrowhead-ca', 'Glamping Resort', 'Mixed', 'Sage', 'glamping_com_north_america_2026_05', 'United States', 'CA', 'Lake Arrowhead', NULL::numeric, NULL::numeric, 'https://www.glamping.com/destination/north-america/california/lake-arrowhead/pine-mountain-camp/', $$Pine Mountain Camp — North American glamping property featured in the Glamping.com collection (Lake Arrowhead, CA).$$, $$Sources: Glamping.com North America directory audit (May 2026). Listing: https://www.glamping.com/destination/north-america/california/lake-arrowhead/pine-mountain-camp/$$, '2026-05-26', '2026-05-26', 'private_commercial', 'https://www.glamping.com/destination/north-america/california/lake-arrowhead/pine-mountain-camp/'),
  ('published', 'Yes', 'Yes', 'Murphys Glamping', 'murphys-glamping-murphys-ca', 'Glamping Resort', 'Mixed', 'Sage', 'glamping_com_north_america_2026_05', 'United States', 'CA', 'Murphys', NULL::numeric, NULL::numeric, 'https://www.glamping.com/destination/north-america/california/murphys/murphys-glamping/', $$Murphys Glamping — North American glamping property featured in the Glamping.com collection (Murphys, CA).$$, $$Sources: Glamping.com North America directory audit (May 2026). Listing: https://www.glamping.com/destination/north-america/california/murphys/murphys-glamping/$$, '2026-05-26', '2026-05-26', 'private_commercial', 'https://www.glamping.com/destination/north-america/california/murphys/murphys-glamping/'),
  ('published', 'Yes', 'Yes', 'Marble Mountain Ranch', 'marble-mountain-ranch-somes-bar-ca', 'Glamping Resort', 'Mixed', 'Sage', 'glamping_com_north_america_2026_05', 'United States', 'CA', 'Somes Bar', NULL::numeric, NULL::numeric, 'https://www.marblemountainranch.com/', $$Marble Mountain Ranch — North American glamping property featured in the Glamping.com collection (Somes Bar, CA).$$, $$Sources: Glamping.com North America directory audit (May 2026). Listing: https://www.glamping.com/destination/north-america/california/somes-bar/marble-mountain-ranch/$$, '2026-05-26', '2026-05-26', 'private_commercial', 'https://www.glamping.com/destination/north-america/california/somes-bar/marble-mountain-ranch/'),
  ('published', 'Yes', 'Yes', 'Chill RV', 'chill-rv-studio-city-ca', 'Glamping Resort', 'Mixed', 'Sage', 'glamping_com_north_america_2026_05', 'United States', 'CA', 'Studio City', NULL::numeric, NULL::numeric, 'https://www.glamping.com/destination/north-america/california/studio-city/chill-rv/', $$Chill RV — North American glamping property featured in the Glamping.com collection (Studio City, CA).$$, $$Sources: Glamping.com North America directory audit (May 2026). Listing: https://www.glamping.com/destination/north-america/california/studio-city/chill-rv/$$, '2026-05-26', '2026-05-26', 'private_commercial', 'https://www.glamping.com/destination/north-america/california/studio-city/chill-rv/'),
  ('published', 'Yes', 'Yes', 'Beach Canyon Authentic Tipi', 'beach-canyon-authentic-tipi-topanga-ca', 'Glamping Resort', 'Mixed', 'Sage', 'glamping_com_north_america_2026_05', 'United States', 'CA', 'Topanga', NULL::numeric, NULL::numeric, 'https://www.glamping.com/destination/north-america/california/topanga/beach-canyon-authentic-tipi-in-topanga-california/', $$Beach Canyon Authentic Tipi — North American glamping property featured in the Glamping.com collection (Topanga, CA).$$, $$Sources: Glamping.com North America directory audit (May 2026). Listing: https://www.glamping.com/destination/north-america/california/topanga/beach-canyon-authentic-tipi-in-topanga-california/$$, '2026-05-26', '2026-05-26', 'private_commercial', 'https://www.glamping.com/destination/north-america/california/topanga/beach-canyon-authentic-tipi-in-topanga-california/'),
  ('published', 'Yes', 'Yes', 'Safari Sunset Eco Ranch', 'safari-sunset-eco-ranch-vista-ca', 'Glamping Resort', 'Mixed', 'Sage', 'glamping_com_north_america_2026_05', 'United States', 'CA', 'Vista', NULL::numeric, NULL::numeric, 'https://www.glamping.com/destination/north-america/california/vista/safari-sunset-eco-ranch/', $$Safari Sunset Eco Ranch — North American glamping property featured in the Glamping.com collection (Vista, CA).$$, $$Sources: Glamping.com North America directory audit (May 2026). Listing: https://www.glamping.com/destination/north-america/california/vista/safari-sunset-eco-ranch/$$, '2026-05-26', '2026-05-26', 'private_commercial', 'https://www.glamping.com/destination/north-america/california/vista/safari-sunset-eco-ranch/'),
  ('published', 'Yes', 'Yes', 'Galt Valley Artsy Tucked Away Retreat', 'galt-valley-artsy-tucked-away-retreat-basalt-co', 'Glamping Resort', 'Mixed', 'Sage', 'glamping_com_north_america_2026_05', 'United States', 'CO', 'Basalt', NULL::numeric, NULL::numeric, 'https://www.glamping.com/destination/north-america/colorado/basalt/galt-valley-artsy-tucked-away-retreat/', $$Galt Valley Artsy Tucked Away Retreat — North American glamping property featured in the Glamping.com collection (Basalt, CO).$$, $$Sources: Glamping.com North America directory audit (May 2026). Listing: https://www.glamping.com/destination/north-america/colorado/basalt/galt-valley-artsy-tucked-away-retreat/$$, '2026-05-26', '2026-05-26', 'private_commercial', 'https://www.glamping.com/destination/north-america/colorado/basalt/galt-valley-artsy-tucked-away-retreat/'),
  ('published', 'Yes', 'Yes', 'Colorado Rafting Tours Royal Gorge Adventure Beach', 'colorado-rafting-tours-royal-gorge-adventure-beach-canon-city-co', 'Glamping Resort', 'Mixed', 'Sage', 'glamping_com_north_america_2026_05', 'United States', 'CO', 'Canon City', NULL::numeric, NULL::numeric, 'https://www.glamping.com/destination/north-america/colorado/canon-city/colorado-rafting-tours-royal-gorge-adventure-beach/', $$Colorado Rafting Tours Royal Gorge Adventure Beach — North American glamping property featured in the Glamping.com collection (Canon City, CO).$$, $$Sources: Glamping.com North America directory audit (May 2026). Listing: https://www.glamping.com/destination/north-america/colorado/canon-city/colorado-rafting-tours-royal-gorge-adventure-beach/$$, '2026-05-26', '2026-05-26', 'private_commercial', 'https://www.glamping.com/destination/north-america/colorado/canon-city/colorado-rafting-tours-royal-gorge-adventure-beach/'),
  ('published', 'Yes', 'Yes', 'Vista Verde Guest Ranch', 'vista-verde-guest-ranch-clark-co', 'Glamping Resort', 'Mixed', 'Sage', 'glamping_com_north_america_2026_05', 'United States', 'CO', 'Clark', NULL::numeric, NULL::numeric, 'https://www.vistaverde.com/', $$Vista Verde Guest Ranch — North American glamping property featured in the Glamping.com collection (Clark, CO).$$, $$Sources: Glamping.com North America directory audit (May 2026). Listing: https://www.glamping.com/destination/north-america/colorado/clark/vista-verde-guest-ranch/$$, '2026-05-26', '2026-05-26', 'private_commercial', 'https://www.glamping.com/destination/north-america/colorado/clark/vista-verde-guest-ranch/'),
  ('published', 'Yes', 'Yes', 'Blue Ocean Yacht Charters', 'blue-ocean-yacht-charters-key-west-fl', 'Glamping Resort', 'Mixed', 'Sage', 'glamping_com_north_america_2026_05', 'United States', 'FL', 'Key West', NULL::numeric, NULL::numeric, 'https://www.glamping.com/destination/north-america/florida/key-west/blue-ocean-yacht-charters/', $$Blue Ocean Yacht Charters — North American glamping property featured in the Glamping.com collection (Key West, FL).$$, $$Sources: Glamping.com North America directory audit (May 2026). Listing: https://www.glamping.com/destination/north-america/florida/key-west/blue-ocean-yacht-charters/$$, '2026-05-26', '2026-05-26', 'private_commercial', 'https://www.glamping.com/destination/north-america/florida/key-west/blue-ocean-yacht-charters/'),
  ('published', 'Yes', 'Yes', 'Aluminum Cabana', 'aluminum-cabana-navarre-fl', 'Glamping Resort', 'Mixed', 'Sage', 'glamping_com_north_america_2026_05', 'United States', 'FL', 'Navarre', NULL::numeric, NULL::numeric, 'https://www.glamping.com/destination/north-america/florida/navarre/aluminum-cabana/', $$Aluminum Cabana — North American glamping property featured in the Glamping.com collection (Navarre, FL).$$, $$Sources: Glamping.com North America directory audit (May 2026). Listing: https://www.glamping.com/destination/north-america/florida/navarre/aluminum-cabana/$$, '2026-05-26', '2026-05-26', 'private_commercial', 'https://www.glamping.com/destination/north-america/florida/navarre/aluminum-cabana/'),
  ('published', 'Yes', 'Yes', 'Heaven''s Gate Mountain Getaway', 'heaven-s-gate-mountain-getaway-ellijay-ga', 'Glamping Resort', 'Mixed', 'Sage', 'glamping_com_north_america_2026_05', 'United States', 'GA', 'Ellijay', NULL::numeric, NULL::numeric, 'https://www.glamping.com/destination/north-america/georgia/ellijay/heavens-gate-mountain-getaway/', $$Heaven's Gate Mountain Getaway — North American glamping property featured in the Glamping.com collection (Ellijay, GA).$$, $$Sources: Glamping.com North America directory audit (May 2026). Listing: https://www.glamping.com/destination/north-america/georgia/ellijay/heavens-gate-mountain-getaway/$$, '2026-05-26', '2026-05-26', 'private_commercial', 'https://www.glamping.com/destination/north-america/georgia/ellijay/heavens-gate-mountain-getaway/'),
  ('published', 'Yes', 'Yes', 'The Lodge on Little St. Simons Island', 'the-lodge-on-little-st-simons-island-saint-simons-island-ga', 'Glamping Resort', 'Mixed', 'Sage', 'glamping_com_north_america_2026_05', 'United States', 'GA', 'Saint Simons Island', NULL::numeric, NULL::numeric, 'https://www.littlestsimonsisland.com/', $$The Lodge on Little St. Simons Island — North American glamping property featured in the Glamping.com collection (Saint Simons Island, GA).$$, $$Sources: Glamping.com North America directory audit (May 2026). Listing: https://www.glamping.com/destination/north-america/georgia/saint-simons-island/the-lodge-on-little-st-simons-island/$$, '2026-05-26', '2026-05-26', 'private_commercial', 'https://www.glamping.com/destination/north-america/georgia/saint-simons-island/the-lodge-on-little-st-simons-island/'),
  ('published', 'Yes', 'Yes', 'Maui Eco Retreat', 'maui-eco-retreat-haiku-hi', 'Glamping Resort', 'Mixed', 'Sage', 'glamping_com_north_america_2026_05', 'United States', 'HI', 'Haiku', NULL::numeric, NULL::numeric, 'https://www.mauiecoretreat.com/', $$Maui Eco Retreat — North American glamping property featured in the Glamping.com collection (Haiku, HI).$$, $$Sources: Glamping.com North America directory audit (May 2026). Listing: https://www.glamping.com/destination/north-america/hawaii/haiku/maui-eco-retreat/$$, '2026-05-26', '2026-05-26', 'private_commercial', 'https://www.glamping.com/destination/north-america/hawaii/haiku/maui-eco-retreat/'),
  ('published', 'Yes', 'Yes', 'Treehouse Ketchum', 'treehouse-ketchum-ketchum-id', 'Glamping Resort', 'Mixed', 'Sage', 'glamping_com_north_america_2026_05', 'United States', 'ID', 'Ketchum', NULL::numeric, NULL::numeric, 'https://www.treehouseketchum.com/', $$Treehouse Ketchum — North American glamping property featured in the Glamping.com collection (Ketchum, ID).$$, $$Sources: Glamping.com North America directory audit (May 2026). Listing: https://www.glamping.com/destination/north-america/idaho/ketchum/treehouse-ketchum/$$, '2026-05-26', '2026-05-26', 'private_commercial', 'https://www.glamping.com/destination/north-america/idaho/ketchum/treehouse-ketchum/'),
  ('published', 'Yes', 'Yes', 'Elysium Woods', 'elysium-woods-sandpoint-id', 'Glamping Resort', 'Mixed', 'Sage', 'glamping_com_north_america_2026_05', 'United States', 'ID', 'Sandpoint', NULL::numeric, NULL::numeric, 'https://www.elysiumwoods.com/', $$Elysium Woods — North American glamping property featured in the Glamping.com collection (Sandpoint, ID).$$, $$Sources: Glamping.com North America directory audit (May 2026). Listing: https://www.glamping.com/destination/north-america/idaho/sandpoint/elysium-woods/$$, '2026-05-26', '2026-05-26', 'private_commercial', 'https://www.glamping.com/destination/north-america/idaho/sandpoint/elysium-woods/'),
  ('published', 'Yes', 'Yes', 'Spencer Pond Camps', 'spencer-pond-camps-beaver-cove-me', 'Glamping Resort', 'Mixed', 'Sage', 'glamping_com_north_america_2026_05', 'United States', 'ME', 'Beaver Cove', NULL::numeric, NULL::numeric, 'https://www.spencerpondcamps.com/', $$Spencer Pond Camps — North American glamping property featured in the Glamping.com collection (Beaver Cove, ME).$$, $$Sources: Glamping.com North America directory audit (May 2026). Listing: https://www.glamping.com/destination/north-america/maine/beaver-cove/spencer-pond-camps/$$, '2026-05-26', '2026-05-26', 'private_commercial', 'https://www.glamping.com/destination/north-america/maine/beaver-cove/spencer-pond-camps/'),
  ('published', 'Yes', 'Yes', 'Eagle Lake Sporting Camps', 'eagle-lake-sporting-camps-eagle-lake-me', 'Glamping Resort', 'Mixed', 'Sage', 'glamping_com_north_america_2026_05', 'United States', 'ME', 'Eagle Lake', NULL::numeric, NULL::numeric, 'https://www.eaglelake.com/', $$Eagle Lake Sporting Camps — North American glamping property featured in the Glamping.com collection (Eagle Lake, ME).$$, $$Sources: Glamping.com North America directory audit (May 2026). Listing: https://www.glamping.com/destination/north-america/maine/eagle-lake/eagle-lake-sporting-camps/$$, '2026-05-26', '2026-05-26', 'private_commercial', 'https://www.glamping.com/destination/north-america/maine/eagle-lake/eagle-lake-sporting-camps/'),
  ('published', 'Yes', 'Yes', 'Seguin', 'seguin-georgetown-me', 'Glamping Resort', 'Mixed', 'Sage', 'glamping_com_north_america_2026_05', 'United States', 'ME', 'Georgetown', NULL::numeric, NULL::numeric, 'https://www.glamping.com/destination/north-america/maine/georgetown/seguin/', $$Seguin — North American glamping property featured in the Glamping.com collection (Georgetown, ME).$$, $$Sources: Glamping.com North America directory audit (May 2026). Listing: https://www.glamping.com/destination/north-america/maine/georgetown/seguin/$$, '2026-05-26', '2026-05-26', 'private_commercial', 'https://www.glamping.com/destination/north-america/maine/georgetown/seguin/'),
  ('published', 'Yes', 'Yes', 'Triple Creek Ranch', 'triple-creek-ranch-darby-mt', 'Glamping Resort', 'Mixed', 'Sage', 'glamping_com_north_america_2026_05', 'United States', 'MT', 'Darby', NULL::numeric, NULL::numeric, 'https://www.triplecreekranch.com/', $$Triple Creek Ranch — North American glamping property featured in the Glamping.com collection (Darby, MT).$$, $$Sources: Glamping.com North America directory audit (May 2026). Listing: https://www.glamping.com/destination/north-america/montana/darby/triple-creek-ranch/$$, '2026-05-26', '2026-05-26', 'private_commercial', 'https://www.glamping.com/destination/north-america/montana/darby/triple-creek-ranch/'),
  ('published', 'Yes', 'Yes', 'Campamonte', 'campamonte-sayulita-nayarit', 'Glamping Resort', 'Mixed', 'Sage', 'glamping_com_north_america_2026_05', 'Mexico', 'Nayarit', 'Sayulita', NULL::numeric, NULL::numeric, 'https://www.campamonte.com/', $$Campamonte — North American glamping property featured in the Glamping.com collection (Sayulita, Nayarit).$$, $$Sources: Glamping.com North America directory audit (May 2026). Listing: https://www.glamping.com/destination/north-america/nayarit/sayulita/campamonte/$$, '2026-05-26', '2026-05-26', 'private_commercial', 'https://www.glamping.com/destination/north-america/nayarit/sayulita/campamonte/'),
  ('published', 'Yes', 'Yes', 'Rancho Gallina', 'rancho-gallina-santa-fe-nm', 'Glamping Resort', 'Mixed', 'Sage', 'glamping_com_north_america_2026_05', 'United States', 'NM', 'Santa Fe', NULL::numeric, NULL::numeric, 'https://www.glamping.com/destination/north-america/new-mexico/santa-fe/rancho-gallina/', $$Rancho Gallina — North American glamping property featured in the Glamping.com collection (Santa Fe, NM).$$, $$Sources: Glamping.com North America directory audit (May 2026). Listing: https://www.glamping.com/destination/north-america/new-mexico/santa-fe/rancho-gallina/$$, '2026-05-26', '2026-05-26', 'private_commercial', 'https://www.glamping.com/destination/north-america/new-mexico/santa-fe/rancho-gallina/'),
  ('published', 'Yes', 'Yes', 'The Glass House', 'the-glass-house-marlboro-ny', 'Glamping Resort', 'Mixed', 'Sage', 'glamping_com_north_america_2026_05', 'United States', 'NY', 'Marlboro', NULL::numeric, NULL::numeric, 'https://www.theglasshouse.us/', $$The Glass House — North American glamping property featured in the Glamping.com collection (Marlboro, NY).$$, $$Sources: Glamping.com North America directory audit (May 2026). Listing: https://www.glamping.com/destination/north-america/new-york/marlboro/the-glass-house/$$, '2026-05-26', '2026-05-26', 'private_commercial', 'https://www.glamping.com/destination/north-america/new-york/marlboro/the-glass-house/'),
  ('published', 'Yes', 'Yes', 'Mountain Horse Farm B&B and Wellness Retreat', 'mountain-horse-farm-b-b-and-wellness-retreat-naples-ny', 'Glamping Resort', 'Mixed', 'Sage', 'glamping_com_north_america_2026_05', 'United States', 'NY', 'Naples', NULL::numeric, NULL::numeric, 'https://www.mountainhorsefarm.com/', $$Mountain Horse Farm B&B and Wellness Retreat — North American glamping property featured in the Glamping.com collection (Naples, NY).$$, $$Sources: Glamping.com North America directory audit (May 2026). Listing: https://www.glamping.com/destination/north-america/new-york/naples/mountain-horse-farm-bb-and-wellness-retreat/$$, '2026-05-26', '2026-05-26', 'private_commercial', 'https://www.glamping.com/destination/north-america/new-york/naples/mountain-horse-farm-bb-and-wellness-retreat/'),
  ('published', 'Yes', 'Yes', 'Americana Island Cabin at Riverside Escapes', 'americana-island-cabin-at-riverside-escapes-alexander-nc', 'Glamping Resort', 'Mixed', 'Sage', 'glamping_com_north_america_2026_05', 'United States', 'NC', 'Alexander', NULL::numeric, NULL::numeric, 'https://www.glamping.com/destination/north-america/north-carolina/alexander/americana-island-cabin-at-riverside-escapes/', $$Americana Island Cabin at Riverside Escapes — North American glamping property featured in the Glamping.com collection (Alexander, NC).$$, $$Sources: Glamping.com North America directory audit (May 2026). Listing: https://www.glamping.com/destination/north-america/north-carolina/alexander/americana-island-cabin-at-riverside-escapes/$$, '2026-05-26', '2026-05-26', 'private_commercial', 'https://www.glamping.com/destination/north-america/north-carolina/alexander/americana-island-cabin-at-riverside-escapes/'),
  ('published', 'Yes', 'Yes', 'Nantahala Cabins Inc', 'nantahala-cabins-inc-bryson-city-nc', 'Glamping Resort', 'Mixed', 'Sage', 'glamping_com_north_america_2026_05', 'United States', 'NC', 'Bryson City', NULL::numeric, NULL::numeric, 'https://www.glamping.com/destination/north-america/north-carolina/bryson-city/nantahala-cabins-inc/', $$Nantahala Cabins Inc — North American glamping property featured in the Glamping.com collection (Bryson City, NC).$$, $$Sources: Glamping.com North America directory audit (May 2026). Listing: https://www.glamping.com/destination/north-america/north-carolina/bryson-city/nantahala-cabins-inc/$$, '2026-05-26', '2026-05-26', 'private_commercial', 'https://www.glamping.com/destination/north-america/north-carolina/bryson-city/nantahala-cabins-inc/'),
  ('published', 'Yes', 'Yes', 'East Coast Glamping', 'east-coast-glamping-hammonds-plains-ns', 'Glamping Resort', 'Mixed', 'Sage', 'glamping_com_north_america_2026_05', 'Canada', 'NS', 'Hammonds Plains', NULL::numeric, NULL::numeric, 'https://www.glamping.com/destination/north-america/nova-scotia/hammonds-plains/east-coast-glamping-inc/', $$East Coast Glamping — North American glamping property featured in the Glamping.com collection (Hammonds Plains, NS).$$, $$Sources: Glamping.com North America directory audit (May 2026). Listing: https://www.glamping.com/destination/north-america/nova-scotia/hammonds-plains/east-coast-glamping-inc/$$, '2026-05-26', '2026-05-26', 'private_commercial', 'https://www.glamping.com/destination/north-america/nova-scotia/hammonds-plains/east-coast-glamping-inc/'),
  ('published', 'Yes', 'Yes', 'Selina Puerto Escondido', 'selina-puerto-escondido-brisas-de-zicatela-oaxaca', 'Glamping Resort', 'Mixed', 'Sage', 'glamping_com_north_america_2026_05', 'Mexico', 'Oaxaca', 'Brisas De Zicatela', NULL::numeric, NULL::numeric, 'https://www.glamping.com/destination/north-america/oaxaca/brisas-de-zicatela/selina-puerto-escondido/', $$Selina Puerto Escondido — North American glamping property featured in the Glamping.com collection (Brisas De Zicatela, Oaxaca).$$, $$Sources: Glamping.com North America directory audit (May 2026). Listing: https://www.glamping.com/destination/north-america/oaxaca/brisas-de-zicatela/selina-puerto-escondido/$$, '2026-05-26', '2026-05-26', 'private_commercial', 'https://www.glamping.com/destination/north-america/oaxaca/brisas-de-zicatela/selina-puerto-escondido/'),
  ('published', 'Yes', 'Yes', 'Finca Las Nieves', 'finca-las-nieves-puerto-escondido-oaxaca', 'Glamping Resort', 'Mixed', 'Sage', 'glamping_com_north_america_2026_05', 'Mexico', 'Oaxaca', 'Puerto Escondido', NULL::numeric, NULL::numeric, 'https://www.glamping.com/destination/north-america/oaxaca/puerto-escondido/finca-las-nieves/', $$Finca Las Nieves — North American glamping property featured in the Glamping.com collection (Puerto Escondido, Oaxaca).$$, $$Sources: Glamping.com North America directory audit (May 2026). Listing: https://www.glamping.com/destination/north-america/oaxaca/puerto-escondido/finca-las-nieves/$$, '2026-05-26', '2026-05-26', 'private_commercial', 'https://www.glamping.com/destination/north-america/oaxaca/puerto-escondido/finca-las-nieves/'),
  ('published', 'Yes', 'Yes', 'Wren Eagle Retreat', 'wren-eagle-retreat-chillicothe-oh', 'Glamping Resort', 'Mixed', 'Sage', 'glamping_com_north_america_2026_05', 'United States', 'OH', 'Chillicothe', NULL::numeric, NULL::numeric, 'https://www.wreneagle.com/', $$Wren Eagle Retreat — North American glamping property featured in the Glamping.com collection (Chillicothe, OH).$$, $$Sources: Glamping.com North America directory audit (May 2026). Listing: https://www.glamping.com/destination/north-america/ohio/chillicothe/wren-eagle-retreat/$$, '2026-05-26', '2026-05-26', 'private_commercial', 'https://www.glamping.com/destination/north-america/ohio/chillicothe/wren-eagle-retreat/'),
  ('published', 'Yes', 'Yes', 'Outpost Co.', 'outpost-co-temagami-on', 'Glamping Resort', 'Mixed', 'Sage', 'glamping_com_north_america_2026_05', 'Canada', 'ON', 'Temagami', NULL::numeric, NULL::numeric, 'https://www.outpostco.com/', $$Outpost Co. — North American glamping property featured in the Glamping.com collection (Temagami, ON).$$, $$Sources: Glamping.com North America directory audit (May 2026). Listing: https://www.glamping.com/destination/north-america/ontario/temagami/outpostco/$$, '2026-05-26', '2026-05-26', 'private_commercial', 'https://www.glamping.com/destination/north-america/ontario/temagami/outpostco/'),
  ('published', 'Yes', 'Yes', 'Oceanside Beachfront RV Resort', 'oceanside-beachfront-rv-resort-coos-bay-or', 'Glamping Resort', 'Mixed', 'Sage', 'glamping_com_north_america_2026_05', 'United States', 'OR', 'Coos Bay', NULL::numeric, NULL::numeric, 'https://www.glamping.com/destination/north-america/oregon/coos-bay/oceanside-beachfront-rv-resort/', $$Oceanside Beachfront RV Resort — North American glamping property featured in the Glamping.com collection (Coos Bay, OR).$$, $$Sources: Glamping.com North America directory audit (May 2026). Listing: https://www.glamping.com/destination/north-america/oregon/coos-bay/oceanside-beachfront-rv-resort/$$, '2026-05-26', '2026-05-26', 'private_commercial', 'https://www.glamping.com/destination/north-america/oregon/coos-bay/oceanside-beachfront-rv-resort/'),
  ('published', 'Yes', 'Yes', 'Shelter Cove Resort & Marina', 'shelter-cove-resort-marina-crescent-or', 'Glamping Resort', 'Mixed', 'Sage', 'glamping_com_north_america_2026_05', 'United States', 'OR', 'Crescent', NULL::numeric, NULL::numeric, 'https://www.glamping.com/destination/north-america/oregon/crescent/shelter-cove-resort-marina/', $$Shelter Cove Resort & Marina — North American glamping property featured in the Glamping.com collection (Crescent, OR).$$, $$Sources: Glamping.com North America directory audit (May 2026). Listing: https://www.glamping.com/destination/north-america/oregon/crescent/shelter-cove-resort-marina/$$, '2026-05-26', '2026-05-26', 'private_commercial', 'https://www.glamping.com/destination/north-america/oregon/crescent/shelter-cove-resort-marina/'),
  ('published', 'Yes', 'Yes', 'Hintercabin', 'hintercabin-la-conception-qc', 'Glamping Resort', 'Mixed', 'Sage', 'glamping_com_north_america_2026_05', 'Canada', 'QC', 'La Conception', NULL::numeric, NULL::numeric, 'https://www.hintercabin.com/', $$Hintercabin — North American glamping property featured in the Glamping.com collection (La Conception, QC).$$, $$Sources: Glamping.com North America directory audit (May 2026). Listing: https://www.glamping.com/destination/north-america/quebec/la-conception/hintercabin/$$, '2026-05-26', '2026-05-26', 'private_commercial', 'https://www.glamping.com/destination/north-america/quebec/la-conception/hintercabin/'),
  ('published', 'Yes', 'Yes', 'Cane Bay Campground', 'cane-bay-campground-frederiksted-st-croix', 'Glamping Resort', 'Mixed', 'Sage', 'glamping_com_north_america_2026_05', 'US Virgin Islands', 'St. Croix', 'Frederiksted', NULL::numeric, NULL::numeric, 'https://www.glamping.com/destination/north-america/st-croix/frederiksted/cane-bay-campground/', $$Cane Bay Campground — North American glamping property featured in the Glamping.com collection (Frederiksted, St. Croix).$$, $$Sources: Glamping.com North America directory audit (May 2026). Listing: https://www.glamping.com/destination/north-america/st-croix/frederiksted/cane-bay-campground/$$, '2026-05-26', '2026-05-26', 'private_commercial', 'https://www.glamping.com/destination/north-america/st-croix/frederiksted/cane-bay-campground/'),
  ('published', 'Yes', 'Yes', 'Lone Star Court', 'lone-star-court-austin-tx', 'Glamping Resort', 'Mixed', 'Sage', 'glamping_com_north_america_2026_05', 'United States', 'TX', 'Austin', NULL::numeric, NULL::numeric, 'https://www.lonestarcourt.com/', $$Lone Star Court — North American glamping property featured in the Glamping.com collection (Austin, TX).$$, $$Sources: Glamping.com North America directory audit (May 2026). Listing: https://www.glamping.com/destination/north-america/texas/austin/lone-star-court/$$, '2026-05-26', '2026-05-26', 'private_commercial', 'https://www.glamping.com/destination/north-america/texas/austin/lone-star-court/'),
  ('published', 'Yes', 'Yes', 'The Hideaway Ranch', 'the-hideaway-ranch-bluffdale-tx', 'Glamping Resort', 'Mixed', 'Sage', 'glamping_com_north_america_2026_05', 'United States', 'TX', 'Bluffdale', NULL::numeric, NULL::numeric, 'https://www.thehideawayranch.com/', $$The Hideaway Ranch — North American glamping property featured in the Glamping.com collection (Bluffdale, TX).$$, $$Sources: Glamping.com North America directory audit (May 2026). Listing: https://www.glamping.com/destination/north-america/texas/bluffdale/the-hideaway-ranch/$$, '2026-05-26', '2026-05-26', 'private_commercial', 'https://www.glamping.com/destination/north-america/texas/bluffdale/the-hideaway-ranch/'),
  ('published', 'Yes', 'Yes', 'Camp Lucy Cottages', 'camp-lucy-cottages-dripping-springs-tx', 'Glamping Resort', 'Mixed', 'Sage', 'glamping_com_north_america_2026_05', 'United States', 'TX', 'Dripping Springs', NULL::numeric, NULL::numeric, 'https://www.camplucy.com/', $$Camp Lucy Cottages — North American glamping property featured in the Glamping.com collection (Dripping Springs, TX).$$, $$Sources: Glamping.com North America directory audit (May 2026). Listing: https://www.glamping.com/destination/north-america/texas/dripping-springs/camp-lucy-cottages/$$, '2026-05-26', '2026-05-26', 'private_commercial', 'https://www.glamping.com/destination/north-america/texas/dripping-springs/camp-lucy-cottages/'),
  ('published', 'Yes', 'Yes', 'Country Woods Inn', 'country-woods-inn-glen-rose-tx', 'Glamping Resort', 'Mixed', 'Sage', 'glamping_com_north_america_2026_05', 'United States', 'TX', 'Glen Rose', NULL::numeric, NULL::numeric, 'https://www.glamping.com/destination/north-america/texas/glen-rose/country-woods-inn/', $$Country Woods Inn — North American glamping property featured in the Glamping.com collection (Glen Rose, TX).$$, $$Sources: Glamping.com North America directory audit (May 2026). Listing: https://www.glamping.com/destination/north-america/texas/glen-rose/country-woods-inn/$$, '2026-05-26', '2026-05-26', 'private_commercial', 'https://www.glamping.com/destination/north-america/texas/glen-rose/country-woods-inn/'),
  ('published', 'Yes', 'Yes', 'Pico Rodavento', 'pico-rodavento-santa-fe-veracruz', 'Glamping Resort', 'Mixed', 'Sage', 'glamping_com_north_america_2026_05', 'Mexico', 'Veracruz', 'Santa Fe', NULL::numeric, NULL::numeric, 'https://www.glamping.com/destination/north-america/veracruz/santa-fe/pico-rodavento/', $$Pico Rodavento — North American glamping property featured in the Glamping.com collection (Santa Fe, Veracruz).$$, $$Sources: Glamping.com North America directory audit (May 2026). Listing: https://www.glamping.com/destination/north-america/veracruz/santa-fe/pico-rodavento/$$, '2026-05-26', '2026-05-26', 'private_commercial', 'https://www.glamping.com/destination/north-america/veracruz/santa-fe/pico-rodavento/'),
  ('published', 'Yes', 'Yes', 'Sterling Ridge Resort', 'sterling-ridge-resort-jeffersonville-vt', 'Glamping Resort', 'Mixed', 'Sage', 'glamping_com_north_america_2026_05', 'United States', 'VT', 'Jeffersonville', NULL::numeric, NULL::numeric, 'https://www.sterlingridgeresort.com/', $$Sterling Ridge Resort — North American glamping property featured in the Glamping.com collection (Jeffersonville, VT).$$, $$Sources: Glamping.com North America directory audit (May 2026). Listing: https://www.glamping.com/destination/north-america/vermont/jeffersonville/sterling-ridge-resort/$$, '2026-05-26', '2026-05-26', 'private_commercial', 'https://www.glamping.com/destination/north-america/vermont/jeffersonville/sterling-ridge-resort/'),
  ('published', 'Yes', 'Yes', '#1 Rock Tavern River Kamp', '1-rock-tavern-river-kamp-luray-va', 'Glamping Resort', 'Mixed', 'Sage', 'glamping_com_north_america_2026_05', 'United States', 'VA', 'Luray', NULL::numeric, NULL::numeric, 'https://www.glamping.com/destination/north-america/virginia/luray/1-rock-tavern-river-kamp/', $$#1 Rock Tavern River Kamp — North American glamping property featured in the Glamping.com collection (Luray, VA).$$, $$Sources: Glamping.com North America directory audit (May 2026). Listing: https://www.glamping.com/destination/north-america/virginia/luray/1-rock-tavern-river-kamp/$$, '2026-05-26', '2026-05-26', 'private_commercial', 'https://www.glamping.com/destination/north-america/virginia/luray/1-rock-tavern-river-kamp/'),
  ('published', 'Yes', 'Yes', 'Langley Lodging', 'langley-lodging-langley-wa', 'Glamping Resort', 'Mixed', 'Sage', 'glamping_com_north_america_2026_05', 'United States', 'WA', 'Langley', NULL::numeric, NULL::numeric, 'https://www.glamping.com/destination/north-america/washington/langley/langley-lodging/', $$Langley Lodging — North American glamping property featured in the Glamping.com collection (Langley, WA).$$, $$Sources: Glamping.com North America directory audit (May 2026). Listing: https://www.glamping.com/destination/north-america/washington/langley/langley-lodging/$$, '2026-05-26', '2026-05-26', 'private_commercial', 'https://www.glamping.com/destination/north-america/washington/langley/langley-lodging/'),
  ('published', 'Yes', 'Yes', 'Silver Cove RV Resort', 'silver-cove-rv-resort-silver-lake-wa', 'Glamping Resort', 'Mixed', 'Sage', 'glamping_com_north_america_2026_05', 'United States', 'WA', 'Silver Lake', NULL::numeric, NULL::numeric, 'https://www.glamping.com/destination/north-america/washington/silver-lake/silver-cove-rv-resort/', $$Silver Cove RV Resort — North American glamping property featured in the Glamping.com collection (Silver Lake, WA).$$, $$Sources: Glamping.com North America directory audit (May 2026). Listing: https://www.glamping.com/destination/north-america/washington/silver-lake/silver-cove-rv-resort/$$, '2026-05-26', '2026-05-26', 'private_commercial', 'https://www.glamping.com/destination/north-america/washington/silver-lake/silver-cove-rv-resort/'),
  ('published', 'Yes', 'Yes', 'Apple Creek Whitetails', 'apple-creek-whitetails-gillett-wi', 'Glamping Resort', 'Mixed', 'Sage', 'glamping_com_north_america_2026_05', 'United States', 'WI', 'Gillett', NULL::numeric, NULL::numeric, 'https://www.glamping.com/destination/north-america/wisconsin/gillett/apple-creek-whitetails/', $$Apple Creek Whitetails — North American glamping property featured in the Glamping.com collection (Gillett, WI).$$, $$Sources: Glamping.com North America directory audit (May 2026). Listing: https://www.glamping.com/destination/north-america/wisconsin/gillett/apple-creek-whitetails/$$, '2026-05-26', '2026-05-26', 'private_commercial', 'https://www.glamping.com/destination/north-america/wisconsin/gillett/apple-creek-whitetails/'),
  ('published', 'Yes', 'Yes', 'Mulroy''s Irish Acres Farm', 'mulroy-s-irish-acres-farm-new-london-wi', 'Glamping Resort', 'Mixed', 'Sage', 'glamping_com_north_america_2026_05', 'United States', 'WI', 'New London', NULL::numeric, NULL::numeric, 'https://www.glamping.com/destination/north-america/wisconsin/new-london/mulroys-irish-acres-farm/', $$Mulroy's Irish Acres Farm — North American glamping property featured in the Glamping.com collection (New London, WI).$$, $$Sources: Glamping.com North America directory audit (May 2026). Listing: https://www.glamping.com/destination/north-america/wisconsin/new-london/mulroys-irish-acres-farm/$$, '2026-05-26', '2026-05-26', 'private_commercial', 'https://www.glamping.com/destination/north-america/wisconsin/new-london/mulroys-irish-acres-farm/')
) AS v(
  research_status, is_glamping_property, is_open, property_name, slug, property_type, unit_type,
  source, discovery_source, country, state, city, lat, lon, url, description, notes,
  date_added, date_updated, land_operator_category, gc_url
)
WHERE NOT EXISTS (
  SELECT 1 FROM public.all_glamping_properties p
  WHERE lower(trim(p.property_name)) = lower(trim(v.property_name))
     OR lower(trim(p.slug)) = lower(trim(v.slug))
     OR lower(trim(COALESCE(p.url, ''))) = lower(trim(v.url))
     OR lower(trim(COALESCE(p.url, ''))) = lower(trim(v.gc_url))
     OR COALESCE(p.notes, '') ILIKE '%' || replace(v.gc_url, 'https://www.glamping.com', '') || '%'
);
