-- Create the hipcamp table for Hipcamp United States sites data
-- Run this SQL in your Supabase SQL Editor before uploading the CSV
--
-- CSV File: csv/sites-Hipcamp-United States- (1).csv
-- To upload the data, use:
--   npx tsx scripts/upload-hipcamp-csv.ts
--
-- All 139 columns from the CSV are included as TEXT to handle mixed data types

CREATE TABLE IF NOT EXISTS hipcamp (
  id BIGSERIAL PRIMARY KEY,
  duplicatenote TEXT,
  source TEXT,
  date_added TEXT,
  date_updated TEXT,
  property_name TEXT,
  site_name TEXT,
  unit_type TEXT,
  property_type TEXT,
  property_total_sites TEXT,
  quantity_of_units TEXT,
  unit_capacity TEXT,
  year_site_opened TEXT,
  of_locations TEXT,
  address TEXT,
  city TEXT,
  state TEXT,
  zip_code TEXT,
  country TEXT,
  occupancy_rate_2024 TEXT,
  avg_retail_daily_rate_2024 TEXT,
  high_rate_2024 TEXT,
  low_rate_2024 TEXT,
  occupancy_rate_2025 TEXT,
  avg_retail_daily_rate_2025 TEXT,
  high_rate_2025 TEXT,
  low_rate_2025 TEXT,
  retail_daily_rate_fees_2025 TEXT,
  revpar_2025 TEXT,
  high_month_2025 TEXT,
  high_avg_occupancy_2025 TEXT,
  low_month_2025 TEXT,
  low_avg_occupancy_2025 TEXT,
  occupancy_rate_2026 TEXT,
  retail_daily_rate_ytd TEXT,
  retail_daily_rate_fees_ytd TEXT,
  high_rate_2026 TEXT,
  low_rate_2026 TEXT,
  revpar_2026 TEXT,
  high_month_2026 TEXT,
  high_avg_occupancy_2026 TEXT,
  low_month_2026 TEXT,
  low_avg_occupancy_2026 TEXT,
  operating_season_months TEXT,
  operating_season_excel_format TEXT,
  avg_rate_next_12_months TEXT,
  high_rate_next_12_months TEXT,
  low_rate_next_12_months TEXT,
  winter_weekday TEXT,
  winter_weekend TEXT,
  spring_weekday TEXT,
  spring_weekend TEXT,
  summer_weekday TEXT,
  summer_weekend TEXT,
  fall_weekday TEXT,
  fall_weekend TEXT,
  url TEXT,
  description TEXT,
  minimum_nights TEXT,
  getting_there TEXT,
  lon TEXT,
  lat TEXT,
  toilet TEXT,
  hot_tub_sauna TEXT,
  pool TEXT,
  pets TEXT,
  water TEXT,
  shower TEXT,
  trash TEXT,
  cooking_equipment TEXT,
  picnic_table TEXT,
  wifi TEXT,
  laundry TEXT,
  campfires TEXT,
  playground TEXT,
  rv_vehicle_length TEXT,
  rv_parking TEXT,
  rv_accommodates_slideout TEXT,
  rv_surface_type TEXT,
  rv_surface_level TEXT,
  rv_vehicles_fifth_wheels TEXT,
  rv_vehicles_class_a_rvs TEXT,
  rv_vehicles_class_b_rvs TEXT,
  rv_vehicles_class_c_rvs TEXT,
  rv_vehicles_toy_hauler TEXT,
  fishing TEXT,
  surfing TEXT,
  horseback_riding TEXT,
  paddling TEXT,
  climbing TEXT,
  off_roading_ohv TEXT,
  boating TEXT,
  swimming TEXT,
  wind_sports TEXT,
  snow_sports TEXT,
  whitewater_paddling TEXT,
  fall_fun TEXT,
  hiking TEXT,
  wildlife_watching TEXT,
  biking TEXT,
  ranch TEXT,
  beach TEXT,
  coastal TEXT,
  suburban TEXT,
  forest TEXT,
  field TEXT,
  wetlands TEXT,
  hot_spring TEXT,
  desert TEXT,
  canyon TEXT,
  waterfall TEXT,
  swimming_hole TEXT,
  lake TEXT,
  cave TEXT,
  redwoods TEXT,
  farm TEXT,
  river_stream_or_creek TEXT,
  mountainous TEXT,
  sage_p_amenity_food_on_site TEXT,
  waterfront TEXT,
  restaurant TEXT,
  dog_park TEXT,
  clubhouse TEXT,
  canoeing_kayaking TEXT,
  alcohol_available TEXT,
  golf_cart_rental TEXT,
  private_bathroom TEXT,
  waterpark TEXT,
  kitchen TEXT,
  patio TEXT,
  electricity TEXT,
  general_store TEXT,
  cable TEXT,
  charcoal_grill TEXT,
  sewer_hook_up TEXT,
  electrical_hook_up TEXT,
  generators_allowed TEXT,
  water_hookup TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable Row Level Security
ALTER TABLE hipcamp ENABLE ROW LEVEL SECURITY;

-- Allow public read access (optional - adjust as needed for your use case)
CREATE POLICY "Allow public read access" ON hipcamp
  FOR SELECT
  USING (true);

-- Create indexes for common queries
CREATE INDEX IF NOT EXISTS idx_hipcamp_coordinates ON hipcamp (lat, lon) WHERE lat IS NOT NULL AND lon IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_hipcamp_property_name ON hipcamp (property_name);
CREATE INDEX IF NOT EXISTS idx_hipcamp_location ON hipcamp (city, state);
CREATE INDEX IF NOT EXISTS idx_hipcamp_state ON hipcamp (state);
