-- Audit log of QuickBooks invoice remap actions (admin, cron, webhook, script).

CREATE TABLE IF NOT EXISTS public.quickbooks_remap_history (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz NOT NULL DEFAULT now(),
  source text NOT NULL CHECK (source IN ('admin', 'cron', 'webhook', 'script')),
  action text NOT NULL CHECK (action IN ('updated', 'matched_dry_run', 'error')),
  dry_run boolean NOT NULL DEFAULT false,
  invoice_id text NOT NULL,
  doc_number text,
  txn_date text,
  matched_line_ids text[] NOT NULL DEFAULT '{}',
  matched_descriptions text[] NOT NULL DEFAULT '{}',
  source_item_name text NOT NULL,
  target_item_id text,
  target_item_name text,
  error_message text,
  actor_user_id uuid,
  actor_email text
);

CREATE INDEX IF NOT EXISTS quickbooks_remap_history_created_at_idx
  ON public.quickbooks_remap_history (created_at DESC);

CREATE INDEX IF NOT EXISTS quickbooks_remap_history_doc_number_idx
  ON public.quickbooks_remap_history (doc_number);

CREATE INDEX IF NOT EXISTS quickbooks_remap_history_action_idx
  ON public.quickbooks_remap_history (action);

ALTER TABLE public.quickbooks_remap_history ENABLE ROW LEVEL SECURITY;

COMMENT ON TABLE public.quickbooks_remap_history IS
  'Audit trail of INV- Appraisal Review → Feasibility Study remaps. Service-role only.';
