-- East Zion Resort: site inventory from eastzionresort.com/lodging + Guesty (May 2026)
-- Enriches anchor row id 12182; updates yurt row 12183; inserts 9 sibling lodging category rows.

UPDATE public.all_glamping_properties SET
  property_id = '3e27838b-f2d5-4431-943f-07286f65144c'::uuid,
  site_name = 'Glamping Tent',
  slug = 'east-zion-resort-glamping-tent-orderville-ut',
  property_type = 'Glamping Resort',
  unit_type = 'Safari Tent',
  source = 'Sage',
  discovery_source = 'web_research_east_zion_lodging_2026_05',
  country = 'United States',
  state = 'UT',
  city = 'Orderville',
  address = '490 E State St, Orderville, UT 84758',
  zip_code = '84758',
  lat = 37.280,
  lon = -112.638,
  url = 'https://www.eastzionresort.com/lodging',
  phone_number = '+1-833-378-9466',
  research_status = 'published',
  is_glamping_property = 'Yes',
  is_open = 'Yes',
  property_total_sites = 57,
  quantity_of_units = 10,
  unit_capacity = '4',
  minimum_nights = '1',
  operating_season_months = 'Year-round (pools Feb 28–Dec 1)',
  unit_private_bathroom = 'Yes',
  unit_shower = 'Yes',
  unit_kitchenette = 'Yes',
  unit_wifi = 'Yes',
  unit_air_conditioning = 'Yes',
  unit_campfires = 'Yes',
  unit_hot_tub = 'No',
  property_family_friendly = 'Yes',
  setting_desert = 'Yes',
  setting_forest = 'Yes',
  activities_hiking = 'Yes',
  activities_wildlife_watching = 'Yes',
  land_operator_category = 'private_commercial',
  date_updated = '2026-05-21',
  description = $$East Zion Resort — luxury glamping resort in Orderville, Utah between Zion and Bryce Canyon. Two campuses (The Hillside at 490 E State St; The Escape at 125 S Center St) plus The Lodge and Zion Cliffs Cabin. Categories: glamping tents, yurts, stargazer cabins, mirror houses, treetop cabins, Airstreams, modern cabins, tiny homes, original treehouse, Zion Cliffs Cabin, and group lodge. Resort pools, lazy river, hot tubs, pickleball, via ferrata, ROAM adventure desk.$$,
  unit_description = $$Glamping Tent category: canvas tents on The Hillside with kitchenette (microwave, two-burner stove, fridge), full bathroom (tub + shower), A/C, deck and propane grill; sleeps up to 4 (two beds). Numbered inventory Glamping Tent #1–#10 per resort site.$$,
  notes = COALESCE(notes, '') || E'\n\nSite enrichment (May 2026): eastzionresort.com/lodging; Guesty lists 57 bookable units. Glamping tents #1–#10 at Hillside. Booking: reservationseastzionresort.guestybookings.com.',
  amenities_raw = 'Kitchenette; full bathroom; A/C; Wi-Fi; deck; propane grill; gas firepit; resort pools and hot tubs; 4 guests max per tent.',
  rate_unit_rates_by_year = '{"2026":{"guesty_property_count":57,"sample_from_rates_usd":{"airstream":89,"stargazer_cabin":141,"mirror_house":133,"lodge":549},"note":"Category ADRs vary; re-quote in Guesty for travel dates"}}'::jsonb
WHERE id = 12182;

UPDATE public.all_glamping_properties SET
  property_id = '3e27838b-f2d5-4431-943f-07286f65144c'::uuid,
  site_name = 'Yurt',
  slug = 'east-zion-resort-yurt-orderville-ut',
  property_type = 'Glamping Resort',
  unit_type = 'Yurt',
  source = 'Sage',
  discovery_source = 'web_research_east_zion_lodging_2026_05',
  country = 'United States',
  state = 'UT',
  city = 'Orderville',
  address = '490 E State St, Orderville, UT 84758',
  zip_code = '84758',
  lat = 37.280,
  lon = -112.638,
  url = 'https://www.eastzionresort.com/yurts',
  phone_number = '+1-833-378-9466',
  research_status = 'published',
  is_glamping_property = 'Yes',
  is_open = 'Yes',
  property_total_sites = 57,
  quantity_of_units = 10,
  unit_capacity = '6',
  minimum_nights = '1',
  operating_season_months = 'Year-round (pools Feb 28–Dec 1)',
  unit_private_bathroom = 'Yes',
  unit_shower = 'Yes',
  unit_kitchenette = 'Yes',
  unit_wifi = 'Yes',
  unit_air_conditioning = 'Yes',
  unit_campfires = 'Yes',
  unit_hot_tub = 'No',
  property_family_friendly = 'Yes',
  setting_desert = 'Yes',
  setting_forest = 'Yes',
  activities_hiking = 'Yes',
  activities_wildlife_watching = 'Yes',
  land_operator_category = 'private_commercial',
  date_updated = '2026-05-21',
  description = 'Sibling site — East Zion Resort (Orderville UT). See anchor row id 12182.',
  unit_description = $$Yurt category on The Hillside: round glamping yurts with kitchenette, full bathroom, deck, A/C; larger yurts sleep up to 6 (two king beds + sofa). Numbered inventory Yurt #1–#10.$$,
  notes = 'Yurt #1–#10; re-quote in Guesty.',
  amenities_raw = 'Kitchenette; full bathroom; king beds; sofa bed; deck; grill; firepit; resort amenities.',
  rate_unit_rates_by_year = '{"2026":{"numbered_units":"Yurt #1-#10"}}'::jsonb
WHERE id = 12183;

INSERT INTO public.all_glamping_properties (
  property_id, research_status, is_glamping_property, is_open,
  property_name, site_name, slug, property_type, unit_type,
  source, discovery_source, country, state, city,
  address, zip_code, lat, lon, url, phone_number,
  description, unit_description, notes,
  date_added, date_updated, land_operator_category,
  property_total_sites, quantity_of_units, unit_capacity, minimum_nights,
  operating_season_months,
  rate_unit_rates_by_year,
  unit_private_bathroom, unit_shower, unit_kitchenette, unit_wifi,
  unit_air_conditioning, unit_campfires, unit_hot_tub,
  property_family_friendly, setting_desert, setting_forest,
  activities_hiking, activities_wildlife_watching, amenities_raw
) VALUES
(
  '3e27838b-f2d5-4431-943f-07286f65144c'::uuid, 'published', 'Yes', 'Yes',
  'East Zion Resort', 'Stargazer Cabin', 'east-zion-resort-glamping-tent-orderville-ut', 'Glamping Resort', 'Cabin',
  'Sage', 'web_research_east_zion_lodging_2026_05', 'United States', 'UT', 'Orderville',
  '490 E State St, Orderville, UT 84758', '84758', 37.280, -112.638,
  'https://www.eastzionresort.com/stargazer-cabin', '+1-833-378-9466',
  'Sibling site — East Zion Resort. See anchor row id 12182.',
  'Stargazer Cabin: glass-ceiling bedroom cabins for dark-sky viewing; king bed (some sleep 4 with sofa); kitchenette, full bath, patio, grill, firepit. Named units include Hidden Abode, Star Gazer, Red Hollow, Wild Sage.',
  'Named stargazer units on marketing site; additional titles on Guesty.',
  '2026-05-21', '2026-05-21', 'private_commercial', 57, 5, '4', '1', 'Year-round',
  '{"2026":{"named_units":["Hidden Abode","Star Gazer","Red Hollow","Wild Sage","Valley View"]}}'::jsonb,
  'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes',
  'Glass ceiling; stargazing; kitchenette; king bed; resort pools and hot tubs.'
),
(
  '3e27838b-f2d5-4431-943f-07286f65144c'::uuid, 'published', 'Yes', 'Yes',
  'East Zion Resort', 'Mirror House', 'east-zion-resort-glamping-tent-orderville-ut', 'Glamping Resort', 'Tiny House',
  'Sage', 'web_research_east_zion_lodging_2026_05', 'United States', 'UT', 'Orderville',
  '490 E State St, Orderville, UT 84758', '84758', 37.280, -112.638,
  'https://www.eastzionresort.com/mirror-house-rentals', '+1-833-378-9466',
  'Sibling site — East Zion Resort. See anchor row id 12182.',
  'Mirror House: mirrored-facade tiny homes on cliffside Hillside; king bed, full bath, kitchenette, grill, firepit; sleeps 2. Units: Mirror Mountain, Mirror Zion, Mirror Overlook.',
  '3 mirror houses on site.',
  '2026-05-21', '2026-05-21', 'private_commercial', 57, 3, '2', '1', 'Year-round',
  '{"2026":{"named_units":["Mirror Mountain","Mirror Zion","Mirror Overlook"]}}'::jsonb,
  'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes',
  'Mirrored facade; panoramic views; kitchenette; king bed.'
),
(
  '3e27838b-f2d5-4431-943f-07286f65144c'::uuid, 'published', 'Yes', 'Yes',
  'East Zion Resort', 'Treetop Cabin', 'east-zion-resort-glamping-tent-orderville-ut', 'Glamping Resort', 'Cabin',
  'Sage', 'web_research_east_zion_lodging_2026_05', 'United States', 'UT', 'Orderville',
  '490 E State St, Orderville, UT 84758', '84758', 37.280, -112.638,
  'https://www.eastzionresort.com/treetop-cabins', '+1-833-378-9466',
  'Sibling site — East Zion Resort. See anchor row id 12182.',
  'Treetop Cabin: elevated wood cabins with rooftop stargazing window, king bed, sofa bed, full bath, kitchenette; sleeps 3–4. Treetop Cabin #1–#10.',
  '10 treetop cabins.',
  '2026-05-21', '2026-05-21', 'private_commercial', 57, 10, '4', '1', 'Year-round',
  '{"2026":{"numbered_units":"Treetop Cabin #1-#10"}}'::jsonb,
  'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes',
  'Rooftop skylight; king bed; sofa bed; deck; grill; resort amenities.'
),
(
  '3e27838b-f2d5-4431-943f-07286f65144c'::uuid, 'published', 'Yes', 'Yes',
  'East Zion Resort', 'Airstream', 'east-zion-resort-glamping-tent-orderville-ut', 'Glamping Resort', 'RV',
  'Sage', 'web_research_east_zion_lodging_2026_05', 'United States', 'UT', 'Orderville',
  '490 E State St, Orderville, UT 84758', '84758', 37.280, -112.638,
  'https://www.eastzionresort.com/airstream-camping', '+1-833-378-9466',
  'Sibling site — East Zion Resort. See anchor row id 12182.',
  'Airstream: retro Airstream glamping near pickleball courts; queen bed, stand-up shower, kitchenette, patio, grill, firepit; sleeps 3. Units: Airstream Dream, Adventure, Legacy, Canyon, Landing.',
  '5 Airstreams on Hillside.',
  '2026-05-21', '2026-05-21', 'private_commercial', 57, 5, '3', '1', 'Year-round',
  '{"2026":{"named_units":["Airstream Dream","Airstream Adventure","Airstream Legacy","Airstream Canyon","Airstream Landing"]}}'::jsonb,
  'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes',
  'Queen bed; stand-up shower; kitchenette; patio; pickleball adjacency.'
),
(
  '3e27838b-f2d5-4431-943f-07286f65144c'::uuid, 'published', 'Yes', 'Yes',
  'East Zion Resort', 'Modern Cabin', 'east-zion-resort-glamping-tent-orderville-ut', 'Glamping Resort', 'Cabin',
  'Sage', 'web_research_east_zion_lodging_2026_05', 'United States', 'UT', 'Orderville',
  '490 E State St, Orderville, UT 84758', '84758', 37.280, -112.638,
  'https://www.eastzionresort.com/zion-cabins', '+1-833-378-9466',
  'Sibling site — East Zion Resort. See anchor row id 12182.',
  'Modern Cabin (Zion Cabins): container-conversion cabins with floor-to-ceiling glass, king/queen + sofa, kitchenette, full bath; sleeps 4. Units: Iron Cliff, Blackstone, Desert Sand, Mountain View.',
  '4 modern cabins on Hillside.',
  '2026-05-21', '2026-05-21', 'private_commercial', 57, 4, '4', '1', 'Year-round',
  '{"2026":{"named_units":["Iron Cliff","Blackstone","Desert Sand","Mountain View"]}}'::jsonb,
  'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes',
  'Container cabin; glass walls; roll-up garage door; panoramic views.'
),
(
  '3e27838b-f2d5-4431-943f-07286f65144c'::uuid, 'published', 'Yes', 'Yes',
  'East Zion Resort', 'Tiny Home', 'east-zion-resort-glamping-tent-orderville-ut', 'Glamping Resort', 'Tiny House',
  'Sage', 'web_research_east_zion_lodging_2026_05', 'United States', 'UT', 'Orderville',
  '125 S Center St, Orderville, UT 84758', '84758', 37.280, -112.638,
  'https://www.eastzionresort.com/tiny-houses5-6', '+1-833-378-9466',
  'Sibling site — East Zion Resort. See anchor row id 12182.',
  'Tiny Home at The Escape: full kitchen, washer/dryer, king beds, patio/rooftop deck; sleeps 4–6. Tiny House #1–#6.',
  'The Escape campus; 6 tiny homes.',
  '2026-05-21', '2026-05-21', 'private_commercial', 57, 6, '6', '1', 'Year-round',
  '{"2026":{"numbered_units":"Tiny House #1-#6","campus":"The Escape"}}'::jsonb,
  'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes',
  'Full kitchen; washer/dryer; rooftop deck; The Escape location.'
),
(
  '3e27838b-f2d5-4431-943f-07286f65144c'::uuid, 'published', 'Yes', 'Yes',
  'East Zion Resort', 'The Original Treehouse', 'east-zion-resort-glamping-tent-orderville-ut', 'Glamping Resort', 'Treehouse',
  'Sage', 'web_research_east_zion_lodging_2026_05', 'United States', 'UT', 'Orderville',
  '125 S Center St, Orderville, UT 84758', '84758', 37.280, -112.638,
  'https://www.eastzionresort.com/treehouse', '+1-833-378-9466',
  'Sibling site — East Zion Resort. See anchor row id 12182.',
  'The Original Treehouse: single treehouse built on preserved 100-year cottonwood trunk at The Escape; king bed, sofa, full bath, kitchenette; sleeps 3–4.',
  'One-of-a-kind unit.',
  '2026-05-21', '2026-05-21', 'private_commercial', 57, 1, '4', '1', 'Year-round',
  NULL,
  'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes',
  'Cottonwood trunk treehouse; rock-climb entry; Sugar Knoll views.'
),
(
  '3e27838b-f2d5-4431-943f-07286f65144c'::uuid, 'published', 'Yes', 'Yes',
  'East Zion Resort', 'Zion Cliffs Cabin', 'east-zion-resort-glamping-tent-orderville-ut', 'Glamping Resort', 'Cabin',
  'Sage', 'web_research_east_zion_lodging_2026_05', 'United States', 'UT', 'Orderville',
  'Red Rock Dr, Orderville, UT 84758', '84758', 37.280, -112.638,
  'https://www.eastzionresort.com/family-rentals', '+1-833-378-9466',
  'Sibling site — East Zion Resort. See anchor row id 12182.',
  'Zion Cliffs Cabin: historic original East Zion log cabin on Red Rock Dr with resort amenity access.',
  'Guesty: Cabin Nestled in the Cliffs.',
  '2026-05-21', '2026-05-21', 'private_commercial', 57, 1, '6', '1', 'Year-round',
  NULL,
  'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes',
  'Historic log cabin; cliff views; resort pools and hot tubs.'
),
(
  '3e27838b-f2d5-4431-943f-07286f65144c'::uuid, 'published', 'Yes', 'Yes',
  'East Zion Resort', 'The Lodge', 'east-zion-resort-glamping-tent-orderville-ut', 'Glamping Resort', 'Lodge',
  'Sage', 'web_research_east_zion_lodging_2026_05', 'United States', 'UT', 'Orderville',
  '708 Red Rock Dr, Orderville, UT 84758', '84758', 37.280, -112.638,
  'https://www.eastzionresort.com/lodge', '+1-833-378-9466',
  'Sibling site — East Zion Resort. See anchor row id 12182.',
  'The Lodge at East Zion: group lodge with adjacent Farmhouse Suite; sleeps up to 35–36 guests; weddings and retreats; resort pool access.',
  'Guesty from ~$549/night.',
  '2026-05-21', '2026-05-21', 'private_commercial', 57, 1, '36', '1', 'Year-round',
  '{"2026":{"guesty_title":"The Lodge at East Zion (sleeps 36)","from_rate_usd":549}}'::jsonb,
  'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes',
  'Group lodge; farmhouse suite; events; sleeps 36.'
);

UPDATE public.all_glamping_properties SET
  description = 'Sibling site — East Zion Resort (Orderville UT). See anchor row id 12182.',
  url = 'https://www.eastzionresort.com/lodging',
  phone_number = '+1-833-378-9466',
  country = 'United States',
  state = 'UT',
  city = 'Orderville',
  property_total_sites = 57,
  minimum_nights = '1',
  is_glamping_property = 'Yes',
  is_open = 'Yes',
  property_type = 'Glamping Resort',
  slug = 'east-zion-resort-glamping-tent-orderville-ut',
  land_operator_category = 'private_commercial',
  property_family_friendly = 'Yes',
  setting_desert = 'Yes',
  setting_forest = 'Yes',
  activities_hiking = 'Yes',
  activities_wildlife_watching = 'Yes',
  unit_private_bathroom = 'Yes',
  unit_shower = 'Yes',
  unit_wifi = 'Yes',
  unit_air_conditioning = 'Yes'
WHERE property_name = 'East Zion Resort' AND id NOT IN (12182, 12183);
