-- Highwood Retreat (Springfield VT): ResNexus enrichment for 3 safari tent camps.
-- Sources: ResNexus book engine C19E9143-1FF2-4069-9DF7-941074AC9852, highwoodretreat.com/camps + /faq (May 2026).

-- Shared property_id for all unit rows at this resort.
UPDATE public.all_glamping_properties SET property_id = 'ea257743-1b29-48da-bf41-5cfede9bdc73'
WHERE property_name = 'Highwood Retreat';

UPDATE public.all_glamping_properties SET
  property_name = 'Highwood Retreat',
  site_name = 'The East Camp',
  slug = 'highwood-retreat-east-camp-springfield-vt',
  url = 'https://resnexus.com/resnexus/reservations/book/C19E9143-1FF2-4069-9DF7-941074AC9852',
  city = 'Springfield',
  state = 'VT',
  country = 'United States',
  address = '237 Randall Hill Rd',
  zip_code = '05156',
  lat = 43.298,
  lon = -72.478,
  is_open = 'Yes',
  research_status = 'published',
  is_glamping_property = 'Yes',
  property_type = 'Glamping Resort',
  unit_type = 'Safari Tent',
  property_total_sites = 3,
  quantity_of_units = 1,
  unit_capacity = '2',
  minimum_nights = '1',
  operating_season_months = 'Year-round',
  unit_private_bathroom = 'Yes',
  unit_shower = 'Yes',
  unit_kitchenette = 'No',
  unit_air_conditioning = 'No',
  unit_campfires = 'Yes',
  unit_wifi = 'No',
  unit_pets = 'Yes',
  property_family_friendly = 'No',
  setting_forest = 'Yes',
  setting_mountainous = 'Yes',
  activities_hiking = 'Yes',
  activities_wildlife_watching = 'Yes',
  description = $$Highwood Retreat — year-round luxury safari-tent camp on 160 private acres in southern Vermont (Springfield). Three hand-crafted canvas camps (East, West, and South opening spring 2026) with ResNexus booking, off-grid battery power, excellent cell service, and no Wi‑Fi. Check-in 4pm / check-out 11am; shuttle from parking (~4–5 min walk). Pet fee $60 per dog (max 2); adults-only (max 2 guests per camp, no children/babies).$$,
  unit_description = $$The East Camp: safari tent with luxury linens, spa robes/slippers, wood-burning stove (firewood included), private deck, fire pit, cooler with ice on request, and composting toilet + safari sink in a private bathhouse steps from the tent (Separette). Seasonal cedar outdoor shower May–Oct. Room service menu (cheese + charcuterie board); no in-tent cooking—bring camp stove or cook on fire pit.$$,
  notes = COALESCE(notes, '') || E'\n\nResNexus enrichment (May 2026): The East Camp unit=1. Standard Rate sample $195/night (2026-05-20→21, 2 guests, +taxes/fees). Pet fee via gift shop tab. FAQ: highwoodretreat.com/faq.',
  amenities_raw = 'Fire pit, firewood, outdoor shower (May–Oct), robes & slippers, coffee & tea, drinking water, dishes & flatware, glassware, Bluetooth speaker, electric kettle, cooler, room service, pet friendly.',
  discovery_source = 'web_research_highwood_resnexus_2026_05',
  date_updated = '2026-05-19',
  land_operator_category = 'private_commercial',
  rate_avg_retail_daily_rate = 195,
  rate_summer_weekday = 195,
  rate_summer_weekend = 195,
  rate_unit_rates_by_year = '{"2026":{"standard":{"base_nightly":195,"included_guests":2,"pet_fee_per_dog":60,"max_pets":2,"note":"ResNexus Standard Rate sample 2026-05-20; taxes/fees additional"}}}'::jsonb
WHERE id = 12118;

UPDATE public.all_glamping_properties SET
  property_name = 'Highwood Retreat',
  site_name = 'The West Camp',
  slug = 'highwood-retreat-west-camp-springfield-vt',
  url = 'https://resnexus.com/resnexus/reservations/book/C19E9143-1FF2-4069-9DF7-941074AC9852',
  city = 'Springfield',
  state = 'VT',
  country = 'United States',
  address = '237 Randall Hill Rd',
  zip_code = '05156',
  lat = 43.298,
  lon = -72.478,
  is_open = 'Yes',
  research_status = 'published',
  is_glamping_property = 'Yes',
  property_type = 'Glamping Resort',
  unit_type = 'Safari Tent',
  property_total_sites = 3,
  quantity_of_units = 1,
  unit_capacity = '2',
  minimum_nights = '1',
  operating_season_months = 'Year-round',
  unit_private_bathroom = 'Yes',
  unit_shower = 'Yes',
  unit_kitchenette = 'No',
  unit_air_conditioning = 'No',
  unit_campfires = 'Yes',
  unit_wifi = 'No',
  unit_pets = 'Yes',
  property_family_friendly = 'No',
  setting_forest = 'Yes',
  setting_mountainous = 'Yes',
  activities_hiking = 'Yes',
  activities_wildlife_watching = 'Yes',
  description = $$Sibling site — Highwood Retreat (Springfield VT). See anchor row id 12118.$$,
  unit_description = $$The West Camp: tree-line safari tent with en-suite SunMar composting toilet and safari sink, luxury bedding, robes/slippers, wood stove, private deck, fire pit, cooler, seasonal outdoor shower (May–Oct), and room service. Same property policies as East Camp.$$,
  notes = COALESCE(notes, '') || E'\n\nResNexus enrichment (May 2026): The West Camp unit=2. Rate aligns with East Camp Standard Rate ($195/night sample); verify seasonal calendar pricing.',
  amenities_raw = 'Fire pit, firewood, outdoor shower (May–Oct), robes & slippers, coffee & tea, drinking water, glassware, Bluetooth speaker, electric kettle, cooler, room service, en-suite composting bath, pet friendly.',
  discovery_source = 'web_research_highwood_resnexus_2026_05',
  date_updated = '2026-05-19',
  land_operator_category = 'private_commercial',
  rate_avg_retail_daily_rate = 195,
  rate_summer_weekday = 195,
  rate_summer_weekend = 195,
  rate_unit_rates_by_year = '{"2026":{"standard":{"base_nightly":195,"included_guests":2,"pet_fee_per_dog":60,"max_pets":2,"note":"Assumed same Standard Rate as East Camp; confirm in ResNexus"}}}'::jsonb
WHERE id = 12119;

UPDATE public.all_glamping_properties SET
  property_name = 'Highwood Retreat',
  site_name = 'The South Camp',
  slug = 'highwood-retreat-south-camp-springfield-vt',
  url = 'https://resnexus.com/resnexus/reservations/book/C19E9143-1FF2-4069-9DF7-941074AC9852',
  city = 'Springfield',
  state = 'VT',
  country = 'United States',
  address = '237 Randall Hill Rd',
  zip_code = '05156',
  lat = 43.298,
  lon = -72.478,
  is_open = 'Under Construction',
  research_status = 'in_progress',
  is_glamping_property = 'Yes',
  property_type = 'Glamping Resort',
  unit_type = 'Safari Tent',
  property_total_sites = 3,
  quantity_of_units = 1,
  unit_capacity = '2',
  operating_season_months = 'Opening spring 2026 (operator)',
  unit_pets = 'Yes',
  property_family_friendly = 'No',
  setting_forest = 'Yes',
  setting_mountainous = 'Yes',
  description = $$Sibling site — Highwood Retreat (Springfield VT). Third safari tent; ResNexus waitlist only (May 2026).$$,
  unit_description = $$The South Camp: under construction for spring 2026 opening per operator; amenities expected to match East/West camps.$$,
  notes = COALESCE(notes, '') || E'\n\nResNexus (May 2026): The South Camp (coming soon!) unit=15 — Join Waitlist; no published nightly rate yet.',
  discovery_source = 'web_research_highwood_resnexus_2026_05',
  date_updated = '2026-05-19',
  land_operator_category = 'private_commercial'
WHERE id = 12120;
