-- Lone Mountain Ranch (Big Sky MT): 26 cabin site rows from lonemountainranch.com/cabins (May 2026).
-- Rates: Synxis category proxies (B&B package sample Mar 2026) where per-SKU nightly not published; +taxes/fees.

UPDATE public.all_glamping_properties SET
  property_name = 'Lone Mountain Ranch',
  site_name = 'Ouzel Cabin',
  url = 'https://lonemountainranch.com/cabins/ouzel/',
  unit_type = 'Cabin',
  property_total_sites = 26,
  quantity_of_units = 1,
  unit_capacity = '4',
  operating_season_months = 'Year-round guest ranch; seasonal activity mix (Nordic winter, summer adventure)',
  unit_private_bathroom = 'Yes',
  unit_shower = 'Yes',
  unit_full_kitchen = 'No',
  unit_wifi = 'Yes',
  unit_pets = 'No',
  unit_campfires = 'Yes',
  unit_picnic_table = 'No',
  unit_patio = 'Yes',
  unit_gas_fireplace = 'No',
  unit_hot_tub = 'No',
  unit_wood_burning_stove = 'Yes',
  property_restaurant = 'Yes',
  property_food_on_site = 'Yes',
  property_sauna = 'Yes',
  property_hot_tub = 'Yes',
  property_family_friendly = 'Yes',
  setting_ranch = 'Yes',
  setting_forest = 'Yes',
  setting_mountainous = 'Yes',
  activities_hiking = 'Yes',
  activities_horseback_riding = 'Yes',
  activities_fishing = 'Yes',
  activities_snow_sports = 'Yes',
  activities_wildlife_watching = 'Yes',
  activities_scenic_drives = 'Yes',
  description = $$Lone Mountain Ranch — luxury historic guest ranch on ~148 acres at 750 Lone Mountain Ranch Road, Big Sky MT (40 min Bozeman airport; ~18 mi to Yellowstone). 26 handcrafted log cabins (1–6 bedrooms) blending pioneer craftsmanship and modern comfort. On-site Horn & Cantle restaurant, spa, 80+ km Nordic ski trails, horseback riding, fly fishing, sleighride dinners, Yellowstone tours. Reservations: Synxis Hotel 42113 or 800-514-4644.$$,
  unit_description = $$Ouzel Cabin: king bed, queen sleeper sofa, sitting area, woodstove, clawfoot tub & walk-in shower, private deck with mountain views. Sleeps 2–4.$$,
  notes = COALESCE(notes, '') || E'\n\nSite enrichment (May 2026): 26 cabins from lonemountainranch.com/cabins + Synxis Hotel=42113. Published per-cabin nightly rates not on marketing site; B&B package category proxies used where noted.',
  amenities_raw = 'Ranch: Horn & Cantle dining, spa, Nordic centre (80+ km trails), horseback, fly fishing, Yellowstone tours, sleighride dinners. Cabin: twice-daily housekeeping, morning coffee, wood-burning stove, luxury bath, private/shared deck.',
  discovery_source = 'web_research_lonemountainranch_synxis_2026_05',
  date_updated = '2026-05-18',
  rate_avg_retail_daily_rate = 1100,
  rate_summer_weekday = 1100,
  rate_summer_weekend = 1100,
  rate_winter_weekday = 1100,
  rate_winter_weekend = 1100,
  rate_unit_rates_by_year = '{"2026":{"bed_breakfast_proxy":{"weekday":1100,"weekend":1100,"note":"Synxis B&B 1BR king+sofa category ~$1100/night sample Mar 2026; +taxes/fees; verify per dates"}}}'::jsonb
WHERE id = 11666;

INSERT INTO public.all_glamping_properties (  property_id,
  research_status, is_glamping_property, is_open,
  property_name, site_name, slug, property_type, unit_type,
  source, discovery_source, country, state, city,
  address, zip_code, lat, lon, url, phone_number,
  description, unit_description, notes,
  date_added, date_updated, land_operator_category,
  property_total_sites, quantity_of_units, unit_capacity,
  rate_avg_retail_daily_rate, rate_summer_weekday, rate_summer_weekend,
  rate_winter_weekday, rate_winter_weekend,
  rate_unit_rates_by_year,
  unit_private_bathroom, unit_shower, unit_full_kitchen,
  unit_pets, unit_campfires, unit_patio, unit_wood_burning_stove,
  property_restaurant, property_food_on_site, property_sauna, property_hot_tub, property_family_friendly,
  setting_ranch, setting_forest, setting_mountainous,
  activities_hiking, activities_horseback_riding, activities_fishing, activities_snow_sports,
  activities_wildlife_watching, activities_scenic_drives,
  amenities_raw) VALUES (
  '88e6fdfd-3aed-4c1e-8726-509900bea596',
  'published', 'Yes', 'Yes',
  'Lone Mountain Ranch', 'Pine Marten Cabin',
  'lone-mountain-ranch-big-sky-mt', 'Glamping', 'Cabin',
  'Sage', 'web_research_lonemountainranch_synxis_2026_05', 'United States', 'MT', 'Big Sky',
  '750 Lone Mountain Ranch Road', '59716', 45.2867, -111.4011,
  'https://lonemountainranch.com/cabins/pine-marten/',
  '(406) 995-4644',
  $$Sibling site — Lone Mountain Ranch (Big Sky). See anchor row id 11666.$$,
  $$Pine Marten: king. wooden soaking tub & walk-in shower. Sleeps 2. Patio: private creek view. $$,
  $$Synxis https://be.synxis.com/?Hotel=42113&Chain=6063. B&B proxy $1050/night.$$,
  '2026-05-18', '2026-05-18', 'private_commercial',
  26, 1, '2',
  1050, 1050, 1050, 1050, 1050, '{"2026":{"bed_breakfast_proxy":{"weekday":1050,"weekend":1050,"note":"Synxis B&B category proxy Mar 2026 sample; +taxes/fees"}}}'::jsonb,
  'Yes', 'Yes', 'No',
  'No', 'Yes', 'Yes', 'Yes',
  'Yes', 'Yes', 'No', 'No', 'Yes',
  'Yes', 'Yes', 'Yes',
  'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes',
  'Pine Marten: wooden soaking tub & walk-in shower; wood-burning stove; king.'
);

INSERT INTO public.all_glamping_properties (  property_id,
  research_status, is_glamping_property, is_open,
  property_name, site_name, slug, property_type, unit_type,
  source, discovery_source, country, state, city,
  address, zip_code, lat, lon, url, phone_number,
  description, unit_description, notes,
  date_added, date_updated, land_operator_category,
  property_total_sites, quantity_of_units, unit_capacity,
  rate_avg_retail_daily_rate, rate_summer_weekday, rate_summer_weekend,
  rate_winter_weekday, rate_winter_weekend,
  rate_unit_rates_by_year,
  unit_private_bathroom, unit_shower, unit_full_kitchen,
  unit_pets, unit_campfires, unit_patio, unit_wood_burning_stove,
  property_restaurant, property_food_on_site, property_sauna, property_hot_tub, property_family_friendly,
  setting_ranch, setting_forest, setting_mountainous,
  activities_hiking, activities_horseback_riding, activities_fishing, activities_snow_sports,
  activities_wildlife_watching, activities_scenic_drives,
  amenities_raw) VALUES (
  '88e6fdfd-3aed-4c1e-8726-509900bea596',
  'published', 'Yes', 'Yes',
  'Lone Mountain Ranch', 'Bitterroot Cabin',
  'lone-mountain-ranch-big-sky-mt', 'Glamping', 'Cabin',
  'Sage', 'web_research_lonemountainranch_synxis_2026_05', 'United States', 'MT', 'Big Sky',
  '750 Lone Mountain Ranch Road', '59716', 45.2867, -111.4011,
  'https://lonemountainranch.com/cabins/bitterroot/',
  '(406) 995-4644',
  $$Sibling site — Lone Mountain Ranch (Big Sky). See anchor row id 11666.$$,
  $$Bitterroot: king + queen sleeper sofa. walk-in shower. Sleeps 2-4. Patio: private. $$,
  $$Synxis https://be.synxis.com/?Hotel=42113&Chain=6063. B&B proxy $1100/night.$$,
  '2026-05-18', '2026-05-18', 'private_commercial',
  26, 1, '4',
  1100, 1100, 1100, 1100, 1100, '{"2026":{"bed_breakfast_proxy":{"weekday":1100,"weekend":1100,"note":"Synxis B&B category proxy Mar 2026 sample; +taxes/fees"}}}'::jsonb,
  'Yes', 'Yes', 'No',
  'No', 'Yes', 'Yes', 'Yes',
  'Yes', 'Yes', 'No', 'No', 'Yes',
  'Yes', 'Yes', 'Yes',
  'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes',
  'Bitterroot: walk-in shower; wood-burning stove; king + queen sleeper sofa.'
);

INSERT INTO public.all_glamping_properties (  property_id,
  research_status, is_glamping_property, is_open,
  property_name, site_name, slug, property_type, unit_type,
  source, discovery_source, country, state, city,
  address, zip_code, lat, lon, url, phone_number,
  description, unit_description, notes,
  date_added, date_updated, land_operator_category,
  property_total_sites, quantity_of_units, unit_capacity,
  rate_avg_retail_daily_rate, rate_summer_weekday, rate_summer_weekend,
  rate_winter_weekday, rate_winter_weekend,
  rate_unit_rates_by_year,
  unit_private_bathroom, unit_shower, unit_full_kitchen,
  unit_pets, unit_campfires, unit_patio, unit_wood_burning_stove,
  property_restaurant, property_food_on_site, property_sauna, property_hot_tub, property_family_friendly,
  setting_ranch, setting_forest, setting_mountainous,
  activities_hiking, activities_horseback_riding, activities_fishing, activities_snow_sports,
  activities_wildlife_watching, activities_scenic_drives,
  amenities_raw) VALUES (
  '88e6fdfd-3aed-4c1e-8726-509900bea596',
  'published', 'Yes', 'Yes',
  'Lone Mountain Ranch', 'Bald Eagle Cabin',
  'lone-mountain-ranch-big-sky-mt', 'Glamping', 'Cabin',
  'Sage', 'web_research_lonemountainranch_synxis_2026_05', 'United States', 'MT', 'Big Sky',
  '750 Lone Mountain Ranch Road', '59716', 45.2867, -111.4011,
  'https://lonemountainranch.com/cabins/bald-eagle/',
  '(406) 995-4644',
  $$Sibling site — Lone Mountain Ranch (Big Sky). See anchor row id 11666.$$,
  $$Bald Eagle: king. tub/shower combo. Sleeps 2. Patio: private creek. $$,
  $$Synxis https://be.synxis.com/?Hotel=42113&Chain=6063. B&B proxy $1050/night.$$,
  '2026-05-18', '2026-05-18', 'private_commercial',
  26, 1, '2',
  1050, 1050, 1050, 1050, 1050, '{"2026":{"bed_breakfast_proxy":{"weekday":1050,"weekend":1050,"note":"Synxis B&B category proxy Mar 2026 sample; +taxes/fees"}}}'::jsonb,
  'Yes', 'Yes', 'No',
  'No', 'Yes', 'Yes', 'Yes',
  'Yes', 'Yes', 'No', 'No', 'Yes',
  'Yes', 'Yes', 'Yes',
  'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes',
  'Bald Eagle: tub/shower combo; wood-burning stove; king.'
);

INSERT INTO public.all_glamping_properties (  property_id,
  research_status, is_glamping_property, is_open,
  property_name, site_name, slug, property_type, unit_type,
  source, discovery_source, country, state, city,
  address, zip_code, lat, lon, url, phone_number,
  description, unit_description, notes,
  date_added, date_updated, land_operator_category,
  property_total_sites, quantity_of_units, unit_capacity,
  rate_avg_retail_daily_rate, rate_summer_weekday, rate_summer_weekend,
  rate_winter_weekday, rate_winter_weekend,
  rate_unit_rates_by_year,
  unit_private_bathroom, unit_shower, unit_full_kitchen,
  unit_pets, unit_campfires, unit_patio, unit_wood_burning_stove,
  property_restaurant, property_food_on_site, property_sauna, property_hot_tub, property_family_friendly,
  setting_ranch, setting_forest, setting_mountainous,
  activities_hiking, activities_horseback_riding, activities_fishing, activities_snow_sports,
  activities_wildlife_watching, activities_scenic_drives,
  amenities_raw) VALUES (
  '88e6fdfd-3aed-4c1e-8726-509900bea596',
  'published', 'Yes', 'Yes',
  'Lone Mountain Ranch', 'Meadowlark Cabin',
  'lone-mountain-ranch-big-sky-mt', 'Glamping', 'Cabin',
  'Sage', 'web_research_lonemountainranch_synxis_2026_05', 'United States', 'MT', 'Big Sky',
  '750 Lone Mountain Ranch Road', '59716', 45.2867, -111.4011,
  'https://lonemountainranch.com/cabins/meadowlark/',
  '(406) 995-4644',
  $$Sibling site — Lone Mountain Ranch (Big Sky). See anchor row id 11666.$$,
  $$Meadowlark: queen (1915 gatekeeper cabin). walk-in tile shower. Sleeps 2. Patio: porch swing. $$,
  $$Synxis https://be.synxis.com/?Hotel=42113&Chain=6063. B&B proxy $1000/night.$$,
  '2026-05-18', '2026-05-18', 'private_commercial',
  26, 1, '2',
  1000, 1000, 1000, 1000, 1000, '{"2026":{"bed_breakfast_proxy":{"weekday":1000,"weekend":1000,"note":"Synxis B&B category proxy Mar 2026 sample; +taxes/fees"}}}'::jsonb,
  'Yes', 'Yes', 'No',
  'No', 'Yes', 'Yes', 'Yes',
  'Yes', 'Yes', 'No', 'No', 'Yes',
  'Yes', 'Yes', 'Yes',
  'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes',
  'Meadowlark: walk-in tile shower; wood-burning stove; queen (1915 gatekeeper cabin).'
);

INSERT INTO public.all_glamping_properties (  property_id,
  research_status, is_glamping_property, is_open,
  property_name, site_name, slug, property_type, unit_type,
  source, discovery_source, country, state, city,
  address, zip_code, lat, lon, url, phone_number,
  description, unit_description, notes,
  date_added, date_updated, land_operator_category,
  property_total_sites, quantity_of_units, unit_capacity,
  rate_avg_retail_daily_rate, rate_summer_weekday, rate_summer_weekend,
  rate_winter_weekday, rate_winter_weekend,
  rate_unit_rates_by_year,
  unit_private_bathroom, unit_shower, unit_full_kitchen,
  unit_pets, unit_campfires, unit_patio, unit_wood_burning_stove,
  property_restaurant, property_food_on_site, property_sauna, property_hot_tub, property_family_friendly,
  setting_ranch, setting_forest, setting_mountainous,
  activities_hiking, activities_horseback_riding, activities_fishing, activities_snow_sports,
  activities_wildlife_watching, activities_scenic_drives,
  amenities_raw) VALUES (
  '88e6fdfd-3aed-4c1e-8726-509900bea596',
  'published', 'Yes', 'Yes',
  'Lone Mountain Ranch', 'Porcupine Cabin',
  'lone-mountain-ranch-big-sky-mt', 'Glamping', 'Cabin',
  'Sage', 'web_research_lonemountainranch_synxis_2026_05', 'United States', 'MT', 'Big Sky',
  '750 Lone Mountain Ranch Road', '59716', 45.2867, -111.4011,
  'https://lonemountainranch.com/cabins/porcupine/',
  '(406) 995-4644',
  $$Sibling site — Lone Mountain Ranch (Big Sky). See anchor row id 11666.$$,
  $$Porcupine: queen. tub/shower combo. Sleeps 2. Patio: shared creek. $$,
  $$Synxis https://be.synxis.com/?Hotel=42113&Chain=6063. B&B proxy $1000/night.$$,
  '2026-05-18', '2026-05-18', 'private_commercial',
  26, 1, '2',
  1000, 1000, 1000, 1000, 1000, '{"2026":{"bed_breakfast_proxy":{"weekday":1000,"weekend":1000,"note":"Synxis B&B category proxy Mar 2026 sample; +taxes/fees"}}}'::jsonb,
  'Yes', 'Yes', 'No',
  'No', 'Yes', 'Yes', 'Yes',
  'Yes', 'Yes', 'No', 'No', 'Yes',
  'Yes', 'Yes', 'Yes',
  'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes',
  'Porcupine: tub/shower combo; wood-burning stove; queen.'
);

INSERT INTO public.all_glamping_properties (  property_id,
  research_status, is_glamping_property, is_open,
  property_name, site_name, slug, property_type, unit_type,
  source, discovery_source, country, state, city,
  address, zip_code, lat, lon, url, phone_number,
  description, unit_description, notes,
  date_added, date_updated, land_operator_category,
  property_total_sites, quantity_of_units, unit_capacity,
  rate_avg_retail_daily_rate, rate_summer_weekday, rate_summer_weekend,
  rate_winter_weekday, rate_winter_weekend,
  rate_unit_rates_by_year,
  unit_private_bathroom, unit_shower, unit_full_kitchen,
  unit_pets, unit_campfires, unit_patio, unit_wood_burning_stove,
  property_restaurant, property_food_on_site, property_sauna, property_hot_tub, property_family_friendly,
  setting_ranch, setting_forest, setting_mountainous,
  activities_hiking, activities_horseback_riding, activities_fishing, activities_snow_sports,
  activities_wildlife_watching, activities_scenic_drives,
  amenities_raw) VALUES (
  '88e6fdfd-3aed-4c1e-8726-509900bea596',
  'published', 'Yes', 'Yes',
  'Lone Mountain Ranch', 'Lodgepole Cabin',
  'lone-mountain-ranch-big-sky-mt', 'Glamping', 'Cabin',
  'Sage', 'web_research_lonemountainranch_synxis_2026_05', 'United States', 'MT', 'Big Sky',
  '750 Lone Mountain Ranch Road', '59716', 45.2867, -111.4011,
  'https://lonemountainranch.com/cabins/lodgepole/',
  '(406) 995-4644',
  $$Sibling site — Lone Mountain Ranch (Big Sky). See anchor row id 11666.$$,
  $$Lodgepole: king. soaking tub & walk-in shower. Sleeps 2. Patio: private forest. $$,
  $$Synxis https://be.synxis.com/?Hotel=42113&Chain=6063. B&B proxy $1050/night.$$,
  '2026-05-18', '2026-05-18', 'private_commercial',
  26, 1, '2',
  1050, 1050, 1050, 1050, 1050, '{"2026":{"bed_breakfast_proxy":{"weekday":1050,"weekend":1050,"note":"Synxis B&B category proxy Mar 2026 sample; +taxes/fees"}}}'::jsonb,
  'Yes', 'Yes', 'No',
  'No', 'Yes', 'Yes', 'Yes',
  'Yes', 'Yes', 'No', 'No', 'Yes',
  'Yes', 'Yes', 'Yes',
  'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes',
  'Lodgepole: soaking tub & walk-in shower; wood-burning stove; king.'
);

INSERT INTO public.all_glamping_properties (  property_id,
  research_status, is_glamping_property, is_open,
  property_name, site_name, slug, property_type, unit_type,
  source, discovery_source, country, state, city,
  address, zip_code, lat, lon, url, phone_number,
  description, unit_description, notes,
  date_added, date_updated, land_operator_category,
  property_total_sites, quantity_of_units, unit_capacity,
  rate_avg_retail_daily_rate, rate_summer_weekday, rate_summer_weekend,
  rate_winter_weekday, rate_winter_weekend,
  rate_unit_rates_by_year,
  unit_private_bathroom, unit_shower, unit_full_kitchen,
  unit_pets, unit_campfires, unit_patio, unit_wood_burning_stove,
  property_restaurant, property_food_on_site, property_sauna, property_hot_tub, property_family_friendly,
  setting_ranch, setting_forest, setting_mountainous,
  activities_hiking, activities_horseback_riding, activities_fishing, activities_snow_sports,
  activities_wildlife_watching, activities_scenic_drives,
  amenities_raw) VALUES (
  '88e6fdfd-3aed-4c1e-8726-509900bea596',
  'published', 'Yes', 'Yes',
  'Lone Mountain Ranch', 'Chipmunk Cabin',
  'lone-mountain-ranch-big-sky-mt', 'Glamping', 'Cabin',
  'Sage', 'web_research_lonemountainranch_synxis_2026_05', 'United States', 'MT', 'Big Sky',
  '750 Lone Mountain Ranch Road', '59716', 45.2867, -111.4011,
  'https://lonemountainranch.com/cabins/chipmunk/',
  '(406) 995-4644',
  $$Sibling site — Lone Mountain Ranch (Big Sky). See anchor row id 11666.$$,
  $$Chipmunk: queen. tub/shower combo. Sleeps 2. Patio: shared creek. $$,
  $$Synxis https://be.synxis.com/?Hotel=42113&Chain=6063. B&B proxy $1000/night.$$,
  '2026-05-18', '2026-05-18', 'private_commercial',
  26, 1, '2',
  1000, 1000, 1000, 1000, 1000, '{"2026":{"bed_breakfast_proxy":{"weekday":1000,"weekend":1000,"note":"Synxis B&B category proxy Mar 2026 sample; +taxes/fees"}}}'::jsonb,
  'Yes', 'Yes', 'No',
  'No', 'Yes', 'Yes', 'Yes',
  'Yes', 'Yes', 'No', 'No', 'Yes',
  'Yes', 'Yes', 'Yes',
  'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes',
  'Chipmunk: tub/shower combo; wood-burning stove; queen.'
);

INSERT INTO public.all_glamping_properties (  property_id,
  research_status, is_glamping_property, is_open,
  property_name, site_name, slug, property_type, unit_type,
  source, discovery_source, country, state, city,
  address, zip_code, lat, lon, url, phone_number,
  description, unit_description, notes,
  date_added, date_updated, land_operator_category,
  property_total_sites, quantity_of_units, unit_capacity,
  rate_avg_retail_daily_rate, rate_summer_weekday, rate_summer_weekend,
  rate_winter_weekday, rate_winter_weekend,
  rate_unit_rates_by_year,
  unit_private_bathroom, unit_shower, unit_full_kitchen,
  unit_pets, unit_campfires, unit_patio, unit_wood_burning_stove,
  property_restaurant, property_food_on_site, property_sauna, property_hot_tub, property_family_friendly,
  setting_ranch, setting_forest, setting_mountainous,
  activities_hiking, activities_horseback_riding, activities_fishing, activities_snow_sports,
  activities_wildlife_watching, activities_scenic_drives,
  amenities_raw) VALUES (
  '88e6fdfd-3aed-4c1e-8726-509900bea596',
  'published', 'Yes', 'Yes',
  'Lone Mountain Ranch', 'Blue Spruce Cabin',
  'lone-mountain-ranch-big-sky-mt', 'Glamping', 'Cabin',
  'Sage', 'web_research_lonemountainranch_synxis_2026_05', 'United States', 'MT', 'Big Sky',
  '750 Lone Mountain Ranch Road', '59716', 45.2867, -111.4011,
  'https://lonemountainranch.com/cabins/blue-spruce/',
  '(406) 995-4644',
  $$Sibling site — Lone Mountain Ranch (Big Sky). See anchor row id 11666.$$,
  $$Blue Spruce: king. soaking tub & walk-in shower. Sleeps 2. Patio: private + creekside nook. $$,
  $$Synxis https://be.synxis.com/?Hotel=42113&Chain=6063. B&B proxy $1050/night.$$,
  '2026-05-18', '2026-05-18', 'private_commercial',
  26, 1, '2',
  1050, 1050, 1050, 1050, 1050, '{"2026":{"bed_breakfast_proxy":{"weekday":1050,"weekend":1050,"note":"Synxis B&B category proxy Mar 2026 sample; +taxes/fees"}}}'::jsonb,
  'Yes', 'Yes', 'No',
  'No', 'Yes', 'Yes', 'Yes',
  'Yes', 'Yes', 'No', 'No', 'Yes',
  'Yes', 'Yes', 'Yes',
  'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes',
  'Blue Spruce: soaking tub & walk-in shower; wood-burning stove; king.'
);

INSERT INTO public.all_glamping_properties (  property_id,
  research_status, is_glamping_property, is_open,
  property_name, site_name, slug, property_type, unit_type,
  source, discovery_source, country, state, city,
  address, zip_code, lat, lon, url, phone_number,
  description, unit_description, notes,
  date_added, date_updated, land_operator_category,
  property_total_sites, quantity_of_units, unit_capacity,
  rate_avg_retail_daily_rate, rate_summer_weekday, rate_summer_weekend,
  rate_winter_weekday, rate_winter_weekend,
  rate_unit_rates_by_year,
  unit_private_bathroom, unit_shower, unit_full_kitchen,
  unit_pets, unit_campfires, unit_patio, unit_wood_burning_stove,
  property_restaurant, property_food_on_site, property_sauna, property_hot_tub, property_family_friendly,
  setting_ranch, setting_forest, setting_mountainous,
  activities_hiking, activities_horseback_riding, activities_fishing, activities_snow_sports,
  activities_wildlife_watching, activities_scenic_drives,
  amenities_raw) VALUES (
  '88e6fdfd-3aed-4c1e-8726-509900bea596',
  'published', 'Yes', 'Yes',
  'Lone Mountain Ranch', 'Bull Moose Cabin',
  'lone-mountain-ranch-big-sky-mt', 'Glamping', 'Cabin',
  'Sage', 'web_research_lonemountainranch_synxis_2026_05', 'United States', 'MT', 'Big Sky',
  '750 Lone Mountain Ranch Road', '59716', 45.2867, -111.4011,
  'https://lonemountainranch.com/cabins/bull-moose/',
  '(406) 995-4644',
  $$Sibling site — Lone Mountain Ranch (Big Sky). See anchor row id 11666.$$,
  $$Bull Moose: king + queen sofa sleeper. copper soaking tub & shower. Sleeps 2-4. Patio: enclosed porch. $$,
  $$Synxis https://be.synxis.com/?Hotel=42113&Chain=6063. B&B proxy $1100/night.$$,
  '2026-05-18', '2026-05-18', 'private_commercial',
  26, 1, '4',
  1100, 1100, 1100, 1100, 1100, '{"2026":{"bed_breakfast_proxy":{"weekday":1100,"weekend":1100,"note":"Synxis B&B category proxy Mar 2026 sample; +taxes/fees"}}}'::jsonb,
  'Yes', 'Yes', 'No',
  'No', 'Yes', 'Yes', 'Yes',
  'Yes', 'Yes', 'No', 'No', 'Yes',
  'Yes', 'Yes', 'Yes',
  'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes',
  'Bull Moose: copper soaking tub & shower; wood-burning stove; king + queen sofa sleeper.'
);

INSERT INTO public.all_glamping_properties (  property_id,
  research_status, is_glamping_property, is_open,
  property_name, site_name, slug, property_type, unit_type,
  source, discovery_source, country, state, city,
  address, zip_code, lat, lon, url, phone_number,
  description, unit_description, notes,
  date_added, date_updated, land_operator_category,
  property_total_sites, quantity_of_units, unit_capacity,
  rate_avg_retail_daily_rate, rate_summer_weekday, rate_summer_weekend,
  rate_winter_weekday, rate_winter_weekend,
  rate_unit_rates_by_year,
  unit_private_bathroom, unit_shower, unit_full_kitchen,
  unit_pets, unit_campfires, unit_patio, unit_wood_burning_stove,
  property_restaurant, property_food_on_site, property_sauna, property_hot_tub, property_family_friendly,
  setting_ranch, setting_forest, setting_mountainous,
  activities_hiking, activities_horseback_riding, activities_fishing, activities_snow_sports,
  activities_wildlife_watching, activities_scenic_drives,
  amenities_raw) VALUES (
  '88e6fdfd-3aed-4c1e-8726-509900bea596',
  'published', 'Yes', 'Yes',
  'Lone Mountain Ranch', 'Black Bear Cabin',
  'lone-mountain-ranch-big-sky-mt', 'Glamping', 'Cabin',
  'Sage', 'web_research_lonemountainranch_synxis_2026_05', 'United States', 'MT', 'Big Sky',
  '750 Lone Mountain Ranch Road', '59716', 45.2867, -111.4011,
  'https://lonemountainranch.com/cabins/blackbear/',
  '(406) 995-4644',
  $$Sibling site — Lone Mountain Ranch (Big Sky). See anchor row id 11666.$$,
  $$Black Bear: king + twin daybed. walk-in shower. Sleeps 2-3. Patio: shared. connects to Cougar duplex$$,
  $$Synxis https://be.synxis.com/?Hotel=42113&Chain=6063. B&B proxy $1100/night.$$,
  '2026-05-18', '2026-05-18', 'private_commercial',
  26, 1, '3',
  1100, 1100, 1100, 1100, 1100, '{"2026":{"bed_breakfast_proxy":{"weekday":1100,"weekend":1100,"note":"Synxis B&B category proxy Mar 2026 sample; +taxes/fees"}}}'::jsonb,
  'Yes', 'Yes', 'No',
  'No', 'Yes', 'Yes', 'Yes',
  'Yes', 'Yes', 'No', 'No', 'Yes',
  'Yes', 'Yes', 'Yes',
  'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes',
  'Black Bear: walk-in shower; wood-burning stove; king + twin daybed.'
);

INSERT INTO public.all_glamping_properties (  property_id,
  research_status, is_glamping_property, is_open,
  property_name, site_name, slug, property_type, unit_type,
  source, discovery_source, country, state, city,
  address, zip_code, lat, lon, url, phone_number,
  description, unit_description, notes,
  date_added, date_updated, land_operator_category,
  property_total_sites, quantity_of_units, unit_capacity,
  rate_avg_retail_daily_rate, rate_summer_weekday, rate_summer_weekend,
  rate_winter_weekday, rate_winter_weekend,
  rate_unit_rates_by_year,
  unit_private_bathroom, unit_shower, unit_full_kitchen,
  unit_pets, unit_campfires, unit_patio, unit_wood_burning_stove,
  property_restaurant, property_food_on_site, property_sauna, property_hot_tub, property_family_friendly,
  setting_ranch, setting_forest, setting_mountainous,
  activities_hiking, activities_horseback_riding, activities_fishing, activities_snow_sports,
  activities_wildlife_watching, activities_scenic_drives,
  amenities_raw) VALUES (
  '88e6fdfd-3aed-4c1e-8726-509900bea596',
  'published', 'Yes', 'Yes',
  'Lone Mountain Ranch', 'Shooting Star Cabin',
  'lone-mountain-ranch-big-sky-mt', 'Glamping', 'Cabin',
  'Sage', 'web_research_lonemountainranch_synxis_2026_05', 'United States', 'MT', 'Big Sky',
  '750 Lone Mountain Ranch Road', '59716', 45.2867, -111.4011,
  'https://lonemountainranch.com/cabins/shooting-star/',
  '(406) 995-4644',
  $$Sibling site — Lone Mountain Ranch (Big Sky). See anchor row id 11666.$$,
  $$Shooting Star: king + bunk beds + sofa. 2 baths (ensuite soaking tub + guest). Sleeps 4-6. Patio: creek porch. $$,
  $$Synxis https://be.synxis.com/?Hotel=42113&Chain=6063. B&B proxy $2300/night.$$,
  '2026-05-18', '2026-05-18', 'private_commercial',
  26, 1, '6',
  2300, 2300, 2300, 2300, 2300, '{"2026":{"bed_breakfast_proxy":{"weekday":2300,"weekend":2300,"note":"Synxis B&B category proxy Mar 2026 sample; +taxes/fees"}}}'::jsonb,
  'Yes', 'Yes', 'No',
  'No', 'Yes', 'Yes', 'Yes',
  'Yes', 'Yes', 'No', 'No', 'Yes',
  'Yes', 'Yes', 'Yes',
  'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes',
  'Shooting Star: 2 baths (ensuite soaking tub + guest); wood-burning stove; king + bunk beds + sofa.'
);

INSERT INTO public.all_glamping_properties (  property_id,
  research_status, is_glamping_property, is_open,
  property_name, site_name, slug, property_type, unit_type,
  source, discovery_source, country, state, city,
  address, zip_code, lat, lon, url, phone_number,
  description, unit_description, notes,
  date_added, date_updated, land_operator_category,
  property_total_sites, quantity_of_units, unit_capacity,
  rate_avg_retail_daily_rate, rate_summer_weekday, rate_summer_weekend,
  rate_winter_weekday, rate_winter_weekend,
  rate_unit_rates_by_year,
  unit_private_bathroom, unit_shower, unit_full_kitchen,
  unit_pets, unit_campfires, unit_patio, unit_wood_burning_stove,
  property_restaurant, property_food_on_site, property_sauna, property_hot_tub, property_family_friendly,
  setting_ranch, setting_forest, setting_mountainous,
  activities_hiking, activities_horseback_riding, activities_fishing, activities_snow_sports,
  activities_wildlife_watching, activities_scenic_drives,
  amenities_raw) VALUES (
  '88e6fdfd-3aed-4c1e-8726-509900bea596',
  'published', 'Yes', 'Yes',
  'Lone Mountain Ranch', 'Cougar Cabin',
  'lone-mountain-ranch-big-sky-mt', 'Glamping', 'Cabin',
  'Sage', 'web_research_lonemountainranch_synxis_2026_05', 'United States', 'MT', 'Big Sky',
  '750 Lone Mountain Ranch Road', '59716', 45.2867, -111.4011,
  'https://lonemountainranch.com/cabins/cougar/',
  '(406) 995-4644',
  $$Sibling site — Lone Mountain Ranch (Big Sky). See anchor row id 11666.$$,
  $$Cougar: king + twin daybed. tub/shower combo. Sleeps 2-3. Patio: shared. connects to Black Bear duplex$$,
  $$Synxis https://be.synxis.com/?Hotel=42113&Chain=6063. B&B proxy $1100/night.$$,
  '2026-05-18', '2026-05-18', 'private_commercial',
  26, 1, '3',
  1100, 1100, 1100, 1100, 1100, '{"2026":{"bed_breakfast_proxy":{"weekday":1100,"weekend":1100,"note":"Synxis B&B category proxy Mar 2026 sample; +taxes/fees"}}}'::jsonb,
  'Yes', 'Yes', 'No',
  'No', 'Yes', 'Yes', 'Yes',
  'Yes', 'Yes', 'No', 'No', 'Yes',
  'Yes', 'Yes', 'Yes',
  'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes',
  'Cougar: tub/shower combo; wood-burning stove; king + twin daybed.'
);

INSERT INTO public.all_glamping_properties (  property_id,
  research_status, is_glamping_property, is_open,
  property_name, site_name, slug, property_type, unit_type,
  source, discovery_source, country, state, city,
  address, zip_code, lat, lon, url, phone_number,
  description, unit_description, notes,
  date_added, date_updated, land_operator_category,
  property_total_sites, quantity_of_units, unit_capacity,
  rate_avg_retail_daily_rate, rate_summer_weekday, rate_summer_weekend,
  rate_winter_weekday, rate_winter_weekend,
  rate_unit_rates_by_year,
  unit_private_bathroom, unit_shower, unit_full_kitchen,
  unit_pets, unit_campfires, unit_patio, unit_wood_burning_stove,
  property_restaurant, property_food_on_site, property_sauna, property_hot_tub, property_family_friendly,
  setting_ranch, setting_forest, setting_mountainous,
  activities_hiking, activities_horseback_riding, activities_fishing, activities_snow_sports,
  activities_wildlife_watching, activities_scenic_drives,
  amenities_raw) VALUES (
  '88e6fdfd-3aed-4c1e-8726-509900bea596',
  'published', 'Yes', 'Yes',
  'Lone Mountain Ranch', 'Lame Deer Cabin',
  'lone-mountain-ranch-big-sky-mt', 'Glamping', 'Cabin',
  'Sage', 'web_research_lonemountainranch_synxis_2026_05', 'United States', 'MT', 'Big Sky',
  '750 Lone Mountain Ranch Road', '59716', 45.2867, -111.4011,
  'https://lonemountainranch.com/cabins/lame-deer/',
  '(406) 995-4644',
  $$Sibling site — Lone Mountain Ranch (Big Sky). See anchor row id 11666.$$,
  $$Lame Deer: king + twin daybed. tub/shower combo. Sleeps 2-3. Patio: private. connects to Canyon duplex$$,
  $$Synxis https://be.synxis.com/?Hotel=42113&Chain=6063. B&B proxy $1100/night.$$,
  '2026-05-18', '2026-05-18', 'private_commercial',
  26, 1, '3',
  1100, 1100, 1100, 1100, 1100, '{"2026":{"bed_breakfast_proxy":{"weekday":1100,"weekend":1100,"note":"Synxis B&B category proxy Mar 2026 sample; +taxes/fees"}}}'::jsonb,
  'Yes', 'Yes', 'No',
  'No', 'Yes', 'Yes', 'Yes',
  'Yes', 'Yes', 'No', 'No', 'Yes',
  'Yes', 'Yes', 'Yes',
  'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes',
  'Lame Deer: tub/shower combo; wood-burning stove; king + twin daybed.'
);

INSERT INTO public.all_glamping_properties (  property_id,
  research_status, is_glamping_property, is_open,
  property_name, site_name, slug, property_type, unit_type,
  source, discovery_source, country, state, city,
  address, zip_code, lat, lon, url, phone_number,
  description, unit_description, notes,
  date_added, date_updated, land_operator_category,
  property_total_sites, quantity_of_units, unit_capacity,
  rate_avg_retail_daily_rate, rate_summer_weekday, rate_summer_weekend,
  rate_winter_weekday, rate_winter_weekend,
  rate_unit_rates_by_year,
  unit_private_bathroom, unit_shower, unit_full_kitchen,
  unit_pets, unit_campfires, unit_patio, unit_wood_burning_stove,
  property_restaurant, property_food_on_site, property_sauna, property_hot_tub, property_family_friendly,
  setting_ranch, setting_forest, setting_mountainous,
  activities_hiking, activities_horseback_riding, activities_fishing, activities_snow_sports,
  activities_wildlife_watching, activities_scenic_drives,
  amenities_raw) VALUES (
  '88e6fdfd-3aed-4c1e-8726-509900bea596',
  'published', 'Yes', 'Yes',
  'Lone Mountain Ranch', 'Canyon Cabin',
  'lone-mountain-ranch-big-sky-mt', 'Glamping', 'Cabin',
  'Sage', 'web_research_lonemountainranch_synxis_2026_05', 'United States', 'MT', 'Big Sky',
  '750 Lone Mountain Ranch Road', '59716', 45.2867, -111.4011,
  'https://lonemountainranch.com/cabins/canyon/',
  '(406) 995-4644',
  $$Sibling site — Lone Mountain Ranch (Big Sky). See anchor row id 11666.$$,
  $$Canyon: king + twin daybed. walk-in shower. Sleeps 2-3. Patio: shared. connects to Lame Deer duplex$$,
  $$Synxis https://be.synxis.com/?Hotel=42113&Chain=6063. B&B proxy $1100/night.$$,
  '2026-05-18', '2026-05-18', 'private_commercial',
  26, 1, '3',
  1100, 1100, 1100, 1100, 1100, '{"2026":{"bed_breakfast_proxy":{"weekday":1100,"weekend":1100,"note":"Synxis B&B category proxy Mar 2026 sample; +taxes/fees"}}}'::jsonb,
  'Yes', 'Yes', 'No',
  'No', 'Yes', 'Yes', 'Yes',
  'Yes', 'Yes', 'No', 'No', 'Yes',
  'Yes', 'Yes', 'Yes',
  'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes',
  'Canyon: walk-in shower; wood-burning stove; king + twin daybed.'
);

INSERT INTO public.all_glamping_properties (  property_id,
  research_status, is_glamping_property, is_open,
  property_name, site_name, slug, property_type, unit_type,
  source, discovery_source, country, state, city,
  address, zip_code, lat, lon, url, phone_number,
  description, unit_description, notes,
  date_added, date_updated, land_operator_category,
  property_total_sites, quantity_of_units, unit_capacity,
  rate_avg_retail_daily_rate, rate_summer_weekday, rate_summer_weekend,
  rate_winter_weekday, rate_winter_weekend,
  rate_unit_rates_by_year,
  unit_private_bathroom, unit_shower, unit_full_kitchen,
  unit_pets, unit_campfires, unit_patio, unit_wood_burning_stove,
  property_restaurant, property_food_on_site, property_sauna, property_hot_tub, property_family_friendly,
  setting_ranch, setting_forest, setting_mountainous,
  activities_hiking, activities_horseback_riding, activities_fishing, activities_snow_sports,
  activities_wildlife_watching, activities_scenic_drives,
  amenities_raw) VALUES (
  '88e6fdfd-3aed-4c1e-8726-509900bea596',
  'published', 'Yes', 'Yes',
  'Lone Mountain Ranch', 'Rainbow Cabin',
  'lone-mountain-ranch-big-sky-mt', 'Glamping', 'Cabin',
  'Sage', 'web_research_lonemountainranch_synxis_2026_05', 'United States', 'MT', 'Big Sky',
  '750 Lone Mountain Ranch Road', '59716', 45.2867, -111.4011,
  'https://lonemountainranch.com/cabins/rainbow/',
  '(406) 995-4644',
  $$Sibling site — Lone Mountain Ranch (Big Sky). See anchor row id 11666.$$,
  $$Rainbow: king. walk-in shower. Sleeps 2. Patio: private near Grayling. $$,
  $$Synxis https://be.synxis.com/?Hotel=42113&Chain=6063. B&B proxy $1050/night.$$,
  '2026-05-18', '2026-05-18', 'private_commercial',
  26, 1, '2',
  1050, 1050, 1050, 1050, 1050, '{"2026":{"bed_breakfast_proxy":{"weekday":1050,"weekend":1050,"note":"Synxis B&B category proxy Mar 2026 sample; +taxes/fees"}}}'::jsonb,
  'Yes', 'Yes', 'No',
  'No', 'Yes', 'Yes', 'Yes',
  'Yes', 'Yes', 'No', 'No', 'Yes',
  'Yes', 'Yes', 'Yes',
  'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes',
  'Rainbow: walk-in shower; wood-burning stove; king.'
);

INSERT INTO public.all_glamping_properties (  property_id,
  research_status, is_glamping_property, is_open,
  property_name, site_name, slug, property_type, unit_type,
  source, discovery_source, country, state, city,
  address, zip_code, lat, lon, url, phone_number,
  description, unit_description, notes,
  date_added, date_updated, land_operator_category,
  property_total_sites, quantity_of_units, unit_capacity,
  rate_avg_retail_daily_rate, rate_summer_weekday, rate_summer_weekend,
  rate_winter_weekday, rate_winter_weekend,
  rate_unit_rates_by_year,
  unit_private_bathroom, unit_shower, unit_full_kitchen,
  unit_pets, unit_campfires, unit_patio, unit_wood_burning_stove,
  property_restaurant, property_food_on_site, property_sauna, property_hot_tub, property_family_friendly,
  setting_ranch, setting_forest, setting_mountainous,
  activities_hiking, activities_horseback_riding, activities_fishing, activities_snow_sports,
  activities_wildlife_watching, activities_scenic_drives,
  amenities_raw) VALUES (
  '88e6fdfd-3aed-4c1e-8726-509900bea596',
  'published', 'Yes', 'Yes',
  'Lone Mountain Ranch', 'Grayling Cabin',
  'lone-mountain-ranch-big-sky-mt', 'Glamping', 'Cabin',
  'Sage', 'web_research_lonemountainranch_synxis_2026_05', 'United States', 'MT', 'Big Sky',
  '750 Lone Mountain Ranch Road', '59716', 45.2867, -111.4011,
  'https://lonemountainranch.com/cabins/grayling/',
  '(406) 995-4644',
  $$Sibling site — Lone Mountain Ranch (Big Sky). See anchor row id 11666.$$,
  $$Grayling: king. tub/shower combo. Sleeps 2. Patio: shared near Rainbow. $$,
  $$Synxis https://be.synxis.com/?Hotel=42113&Chain=6063. B&B proxy $1050/night.$$,
  '2026-05-18', '2026-05-18', 'private_commercial',
  26, 1, '2',
  1050, 1050, 1050, 1050, 1050, '{"2026":{"bed_breakfast_proxy":{"weekday":1050,"weekend":1050,"note":"Synxis B&B category proxy Mar 2026 sample; +taxes/fees"}}}'::jsonb,
  'Yes', 'Yes', 'No',
  'No', 'Yes', 'Yes', 'Yes',
  'Yes', 'Yes', 'No', 'No', 'Yes',
  'Yes', 'Yes', 'Yes',
  'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes',
  'Grayling: tub/shower combo; wood-burning stove; king.'
);

INSERT INTO public.all_glamping_properties (  property_id,
  research_status, is_glamping_property, is_open,
  property_name, site_name, slug, property_type, unit_type,
  source, discovery_source, country, state, city,
  address, zip_code, lat, lon, url, phone_number,
  description, unit_description, notes,
  date_added, date_updated, land_operator_category,
  property_total_sites, quantity_of_units, unit_capacity,
  rate_avg_retail_daily_rate, rate_summer_weekday, rate_summer_weekend,
  rate_winter_weekday, rate_winter_weekend,
  rate_unit_rates_by_year,
  unit_private_bathroom, unit_shower, unit_full_kitchen,
  unit_pets, unit_campfires, unit_patio, unit_wood_burning_stove,
  property_restaurant, property_food_on_site, property_sauna, property_hot_tub, property_family_friendly,
  setting_ranch, setting_forest, setting_mountainous,
  activities_hiking, activities_horseback_riding, activities_fishing, activities_snow_sports,
  activities_wildlife_watching, activities_scenic_drives,
  amenities_raw) VALUES (
  '88e6fdfd-3aed-4c1e-8726-509900bea596',
  'published', 'Yes', 'Yes',
  'Lone Mountain Ranch', 'Aspen Cabin',
  'lone-mountain-ranch-big-sky-mt', 'Glamping', 'Cabin',
  'Sage', 'web_research_lonemountainranch_synxis_2026_05', 'United States', 'MT', 'Big Sky',
  '750 Lone Mountain Ranch Road', '59716', 45.2867, -111.4011,
  'https://lonemountainranch.com/cabins/aspen/',
  '(406) 995-4644',
  $$Sibling site — Lone Mountain Ranch (Big Sky). See anchor row id 11666.$$,
  $$Aspen: 2 king bedrooms + sofa. 2 baths (clawfoot + tub/shower). Sleeps 4-6. Patio: panoramic deck. $$,
  $$Synxis https://be.synxis.com/?Hotel=42113&Chain=6063. B&B proxy $2300/night.$$,
  '2026-05-18', '2026-05-18', 'private_commercial',
  26, 1, '6',
  2300, 2300, 2300, 2300, 2300, '{"2026":{"bed_breakfast_proxy":{"weekday":2300,"weekend":2300,"note":"Synxis B&B category proxy Mar 2026 sample; +taxes/fees"}}}'::jsonb,
  'Yes', 'Yes', 'No',
  'No', 'Yes', 'Yes', 'Yes',
  'Yes', 'Yes', 'No', 'No', 'Yes',
  'Yes', 'Yes', 'Yes',
  'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes',
  'Aspen: 2 baths (clawfoot + tub/shower); wood-burning stove; 2 king bedrooms + sofa.'
);

INSERT INTO public.all_glamping_properties (  property_id,
  research_status, is_glamping_property, is_open,
  property_name, site_name, slug, property_type, unit_type,
  source, discovery_source, country, state, city,
  address, zip_code, lat, lon, url, phone_number,
  description, unit_description, notes,
  date_added, date_updated, land_operator_category,
  property_total_sites, quantity_of_units, unit_capacity,
  rate_avg_retail_daily_rate, rate_summer_weekday, rate_summer_weekend,
  rate_winter_weekday, rate_winter_weekend,
  rate_unit_rates_by_year,
  unit_private_bathroom, unit_shower, unit_full_kitchen,
  unit_pets, unit_campfires, unit_patio, unit_wood_burning_stove,
  property_restaurant, property_food_on_site, property_sauna, property_hot_tub, property_family_friendly,
  setting_ranch, setting_forest, setting_mountainous,
  activities_hiking, activities_horseback_riding, activities_fishing, activities_snow_sports,
  activities_wildlife_watching, activities_scenic_drives,
  amenities_raw) VALUES (
  '88e6fdfd-3aed-4c1e-8726-509900bea596',
  'published', 'Yes', 'Yes',
  'Lone Mountain Ranch', 'Bighorn Cabin',
  'lone-mountain-ranch-big-sky-mt', 'Glamping', 'Cabin',
  'Sage', 'web_research_lonemountainranch_synxis_2026_05', 'United States', 'MT', 'Big Sky',
  '750 Lone Mountain Ranch Road', '59716', 45.2867, -111.4011,
  'https://lonemountainranch.com/cabins/bighorn/',
  '(406) 995-4644',
  $$Sibling site — Lone Mountain Ranch (Big Sky). See anchor row id 11666.$$,
  $$Bighorn: 2 king + queen sofa. 2 en-suite (clawfoot + shower). Sleeps 4-6. Patio: creek deck. $$,
  $$Synxis https://be.synxis.com/?Hotel=42113&Chain=6063. B&B proxy $2300/night.$$,
  '2026-05-18', '2026-05-18', 'private_commercial',
  26, 1, '6',
  2300, 2300, 2300, 2300, 2300, '{"2026":{"bed_breakfast_proxy":{"weekday":2300,"weekend":2300,"note":"Synxis B&B category proxy Mar 2026 sample; +taxes/fees"}}}'::jsonb,
  'Yes', 'Yes', 'No',
  'No', 'Yes', 'Yes', 'Yes',
  'Yes', 'Yes', 'No', 'No', 'Yes',
  'Yes', 'Yes', 'Yes',
  'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes',
  'Bighorn: 2 en-suite (clawfoot + shower); wood-burning stove; 2 king + queen sofa.'
);

INSERT INTO public.all_glamping_properties (  property_id,
  research_status, is_glamping_property, is_open,
  property_name, site_name, slug, property_type, unit_type,
  source, discovery_source, country, state, city,
  address, zip_code, lat, lon, url, phone_number,
  description, unit_description, notes,
  date_added, date_updated, land_operator_category,
  property_total_sites, quantity_of_units, unit_capacity,
  rate_avg_retail_daily_rate, rate_summer_weekday, rate_summer_weekend,
  rate_winter_weekday, rate_winter_weekend,
  rate_unit_rates_by_year,
  unit_private_bathroom, unit_shower, unit_full_kitchen,
  unit_pets, unit_campfires, unit_patio, unit_wood_burning_stove,
  property_restaurant, property_food_on_site, property_sauna, property_hot_tub, property_family_friendly,
  setting_ranch, setting_forest, setting_mountainous,
  activities_hiking, activities_horseback_riding, activities_fishing, activities_snow_sports,
  activities_wildlife_watching, activities_scenic_drives,
  amenities_raw) VALUES (
  '88e6fdfd-3aed-4c1e-8726-509900bea596',
  'published', 'Yes', 'Yes',
  'Lone Mountain Ranch', 'Hilltop Cabin',
  'lone-mountain-ranch-big-sky-mt', 'Glamping', 'Cabin',
  'Sage', 'web_research_lonemountainranch_synxis_2026_05', 'United States', 'MT', 'Big Sky',
  '750 Lone Mountain Ranch Road', '59716', 45.2867, -111.4011,
  'https://lonemountainranch.com/cabins/hilltop/',
  '(406) 995-4644',
  $$Sibling site — Lone Mountain Ranch (Big Sky). See anchor row id 11666.$$,
  $$Hilltop: 2 king + twin daybed. 2 (soaking tub + shower). Sleeps 4-5. Patio: screened porch. $$,
  $$Synxis https://be.synxis.com/?Hotel=42113&Chain=6063. B&B proxy $2300/night.$$,
  '2026-05-18', '2026-05-18', 'private_commercial',
  26, 1, '5',
  2300, 2300, 2300, 2300, 2300, '{"2026":{"bed_breakfast_proxy":{"weekday":2300,"weekend":2300,"note":"Synxis B&B category proxy Mar 2026 sample; +taxes/fees"}}}'::jsonb,
  'Yes', 'Yes', 'No',
  'No', 'Yes', 'Yes', 'Yes',
  'Yes', 'Yes', 'No', 'No', 'Yes',
  'Yes', 'Yes', 'Yes',
  'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes',
  'Hilltop: 2 (soaking tub + shower); wood-burning stove; 2 king + twin daybed.'
);

INSERT INTO public.all_glamping_properties (  property_id,
  research_status, is_glamping_property, is_open,
  property_name, site_name, slug, property_type, unit_type,
  source, discovery_source, country, state, city,
  address, zip_code, lat, lon, url, phone_number,
  description, unit_description, notes,
  date_added, date_updated, land_operator_category,
  property_total_sites, quantity_of_units, unit_capacity,
  rate_avg_retail_daily_rate, rate_summer_weekday, rate_summer_weekend,
  rate_winter_weekday, rate_winter_weekend,
  rate_unit_rates_by_year,
  unit_private_bathroom, unit_shower, unit_full_kitchen,
  unit_pets, unit_campfires, unit_patio, unit_wood_burning_stove,
  property_restaurant, property_food_on_site, property_sauna, property_hot_tub, property_family_friendly,
  setting_ranch, setting_forest, setting_mountainous,
  activities_hiking, activities_horseback_riding, activities_fishing, activities_snow_sports,
  activities_wildlife_watching, activities_scenic_drives,
  amenities_raw) VALUES (
  '88e6fdfd-3aed-4c1e-8726-509900bea596',
  'published', 'Yes', 'Yes',
  'Lone Mountain Ranch', 'Coyote Cabin',
  'lone-mountain-ranch-big-sky-mt', 'Glamping', 'Cabin',
  'Sage', 'web_research_lonemountainranch_synxis_2026_05', 'United States', 'MT', 'Big Sky',
  '750 Lone Mountain Ranch Road', '59716', 45.2867, -111.4011,
  'https://lonemountainranch.com/cabins/coyote/',
  '(406) 995-4644',
  $$Sibling site — Lone Mountain Ranch (Big Sky). See anchor row id 11666.$$,
  $$Coyote: 2 king + queen sofa. 2 en-suite. Sleeps 4-6. Patio: covered mountain porch. $$,
  $$Synxis https://be.synxis.com/?Hotel=42113&Chain=6063. B&B proxy $2300/night.$$,
  '2026-05-18', '2026-05-18', 'private_commercial',
  26, 1, '6',
  2300, 2300, 2300, 2300, 2300, '{"2026":{"bed_breakfast_proxy":{"weekday":2300,"weekend":2300,"note":"Synxis B&B category proxy Mar 2026 sample; +taxes/fees"}}}'::jsonb,
  'Yes', 'Yes', 'No',
  'No', 'Yes', 'Yes', 'Yes',
  'Yes', 'Yes', 'No', 'No', 'Yes',
  'Yes', 'Yes', 'Yes',
  'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes',
  'Coyote: 2 en-suite; wood-burning stove; 2 king + queen sofa.'
);

INSERT INTO public.all_glamping_properties (  property_id,
  research_status, is_glamping_property, is_open,
  property_name, site_name, slug, property_type, unit_type,
  source, discovery_source, country, state, city,
  address, zip_code, lat, lon, url, phone_number,
  description, unit_description, notes,
  date_added, date_updated, land_operator_category,
  property_total_sites, quantity_of_units, unit_capacity,
  rate_avg_retail_daily_rate, rate_summer_weekday, rate_summer_weekend,
  rate_winter_weekday, rate_winter_weekend,
  rate_unit_rates_by_year,
  unit_private_bathroom, unit_shower, unit_full_kitchen,
  unit_pets, unit_campfires, unit_patio, unit_wood_burning_stove,
  property_restaurant, property_food_on_site, property_sauna, property_hot_tub, property_family_friendly,
  setting_ranch, setting_forest, setting_mountainous,
  activities_hiking, activities_horseback_riding, activities_fishing, activities_snow_sports,
  activities_wildlife_watching, activities_scenic_drives,
  amenities_raw) VALUES (
  '88e6fdfd-3aed-4c1e-8726-509900bea596',
  'published', 'Yes', 'Yes',
  'Lone Mountain Ranch', 'Larkspur Cabin',
  'lone-mountain-ranch-big-sky-mt', 'Glamping', 'Cabin',
  'Sage', 'web_research_lonemountainranch_synxis_2026_05', 'United States', 'MT', 'Big Sky',
  '750 Lone Mountain Ranch Road', '59716', 45.2867, -111.4011,
  'https://lonemountainranch.com/cabins/larkspur/',
  '(406) 995-4644',
  $$Sibling site — Lone Mountain Ranch (Big Sky). See anchor row id 11666.$$,
  $$Larkspur: 2 king + queen sofa. 2 en-suite (clawfoot + shower). Sleeps 4-6. Patio: expansive covered porch. $$,
  $$Synxis https://be.synxis.com/?Hotel=42113&Chain=6063. B&B proxy $2300/night.$$,
  '2026-05-18', '2026-05-18', 'private_commercial',
  26, 1, '6',
  2300, 2300, 2300, 2300, 2300, '{"2026":{"bed_breakfast_proxy":{"weekday":2300,"weekend":2300,"note":"Synxis B&B category proxy Mar 2026 sample; +taxes/fees"}}}'::jsonb,
  'Yes', 'Yes', 'No',
  'No', 'Yes', 'Yes', 'Yes',
  'Yes', 'Yes', 'No', 'No', 'Yes',
  'Yes', 'Yes', 'Yes',
  'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes',
  'Larkspur: 2 en-suite (clawfoot + shower); wood-burning stove; 2 king + queen sofa.'
);

INSERT INTO public.all_glamping_properties (  property_id,
  research_status, is_glamping_property, is_open,
  property_name, site_name, slug, property_type, unit_type,
  source, discovery_source, country, state, city,
  address, zip_code, lat, lon, url, phone_number,
  description, unit_description, notes,
  date_added, date_updated, land_operator_category,
  property_total_sites, quantity_of_units, unit_capacity,
  rate_avg_retail_daily_rate, rate_summer_weekday, rate_summer_weekend,
  rate_winter_weekday, rate_winter_weekend,
  rate_unit_rates_by_year,
  unit_private_bathroom, unit_shower, unit_full_kitchen,
  unit_pets, unit_campfires, unit_patio, unit_wood_burning_stove,
  property_restaurant, property_food_on_site, property_sauna, property_hot_tub, property_family_friendly,
  setting_ranch, setting_forest, setting_mountainous,
  activities_hiking, activities_horseback_riding, activities_fishing, activities_snow_sports,
  activities_wildlife_watching, activities_scenic_drives,
  amenities_raw) VALUES (
  '88e6fdfd-3aed-4c1e-8726-509900bea596',
  'published', 'Yes', 'Yes',
  'Lone Mountain Ranch', 'Bison Lodge',
  'lone-mountain-ranch-big-sky-mt', 'Glamping', 'Lodge',
  'Sage', 'web_research_lonemountainranch_synxis_2026_05', 'United States', 'MT', 'Big Sky',
  '750 Lone Mountain Ranch Road', '59716', 45.2867, -111.4011,
  'https://lonemountainranch.com/cabins/bison-lodge/',
  '(406) 995-4644',
  $$Sibling site — Lone Mountain Ranch (Big Sky). See anchor row id 11666.$$,
  $$Bison Lodge: 6 king bedrooms. 6 baths. Sleeps 16. Patio: pool, hot tub, sauna, firepit. 5000 sf; availability from Jul 2026 per operator$$,
  $$Synxis https://be.synxis.com/?Hotel=42113&Chain=6063. Group/lodge — request Synxis quote for dates.$$,
  '2026-05-18', '2026-05-18', 'private_commercial',
  26, 1, '16',
  NULL, NULL, NULL, NULL, NULL, NULL,
  'Yes', 'Yes', 'No',
  'No', 'Yes', 'Yes', 'Yes',
  'Yes', 'Yes', 'Yes', 'Yes', 'Yes',
  'Yes', 'Yes', 'Yes',
  'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes',
  'Bison Lodge: 6 baths; wood-burning stove; 6 king bedrooms.'
);

INSERT INTO public.all_glamping_properties (  property_id,
  research_status, is_glamping_property, is_open,
  property_name, site_name, slug, property_type, unit_type,
  source, discovery_source, country, state, city,
  address, zip_code, lat, lon, url, phone_number,
  description, unit_description, notes,
  date_added, date_updated, land_operator_category,
  property_total_sites, quantity_of_units, unit_capacity,
  rate_avg_retail_daily_rate, rate_summer_weekday, rate_summer_weekend,
  rate_winter_weekday, rate_winter_weekend,
  rate_unit_rates_by_year,
  unit_private_bathroom, unit_shower, unit_full_kitchen,
  unit_pets, unit_campfires, unit_patio, unit_wood_burning_stove,
  property_restaurant, property_food_on_site, property_sauna, property_hot_tub, property_family_friendly,
  setting_ranch, setting_forest, setting_mountainous,
  activities_hiking, activities_horseback_riding, activities_fishing, activities_snow_sports,
  activities_wildlife_watching, activities_scenic_drives,
  amenities_raw) VALUES (
  '88e6fdfd-3aed-4c1e-8726-509900bea596',
  'published', 'Yes', 'Yes',
  'Lone Mountain Ranch', 'Ridgetop Lodge',
  'lone-mountain-ranch-big-sky-mt', 'Glamping', 'Lodge',
  'Sage', 'web_research_lonemountainranch_synxis_2026_05', 'United States', 'MT', 'Big Sky',
  '750 Lone Mountain Ranch Road', '59716', 45.2867, -111.4011,
  'https://lonemountainranch.com/cabins/ridgetop-lodge/',
  '(406) 995-4644',
  $$Sibling site — Lone Mountain Ranch (Big Sky). See anchor row id 11666.$$,
  $$Ridgetop Lodge: 6 en-suite bedrooms. 8 baths. Sleeps 12-18. Patio: hot tub, decks, game room. $$,
  $$Synxis https://be.synxis.com/?Hotel=42113&Chain=6063. Group/lodge — request Synxis quote for dates.$$,
  '2026-05-18', '2026-05-18', 'private_commercial',
  26, 1, '18',
  NULL, NULL, NULL, NULL, NULL, NULL,
  'Yes', 'Yes', 'No',
  'No', 'Yes', 'Yes', 'Yes',
  'Yes', 'Yes', 'Yes', 'Yes', 'Yes',
  'Yes', 'Yes', 'Yes',
  'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes',
  'Ridgetop Lodge: 8 baths; wood-burning stove; 6 en-suite bedrooms.'
);

INSERT INTO public.all_glamping_properties (  property_id,
  research_status, is_glamping_property, is_open,
  property_name, site_name, slug, property_type, unit_type,
  source, discovery_source, country, state, city,
  address, zip_code, lat, lon, url, phone_number,
  description, unit_description, notes,
  date_added, date_updated, land_operator_category,
  property_total_sites, quantity_of_units, unit_capacity,
  rate_avg_retail_daily_rate, rate_summer_weekday, rate_summer_weekend,
  rate_winter_weekday, rate_winter_weekend,
  rate_unit_rates_by_year,
  unit_private_bathroom, unit_shower, unit_full_kitchen,
  unit_pets, unit_campfires, unit_patio, unit_wood_burning_stove,
  property_restaurant, property_food_on_site, property_sauna, property_hot_tub, property_family_friendly,
  setting_ranch, setting_forest, setting_mountainous,
  activities_hiking, activities_horseback_riding, activities_fishing, activities_snow_sports,
  activities_wildlife_watching, activities_scenic_drives,
  amenities_raw) VALUES (
  '88e6fdfd-3aed-4c1e-8726-509900bea596',
  'published', 'Yes', 'Yes',
  'Lone Mountain Ranch', 'B-K Lodge',
  'lone-mountain-ranch-big-sky-mt', 'Glamping', 'Lodge',
  'Sage', 'web_research_lonemountainranch_synxis_2026_05', 'United States', 'MT', 'Big Sky',
  '750 Lone Mountain Ranch Road', '59716', 45.2867, -111.4011,
  'https://lonemountainranch.com/cabins/b-k/',
  '(406) 995-4644',
  $$Sibling site — Lone Mountain Ranch (Big Sky). See anchor row id 11666.$$,
  $$B-K: 2 king suites + 4-bed bunk room. 3 baths. Sleeps 8-9. Patio: creekside firepit (1936 schoolhouse). $$,
  $$Synxis https://be.synxis.com/?Hotel=42113&Chain=6063. Group/lodge — request Synxis quote for dates.$$,
  '2026-05-18', '2026-05-18', 'private_commercial',
  26, 1, '9',
  NULL, NULL, NULL, NULL, NULL, NULL,
  'Yes', 'Yes', 'No',
  'No', 'Yes', 'Yes', 'Yes',
  'Yes', 'Yes', 'No', 'No', 'Yes',
  'Yes', 'Yes', 'Yes',
  'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes',
  'B-K: 3 baths; wood-burning stove; 2 king suites + 4-bed bunk room.'
);

INSERT INTO public.all_glamping_properties (  property_id,
  research_status, is_glamping_property, is_open,
  property_name, site_name, slug, property_type, unit_type,
  source, discovery_source, country, state, city,
  address, zip_code, lat, lon, url, phone_number,
  description, unit_description, notes,
  date_added, date_updated, land_operator_category,
  property_total_sites, quantity_of_units, unit_capacity,
  rate_avg_retail_daily_rate, rate_summer_weekday, rate_summer_weekend,
  rate_winter_weekday, rate_winter_weekend,
  rate_unit_rates_by_year,
  unit_private_bathroom, unit_shower, unit_full_kitchen,
  unit_pets, unit_campfires, unit_patio, unit_wood_burning_stove,
  property_restaurant, property_food_on_site, property_sauna, property_hot_tub, property_family_friendly,
  setting_ranch, setting_forest, setting_mountainous,
  activities_hiking, activities_horseback_riding, activities_fishing, activities_snow_sports,
  activities_wildlife_watching, activities_scenic_drives,
  amenities_raw) VALUES (
  '88e6fdfd-3aed-4c1e-8726-509900bea596',
  'published', 'Yes', 'Yes',
  'Lone Mountain Ranch', 'Douglas Fir House',
  'lone-mountain-ranch-big-sky-mt', 'Glamping', 'Lodge',
  'Sage', 'web_research_lonemountainranch_synxis_2026_05', 'United States', 'MT', 'Big Sky',
  '750 Lone Mountain Ranch Road', '59716', 45.2867, -111.4011,
  'https://lonemountainranch.com/cabins/douglas-fir-house/',
  '(406) 995-4644',
  $$Sibling site — Lone Mountain Ranch (Big Sky). See anchor row id 11666.$$,
  $$Douglas Fir House: 3 queen + 4 twin. 2 baths. Sleeps 10. Patio: wraparound deck + sauna. full kitchen$$,
  $$Synxis https://be.synxis.com/?Hotel=42113&Chain=6063. Group/lodge — request Synxis quote for dates.$$,
  '2026-05-18', '2026-05-18', 'private_commercial',
  26, 1, '10',
  NULL, NULL, NULL, NULL, NULL, NULL,
  'Yes', 'Yes', 'Yes',
  'No', 'Yes', 'Yes', 'Yes',
  'Yes', 'Yes', 'Yes', 'No', 'Yes',
  'Yes', 'Yes', 'Yes',
  'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes',
  'Douglas Fir House: 2 baths; wood-burning stove; 3 queen + 4 twin.'
);

