-- Shinta Mani Wild: site inventory from shintamani.com/wild + Synxis (May 2026)
-- Sources: /wild/tents, Synxis (hotel 48567 / chain 27625), AFAR Hotels We Love (Apr 2026)
-- Enriches anchor row id 12193; inserts 2 sibling tent category rows (15 tents total).

UPDATE public.all_glamping_properties SET
  property_id = '669f2d86-4423-42c9-9439-3929557fcae6'::uuid,
  site_name = 'Wild Tent',
  slug = 'shinta-mani-wild-koh-kong-kh',
  property_type = 'Glamping Resort',
  unit_type = 'Safari Tent',
  source = 'Sage',
  discovery_source = 'web_research_shinta_mani_wild_synxis_2026_05',
  country = 'Cambodia',
  state = 'Koh Kong',
  city = 'Kampong Seila',
  address = 'Prey Praseth Village, Ou Bak Rothed Commune, Kampong Seila, Cambodia 180403',
  zip_code = '180403',
  lat = 11.580,
  lon = 103.880,
  url = 'https://be.synxis.com/?adult=2&arrive=2026-05-23&chain=27625&child=0&currency=USD&depart=2026-05-26&hotel=48567&level=hotel&locale=en-US&productcurrency=USD&rooms=1&start=availresults',
  phone_number = '+855-96-919-0000',
  research_status = 'published',
  is_glamping_property = 'Yes',
  is_open = 'Yes',
  property_total_sites = 15,
  quantity_of_units = 10,
  unit_capacity = '2',
  minimum_nights = '3',
  operating_season_months = 'Year-round; seasonal camp themes Jan–Dec',
  unit_private_bathroom = 'Yes',
  unit_shower = 'Yes',
  unit_kitchenette = 'No',
  unit_wifi = 'Yes',
  unit_air_conditioning = 'Yes',
  unit_campfires = 'Yes',
  unit_hot_tub = 'Yes',
  property_family_friendly = 'No',
  setting_forest = 'Yes',
  activities_wildlife_watching = 'Yes',
  activities_hiking = 'Yes',
  land_operator_category = 'private_commercial',
  date_updated = '2026-05-21',
  description = $$Shinta Mani Wild — Bill Bensley conservation camp on 865 acres in Cambodia's South Cardamom rainforest (purchased from logging auction). Fifteen bespoke canvas tents on the river without felling trees; all-inclusive 3-night+ stays with meals, drinks, activities, transfers, and unlimited spa. Wildlife Alliance anti-poaching partnership; zipline arrival, jungle cruises, kayaking. Categories: Wild Tent, Waterfall Tent, Two Bedroom Tent.$$,
  unit_description = $$Wild Tent category: ten river-valley tents deeper in the forest with expedition-style décor, outdoor decks, open-air soaking tubs, and air-conditioned bedrooms. Named units include The Shinta Mani Foundation Tent, The Bohemian Tent, The Great Conservationists Tent, The Butterfly Tent, King Jayavarman's Tent, The Botanists Tent, The Birders Tent, Shinta Mani's Tent With a Heart, The Elephants Tent, and The Terrapins Tent.$$,
  notes = COALESCE(notes, '') || E'\n\nSite enrichment (May 2026): shintamani.com/wild/tents; Synxis hotel 48567 (May 23–26, 2026 sample). AFAR from-rate ~USD 1,900/night. All-inclusive; 3-night minimum. Fifteen individually named tents — see research doc.',
  amenities_raw = 'All-inclusive F&B; Bensley Butler; outdoor soaking tub; A/C; open-air bath; zipline arrival; jungle cruise; anti-poaching patrol option; foraged cuisine; unlimited spa; Wi-Fi.',
  rate_avg_retail_daily_rate = 1900,
  rate_summer_weekday = 1900,
  rate_summer_weekend = 1900,
  rate_unit_rates_by_year = '{"2026":{"sample_dates":"2026-05-23_to_2026-05-26","currency":"USD","guests":2,"hotel":48567,"chain":27625,"minimum_nights":3,"all_inclusive":true,"categories":["Wild Tent","Waterfall Tent","Two Bedroom Tent"],"named_tents":["The Cambodian Royalty Tent","First Lady Jackie Kennedy''s Tent","The Shinta Mani Foundation Tent","The Bohemian Tent","The Great Conservationists Tent","The Wildlife Alliance Tent","The Butterfly Tent","King Jayavarman''s Tent","The Botanists Tent","The Birders Tent","Shinta Mani''s Tent With a Heart","The Elephants Tent","The Terrapins Tent","The National Geographic Tent","The Gibbons Tent"],"afar_from_rate_usd":1900,"note":"Synxis per-tent ADRs not captured in automated scrape"}}'::jsonb
WHERE id = 12193;

INSERT INTO public.all_glamping_properties (
  property_id, research_status, is_glamping_property, is_open,
  property_name, site_name, slug, property_type, unit_type,
  source, discovery_source, country, state, city,
  address, zip_code, lat, lon, url, phone_number,
  description, unit_description, notes,
  date_added, date_updated, land_operator_category,
  property_total_sites, quantity_of_units, unit_capacity, minimum_nights,
  operating_season_months,
  rate_avg_retail_daily_rate, rate_summer_weekday, rate_summer_weekend,
  rate_unit_rates_by_year,
  unit_private_bathroom, unit_shower, unit_kitchenette, unit_wifi,
  unit_air_conditioning, unit_campfires, unit_hot_tub,
  setting_forest, activities_wildlife_watching, activities_hiking,
  amenities_raw
) VALUES
(
  '669f2d86-4423-42c9-9439-3929557fcae6'::uuid,
  'published', 'Yes', 'Yes',
  'Shinta Mani Wild', 'Waterfall Tent',
  'shinta-mani-wild-koh-kong-kh', 'Glamping Resort', 'Safari Tent',
  'Sage', 'web_research_shinta_mani_wild_synxis_2026_05', 'Cambodia', 'Koh Kong', 'Kampong Seila',
  'Prey Praseth Village, Ou Bak Rothed Commune, Kampong Seila, Cambodia 180403', '180403',
  11.580, 103.880,
  'https://be.synxis.com/?adult=2&arrive=2026-05-23&chain=27625&child=0&currency=USD&depart=2026-05-26&hotel=48567&level=hotel&locale=en-US&productcurrency=USD&rooms=1&start=availresults',
  '+855-96-919-0000',
  'Sibling site — Shinta Mani Wild (Cambodia). See anchor row id 12193.',
  'Waterfall Tent category: four tents at the camp''s waterfall edge with rushing-water setting; romantic/secluded positioning. Units: The Cambodian Royalty Tent, First Lady Jackie Kennedy''s Tent, The National Geographic Tent, The Gibbons Tent.',
  '4 waterfall tents; all-inclusive 3-night min.',
  '2026-05-21', '2026-05-21', 'private_commercial',
  15, 4, '2', '3', 'Year-round; seasonal camp themes Jan–Dec',
  NULL, NULL, NULL,
  '{"2026":{"named_units":["The Cambodian Royalty Tent","First Lady Jackie Kennedy''s Tent","The National Geographic Tent","The Gibbons Tent"]}}'::jsonb,
  'Yes', 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'Yes',
  'Yes', 'Yes', 'Yes',
  'Waterfall setting; soaking tub; all-inclusive; couples-oriented.'
),
(
  '669f2d86-4423-42c9-9439-3929557fcae6'::uuid,
  'published', 'Yes', 'Yes',
  'Shinta Mani Wild', 'Two Bedroom Tent',
  'shinta-mani-wild-koh-kong-kh', 'Glamping Resort', 'Safari Tent',
  'Sage', 'web_research_shinta_mani_wild_synxis_2026_05', 'Cambodia', 'Koh Kong', 'Kampong Seila',
  'Prey Praseth Village, Ou Bak Rothed Commune, Kampong Seila, Cambodia 180403', '180403',
  11.580, 103.880,
  'https://be.synxis.com/?adult=2&arrive=2026-05-23&chain=27625&child=0&currency=USD&depart=2026-05-26&hotel=48567&level=hotel&locale=en-US&productcurrency=USD&rooms=1&start=availresults',
  '+855-96-919-0000',
  'Sibling site — Shinta Mani Wild (Cambodia). See anchor row id 12193.',
  'Two Bedroom Tent: single 141 sqm tent (The Wildlife Alliance Tent, #6) near Raging Big Sister Falls; sleeps 4–6 with optional Jungle Capsule add-on; family/group category.',
  'One two-bedroom tent on property.',
  '2026-05-21', '2026-05-21', 'private_commercial',
  15, 1, '6', '3', 'Year-round; seasonal camp themes Jan–Dec',
  NULL, NULL, NULL,
  '{"2026":{"named_units":["The Wildlife Alliance Tent"]}}'::jsonb,
  'Yes', 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'Yes',
  'Yes', 'Yes', 'Yes',
  'Two bedrooms; Wildlife Alliance theme; optional Jungle Capsule; all-inclusive.'
);

UPDATE public.all_glamping_properties SET
  description = 'Sibling site — Shinta Mani Wild (Cambodia). See anchor row id 12193.',
  url = 'https://be.synxis.com/?adult=2&arrive=2026-05-23&chain=27625&child=0&currency=USD&depart=2026-05-26&hotel=48567&level=hotel&locale=en-US&productcurrency=USD&rooms=1&start=availresults',
  phone_number = '+855-96-919-0000',
  country = 'Cambodia',
  state = 'Koh Kong',
  city = 'Kampong Seila',
  address = 'Prey Praseth Village, Ou Bak Rothed Commune, Kampong Seila, Cambodia 180403',
  zip_code = '180403',
  lat = 11.580,
  lon = 103.880,
  property_total_sites = 15,
  minimum_nights = '3',
  is_glamping_property = 'Yes',
  is_open = 'Yes',
  property_type = 'Glamping Resort',
  slug = 'shinta-mani-wild-koh-kong-kh',
  land_operator_category = 'private_commercial',
  setting_forest = 'Yes',
  activities_wildlife_watching = 'Yes',
  activities_hiking = 'Yes',
  unit_private_bathroom = 'Yes',
  unit_shower = 'Yes',
  unit_wifi = 'Yes',
  unit_air_conditioning = 'Yes',
  unit_hot_tub = 'Yes',
  unit_campfires = 'Yes'
WHERE property_name = 'Shinta Mani Wild' AND id <> 12193;
