-- SUJÁN Jawai enrichment + new properties The Serai & Sher Bagh (May 2026)
-- Sources: Synxis (chain 23169), thesujanlife.com camp pages, AFAR / CN Traveler

-- ========== SUJÁN JAWAI (anchor id 12194) ==========
UPDATE public.all_glamping_properties SET
  property_id = '05de5919-3265-49fe-99e6-4c54be45a9d0'::uuid,
  site_name = 'Tented Rock Suite',
  slug = 'sujan-jawai-pali-rj-in',
  property_type = 'Glamping Resort',
  unit_type = 'Safari Tent',
  source = 'Sage',
  discovery_source = 'web_research_sujan_synxis_site_2026_05',
  country = 'India',
  state = 'RJ',
  city = 'Jawai',
  address = 'Jawai Bandh Bisalpur, Jawai Bandh, Rajasthan 306401, India',
  zip_code = '306401',
  lat = 25.080,
  lon = 73.680,
  url = 'https://thesujanlife.com/sujan-camps/sujan-jawai',
  phone_number = '+91-11-4617-2700',
  research_status = 'published',
  is_glamping_property = 'Yes',
  is_open = 'Yes',
  property_total_sites = 10,
  quantity_of_units = 1,
  unit_capacity = '4',
  minimum_nights = '1',
  operating_season_months = 'Year-round',
  unit_private_bathroom = 'Yes',
  unit_shower = 'Yes',
  unit_kitchenette = 'No',
  unit_wifi = 'Yes',
  unit_air_conditioning = 'Yes',
  unit_campfires = 'Yes',
  unit_hot_tub = 'Yes',
  property_family_friendly = 'Yes',
  setting_mountainous = 'Yes',
  setting_desert = 'Yes',
  activities_wildlife_watching = 'Yes',
  activities_hiking = 'Yes',
  activities_horseback_riding = 'Yes',
  land_operator_category = 'private_commercial',
  date_updated = '2026-05-21',
  description = $$SUJÁN Jawai — pioneering conservation-led luxury tented camp among billion-year-old granite formations in Rajasthan's Aravalli Hills, where leopards coexist with Rabari villages. Ten intimate tented suites including Rock Suites, the two-tent Felidae family suite, the secluded Royal Panthera Suite, and private Eden encampment. Wilderness-edge pool, Marwari horse rides, twice-daily drives, Relais & Châteaux hospitality.$$,
  unit_description = $$Tented Rock Suite: king bed plus two daybeds (sleeps up to four); 1,020 sq ft; private deck with writing desk and lounge; sweeping Jawai wilderness views; stilted tent minimizing footprint. Synxis lists 1 king bed.$$,
  notes = COALESCE(notes, '') || E'\n\nSite enrichment (May 2026): Synxis hotel 2201. Sample May 29–30, 2026 (1 adult, USD): BAR $909, Published $1,239/night. AFAR from-rate ~$1,100 (Apr 2026).',
  amenities_raw = 'King bed; 2 daybeds; 1,020 sq ft; private deck; outdoor lounge; leopard/wildlife drives; pool; butler-style camp service.',
  rate_avg_retail_daily_rate = 909,
  rate_summer_weekday = 909,
  rate_summer_weekend = 1239,
  rate_unit_rates_by_year = '{"2026":{"sample_dates":"2026-05-29_to_2026-05-30","currency":"USD","guests":1,"synxis_hotel":2201,"tiers":[{"rate_plan":"best_available","nightly":909},{"rate_plan":"published","nightly":1239}],"afar_from_rate":1100}}'::jsonb
WHERE id = 12194;

INSERT INTO public.all_glamping_properties (
  property_id, research_status, is_glamping_property, is_open,
  property_name, site_name, slug, property_type, unit_type,
  source, discovery_source, country, state, city,
  address, zip_code, lat, lon, url, phone_number,
  description, unit_description, notes,
  date_added, date_updated, land_operator_category,
  property_total_sites, quantity_of_units, unit_capacity, minimum_nights,
  operating_season_months,
  rate_avg_retail_daily_rate, rate_summer_weekday, rate_summer_weekend,
  rate_unit_rates_by_year,
  unit_private_bathroom, unit_shower, unit_kitchenette, unit_wifi,
  unit_air_conditioning, unit_campfires, unit_hot_tub,
  property_family_friendly, setting_mountainous, setting_desert,
  activities_wildlife_watching, activities_hiking, activities_horseback_riding,
  amenities_raw
) VALUES
(
  '05de5919-3265-49fe-99e6-4c54be45a9d0'::uuid,
  'published', 'Yes', 'Yes',
  'Suján Jawai', 'The Felidae Suite',
  'sujan-jawai-pali-rj-in', 'Glamping Resort', 'Safari Tent',
  'Sage', 'web_research_sujan_synxis_site_2026_05', 'India', 'RJ', 'Jawai',
  'Jawai Bandh Bisalpur, Jawai Bandh, Rajasthan 306401, India', '306401',
  25.080, 73.680,
  'https://thesujanlife.com/sujan-camps/sujan-jawai',
  '+91-11-4617-2700',
  'Sibling site — Suján Jawai (Pali RJ). See anchor row id 12194.',
  'The Felidae Suite (Family Felidae Suite): two tents sharing a common plinth and verandah, set apart for privacy; ideal for families or groups of four; favorite leopard-viewing location on camp.',
  'Not in Synxis online inventory for sampled dates — contact reservations@thesujanlife.com.',
  '2026-05-21', '2026-05-21', 'private_commercial',
  10, 1, '4', '1', 'Year-round',
  NULL, NULL, NULL, NULL,
  'Yes', 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'Yes',
  'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes',
  'Two connected tents; shared verandah; family/group suite; leopard country views.'
),
(
  '05de5919-3265-49fe-99e6-4c54be45a9d0'::uuid,
  'published', 'Yes', 'Yes',
  'Suján Jawai', 'The Royal Panthera Suite',
  'sujan-jawai-pali-rj-in', 'Glamping Resort', 'Safari Tent',
  'Sage', 'web_research_sujan_synxis_site_2026_05', 'India', 'RJ', 'Jawai',
  'Jawai Bandh Bisalpur, Jawai Bandh, Rajasthan 306401, India', '306401',
  25.080, 73.680,
  'https://thesujanlife.com/sujan-camps/sujan-jawai',
  '+91-11-4617-2700',
  'Sibling site — Suján Jawai (Pali RJ). See anchor row id 12194.',
  'The Royal Panthera Suite: secluded from main camp; king bed; 1,770 sq ft; romance and privacy amid wilderness; private deck and unparalleled space.',
  'Synxis May 29–30, 2026 (1 adult, USD): BAR $2,076, Published $2,272/night.',
  '2026-05-21', '2026-05-21', 'private_commercial',
  10, 1, '2', '1', 'Year-round',
  2076, 2076, 2272,
  '{"2026":{"sample_dates":"2026-05-29_to_2026-05-30","currency":"USD","guests":1,"synxis_hotel":2201,"tiers":[{"rate_plan":"best_available","nightly":2076},{"rate_plan":"published","nightly":2272}]}}'::jsonb,
  'Yes', 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'Yes',
  'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes',
  'King bed; 1,770 sq ft; private secluded suite; deck; wilderness views.'
),
(
  '05de5919-3265-49fe-99e6-4c54be45a9d0'::uuid,
  'published', 'Yes', 'Yes',
  'Suján Jawai', 'Eden at Jawai',
  'sujan-jawai-pali-rj-in', 'Glamping Resort', 'Villa',
  'Sage', 'web_research_sujan_synxis_site_2026_05', 'India', 'RJ', 'Jawai',
  'Jawai Bandh Bisalpur, Jawai Bandh, Rajasthan 306401, India', '306401',
  25.080, 73.680,
  'https://thesujanlife.com/sujan-camps/sujan-jawai',
  '+91-11-4617-2700',
  'Sibling site — Suján Jawai (Pali RJ). See anchor row id 12194.',
  'Eden at Jawai: exclusive private encampment with three double bedrooms, private entrance, private pool, boma, and bespoke dining; set away from guest tents.',
  'Private encampment — book via SUJÁN reservations; not in Synxis online engine.',
  '2026-05-21', '2026-05-21', 'private_commercial',
  10, 1, '6', '1', 'Year-round',
  NULL, NULL, NULL, NULL,
  'Yes', 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'Yes',
  'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes',
  'Private encampment; 3 bedrooms; private pool; boma; bespoke service.'
);

UPDATE public.all_glamping_properties SET
  description = 'Sibling site — Suján Jawai (Pali RJ). See anchor row id 12194.',
  url = 'https://thesujanlife.com/sujan-camps/sujan-jawai',
  phone_number = '+91-11-4617-2700',
  country = 'India', state = 'RJ', city = 'Jawai',
  address = 'Jawai Bandh Bisalpur, Jawai Bandh, Rajasthan 306401, India',
  zip_code = '306401', lat = 25.080, lon = 73.680,
  property_total_sites = 10, quantity_of_units = 1,
  is_glamping_property = 'Yes', is_open = 'Yes',
  property_type = 'Glamping Resort', slug = 'sujan-jawai-pali-rj-in',
  land_operator_category = 'private_commercial',
  property_family_friendly = 'Yes',
  setting_mountainous = 'Yes', setting_desert = 'Yes',
  activities_wildlife_watching = 'Yes', activities_hiking = 'Yes',
  activities_horseback_riding = 'Yes',
  unit_private_bathroom = 'Yes', unit_shower = 'Yes',
  unit_wifi = 'Yes', unit_air_conditioning = 'Yes',
  unit_hot_tub = 'Yes', unit_campfires = 'Yes'
WHERE property_name = 'Suján Jawai' AND id <> 12194;

-- ========== SUJÁN THE SERAI (new property) ==========
INSERT INTO public.all_glamping_properties (
  property_id, research_status, is_glamping_property, is_open,
  property_name, site_name, slug, property_type, unit_type,
  source, discovery_source, country, state, city,
  address, zip_code, lat, lon, url, phone_number,
  description, unit_description, notes,
  date_added, date_updated, land_operator_category,
  property_total_sites, quantity_of_units, unit_capacity, minimum_nights,
  operating_season_months,
  rate_avg_retail_daily_rate, rate_summer_weekday, rate_summer_weekend,
  rate_unit_rates_by_year,
  unit_private_bathroom, unit_shower, unit_kitchenette, unit_wifi,
  unit_air_conditioning, unit_campfires, unit_hot_tub,
  property_family_friendly, setting_desert,
  activities_wildlife_watching, activities_hiking, activities_scenic_drives,
  amenities_raw
)
SELECT * FROM (VALUES
(
  'f8a1b2c3-d4e5-4f6a-9b0c-1d2e3f4a5b6c'::uuid,
  'published', 'Yes', 'Yes',
  'Suján The Serai', 'Luxury Tent',
  'sujan-the-serai-jaisalmer-rj-in', 'Glamping Resort', 'Safari Tent',
  'Sage', 'web_research_sujan_synxis_site_2026_05', 'India', 'RJ', 'Jaisalmer',
  'Bherwa, Jaisalmer, Rajasthan 345001, India', '345001',
  26.920::numeric, 70.920::numeric,
  'https://thesujanlife.com/sujan-camps/sujan-the-serai',
  '+91-11-4617-2700',
  $$SUJÁN The Serai — 21 hand-stitched canvas tents on a 100-acre private Thar Desert estate near Jaisalmer, inspired by royal Rajput caravan encampments. Relais & Châteaux desert camp with organic farm, spa, Manganiyar musicians, camel/jeep sundowners, and Golden Fort UNESCO excursions. Categories: fourteen Luxury Tents, six Luxury Tented Suites, one Royal Tented Suite.$$,
  'Luxury Tent: king bed; 960 sq ft; pitched on local Jaisalmer stone base; outdoor veranda and seating; inner tented lounge; desert-scape views. Fourteen tents on property.',
  'Synxis hotel 2200. Sample Oct 15–16, 2026 (1 adult, USD Published): $1,012/night. Property closed on Synxis for May 29–30, 2026.',
  '2026-05-21', '2026-05-21', 'private_commercial',
  21, 1, '2', '1', 'Oct–Mar peak desert season',
  1012, 1012, 1012,
  '{"2026":{"sample_dates":"2026-10-15_to_2026-10-16","currency":"USD","guests":1,"synxis_hotel":2200,"tiers":[{"rate_plan":"published","nightly":1012}],"note":"May 2026 dates unavailable online"}}'::jsonb,
  'Yes', 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'Yes',
  'Yes', 'Yes', 'Yes', 'Yes', 'Yes',
  'King bed; 960 sq ft; veranda; stone plinth; lounge; desert views; Relais & Châteaux.'
)
) AS v(
  property_id, research_status, is_glamping_property, is_open,
  property_name, site_name, slug, property_type, unit_type,
  source, discovery_source, country, state, city,
  address, zip_code, lat, lon, url, phone_number,
  description, unit_description, notes,
  date_added, date_updated, land_operator_category,
  property_total_sites, quantity_of_units, unit_capacity, minimum_nights,
  operating_season_months,
  rate_avg_retail_daily_rate, rate_summer_weekday, rate_summer_weekend,
  rate_unit_rates_by_year,
  unit_private_bathroom, unit_shower, unit_kitchenette, unit_wifi,
  unit_air_conditioning, unit_campfires, unit_hot_tub,
  property_family_friendly, setting_desert,
  activities_wildlife_watching, activities_hiking, activities_scenic_drives,
  amenities_raw
)
WHERE NOT EXISTS (
  SELECT 1 FROM public.all_glamping_properties p
  WHERE p.slug = 'sujan-the-serai-jaisalmer-rj-in' AND p.site_name = 'Luxury Tent'
);

INSERT INTO public.all_glamping_properties (
  property_id, research_status, is_glamping_property, is_open,
  property_name, site_name, slug, property_type, unit_type,
  source, discovery_source, country, state, city,
  address, zip_code, lat, lon, url, phone_number,
  description, unit_description, notes,
  date_added, date_updated, land_operator_category,
  property_total_sites, quantity_of_units, unit_capacity, minimum_nights,
  operating_season_months,
  rate_avg_retail_daily_rate, rate_summer_weekday, rate_summer_weekend,
  rate_unit_rates_by_year,
  unit_private_bathroom, unit_shower, unit_kitchenette, unit_wifi,
  unit_air_conditioning, unit_campfires, unit_hot_tub,
  property_family_friendly, setting_desert,
  activities_wildlife_watching, activities_hiking, activities_scenic_drives,
  amenities_raw
) VALUES
(
  'f8a1b2c3-d4e5-4f6a-9b0c-1d2e3f4a5b6c'::uuid,
  'published', 'Yes', 'Yes',
  'Suján The Serai', 'Luxury Tented Suite',
  'sujan-the-serai-jaisalmer-rj-in', 'Glamping Resort', 'Safari Tent',
  'Sage', 'web_research_sujan_synxis_site_2026_05', 'India', 'RJ', 'Jaisalmer',
  'Bherwa, Jaisalmer, Rajasthan 345001, India', '345001',
  26.920, 70.920,
  'https://thesujanlife.com/sujan-camps/sujan-the-serai',
  '+91-11-4617-2700',
  'Sibling site — Suján The Serai (Jaisalmer RJ). See anchor Luxury Tent row.',
  'Luxury Tented Suite: king bed; 1,260 sq ft; private heated plunge pool; seclusion; six suites on property.',
  'Synxis Oct 15–16, 2026 Published: $1,487/night (1 adult, USD).',
  '2026-05-21', '2026-05-21', 'private_commercial',
  21, 1, '2', '1', 'Oct–Mar peak desert season',
  1487, 1487, 1487,
  '{"2026":{"sample_dates":"2026-10-15_to_2026-10-16","currency":"USD","guests":1,"synxis_hotel":2200,"tiers":[{"rate_plan":"published","nightly":1487}]}}'::jsonb,
  'Yes', 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'Yes',
  'Yes', 'Yes', 'Yes', 'Yes', 'Yes',
  'King bed; 1,260 sq ft; heated plunge pool; desert suite.'
),
(
  'f8a1b2c3-d4e5-4f6a-9b0c-1d2e3f4a5b6c'::uuid,
  'published', 'Yes', 'Yes',
  'Suján The Serai', 'Royal Tented Suite',
  'sujan-the-serai-jaisalmer-rj-in', 'Glamping Resort', 'Villa',
  'Sage', 'web_research_sujan_synxis_site_2026_05', 'India', 'RJ', 'Jaisalmer',
  'Bherwa, Jaisalmer, Rajasthan 345001, India', '345001',
  26.920, 70.920,
  'https://thesujanlife.com/sujan-camps/sujan-the-serai',
  '+91-11-4617-2700',
  'Sibling site — Suján The Serai (Jaisalmer RJ). See anchor Luxury Tent row.',
  'Royal Tented Suite: private encampment with king bed; 3,260 sq ft; heated outdoor plunge pool; massage area; pergola dining and lounge tents.',
  'Synxis Oct 15–16, 2026 Published: $2,313/night (1 adult, USD).',
  '2026-05-21', '2026-05-21', 'private_commercial',
  21, 1, '2', '1', 'Oct–Mar peak desert season',
  2313, 2313, 2313,
  '{"2026":{"sample_dates":"2026-10-15_to_2026-10-16","currency":"USD","guests":1,"synxis_hotel":2200,"tiers":[{"rate_plan":"published","nightly":2313}]}}'::jsonb,
  'Yes', 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'Yes',
  'Yes', 'Yes', 'Yes', 'Yes', 'Yes',
  'King bed; 3,260 sq ft; private pool; massage area; pergola tents.'
);

UPDATE public.all_glamping_properties SET
  description = 'Sibling site — Suján The Serai (Jaisalmer RJ). See anchor Luxury Tent row.',
  url = 'https://thesujanlife.com/sujan-camps/sujan-the-serai',
  phone_number = '+91-11-4617-2700',
  country = 'India', state = 'RJ', city = 'Jaisalmer',
  address = 'Bherwa, Jaisalmer, Rajasthan 345001, India',
  zip_code = '345001', lat = 26.920, lon = 70.920,
  property_total_sites = 21, quantity_of_units = 1,
  is_glamping_property = 'Yes', is_open = 'Yes',
  property_type = 'Glamping Resort', slug = 'sujan-the-serai-jaisalmer-rj-in',
  land_operator_category = 'private_commercial',
  property_family_friendly = 'Yes', setting_desert = 'Yes',
  activities_wildlife_watching = 'Yes', activities_hiking = 'Yes',
  activities_scenic_drives = 'Yes',
  unit_private_bathroom = 'Yes', unit_shower = 'Yes',
  unit_wifi = 'Yes', unit_air_conditioning = 'Yes',
  unit_hot_tub = 'Yes', unit_campfires = 'Yes'
WHERE property_name = 'Suján The Serai' AND site_name <> 'Luxury Tent';

-- ========== SUJÁN SHER BAGH (new property) ==========
INSERT INTO public.all_glamping_properties (
  property_id, research_status, is_glamping_property, is_open,
  property_name, site_name, slug, property_type, unit_type,
  source, discovery_source, country, state, city,
  address, zip_code, lat, lon, url, phone_number,
  description, unit_description, notes,
  date_added, date_updated, land_operator_category,
  property_total_sites, quantity_of_units, unit_capacity, minimum_nights,
  operating_season_months,
  rate_avg_retail_daily_rate, rate_summer_weekday, rate_summer_weekend,
  rate_unit_rates_by_year,
  unit_private_bathroom, unit_shower, unit_kitchenette, unit_wifi,
  unit_air_conditioning, unit_campfires, unit_hot_tub,
  property_family_friendly, setting_forest,
  activities_wildlife_watching, activities_hiking,
  amenities_raw
)
SELECT * FROM (VALUES
(
  'a1b2c3d4-e5f6-4789-a0b1-c2d3e4f56789'::uuid,
  'published', 'Yes', 'Yes',
  'Suján Sher Bagh', 'Tented Jungle Suite',
  'sujan-sher-bagh-ranthambhore-rj-in', 'Glamping Resort', 'Safari Tent',
  'Sage', 'web_research_sujan_synxis_site_2026_05', 'India', 'RJ', 'Ranthambhore',
  'Sherpur Khiljipur, Sawai Madhopur, Ranthambhore, Rajasthan 322001, India', '322001',
  26.020::numeric, 76.390::numeric,
  'https://thesujanlife.com/sujan-camps/sujan-sher-bagh',
  '+91-11-4617-2700',
  $$SUJÁN Sher Bagh — India's first positive-impact safari camp (est. 25 years ago) on the edge of Ranthambhore National Park. Twelve campaign-style tented suites under peepal trees with copper bathtubs, Anglo-Indian farm-to-table dining, and tiger/leopard game drives. Relais & Châteaux. Suite types: Jungle, Machhli, Royal Sher, and Imperial Raj Bagh.$$,
  'Tented Jungle Suite: classic Indian wilderness safari tent; king bed; 568 sq ft; ensuite with brass bathtub; campaign furniture; vintage objects.',
  'Synxis hotel 1959. Sample May 29–30, 2026 Published: $734/night (1 adult, USD). CN Traveler from ~$1,349. National park fees and drives extra.',
  '2026-05-21', '2026-05-21', 'private_commercial',
  12, 1, '2', '1', 'Oct–Jun safari season',
  734, 734, 734,
  '{"2026":{"sample_dates":"2026-05-29_to_2026-05-30","currency":"USD","guests":1,"synxis_hotel":1959,"tiers":[{"rate_plan":"published","nightly":734}],"cntraveler_from_rate":1349}}'::jsonb,
  'Yes', 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'No',
  'Yes', 'Yes', 'Yes', 'Yes',
  'King bed; 568 sq ft; brass bathtub; campaign-style tent; Ranthambhore edge.'
)
) AS v(
  property_id, research_status, is_glamping_property, is_open,
  property_name, site_name, slug, property_type, unit_type,
  source, discovery_source, country, state, city,
  address, zip_code, lat, lon, url, phone_number,
  description, unit_description, notes,
  date_added, date_updated, land_operator_category,
  property_total_sites, quantity_of_units, unit_capacity, minimum_nights,
  operating_season_months,
  rate_avg_retail_daily_rate, rate_summer_weekday, rate_summer_weekend,
  rate_unit_rates_by_year,
  unit_private_bathroom, unit_shower, unit_kitchenette, unit_wifi,
  unit_air_conditioning, unit_campfires, unit_hot_tub,
  property_family_friendly, setting_forest,
  activities_wildlife_watching, activities_hiking,
  amenities_raw
)
WHERE NOT EXISTS (
  SELECT 1 FROM public.all_glamping_properties p
  WHERE p.slug = 'sujan-sher-bagh-ranthambhore-rj-in' AND p.site_name = 'Tented Jungle Suite'
);

INSERT INTO public.all_glamping_properties (
  property_id, research_status, is_glamping_property, is_open,
  property_name, site_name, slug, property_type, unit_type,
  source, discovery_source, country, state, city,
  address, zip_code, lat, lon, url, phone_number,
  description, unit_description, notes,
  date_added, date_updated, land_operator_category,
  property_total_sites, quantity_of_units, unit_capacity, minimum_nights,
  operating_season_months,
  rate_avg_retail_daily_rate, rate_summer_weekday, rate_summer_weekend,
  rate_unit_rates_by_year,
  unit_private_bathroom, unit_shower, unit_kitchenette, unit_wifi,
  unit_air_conditioning, unit_campfires, unit_hot_tub,
  property_family_friendly, setting_forest,
  activities_wildlife_watching, activities_hiking,
  amenities_raw
) VALUES
(
  'a1b2c3d4-e5f6-4789-a0b1-c2d3e4f56789'::uuid,
  'published', 'Yes', 'Yes',
  'Suján Sher Bagh', 'The Machhli Suite',
  'sujan-sher-bagh-ranthambhore-rj-in', 'Glamping Resort', 'Safari Tent',
  'Sage', 'web_research_sujan_synxis_site_2026_05', 'India', 'RJ', 'Ranthambhore',
  'Sherpur Khiljipur, Sawai Madhopur, Ranthambhore, Rajasthan 322001, India', '322001',
  26.020, 76.390,
  'https://thesujanlife.com/sujan-camps/sujan-sher-bagh',
  '+91-11-4617-2700',
  'Sibling site — Suján Sher Bagh (Ranthambhore RJ). See anchor Tented Jungle Suite row.',
  'The Machhli Suite: named for legendary Ranthambhore tigress; two tents (not interconnected); celebrates camp heritage and tiger conservation.',
  'Not in Synxis online inventory for sampled dates — contact reservations.',
  '2026-05-21', '2026-05-21', 'private_commercial',
  12, 1, '4', '1', 'Oct–Jun safari season',
  NULL, NULL, NULL, NULL,
  'Yes', 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'No',
  'Yes', 'Yes', 'Yes', 'Yes',
  'Two tents; Machhli heritage suite; tiger reserve views.'
),
(
  'a1b2c3d4-e5f6-4789-a0b1-c2d3e4f56789'::uuid,
  'published', 'Yes', 'Yes',
  'Suján Sher Bagh', 'The Royal Sher Suite',
  'sujan-sher-bagh-ranthambhore-rj-in', 'Glamping Resort', 'Safari Tent',
  'Sage', 'web_research_sujan_synxis_site_2026_05', 'India', 'RJ', 'Ranthambhore',
  'Sherpur Khiljipur, Sawai Madhopur, Ranthambhore, Rajasthan 322001, India', '322001',
  26.020, 76.390,
  'https://thesujanlife.com/sujan-camps/sujan-sher-bagh',
  '+91-11-4617-2700',
  'Sibling site — Suján Sher Bagh (Ranthambhore RJ). See anchor Tented Jungle Suite row.',
  'The Royal Sher Suite: one double-bedroom suite; 753 sq ft; ultimate privacy and seclusion; king bed; luxury campaign style.',
  'Synxis May 29–30, 2026 Published: $1,394/night (1 adult, USD).',
  '2026-05-21', '2026-05-21', 'private_commercial',
  12, 1, '2', '1', 'Oct–Jun safari season',
  1394, 1394, 1394,
  '{"2026":{"sample_dates":"2026-05-29_to_2026-05-30","currency":"USD","guests":1,"synxis_hotel":1959,"tiers":[{"rate_plan":"published","nightly":1394}]}}'::jsonb,
  'Yes', 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'No',
  'Yes', 'Yes', 'Yes', 'Yes',
  'King bed; 753 sq ft; secluded royal suite; copper bath.'
),
(
  'a1b2c3d4-e5f6-4789-a0b1-c2d3e4f56789'::uuid,
  'published', 'Yes', 'Yes',
  'Suján Sher Bagh', 'The Imperial Raj Bagh Suite',
  'sujan-sher-bagh-ranthambhore-rj-in', 'Glamping Resort', 'Villa',
  'Sage', 'web_research_sujan_synxis_site_2026_05', 'India', 'RJ', 'Ranthambhore',
  'Sherpur Khiljipur, Sawai Madhopur, Ranthambhore, Rajasthan 322001, India', '322001',
  26.020, 76.390,
  'https://thesujanlife.com/sujan-camps/sujan-sher-bagh',
  '+91-11-4617-2700',
  'Sibling site — Suján Sher Bagh (Ranthambhore RJ). See anchor Tented Jungle Suite row.',
  'The Imperial Raj Bagh Suite: finest camp address; two double-bedroom suite; secluded from main tents; spacious quiet retreat.',
  'Not in Synxis online inventory for sampled dates — contact reservations.',
  '2026-05-21', '2026-05-21', 'private_commercial',
  12, 1, '4', '1', 'Oct–Jun safari season',
  NULL, NULL, NULL, NULL,
  'Yes', 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'No',
  'Yes', 'Yes', 'Yes', 'Yes',
  'Two double bedrooms; imperial suite; private; campaign luxury.'
);

UPDATE public.all_glamping_properties SET
  description = 'Sibling site — Suján Sher Bagh (Ranthambhore RJ). See anchor Tented Jungle Suite row.',
  url = 'https://thesujanlife.com/sujan-camps/sujan-sher-bagh',
  phone_number = '+91-11-4617-2700',
  country = 'India', state = 'RJ', city = 'Ranthambhore',
  address = 'Sherpur Khiljipur, Sawai Madhopur, Ranthambhore, Rajasthan 322001, India',
  zip_code = '322001', lat = 26.020, lon = 76.390,
  property_total_sites = 12, quantity_of_units = 1,
  is_glamping_property = 'Yes', is_open = 'Yes',
  property_type = 'Glamping Resort', slug = 'sujan-sher-bagh-ranthambhore-rj-in',
  land_operator_category = 'private_commercial',
  property_family_friendly = 'Yes', setting_forest = 'Yes',
  activities_wildlife_watching = 'Yes', activities_hiking = 'Yes',
  unit_private_bathroom = 'Yes', unit_shower = 'Yes',
  unit_wifi = 'Yes', unit_air_conditioning = 'Yes',
  unit_campfires = 'Yes'
WHERE property_name = 'Suján Sher Bagh' AND site_name <> 'Tented Jungle Suite';
