-- The Canyon at Pond Creek (Pikeville TN): property enrichment + 6 geodesic dome site rows.
-- Sources: us2.cloudbeds.com booking engine NxfNT7 + metadata API (May 2026).
-- Sample rates: Cloudbeds Standard Rate, check-in 2026-06-16, check-out 2026-06-18 (2 nights, excl. taxes/fees).

UPDATE public.all_glamping_properties SET
  property_name = 'The Canyon at Pond Creek',
  site_name = 'Dome#1',
  slug = 'the-canyon-at-pond-creek-pikeville-tn',
  url = 'https://us2.cloudbeds.com/en/reservation/NxfNT7?rid=72539036008681',
  address = '1316 Canyon Dr',
  city = 'Pikeville',
  state = 'TN',
  zip_code = '37367',
  country = 'United States',
  lat = 35.5111,
  lon = -85.3415,
  phone_number = '+1-423-243-0697',
  is_open = 'Yes',
  research_status = 'published',
  is_glamping_property = 'Yes',
  property_type = 'Glamping Resort',
  unit_type = 'Geodesic Dome',
  property_total_sites = 6,
  quantity_of_units = 1,
  unit_capacity = '8',
  minimum_nights = '2',
  operating_season_months = 'Year-round (Cloudbeds booking engine; 4WD/AWD recommended for gravel access road)',
  unit_private_bathroom = 'Yes',
  unit_shower = 'Yes',
  unit_kitchenette = 'Yes',
  unit_hot_tub = 'Yes',
  unit_air_conditioning = 'Yes',
  unit_wifi = 'Yes',
  unit_pets = 'No',
  property_family_friendly = 'Yes',
  setting_mountainous = 'Yes',
  setting_forest = 'Yes',
  activities_hiking = 'Yes',
  activities_climbing = 'Yes',
  activities_wildlife_watching = 'Yes',
  activities_stargazing = 'Yes',
  description = $$The Canyon at Pond Creek — luxury geodesic domes on ~447 acres of Cumberland Plateau canyon wilderness near Pikeville TN (1316 Canyon Dr). Six cliff-top domes overlook the Sequatchie Valley with private decks, full kitchens, ensuite baths, hot tubs, Wi‑Fi, and canyon views. Gated gravel access (4WD/AWD recommended); ~25 min to Fall Creek Falls State Park; ~1 hr Chattanooga. On-site climbing, hiking trails, and swimming holes.$$,
  unit_description = $$Dome#1: California king, two full beds in loft, queen sofa bed, full-size refrigerator; sleeps 6–8. Geodesic dome with kitchen, ensuite bath, hot tub, A/C, Wi‑Fi, TV; private canyon-view deck.$$,
  notes = COALESCE(notes, '') || E'\n\nSite enrichment (May 2026): Cloudbeds NxfNT7 + metadata. Sample Standard Rate $598 / 2 nights ($299/night) for 2026-06-16–18 excl. taxes/fees. Cloudbeds room id 72539036008681.',
  amenities_raw = 'California king, loft full beds, queen sofa bed, full fridge, kitchen, ensuite bath/shower, hot tub, A/C, Wi‑Fi, TV, coffee maker, microwave, hair dryer, linens/towels.',
  discovery_source = 'web_research_cloudbeds_2026_05',
  date_updated = '2026-05-18',
  land_operator_category = 'private_commercial',
  rate_avg_retail_daily_rate = 299,
  rate_summer_weekday = 299,
  rate_summer_weekend = 299,
  rate_unit_rates_by_year = '{"2026":{"summer":{"weekday":299,"weekend":299,"nights":2,"total":598,"sample_checkin":"2026-06-16","sample_checkout":"2026-06-18","source":"cloudbeds NxfNT7 Standard Rate excl taxes/fees"}}}'::jsonb
WHERE id = 11795;

INSERT INTO public.all_glamping_properties (
  property_id,
  research_status, is_glamping_property, is_open,
  property_name, site_name, slug, property_type, unit_type,
  source, discovery_source, country, state, city,
  address, zip_code, lat, lon, url, phone_number,
  description, unit_description, notes,
  date_added, date_updated, land_operator_category,
  property_total_sites, quantity_of_units, unit_capacity,
  minimum_nights,
  rate_avg_retail_daily_rate, rate_summer_weekday, rate_summer_weekend,
  rate_unit_rates_by_year,
  unit_private_bathroom, unit_shower, unit_kitchenette, unit_hot_tub,
  unit_air_conditioning, unit_wifi, unit_pets,
  setting_mountainous, setting_forest,
  activities_hiking, activities_climbing, activities_wildlife_watching, activities_stargazing,
  amenities_raw
)
SELECT
  property_id, research_status, is_glamping_property, is_open,
  property_name, site_name, slug, property_type, unit_type,
  source, discovery_source, country, state, city,
  address, zip_code, lat, lon, url, phone_number,
  description, unit_description, notes,
  date_added, date_updated, land_operator_category,
  property_total_sites, quantity_of_units, unit_capacity,
  minimum_nights,
  rate_avg_retail_daily_rate, rate_summer_weekday, rate_summer_weekend,
  rate_unit_rates_by_year,
  unit_private_bathroom, unit_shower, unit_kitchenette, unit_hot_tub,
  unit_air_conditioning, unit_wifi, unit_pets,
  setting_mountainous, setting_forest,
  activities_hiking, activities_climbing, activities_wildlife_watching, activities_stargazing,
  amenities_raw
FROM (VALUES
(
  '7bf42b80-03f3-4be9-b7e5-0abcf3238c09',
  'published', 'Yes', 'Yes',
  'The Canyon at Pond Creek', 'Dome#2',
  'the-canyon-at-pond-creek-pikeville-tn', 'Glamping Resort', 'Geodesic Dome',
  'Sage', 'web_research_cloudbeds_2026_05', 'United States', 'TN', 'Pikeville',
  '1316 Canyon Dr', '37367', 35.5111::numeric, -85.3415::numeric,
  'https://us2.cloudbeds.com/en/reservation/NxfNT7?rid=72538896417001',
  '+1-423-243-0697',
  $$Sibling site — The Canyon at Pond Creek (Pikeville TN). See anchor Dome#1 row id 11795.$$,
  $$Dome#2: California king, two full beds in loft, queen sofa bed, full-size refrigerator; sleeps 6–8. Geodesic dome with kitchen, ensuite bath, hot tub, canyon-view deck.$$,
  $$Cloudbeds room id 72538896417001. Sample $638 / 2 nights ($319/night) 2026-06-16–18 excl. taxes/fees.$$,
  '2026-05-18', '2026-05-18', 'private_commercial',
  6, 1, '8', '2',
  319, 319, 319,
  '{"2026":{"summer":{"weekday":319,"weekend":319,"nights":2,"total":638,"sample_checkin":"2026-06-16","sample_checkout":"2026-06-18","source":"cloudbeds NxfNT7"}}}'::jsonb,
  'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'No',
  'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes',
  'California king, loft full beds, queen sofa, full fridge, kitchen, bath, hot tub, A/C, Wi‑Fi.'
),
(
  '7bf42b80-03f3-4be9-b7e5-0abcf3238c09',
  'published', 'Yes', 'Yes',
  'The Canyon at Pond Creek', 'Dome#3',
  'the-canyon-at-pond-creek-pikeville-tn', 'Glamping Resort', 'Geodesic Dome',
  'Sage', 'web_research_cloudbeds_2026_05', 'United States', 'TN', 'Pikeville',
  '1316 Canyon Dr', '37367', 35.5111::numeric, -85.3415::numeric,
  'https://us2.cloudbeds.com/en/reservation/NxfNT7?rid=72539036008694',
  '+1-423-243-0697',
  $$Sibling site — The Canyon at Pond Creek (Pikeville TN).$$,
  $$Dome#3: Queen bed, full bed in loft, small refrigerator; sleeps 3–4. Geodesic dome with kitchen, ensuite bath, hot tub, canyon view.$$,
  $$Cloudbeds room id 72539036008694. Sample $578 / 2 nights ($289/night) 2026-06-16–18 excl. taxes/fees.$$,
  '2026-05-18', '2026-05-18', 'private_commercial',
  6, 1, '4', '2',
  289, 289, 289,
  '{"2026":{"summer":{"weekday":289,"weekend":289,"nights":2,"total":578,"sample_checkin":"2026-06-16","sample_checkout":"2026-06-18","source":"cloudbeds NxfNT7"}}}'::jsonb,
  'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'No',
  'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes',
  'Queen bed, loft full bed, small fridge, kitchen, bath, hot tub, A/C, Wi‑Fi.'
),
(
  '7bf42b80-03f3-4be9-b7e5-0abcf3238c09',
  'published', 'Yes', 'Yes',
  'The Canyon at Pond Creek', 'Dome#4',
  'the-canyon-at-pond-creek-pikeville-tn', 'Glamping Resort', 'Geodesic Dome',
  'Sage', 'web_research_cloudbeds_2026_05', 'United States', 'TN', 'Pikeville',
  '1316 Canyon Dr', '37367', 35.5111::numeric, -85.3415::numeric,
  'https://us2.cloudbeds.com/en/reservation/NxfNT7?rid=72539610263689',
  '+1-423-243-0697',
  $$Sibling site — The Canyon at Pond Creek (Pikeville TN).$$,
  $$Dome#4: Queen bed, queen sofa bed, full bed in loft, small refrigerator; sleeps 4–6. Geodesic dome with kitchen, ensuite bath, hot tub.$$,
  $$Cloudbeds room id 72539610263689. Sample $598 / 2 nights ($299/night) 2026-06-16–18 excl. taxes/fees.$$,
  '2026-05-18', '2026-05-18', 'private_commercial',
  6, 1, '6', '2',
  299, 299, 299,
  '{"2026":{"summer":{"weekday":299,"weekend":299,"nights":2,"total":598,"sample_checkin":"2026-06-16","sample_checkout":"2026-06-18","source":"cloudbeds NxfNT7"}}}'::jsonb,
  'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'No',
  'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes',
  'Queen bed, queen sofa, loft full bed, small fridge, kitchen, bath, hot tub, A/C, Wi‑Fi.'
),
(
  '7bf42b80-03f3-4be9-b7e5-0abcf3238c09',
  'published', 'Yes', 'Yes',
  'The Canyon at Pond Creek', 'Dome#5',
  'the-canyon-at-pond-creek-pikeville-tn', 'Glamping Resort', 'Geodesic Dome',
  'Sage', 'web_research_cloudbeds_2026_05', 'United States', 'TN', 'Pikeville',
  '1316 Canyon Dr', '37367', 35.5111::numeric, -85.3415::numeric,
  'https://us2.cloudbeds.com/en/reservation/NxfNT7?rid=72539610267789',
  '+1-423-243-0697',
  $$Sibling site — The Canyon at Pond Creek (Pikeville TN).$$,
  $$Dome#5: Queen bed, full bed in loft, queen sofa bed, small refrigerator; sleeps 4–6. Geodesic dome with kitchen, ensuite bath, hot tub.$$,
  $$Cloudbeds room id 72539610267789. Sample $598 / 2 nights ($299/night) 2026-06-16–18 excl. taxes/fees.$$,
  '2026-05-18', '2026-05-18', 'private_commercial',
  6, 1, '6', '2',
  299, 299, 299,
  '{"2026":{"summer":{"weekday":299,"weekend":299,"nights":2,"total":598,"sample_checkin":"2026-06-16","sample_checkout":"2026-06-18","source":"cloudbeds NxfNT7"}}}'::jsonb,
  'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'No',
  'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes',
  'Queen bed, loft full bed, queen sofa, small fridge, kitchen, bath, hot tub, A/C, Wi‑Fi.'
),
(
  '7bf42b80-03f3-4be9-b7e5-0abcf3238c09',
  'published', 'Yes', 'Yes',
  'The Canyon at Pond Creek', 'Dome#6',
  'the-canyon-at-pond-creek-pikeville-tn', 'Glamping Resort', 'Geodesic Dome',
  'Sage', 'web_research_cloudbeds_2026_05', 'United States', 'TN', 'Pikeville',
  '1316 Canyon Dr', '37367', 35.5111::numeric, -85.3415::numeric,
  'https://us2.cloudbeds.com/en/reservation/NxfNT7?rid=72539949019320',
  '+1-423-243-0697',
  $$Sibling site — The Canyon at Pond Creek (Pikeville TN).$$,
  $$Dome#6: Queen sofa bed, king bed in loft, full-size refrigerator; sleeps 4. Geodesic dome with kitchen, ensuite bath, hot tub, canyon view.$$,
  $$Cloudbeds room id 72539949019320. Sample $598 / 2 nights ($299/night) 2026-06-16–18 excl. taxes/fees.$$,
  '2026-05-18', '2026-05-18', 'private_commercial',
  6, 1, '4', '2',
  299, 299, 299,
  '{"2026":{"summer":{"weekday":299,"weekend":299,"nights":2,"total":598,"sample_checkin":"2026-06-16","sample_checkout":"2026-06-18","source":"cloudbeds NxfNT7"}}}'::jsonb,
  'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'No',
  'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes',
  'Queen sofa bed, king loft bed, full fridge, kitchen, bath, hot tub, A/C, Wi‑Fi.'
)
) AS v(
  property_id, research_status, is_glamping_property, is_open,
  property_name, site_name, slug, property_type, unit_type,
  source, discovery_source, country, state, city,
  address, zip_code, lat, lon, url, phone_number,
  description, unit_description, notes,
  date_added, date_updated, land_operator_category,
  property_total_sites, quantity_of_units, unit_capacity,
  minimum_nights,
  rate_avg_retail_daily_rate, rate_summer_weekday, rate_summer_weekend,
  rate_unit_rates_by_year,
  unit_private_bathroom, unit_shower, unit_kitchenette, unit_hot_tub,
  unit_air_conditioning, unit_wifi, unit_pets,
  setting_mountainous, setting_forest,
  activities_hiking, activities_climbing, activities_wildlife_watching, activities_stargazing,
  amenities_raw
)
WHERE NOT EXISTS (
  SELECT 1 FROM public.all_glamping_properties p
  WHERE p.property_id = v.property_id AND p.site_name = v.site_name
);
