-- Capella Ubud: site inventory from capellahotels.com + Synxis booker (May 2026)
-- Sources: accommodation page, Synxis RBE (hotel 3217 / chain 21430), AFAR Hotels We Love (Apr 2026)
-- Enriches anchor row id 12187; inserts 4 sibling tent/lodge category rows (23 tented suites total).

UPDATE public.all_glamping_properties SET
  property_id = '5df9503b-6850-4c93-aa07-1f56ad0eb18a'::uuid,
  site_name = 'Keliki Tent',
  slug = 'capella-ubud-keliki-valley-tent-bali-id',
  property_type = 'Glamping Resort',
  unit_type = 'Safari Tent',
  source = 'Sage',
  discovery_source = 'web_research_capella_ubud_synxis_2026_05',
  country = 'Indonesia',
  state = 'Bali',
  city = 'Ubud',
  address = 'Jl. Raya Dalem, Banjar Triwangsa Desa Keliki, Kecamatan Tegallalang Ubud, Gianyar Bali 80561, Indonesia',
  zip_code = '80561',
  lat = -8.450,
  lon = 115.280,
  url = 'https://be.synxis.com/?adult=1&arrive=2026-10-14&chain=21430&child=0&currency=IDR&depart=2026-10-16&departure=2026-10-16&dest=RBE&hotel=3217&lang=en-US&level=hotel&locale=en-US&productcurrency=IDR&rooms=1&start=availresults',
  phone_number = '+62-361-2091888',
  research_status = 'published',
  is_glamping_property = 'Yes',
  is_open = 'Yes',
  property_total_sites = 23,
  quantity_of_units = 1,
  unit_capacity = '2',
  minimum_nights = '1',
  operating_season_months = 'Year-round',
  unit_private_bathroom = 'Yes',
  unit_shower = 'Yes',
  unit_kitchenette = 'No',
  unit_wifi = 'Yes',
  unit_air_conditioning = 'Yes',
  unit_campfires = 'No',
  unit_hot_tub = 'Yes',
  property_family_friendly = 'Yes',
  setting_forest = 'Yes',
  activities_wildlife_watching = 'Yes',
  activities_hiking = 'Yes',
  land_operator_category = 'private_commercial',
  date_updated = '2026-05-21',
  description = $$Capella Ubud, Bali — Bill Bensley-designed rainforest camp in Keliki Village with 23 teak-floored tented suites (no trees felled), ~4.5 miles from central Ubud along the sacred Wos River. Categories: Keliki Tent, Valley Tent, Forest Tent, Terrace Tent, and Two Bedroom Lodge. Included guest services: breakfast at Mads Lange, Officers' Tent rituals, Capella Culturist, The Cistern heated pool, in-tent refreshments, Camp Rangers cultural activities, and more. Book via Synxis or capellahotels.com.$$,
  unit_description = $$Keliki Tent: one-bedroom tented suite with heated private pool and Keliki Valley views; outdoor deck with daybed; copper bathtub; indoor and outdoor showers; curated in-tent amenities.$$,
  notes = COALESCE(notes, '') || E'\n\nSite enrichment (May 2026): capellahotels.com/en/capella-ubud/accommodation; Synxis hotel 3217 (Oct 14–16, 2026 sample — category ADRs not captured in automated scrape). AFAR from-rate ~USD 650/night (Apr 2026). info.ubud@capellahotels.com.',
  amenities_raw = 'Heated private pool; valley views; outdoor deck; daybed; copper bathtub; indoor/outdoor showers; breakfast; Officers Tent rituals; Culturist; The Cistern pool; in-tent refreshments; Bamford toiletries; Wi-Fi; Camp Rangers activities.',
  rate_avg_retail_daily_rate = 650,
  rate_summer_weekday = 650,
  rate_summer_weekend = 650,
  rate_unit_rates_by_year = '{"2026":{"sample_dates":"2026-10-14_to_2026-10-16","currency_requested":"IDR","currency_usd_check":"USD","guests":1,"hotel":3217,"chain":21430,"synxis_url":"be.synxis.com","categories":["Keliki Tent","Valley Tent","Forest Tent","Terrace Tent","Two Bedroom Lodge"],"afar_from_rate_usd":650,"note":"Synxis room/rate cards did not render in automated scrape; re-quote per category for travel dates"}}'::jsonb
WHERE id = 12187;

INSERT INTO public.all_glamping_properties (
  property_id, research_status, is_glamping_property, is_open,
  property_name, site_name, slug, property_type, unit_type,
  source, discovery_source, country, state, city,
  address, zip_code, lat, lon, url, phone_number,
  description, unit_description, notes,
  date_added, date_updated, land_operator_category,
  property_total_sites, quantity_of_units, unit_capacity, minimum_nights,
  operating_season_months,
  rate_avg_retail_daily_rate, rate_summer_weekday, rate_summer_weekend,
  rate_unit_rates_by_year,
  unit_private_bathroom, unit_shower, unit_kitchenette, unit_wifi,
  unit_air_conditioning, unit_campfires, unit_hot_tub,
  property_family_friendly, setting_forest,
  activities_wildlife_watching, activities_hiking,
  amenities_raw
) VALUES
(
  '5df9503b-6850-4c93-aa07-1f56ad0eb18a'::uuid,
  'published', 'Yes', 'Yes',
  'Capella Ubud', 'Valley Tent',
  'capella-ubud-keliki-valley-tent-bali-id', 'Glamping Resort', 'Safari Tent',
  'Sage', 'web_research_capella_ubud_synxis_2026_05', 'Indonesia', 'Bali', 'Ubud',
  'Jl. Raya Dalem, Banjar Triwangsa Desa Keliki, Kecamatan Tegallalang Ubud, Gianyar Bali 80561, Indonesia', '80561',
  -8.450, 115.280,
  'https://be.synxis.com/?adult=1&arrive=2026-10-14&chain=21430&child=0&currency=IDR&depart=2026-10-16&departure=2026-10-16&dest=RBE&hotel=3217&lang=en-US&level=hotel&locale=en-US&productcurrency=IDR&rooms=1&start=availresults',
  '+62-361-2091888',
  'Sibling site — Capella Ubud (Bali). See anchor row id 12187.',
  'Valley Tent: one-bedroom tented suite with plunge pool and jungle views; outdoor deck with daybed; copper bathtub; indoor and outdoor showers; largest one-bedroom category per Capella site copy.',
  'Re-quote ADR in Synxis for travel dates; Oct 2026 sample not captured in scrape.',
  '2026-05-21', '2026-05-21', 'private_commercial',
  23, 1, '2', '1', 'Year-round',
  NULL, NULL, NULL,
  '{"2026":{"note":"Valley Tent — re-quote in Synxis for Oct 14–16, 2026 or preferred dates"}}'::jsonb,
  'Yes', 'Yes', 'No', 'Yes', 'Yes', 'No', 'Yes',
  'Yes', 'Yes', 'Yes', 'Yes',
  'Plunge pool; jungle views; deck; daybed; copper tub; indoor/outdoor showers; included guest services.'
),
(
  '5df9503b-6850-4c93-aa07-1f56ad0eb18a'::uuid,
  'published', 'Yes', 'Yes',
  'Capella Ubud', 'Forest Tent',
  'capella-ubud-keliki-valley-tent-bali-id', 'Glamping Resort', 'Safari Tent',
  'Sage', 'web_research_capella_ubud_synxis_2026_05', 'Indonesia', 'Bali', 'Ubud',
  'Jl. Raya Dalem, Banjar Triwangsa Desa Keliki, Kecamatan Tegallalang Ubud, Gianyar Bali 80561, Indonesia', '80561',
  -8.450, 115.280,
  'https://be.synxis.com/?adult=1&arrive=2026-10-14&chain=21430&child=0&currency=IDR&depart=2026-10-16&departure=2026-10-16&dest=RBE&hotel=3217&lang=en-US&level=hotel&locale=en-US&productcurrency=IDR&rooms=1&start=availresults',
  '+62-361-2091888',
  'Sibling site — Capella Ubud (Bali). See anchor row id 12187.',
  'Forest Tent: one-bedroom tented suite with plunge pool and lush panoramas; outdoor deck with daybed; copper bathtub; indoor and outdoor showers; accessible by camp buggy.',
  'Re-quote ADR in Synxis for travel dates.',
  '2026-05-21', '2026-05-21', 'private_commercial',
  23, 1, '2', '1', 'Year-round',
  NULL, NULL, NULL,
  NULL,
  'Yes', 'Yes', 'No', 'Yes', 'Yes', 'No', 'Yes',
  'Yes', 'Yes', 'Yes', 'Yes',
  'Plunge pool; lush panoramas; buggy access; deck; daybed; copper tub; showers.'
),
(
  '5df9503b-6850-4c93-aa07-1f56ad0eb18a'::uuid,
  'published', 'Yes', 'Yes',
  'Capella Ubud', 'Terrace Tent',
  'capella-ubud-keliki-valley-tent-bali-id', 'Glamping Resort', 'Safari Tent',
  'Sage', 'web_research_capella_ubud_synxis_2026_05', 'Indonesia', 'Bali', 'Ubud',
  'Jl. Raya Dalem, Banjar Triwangsa Desa Keliki, Kecamatan Tegallalang Ubud, Gianyar Bali 80561, Indonesia', '80561',
  -8.450, 115.280,
  'https://be.synxis.com/?adult=1&arrive=2026-10-14&chain=21430&child=0&currency=IDR&depart=2026-10-16&departure=2026-10-16&dest=RBE&hotel=3217&lang=en-US&level=hotel&locale=en-US&productcurrency=IDR&rooms=1&start=availresults',
  '+62-361-2091888',
  'Sibling site — Capella Ubud (Bali). See anchor row id 12187.',
  'Terrace Tent: one-bedroom tented suite with plunge pool and forest views; outdoor deck with daybed; copper bathtub; indoor and outdoor showers; forest-front setting.',
  'Re-quote ADR in Synxis for travel dates.',
  '2026-05-21', '2026-05-21', 'private_commercial',
  23, 1, '2', '1', 'Year-round',
  NULL, NULL, NULL,
  NULL,
  'Yes', 'Yes', 'No', 'Yes', 'Yes', 'No', 'Yes',
  'Yes', 'Yes', 'Yes', 'Yes',
  'Plunge pool; forest views; deck; daybed; copper tub; showers.'
),
(
  '5df9503b-6850-4c93-aa07-1f56ad0eb18a'::uuid,
  'published', 'Yes', 'Yes',
  'Capella Ubud', 'Two Bedroom Lodge',
  'capella-ubud-keliki-valley-tent-bali-id', 'Glamping Resort', 'Safari Tent',
  'Sage', 'web_research_capella_ubud_synxis_2026_05', 'Indonesia', 'Bali', 'Ubud',
  'Jl. Raya Dalem, Banjar Triwangsa Desa Keliki, Kecamatan Tegallalang Ubud, Gianyar Bali 80561, Indonesia', '80561',
  -8.450, 115.280,
  'https://be.synxis.com/?adult=1&arrive=2026-10-14&chain=21430&child=0&currency=IDR&depart=2026-10-16&departure=2026-10-16&dest=RBE&hotel=3217&lang=en-US&level=hotel&locale=en-US&productcurrency=IDR&rooms=1&start=availresults',
  '+62-361-2091888',
  'Sibling site — Capella Ubud (Bali). See anchor row id 12187.',
  'Two Bedroom Lodge: two-bedroom family lodge with oriental-themed interior, Keliki Valley views, and private 19 sqm pool; premium multi-bedroom category.',
  'Family lodge; re-quote ADR in Synxis for travel dates.',
  '2026-05-21', '2026-05-21', 'private_commercial',
  23, 1, '4', '1', 'Year-round',
  NULL, NULL, NULL,
  NULL,
  'Yes', 'Yes', 'No', 'Yes', 'Yes', 'No', 'Yes',
  'Yes', 'Yes', 'Yes', 'Yes',
  'Two bedrooms; 19 sqm private pool; valley views; family lodge; included guest services.'
);

UPDATE public.all_glamping_properties SET
  description = 'Sibling site — Capella Ubud (Bali). See anchor row id 12187.',
  url = 'https://be.synxis.com/?adult=1&arrive=2026-10-14&chain=21430&child=0&currency=IDR&depart=2026-10-16&departure=2026-10-16&dest=RBE&hotel=3217&lang=en-US&level=hotel&locale=en-US&productcurrency=IDR&rooms=1&start=availresults',
  phone_number = '+62-361-2091888',
  country = 'Indonesia',
  state = 'Bali',
  city = 'Ubud',
  address = 'Jl. Raya Dalem, Banjar Triwangsa Desa Keliki, Kecamatan Tegallalang Ubud, Gianyar Bali 80561, Indonesia',
  zip_code = '80561',
  lat = -8.450,
  lon = 115.280,
  property_total_sites = 23,
  quantity_of_units = 1,
  minimum_nights = '1',
  is_glamping_property = 'Yes',
  is_open = 'Yes',
  property_type = 'Glamping Resort',
  slug = 'capella-ubud-keliki-valley-tent-bali-id',
  land_operator_category = 'private_commercial',
  property_family_friendly = 'Yes',
  setting_forest = 'Yes',
  activities_wildlife_watching = 'Yes',
  activities_hiking = 'Yes',
  unit_private_bathroom = 'Yes',
  unit_shower = 'Yes',
  unit_wifi = 'Yes',
  unit_air_conditioning = 'Yes',
  unit_hot_tub = 'Yes'
WHERE property_name = 'Capella Ubud' AND id <> 12187;
