-- Naviva, a Four Seasons Resort: site inventory from fourseasons.com (May 2026)
-- Sources: accommodations + CAW booker (PVR784, May 21–22 2026, 2 adults), AFAR Hotels We Love (Apr 2026)
-- Enriches anchor row id 12190; inserts 1 sibling category row (15 bungalows total).

INSERT INTO public.glamping_brands (slug, display_name, brand_tier, legacy_chain_key, website_url)
VALUES ('four-seasons', 'Four Seasons', 'standalone', 'four seasons', 'https://www.fourseasons.com/')
ON CONFLICT (slug) DO UPDATE SET display_name = EXCLUDED.display_name, updated_at = now();

UPDATE public.all_glamping_properties SET
  property_id = '8dc6fb82-3351-4a68-a708-235d05e11a2b'::uuid,
  brand_id = (SELECT id FROM public.glamping_brands WHERE slug = 'four-seasons'),
  site_name = 'Ocean-View Bungalow',
  slug = 'naviva-four-seasons-resort-punta-mita-mx',
  property_type = 'Glamping Resort',
  unit_type = 'Safari Tent',
  source = 'Sage',
  discovery_source = 'web_research_naviva_fs_booking_2026_05',
  country = 'Mexico',
  state = 'Nayarit',
  city = 'Punta de Mita',
  address = 'Punta Mita, Riviera Nayarit, Mexico',
  zip_code = '63734',
  lat = 20.790,
  lon = -105.520,
  url = 'https://www.fourseasons.com/naviva/accommodations/',
  phone_number = '+52-329-291-6100',
  research_status = 'published',
  is_glamping_property = 'Yes',
  is_open = 'Yes',
  property_total_sites = 15,
  quantity_of_units = 1,
  unit_capacity = '2',
  minimum_nights = '1',
  operating_season_months = 'Year-round',
  unit_private_bathroom = 'Yes',
  unit_shower = 'Yes',
  unit_kitchenette = 'No',
  unit_wifi = 'Yes',
  unit_air_conditioning = 'Yes',
  unit_campfires = 'Yes',
  unit_hot_tub = 'Yes',
  property_family_friendly = 'No',
  setting_forest = 'Yes',
  setting_coastal = 'Yes',
  setting_beach = 'Yes',
  activities_wildlife_watching = 'Yes',
  activities_hiking = 'Yes',
  land_operator_category = 'private_commercial',
  date_updated = '2026-05-21',
  description = $$Naviva®, a Four Seasons Resort — adults-only luxury tented camp in the Punta Mita jungle (48 forested acres), three minutes from Four Seasons Punta Mita. Fifteen stand-alone bungalow tents under monarch-butterfly-inspired canopies with air conditioning, biophilic design, and Four Seasons service. Categories: Ocean-View Bungalow and Ocean-View Grand Bungalow. Primary booking via Naviva® All-Inclusive Package (meals, premium beverages, spa journey, daily experiences).$$,
  unit_description = $$Ocean-View Bungalow: one king bed; 116 m² (1,259 sq ft) indoor-outdoor space for 2 adults; open-air living room and separate bedroom opening to expansive deck with private plunge pool and hammock; ocean views and sunsets; indoor/outdoor shower; includes all food and beverage, spa journey, and daily experiences under all-inclusive package.$$,
  notes = COALESCE(notes, '') || E'\n\nSite enrichment (May 2026): fourseasons.com/naviva CAW (PVR784). Sample dates May 21–22, 2026, 2 adults. AFAR from-rate ~$3,861/night (Apr 2026). Live nightly rates render client-side in FS booker — re-quote for travel dates. Adults-only.',
  amenities_raw = 'King bed; 1,259 sq ft; private plunge pool; hammock; open-air living; separate bedroom; indoor/outdoor shower; A/C; all-inclusive F&B; spa journey; ocean views; Four Seasons service.',
  rate_avg_retail_daily_rate = 3861,
  rate_summer_weekday = 3861,
  rate_summer_weekend = 3861,
  rate_unit_rates_by_year = '{"2026":{"sample_dates":"2026-05-21_to_2026-05-22","currency":"USD","guests":2,"location_id":"PVR784","offer":"Naviva All-Inclusive Package (RACALL)","afar_from_rate":3861,"note":"Category-specific ADRs not exposed in static scrape; verify in FS CAW booker"}}'::jsonb
WHERE id = 12190;

INSERT INTO public.all_glamping_properties (
  property_id, brand_id, research_status, is_glamping_property, is_open,
  property_name, site_name, slug, property_type, unit_type,
  source, discovery_source, country, state, city,
  address, zip_code, lat, lon, url, phone_number,
  description, unit_description, notes,
  date_added, date_updated, land_operator_category,
  property_total_sites, quantity_of_units, unit_capacity, minimum_nights,
  operating_season_months,
  rate_avg_retail_daily_rate, rate_summer_weekday, rate_summer_weekend,
  rate_unit_rates_by_year,
  unit_private_bathroom, unit_shower, unit_kitchenette, unit_wifi,
  unit_air_conditioning, unit_campfires, unit_hot_tub,
  property_family_friendly, setting_forest, setting_coastal, setting_beach,
  activities_wildlife_watching, activities_hiking, amenities_raw
) VALUES
(
  '8dc6fb82-3351-4a68-a708-235d05e11a2b'::uuid,
  (SELECT id FROM public.glamping_brands WHERE slug = 'four-seasons'),
  'published', 'Yes', 'Yes',
  'Naviva', 'Ocean-View Grand Bungalow',
  'naviva-four-seasons-resort-punta-mita-mx', 'Glamping Resort', 'Safari Tent',
  'Sage', 'web_research_naviva_fs_booking_2026_05', 'Mexico', 'Nayarit', 'Punta de Mita',
  'Punta Mita, Riviera Nayarit, Mexico', '63734',
  20.790, -105.520,
  'https://www.fourseasons.com/naviva/accommodations/',
  '+52-329-291-6100',
  'Sibling site — Naviva (Punta Mita MX). See anchor row id 12190.',
  'Ocean-View Grand Bungalow: one king bed; 149–160 m² (1,604–1,722 sq ft) for 2 adults; screened porch; extended deck with private plunge pool and gas firepit; lounge area; indoor shower, bathtub, and outdoor shower; all-inclusive F&B, spa journey, and daily experiences.',
  'Premium category per FS accommodations page. Re-quote ADR in CAW booker for travel dates.',
  '2026-05-21', '2026-05-21', 'private_commercial',
  15, 1, '2', '1', 'Year-round',
  NULL, NULL, NULL,
  NULL,
  'Yes', 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'Yes',
  'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes',
  'King bed; up to 1,722 sq ft; plunge pool; firepit; screened porch; indoor/outdoor bath; all-inclusive package; ocean views.'
);

UPDATE public.all_glamping_properties SET
  brand_id = (SELECT id FROM public.glamping_brands WHERE slug = 'four-seasons'),
  description = 'Sibling site — Naviva (Punta Mita MX). See anchor row id 12190.',
  url = 'https://www.fourseasons.com/naviva/accommodations/',
  phone_number = '+52-329-291-6100',
  country = 'Mexico',
  state = 'Nayarit',
  city = 'Punta de Mita',
  address = 'Punta Mita, Riviera Nayarit, Mexico',
  zip_code = '63734',
  lat = 20.790,
  lon = -105.520,
  property_total_sites = 15,
  quantity_of_units = 1,
  is_glamping_property = 'Yes',
  is_open = 'Yes',
  property_type = 'Glamping Resort',
  slug = 'naviva-four-seasons-resort-punta-mita-mx',
  land_operator_category = 'private_commercial',
  property_family_friendly = 'No',
  setting_forest = 'Yes',
  setting_coastal = 'Yes',
  setting_beach = 'Yes',
  activities_wildlife_watching = 'Yes',
  activities_hiking = 'Yes',
  unit_private_bathroom = 'Yes',
  unit_shower = 'Yes',
  unit_wifi = 'Yes',
  unit_air_conditioning = 'Yes',
  unit_hot_tub = 'Yes',
  unit_campfires = 'Yes'
WHERE property_name = 'Naviva' AND id <> 12190;
