-- The Yurtopian Wimberley (Wimberley TX): 6 named luxury yurt site rows from theyurtopian.com (May 2026).
-- Booking: https://theyurtopian.com/book-glamping-in-texas-hill-country/ (Wimberley yurts; dynamic calendar pricing).

UPDATE public.all_glamping_properties SET
  property_name = 'The Yurtopian Wimberley',
  site_name = 'Cara Ger',
  url = 'https://theyurtopian.com/book-glamping-in-texas-hill-country/',
  unit_type = 'Yurt',
  property_type = 'Glamping Resort',
  property_total_sites = 6,
  quantity_of_units = 1,
  unit_capacity = '2',
  minimum_nights = '1',
  operating_season_months = 'Year-round glamping; single-night stays often available Sun–Thu (not holidays) per operator FAQ',
  city = 'Wimberley',
  state = 'TX',
  country = 'United States',
  address = '135 Winn Ranch Road',
  zip_code = '78676',
  lat = 29.971787,
  lon = -98.111729,
  phone_number = '+1 512-333-2202',
  unit_private_bathroom = 'Yes',
  unit_shower = 'Yes',
  unit_full_kitchen = 'No',
  unit_kitchenette = 'Yes',
  unit_wifi = 'Yes',
  unit_pets = 'No',
  unit_campfires = 'Yes',
  unit_picnic_table = 'Yes',
  unit_patio = 'Yes',
  unit_hot_tub = 'Yes',
  unit_air_conditioning = 'Yes',
  unit_electricity = 'Yes',
  property_hot_tub = 'Yes',
  property_family_friendly = 'No',
  setting_forest = 'Yes',
  setting_field = 'Yes',
  activities_stargazing = 'Yes',
  activities_hiking = 'Yes',
  activities_wildlife_watching = 'Yes',
  description = $$The Yurtopian Wimberley — adults-only luxury Mongolian yurt glamping on ~23 wooded acres off CR 1492 & Shade Road, 135 Winn Ranch Road, Wimberley TX (~5 min from downtown). Six hand-painted private yurts (Cara, Mila, Greta, Sasha, Lena, Becca Ger), each 300+ ft apart with rooftop deck, private hot tub/plunge pool, gas fire pit, outdoor kitchen (propane grill, mini fridge, pour-over coffee), outdoor stone shower, and ensuite bathroom. King beds, A/C & heat, Roku smart TV. Wimberley Dark Sky Community stargazing. Book via theyurtopian.com reservation calendar (hotel-style dynamic rates). No pets at Wimberley location per operator.$$,
  unit_description = $$Cara Ger — welcoming Wimberley yurt with valley views; hand-painted Mongolian interior; king bed; sofa; A/C & heat; private hot tub/plunge pool; gas fire pit; outdoor kitchen (grill, mini fridge, pour-over coffee, sink); outdoor stone shower + private bath; rooftop deck. Adults-only couples retreat.$$,
  notes = COALESCE(notes, '') || E'\n\nSite enrichment (May 2026): 6 named Wimberley yurts from theyurtopian.com unit pages + book-glamping-in-texas-hill-country. Nightly rate $362.50 is prior Sage property proxy — verify on live booking calendar (taxes/fees extra). Wimberley: adults-only, not pet-friendly per booking page (Greta unit page once flagged dog-friendly; resort FAQ confirms no pets Wimberley).',
  amenities_raw = 'Per yurt: king bed, hand-painted dome, minisplit A/C-heat, private hot tub-plunge pool, gas fire pit, outdoor kitchenette, propane grill, outdoor stone shower, private bathroom, rooftop deck, Roku TV, picnic table. Property: 23 acres, wooded privacy, dark-sky stargazing, near Wimberley Square.',
  discovery_source = 'web_research_theyurtopian_wimberley_2026_05',
  date_updated = '2026-05-18',
  land_operator_category = 'private_commercial',
  rate_avg_retail_daily_rate = 363,
  rate_summer_weekday = 363,
  rate_summer_weekend = 363,
  rate_unit_rates_by_year = '{"2026":{"sage_proxy_nightly":363,"unit_page":"https://theyurtopian.com/texas-hill-country-glamping-cara/","note":"Verify theyurtopian.com booking calendar; prior Sage avg $362.50"}}'::jsonb
WHERE id = 11439;

INSERT INTO public.all_glamping_properties (
  property_id,
  research_status, is_glamping_property, is_open,
  property_name, site_name, slug, property_type, unit_type,
  source, discovery_source, country, state, city,
  address, zip_code, lat, lon, url, phone_number,
  description, unit_description, notes,
  date_added, date_updated, land_operator_category,
  property_total_sites, quantity_of_units, unit_capacity, minimum_nights,
  rate_avg_retail_daily_rate, rate_summer_weekday, rate_summer_weekend,
  rate_unit_rates_by_year,
  unit_private_bathroom, unit_shower, unit_full_kitchen, unit_kitchenette, unit_wifi, unit_pets,
  unit_campfires, unit_picnic_table, unit_patio, unit_hot_tub, unit_air_conditioning, unit_electricity,
  property_hot_tub, property_family_friendly,
  setting_forest, setting_field,
  activities_stargazing, activities_hiking, activities_wildlife_watching,
  amenities_raw
) VALUES
(
  '3566f6a0-9a83-4a90-bb50-4c99b480dc5f',
  'published', 'Yes', 'Yes',
  'The Yurtopian Wimberley', 'Mila Ger',
  'the-yurtopian-wimberley', 'Glamping Resort', 'Yurt',
  'Sage', 'web_research_theyurtopian_wimberley_2026_05', 'United States', 'TX', 'Wimberley',
  '135 Winn Ranch Road', '78676', 29.971787, -98.111729,
  'https://theyurtopian.com/glamping-near-austin-mila/',
  '+1 512-333-2202',
  $$Sibling — The Yurtopian Wimberley. Anchor id 11439 (Cara Ger).$$,
  $$Mila Ger — Hill Country views; king bed under painted dome; sofa; A/C & heat; outdoor kitchenette (hot plate, mini fridge, sink, dishes); propane grill; outdoor stone shower + private bath; hot tub; fire pit; rooftop deck.$$,
  $$Unit page May 2026. Rate proxy $363/night — verify booking calendar.$$,
  '2026-05-18', '2026-05-18', 'private_commercial',
  6, 1, '2', '1',
  363, 363, 363,
  '{"2026":{"sage_proxy_nightly":363,"unit_page":"https://theyurtopian.com/glamping-near-austin-mila/"}}'::jsonb,
  'Yes', 'Yes', 'No', 'Yes', 'Yes', 'No',
  'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes',
  'Yes', 'No',
  'Yes', 'Yes',
  'Yes', 'Yes', 'Yes',
  'King bed, sofa, valley views, outdoor kitchenette w/ hot plate.'
),
(
  '3566f6a0-9a83-4a90-bb50-4c99b480dc5f',
  'published', 'Yes', 'Yes',
  'The Yurtopian Wimberley', 'Greta Ger',
  'the-yurtopian-wimberley', 'Glamping Resort', 'Yurt',
  'Sage', 'web_research_theyurtopian_wimberley_2026_05', 'United States', 'TX', 'Wimberley',
  '135 Winn Ranch Road', '78676', 29.971787, -98.111729,
  'https://theyurtopian.com/glamping-in-wimberley-texas/greta-ger/',
  '+1 512-333-2202',
  $$Sibling — The Yurtopian Wimberley. Anchor id 11439.$$,
  $$Greta Ger — secluded woods yurt; leather couch; king bed; hand-painted interior; A/C & heat; outdoor kitchen (grill, mini fridge, pour-over coffee); stone shower + private bath; hot tub; gas fire pit; rooftop deck. Unit page once labeled dog-friendly; resort booking FAQ: Wimberley not pet-friendly.$$,
  $$Unit page May 2026. Rate proxy $363/night.$$,
  '2026-05-18', '2026-05-18', 'private_commercial',
  6, 1, '2', '1',
  363, 363, 363,
  '{"2026":{"sage_proxy_nightly":363,"unit_page":"https://theyurtopian.com/glamping-in-wimberley-texas/greta-ger/"}}'::jsonb,
  'Yes', 'Yes', 'No', 'Yes', 'Yes', 'No',
  'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes',
  'Yes', 'No',
  'Yes', 'Yes',
  'Yes', 'Yes', 'Yes',
  'Secluded; leather couch; woods setting.'
),
(
  '3566f6a0-9a83-4a90-bb50-4c99b480dc5f',
  'published', 'Yes', 'Yes',
  'The Yurtopian Wimberley', 'Sasha Ger',
  'the-yurtopian-wimberley', 'Glamping Resort', 'Yurt',
  'Sage', 'web_research_theyurtopian_wimberley_2026_05', 'United States', 'TX', 'Wimberley',
  '135 Winn Ranch Road', '78676', 29.971787, -98.111729,
  'https://theyurtopian.com/wimberley-texas-glamping-sasha-ger/',
  '+1 512-333-2202',
  $$Sibling — The Yurtopian Wimberley. Anchor id 11439.$$,
  $$Sasha Ger — original OG yurt; deep-woods privacy; southwest sunset views from rooftop deck; lower-deck lounge; extra yard sunset seating; king bed; standard Yurtopian outdoor bath, kitchen, hot tub, fire pit.$$,
  $$Unit page May 2026. Rate proxy $363/night.$$,
  '2026-05-18', '2026-05-18', 'private_commercial',
  6, 1, '2', '1',
  363, 363, 363,
  '{"2026":{"sage_proxy_nightly":363,"unit_page":"https://theyurtopian.com/wimberley-texas-glamping-sasha-ger/"}}'::jsonb,
  'Yes', 'Yes', 'No', 'Yes', 'Yes', 'No',
  'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes',
  'Yes', 'No',
  'Yes', 'Yes',
  'Yes', 'Yes', 'Yes',
  'OG yurt; sunset views; extra outdoor lounge zone.'
),
(
  '3566f6a0-9a83-4a90-bb50-4c99b480dc5f',
  'published', 'Yes', 'Yes',
  'The Yurtopian Wimberley', 'Lena Ger',
  'the-yurtopian-wimberley', 'Glamping Resort', 'Yurt',
  'Sage', 'web_research_theyurtopian_wimberley_2026_05', 'United States', 'TX', 'Wimberley',
  '135 Winn Ranch Road', '78676', 29.971787, -98.111729,
  'https://theyurtopian.com/glamping-near-austin-lena-ger/',
  '+1 512-333-2202',
  $$Sibling — The Yurtopian Wimberley. Anchor id 11439.$$,
  $$Lena Ger — highest point on Wimberley property; valley + oak-tree deck views; hand-painted orange interior; king bed; sofa; desk; 55" Roku TV; covered dining; outdoor kitchenette; stone shower; private bath; hot tub; fire pit; rooftop deck.$$,
  $$Unit page lists full amenity set May 2026. Rate proxy $363/night.$$,
  '2026-05-18', '2026-05-18', 'private_commercial',
  6, 1, '2', '1',
  363, 363, 363,
  '{"2026":{"sage_proxy_nightly":363,"unit_page":"https://theyurtopian.com/glamping-near-austin-lena-ger/"}}'::jsonb,
  'Yes', 'Yes', 'No', 'Yes', 'Yes', 'No',
  'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes',
  'Yes', 'No',
  'Yes', 'Yes',
  'Yes', 'Yes', 'Yes',
  'Highest elevation site; oak shade on deck; orange interior theme.'
),
(
  '3566f6a0-9a83-4a90-bb50-4c99b480dc5f',
  'published', 'Yes', 'Yes',
  'The Yurtopian Wimberley', 'Becca Ger',
  'the-yurtopian-wimberley', 'Glamping Resort', 'Yurt',
  'Sage', 'web_research_theyurtopian_wimberley_2026_05', 'United States', 'TX', 'Wimberley',
  '135 Winn Ranch Road', '78676', 29.971787, -98.111729,
  'https://theyurtopian.com/romantic-glamping-in-texas-becca/',
  '+1 512-333-2202',
  $$Sibling — The Yurtopian Wimberley. Anchor id 11439.$$,
  $$Becca Ger — romantic hilltop yurt; signature red hand-painted door; king bed; expansive rooftop deck for stargazing; Wimberley Valley sunset views; hot tub; fire pit; outdoor kitchen; stone shower; private bath; sofa; Roku TV.$$,
  $$Unit page May 2026. Rate proxy $363/night.$$,
  '2026-05-18', '2026-05-18', 'private_commercial',
  6, 1, '2', '1',
  363, 363, 363,
  '{"2026":{"sage_proxy_nightly":363,"unit_page":"https://theyurtopian.com/romantic-glamping-in-texas-becca/"}}'::jsonb,
  'Yes', 'Yes', 'No', 'Yes', 'Yes', 'No',
  'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes',
  'Yes', 'No',
  'Yes', 'Yes',
  'Yes', 'Yes', 'Yes',
  'Red door; rooftop stargazing; romantic positioning.'
);
