-- Bespoke Outdoor Bubbles (Cleveland TX): 4 bookable dome/bubble site rows from bespokeoutdoorbubbles.com/accommodations (May 2026).
-- Rates: marketing "from" prices on accommodations page; MotoPress calendar pricing varies by date.

UPDATE public.all_glamping_properties SET
  property_name = 'Bespoke Outdoor Bubbles',
  site_name = 'Blissful Bubble Dome',
  url = 'https://bespokeoutdoorbubbles.com/blissful-bubble-dome/',
  unit_type = 'Bubble Tent',
  property_total_sites = 4,
  quantity_of_units = 1,
  unit_capacity = '2',
  minimum_nights = '1',
  operating_season_months = 'Year-round (verify holiday blackouts on operator calendar)',
  unit_private_bathroom = 'Yes',
  unit_shower = 'Yes',
  unit_full_kitchen = 'No',
  unit_kitchenette = 'No',
  unit_wifi = 'Yes',
  unit_pets = 'No',
  unit_campfires = 'Yes',
  unit_picnic_table = 'Yes',
  unit_air_conditioning = 'Yes',
  unit_electricity = 'Yes',
  unit_gas_fireplace = 'No',
  property_hot_tub = 'Yes',
  property_family_friendly = 'Yes',
  setting_forest = 'Yes',
  setting_field = 'Yes',
  activities_swimming = 'Yes',
  activities_wildlife_watching = 'Yes',
  description = $$Bespoke Outdoor Bubbles — luxury inflatable glamping domes on a ~8-acre ranchette in Sam Houston National Forest near North Cleveland TX (1060 Lilley Yeager Loop North). Four bookable stays: three individual bubble domes plus an Ultimate Bubble Bundle (exclusive use of all three). Shared amenities include Olympic-length pool & hot tub (typically 8am–10pm), outdoor kitchen, dining pavilion, fire pit, lawn games, and farm animals (goats, chickens, pigs, rabbits). ~45 min from Houston. Book via bespokeoutdoorbubbles.com (MotoPress Hotel Booking). No pets.$$,
  unit_description = $$Blissful Bubble Dome — romantic couples dome with lower 2/3 opaque walls for privacy and upper 1/3 transparent for stargazing. King bed (sleeps 2); private ensuite with clawfoot tub; A/C & heat; toiletries provided. Shared pool, hot tub, outdoor kitchen & pavilion on property.$$,
  notes = COALESCE(notes, '') || E'\n\nSite enrichment (May 2026): 4 SKUs from bespokeoutdoorbubbles.com/accommodations + unit pages. Published from-rates on accommodations page May 2026; calendar pricing may differ (+taxes/fees). Phone +1 (888) 303-0373.',
  amenities_raw = 'Dome: king bed, private bath w/ clawfoot tub, A/C & heat, partial transparency for stargazing. Property: shared Olympic pool & hot tub, outdoor kitchen w/ BBQ, fire pit, corn hole, hammocks, Wi‑Fi, free parking, farm animal visits, host greeting.',
  discovery_source = 'web_research_bespokeoutdoorbubbles_2026_05',
  date_updated = '2026-05-18',
  land_operator_category = 'private_commercial',
  phone_number = '+1 (888) 303-0373',
  rate_avg_retail_daily_rate = 224,
  rate_summer_weekday = 224,
  rate_summer_weekend = 224,
  rate_winter_weekday = 224,
  rate_winter_weekend = 224,
  rate_unit_rates_by_year = '{"2026":{"marketing_from_rate":{"weekday":224,"weekend":224,"note":"Accommodations page from $224/night; verify MotoPress calendar"}}}'::jsonb
WHERE id = 11573;

INSERT INTO public.all_glamping_properties (
  property_id,
  research_status, is_glamping_property, is_open,
  property_name, site_name, slug, property_type, unit_type,
  source, discovery_source, country, state, city,
  address, zip_code, lat, lon, url, phone_number,
  description, unit_description, notes,
  date_added, date_updated, land_operator_category,
  property_total_sites, quantity_of_units, unit_capacity, minimum_nights,
  rate_avg_retail_daily_rate, rate_summer_weekday, rate_summer_weekend,
  rate_winter_weekday, rate_winter_weekend,
  rate_unit_rates_by_year,
  unit_private_bathroom, unit_shower, unit_full_kitchen, unit_wifi,
  unit_pets, unit_campfires, unit_picnic_table, unit_air_conditioning, unit_electricity,
  property_hot_tub, property_family_friendly,
  setting_forest, setting_field,
  activities_swimming, activities_wildlife_watching,
  amenities_raw
) VALUES
(
  'a6a4956b-e4eb-4e5e-8d47-f091395afc68',
  'published', 'Yes', 'Yes',
  'Bespoke Outdoor Bubbles', 'Unique Sky Bubble Dome',
  'bespoke-outdoor-bubbles-cleveland-tx', 'Glamping', 'Bubble Tent',
  'Sage', 'web_research_bespokeoutdoorbubbles_2026_05', 'United States', 'TX', 'Cleveland',
  '1060 Lilley Yeager Loop North', '77328', 30.342, -95.12,
  'https://bespokeoutdoorbubbles.com/unique-sky-bubble-dome/',
  '+1 (888) 303-0373',
  $$Sibling site — Bespoke Outdoor Bubbles (North Cleveland TX). See anchor row id 11573.$$,
  $$Unique Sky Bubble Dome — fully transparent roof for stargazing; king bed (sleeps 2 adults + 1 child per operator copy). Private ensuite with stand-up shower; A/C & heat; retractable awning. Ideal for honeymoons/anniversaries.$$,
  $$https://bespokeoutdoorbubbles.com/unique-sky-bubble-dome/. From $224/night on accommodations page (May 2026).$$,
  '2026-05-18', '2026-05-18', 'private_commercial',
  4, 1, '3', '1',
  224, 224, 224, 224, 224,
  '{"2026":{"marketing_from_rate":{"weekday":224,"weekend":224}}}'::jsonb,
  'Yes', 'Yes', 'No', 'Yes',
  'No', 'Yes', 'Yes', 'Yes', 'Yes',
  'Yes', 'Yes',
  'Yes', 'Yes',
  'Yes', 'Yes',
  'Transparent sky dome; king bed; stand-up shower; shared pool/hot tub & outdoor kitchen.'
),
(
  'a6a4956b-e4eb-4e5e-8d47-f091395afc68',
  'published', 'Yes', 'Yes',
  'Bespoke Outdoor Bubbles', 'Exquisite Luxurious Bubble',
  'bespoke-outdoor-bubbles-cleveland-tx', 'Glamping', 'Bubble Tent',
  'Sage', 'web_research_bespokeoutdoorbubbles_2026_05', 'United States', 'TX', 'Cleveland',
  '1060 Lilley Yeager Loop North', '77328', 30.342, -95.12,
  'https://bespokeoutdoorbubbles.com/exquisite-luxurious-bubble/',
  '+1 (888) 303-0373',
  $$Sibling site — Bespoke Outdoor Bubbles (North Cleveland TX). See anchor row id 11573.$$,
  $$Exquisite Luxurious Bubble — largest dome; 2 bedrooms; private ensuite with clawfoot tub; sleeps up to 5–6 guests per operator listing. Spacious layout for families/groups; A/C & heat; transparent top for stargazing.$$,
  $$https://bespokeoutdoorbubbles.com/exquisite-luxurious-bubble/. From $224/night on accommodations page (May 2026); capacity higher than couple domes.$$,
  '2026-05-18', '2026-05-18', 'private_commercial',
  4, 1, '6', '1',
  224, 224, 224, 224, 224,
  '{"2026":{"marketing_from_rate":{"weekday":224,"weekend":224,"note":"Listed from $224/night; verify party size pricing on calendar"}}}'::jsonb,
  'Yes', 'Yes', 'No', 'Yes',
  'No', 'Yes', 'Yes', 'Yes', 'Yes',
  'Yes', 'Yes',
  'Yes', 'Yes',
  'Yes', 'Yes',
  'Largest dome; 2 bedrooms; clawfoot tub; family/group layout; shared resort-style pool & hot tub.'
),
(
  'a6a4956b-e4eb-4e5e-8d47-f091395afc68',
  'published', 'Yes', 'Yes',
  'Bespoke Outdoor Bubbles', 'Ultimate Bubble Bundle',
  'bespoke-outdoor-bubbles-cleveland-tx', 'Glamping', 'Bubble Tent',
  'Sage', 'web_research_bespokeoutdoorbubbles_2026_05', 'United States', 'TX', 'Cleveland',
  '1060 Lilley Yeager Loop North', '77328', 30.342, -95.12,
  'https://bespokeoutdoorbubbles.com/ultimate-bubble-bundle/',
  '+1 (888) 303-0373',
  $$Sibling site — Bespoke Outdoor Bubbles (North Cleveland TX). See anchor row id 11573.$$,
  $$Ultimate Bubble Bundle — books all three domes together with exclusive property access (6 guests, 3 bedrooms, 3 baths per operator). Includes Blissful, Unique Sky, and Exquisite units plus private use of pool, hot tub, outdoor kitchen, pavilion, and grounds.$$,
  $$https://bespokeoutdoorbubbles.com/ultimate-bubble-bundle/. From $630/night on accommodations page (May 2026).$$,
  '2026-05-18', '2026-05-18', 'private_commercial',
  4, 1, '6', '1',
  630, 630, 630, 630, 630,
  '{"2026":{"marketing_from_rate":{"weekday":630,"weekend":630,"note":"Whole-property bundle; all three domes"}}}'::jsonb,
  'Yes', 'Yes', 'No', 'Yes',
  'No', 'Yes', 'Yes', 'Yes', 'Yes',
  'Yes', 'Yes',
  'Yes', 'Yes',
  'Yes', 'Yes',
  'Exclusive 3-dome buyout; 3 bedrooms; private pool/hot tub; events/retreats.'
);
