-- Mapito Safari Camp, Serengeti: site inventory from marriott.com + mapitosafaricamp.com (May 2026)
-- Sources: rateListMenu.mi JROSK (May 21–22 2026), rooms/overview pages
-- Enriches anchor row id 12226; inserts 3 sibling rows (~15 tents + 1 villa = 16 units).

UPDATE public.all_glamping_properties SET
  property_id = '1c3cf7b1-f2f4-4154-93a3-b0b641b21d14'::uuid,
  brand_id = (SELECT id FROM public.glamping_brands WHERE slug = 'marriott'),
  site_name = 'Deluxe Tent',
  slug = 'mapito-safari-camp-serengeti-tz',
  property_type = 'Glamping Resort',
  unit_type = 'Safari Tent',
  source = 'Sage',
  discovery_source = 'web_research_mapito_marriott_2026_05',
  country = 'Tanzania',
  state = NULL,
  city = 'Serengeti',
  address = 'Robanda, Ikoma Region, Serengeti, Tanzania',
  lat = -2.179,
  lon = 34.681,
  url = 'https://www.marriott.com/reservation/rateListMenu.mi?propertyCode=JROSK&currencyCode=USD',
  phone_number = '+255-690-051-281',
  research_status = 'published',
  is_glamping_property = 'Yes',
  is_open = 'Yes',
  property_total_sites = 16,
  quantity_of_units = 1,
  unit_capacity = '3',
  unit_bed = '1 King',
  minimum_nights = '1',
  operating_season_months = 'Year-round (migration seasons peak demand)',
  unit_private_bathroom = 'Yes',
  unit_shower = 'Yes',
  unit_wifi = 'Yes',
  unit_hot_tub = 'No',
  property_family_friendly = 'Yes',
  setting_field = 'Yes',
  activities_wildlife_watching = 'Yes',
  activities_hiking = 'Yes',
  land_operator_category = 'private_commercial',
  glamping_service_tier = 'luxury',
  date_updated = '2026-05-21',
  description = $$Mapito Safari Camp, Serengeti — Marriott Autograph Collection (opened 2025), first Autograph safari camp in the Serengeti. ~15 luxury tented suites plus one two-bedroom villa in Robanda on the western Serengeti migration corridor. Retractable stargazing roofs, telescopes on verandas, outdoor showers, camp pool, The Boma restaurant, and all-inclusive safari package (meals, game drives, transfers). Big Five and Great Migration viewing.$$,
  unit_description = $$Deluxe Tent: entry-level luxury tent (54 sqm); one king bed; savannah views; retractable stargazing roof; indoor/outdoor shower; veranda with telescope; minibar and French press. Occupancy 2 adults + 1 child. Marriott category: Guest room, 1 King, Savannah view (All-Inclusive Safari Experience).$$,
  notes = COALESCE(notes, '') || E'\n\nSite enrichment (May 2026): marriott.com JROSK rateListMenu + mapitosafaricamp.com. Sample May 21–22 2026 USD from 1,651/night (Deluxe/Guest room, 1 guest). Portfolio cited ~$800 from-rate; live Marriott higher all-inclusive. 15 tents + 1 villa per overview.',
  amenities_raw = '54 sqm; king bed; retractable stargazing roof; indoor/outdoor shower; savannah view; veranda; telescope; minibar; tea/coffee; all-inclusive meals and safaris.',
  rate_avg_retail_daily_rate = 1651,
  rate_summer_weekday = 1651,
  rate_summer_weekend = 1651,
  rate_unit_rates_by_year = '{"2026":{"sample_dates":"2026-05-21_to_2026-05-22","currency":"USD","guests":1,"property_code":"JROSK","marriott_room":"Deluxe Tent / Guest room 1 King","from_rate_usd":1651,"all_inclusive":true,"portfolio_from_rate_usd":800}}'::jsonb
WHERE id = 12226;

INSERT INTO public.all_glamping_properties (
  property_id, brand_id, research_status, is_glamping_property, is_open,
  property_name, site_name, slug, property_type, unit_type,
  source, discovery_source, country, state, city,
  address, lat, lon, url, phone_number,
  description, unit_description, notes,
  date_added, date_updated, land_operator_category,
  property_total_sites, quantity_of_units, unit_capacity, unit_bed, minimum_nights,
  operating_season_months,
  rate_avg_retail_daily_rate, rate_summer_weekday, rate_summer_weekend,
  rate_unit_rates_by_year,
  unit_private_bathroom, unit_shower, unit_wifi,
  property_family_friendly, setting_field,
  activities_wildlife_watching, activities_hiking,
  glamping_service_tier, amenities_raw
) VALUES
(
  '1c3cf7b1-f2f4-4154-93a3-b0b641b21d14'::uuid,
  (SELECT id FROM public.glamping_brands WHERE slug = 'marriott'),
  'published', 'Yes', 'Yes',
  'Mapito Safari Camp, Serengeti', 'VIP Tent',
  'mapito-safari-camp-serengeti-tz', 'Glamping Resort', 'Safari Tent',
  'Sage', 'web_research_mapito_marriott_2026_05', 'Tanzania', NULL, 'Serengeti',
  'Robanda, Ikoma Region, Serengeti, Tanzania', -2.179, 34.681,
  'https://mapitosafaricamp.com/vip-tent/',
  '+255-690-051-281',
  'Sibling site — Mapito Safari Camp, Serengeti. See anchor row id 12226 (Deluxe Tent).',
  'VIP Tent: upgraded 108 sqm tent with king bed, lounge/living area, work desk; retractable stargazing roof; indoor/outdoor shower; veranda and telescope. Occupancy 2 adults, 1 child, 1 infant. Marriott: 1 Bedroom Tented Suite, 1 King.',
  'Marriott May 21–22 2026: from 1,896 USD/night (1 Bedroom Tented Suite, 1 guest, all-inclusive).',
  '2026-05-21', '2026-05-21', 'private_commercial', 16, 1, '4', '1 King', '1', 'Year-round (migration seasons peak demand)',
  1896, 1896, 1896,
  '{"2026":{"property_code":"JROSK","marriott_room":"1 Bedroom Tented Suite 1 King","from_rate_usd":1896,"all_inclusive":true,"size_sqm":108}}'::jsonb,
  'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes',
  'luxury', '108 sqm; king; lounge; work desk; stargazing roof; outdoor shower; telescope; all-inclusive.'
),
(
  '1c3cf7b1-f2f4-4154-93a3-b0b641b21d14'::uuid,
  (SELECT id FROM public.glamping_brands WHERE slug = 'marriott'),
  'published', 'Yes', 'Yes',
  'Mapito Safari Camp, Serengeti', 'Family Tent',
  'mapito-safari-camp-serengeti-tz', 'Glamping Resort', 'Safari Tent',
  'Sage', 'web_research_mapito_marriott_2026_05', 'Tanzania', NULL, 'Serengeti',
  'Robanda, Ikoma Region, Serengeti, Tanzania', -2.179, 34.681,
  'https://mapitosafaricamp.com/family-tent/',
  '+255-690-051-281',
  'Sibling site — Mapito Safari Camp, Serengeti. See anchor row id 12226.',
  'Family Tent: 108 sqm with two ensuite bedrooms (king + two twins), shared veranda; retractable stargazing roof; outdoor shower. Occupancy 4 adults or 2 adults + 2 children. Marriott: 2 Bedroom Tented Suite.',
  'Re-quote 2BR Tented Suite in JROSK rateListMenu for party size/dates (not on May 21–22 sample).',
  '2026-05-21', '2026-05-21', 'private_commercial', 16, 1, '4', '1 King, 2 Twins', '1', 'Year-round (migration seasons peak demand)',
  NULL, NULL, NULL,
  '{"2026":{"property_code":"JROSK","marriott_room":"2 Bedroom Tented Suite","size_sqm":108,"note":"Rate not returned May 21–22 2026 sample"}}'::jsonb,
  'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes',
  'luxury', 'Two ensuite bedrooms; king + twins; shared veranda; stargazing roof; telescope; all-inclusive.'
),
(
  '1c3cf7b1-f2f4-4154-93a3-b0b641b21d14'::uuid,
  (SELECT id FROM public.glamping_brands WHERE slug = 'marriott'),
  'published', 'Yes', 'Yes',
  'Mapito Safari Camp, Serengeti', 'Two-Bedroom Villa',
  'mapito-safari-camp-serengeti-tz', 'Glamping Resort', 'Villa',
  'Sage', 'web_research_mapito_marriott_2026_05', 'Tanzania', NULL, 'Serengeti',
  'Robanda, Ikoma Region, Serengeti, Tanzania', -2.179, 34.681,
  'https://mapitosafaricamp.com/two-bed-villa/',
  '+255-690-051-281',
  'Sibling site — Mapito Safari Camp, Serengeti. See anchor row id 12226.',
  'Two-Bedroom Villa: 240 sqm with two full ensuite bedrooms, powder room, private outdoor shower, private pool, private boma and kitchen, recreational space. Beds: king, two twins, double sofa bed. Up to 6 adults. Marriott: 2 Bedroom Villa (max occupancy 6 per FAQ).',
  'Re-quote 2 Bedroom Villa in JROSK rateListMenu; not on May 21–22 sample.',
  '2026-05-21', '2026-05-21', 'private_commercial', 16, 1, '6', '1 King, 2 Twins, Sofa bed', '1', 'Year-round (migration seasons peak demand)',
  NULL, NULL, NULL,
  '{"2026":{"property_code":"JROSK","marriott_room":"2 Bedroom Villa","max_occupancy":6,"size_sqm":240,"private_pool":true}}'::jsonb,
  'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes',
  'luxury', '240 sqm; private pool; private boma; kitchen; 2 ensuites; powder room; telescope; savannah view.'
);

UPDATE public.all_glamping_properties SET
  brand_id = (SELECT id FROM public.glamping_brands WHERE slug = 'marriott'),
  property_id = '1c3cf7b1-f2f4-4154-93a3-b0b641b21d14'::uuid,
  description = 'Sibling site — Mapito Safari Camp, Serengeti (Autograph Collection). See anchor row id 12226 (Deluxe Tent).',
  phone_number = '+255-690-051-281',
  country = 'Tanzania',
  state = NULL,
  city = 'Serengeti',
  address = 'Robanda, Ikoma Region, Serengeti, Tanzania',
  lat = -2.179,
  lon = 34.681,
  property_total_sites = 16,
  minimum_nights = '1',
  is_glamping_property = 'Yes',
  is_open = 'Yes',
  property_type = 'Glamping Resort',
  slug = 'mapito-safari-camp-serengeti-tz',
  land_operator_category = 'private_commercial',
  glamping_service_tier = 'luxury',
  property_family_friendly = 'Yes',
  setting_field = 'Yes',
  activities_wildlife_watching = 'Yes',
  activities_hiking = 'Yes',
  unit_private_bathroom = 'Yes',
  unit_shower = 'Yes',
  unit_wifi = 'Yes',
  operating_season_months = 'Year-round (migration seasons peak demand)',
  discovery_source = 'web_research_mapito_marriott_2026_05',
  research_status = 'published'
WHERE property_name = 'Mapito Safari Camp, Serengeti' AND id <> 12226;
