-- Bukubaki Eco Surf Resort: site inventory from bukubaki.com/alojamentos (May 2026)
-- Sources: PT/EN accommodations pages (Guestcentric BAR rates)
-- Enriches anchor row id 11136; inserts 7 sibling rows (8 accommodation categories)

UPDATE public.all_glamping_properties SET
  property_id = '04267af0-1eb0-4fae-be23-506051ffb2ff'::uuid,
  site_name = 'Canadian Room Comfort',
  slug = 'bukubaki-eco-surf-resort',
  property_type = 'Glamping Resort',
  unit_type = 'Safari Tent',
  source = 'Sage',
  discovery_source = 'web_research_bukubaki_alojamentos_2026_05',
  country = 'Portugal',
  state = NULL,
  city = 'Peniche',
  address = 'Rua do Juncal 6, Mte. Mendo, 2525-331, Portugal',
  lat = 39.3557,
  lon = -9.3395,
  url = 'https://www.bukubaki.com/alojamentos',
  phone_number = '+351-967-138-917',
  research_status = 'published',
  is_glamping_property = 'Yes',
  is_open = 'Yes',
  property_total_sites = 8,
  quantity_of_units = 1,
  unit_capacity = '2',
  unit_bed = '1 Double',
  minimum_nights = '1',
  operating_season_months = 'Year-round',
  unit_private_bathroom = 'No',
  unit_shower = 'Yes',
  unit_kitchenette = 'No',
  unit_wifi = 'Yes',
  property_family_friendly = 'Yes',
  setting_forest = 'Yes',
  setting_coastal = 'Yes',
  activities_hiking = 'Yes',
  activities_surfing = 'Yes',
  land_operator_category = 'private_commercial',
  glamping_service_tier = 'upscale',
  date_updated = '2026-05-21',
  description = $$Bukubaki Eco Surf Resort — eco surf and wellness retreat in a pine forest near Peniche, Portugal. Core inventory is Canadian glamping tents plus suspended treehouses, a ground bungalow, and shared villas. Free Wi-Fi; restaurant/gastrobar; surf and nature experiences. Accessible units: 2 adapted Canadian Rooms and 1 accessible bungalow (PAIPD).$$,
  unit_description = $$Canadian Room Comfort: glamping tent for 2 with double bed, bedside tables, open wardrobe, electric heater, terrace with wooden loungers, and access to shared bathroom facilities. Room-only (Só Alojamento) rates on bukubaki.com.$$,
  notes = COALESCE(notes, '') || E'\n\nSite enrichment (May 2026): bukubaki.com/alojamentos. Canadian tents are primary product. Comfort BAR rate not rendered in static scrape — re-quote on booking engine.',
  amenities_raw = 'Glamping tent; double bed; terrace; shared bathrooms; electric heater; free Wi-Fi; forest setting.',
  rate_avg_retail_daily_rate = NULL,
  rate_summer_weekday = NULL,
  rate_summer_weekend = NULL,
  rate_unit_rates_by_year = '{"2026":{"currency":"EUR","meal_plan":"room_only","from_rate_eur":null,"note":"Comfort tier BAR empty on May 2026 page load; Family/Group from 82 EUR"}}'::jsonb
WHERE id = 11136;

INSERT INTO public.all_glamping_properties (
  property_id, research_status, is_glamping_property, is_open,
  property_name, site_name, slug, property_type, unit_type,
  source, discovery_source, country, state, city,
  address, lat, lon, url, phone_number,
  description, unit_description, notes,
  date_added, date_updated, land_operator_category,
  property_total_sites, quantity_of_units, unit_capacity, unit_bed, minimum_nights,
  operating_season_months,
  rate_avg_retail_daily_rate, rate_summer_weekday, rate_summer_weekend,
  rate_unit_rates_by_year,
  unit_private_bathroom, unit_shower, unit_kitchenette, unit_wifi,
  property_family_friendly, setting_forest, setting_coastal,
  activities_hiking, activities_surfing, glamping_service_tier, amenities_raw
) VALUES
(
  '04267af0-1eb0-4fae-be23-506051ffb2ff'::uuid,
  'published', 'Yes', 'Yes',
  'Bukubaki Eco Surf Resort', 'Canadian Room Family',
  'bukubaki-eco-surf-resort', 'Glamping Resort', 'Safari Tent',
  'Sage', 'web_research_bukubaki_alojamentos_2026_05', 'Portugal', NULL, 'Peniche',
  'Rua do Juncal 6, Mte. Mendo, 2525-331, Portugal', 39.3557, -9.3395,
  'https://www.bukubaki.com/alojamentos',
  '+351-967-138-917',
  'Sibling site — Bukubaki Eco Surf Resort. See anchor row id 11136 (Canadian Room Comfort).',
  'Canadian Room Family: glamping tent for up to 3 — double bed plus extendable single futon; terrace; shared bathroom access.',
  'From €82/night room-only (May 2026 alojamentos page).',
  '2026-05-21', '2026-05-21', 'private_commercial', 8, 1, '3', '1 Double, 1 Futon', '1', 'Year-round',
  82, 82, 82,
  '{"2026":{"currency":"EUR","from_rate_eur":82,"meal_plan":"room_only"}}'::jsonb,
  'No', 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'upscale', 'Tent; double + futon; terrace; shared bath; Wi-Fi.'
),
(
  '04267af0-1eb0-4fae-be23-506051ffb2ff'::uuid,
  'published', 'Yes', 'Yes',
  'Bukubaki Eco Surf Resort', 'Canadian Room Group',
  'bukubaki-eco-surf-resort', 'Glamping Resort', 'Safari Tent',
  'Sage', 'web_research_bukubaki_alojamentos_2026_05', 'Portugal', NULL, 'Peniche',
  'Rua do Juncal 6, Mte. Mendo, 2525-331, Portugal', 39.3557, -9.3395,
  'https://www.bukubaki.com/alojamentos',
  '+351-967-138-917',
  'Sibling site — Bukubaki Eco Surf Resort. See anchor row id 11136.',
  'Canadian Room Group: glamping tent for up to 4 with four single beds (can combine to double); terrace; shared bathrooms.',
  'From €82/night room-only (May 2026).',
  '2026-05-21', '2026-05-21', 'private_commercial', 8, 1, '4', '4 Single', '1', 'Year-round',
  82, 82, 82,
  '{"2026":{"currency":"EUR","from_rate_eur":82,"meal_plan":"room_only"}}'::jsonb,
  'No', 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'upscale', 'Four singles; terrace; shared bath; Wi-Fi.'
),
(
  '04267af0-1eb0-4fae-be23-506051ffb2ff'::uuid,
  'published', 'Yes', 'Yes',
  'Bukubaki Eco Surf Resort', 'Treehouse Tiny',
  'bukubaki-eco-surf-resort', 'Glamping Resort', 'Treehouse',
  'Sage', 'web_research_bukubaki_alojamentos_2026_05', 'Portugal', NULL, 'Peniche',
  'Rua do Juncal 6, Mte. Mendo, 2525-331, Portugal', 39.3557, -9.3395,
  'https://www.bukubaki.com/alojamentos',
  '+351-967-138-917',
  'Sibling site — Bukubaki Eco Surf Resort. See anchor row id 11136.',
  'Treehouse Tiny: suspended treehouse for 4 — open double bedroom + bunk room; private bathroom; kitchenette (stove, fridge); wooden terrace with loungers.',
  'From €147/night room-only (May 2026).',
  '2026-05-21', '2026-05-21', 'private_commercial', 8, 1, '4', '1 Double, 1 Bunk', '1', 'Year-round',
  147, 147, 147,
  '{"2026":{"currency":"EUR","from_rate_eur":147,"meal_plan":"room_only"}}'::jsonb,
  'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'upscale', 'Suspended treehouse; kitchenette; private bath; A/C; terrace.'
),
(
  '04267af0-1eb0-4fae-be23-506051ffb2ff'::uuid,
  'published', 'Yes', 'Yes',
  'Bukubaki Eco Surf Resort', 'Bungalow',
  'bukubaki-eco-surf-resort', 'Glamping Resort', 'Bungalow',
  'Sage', 'web_research_bukubaki_alojamentos_2026_05', 'Portugal', NULL, 'Peniche',
  'Rua do Juncal 6, Mte. Mendo, 2525-331, Portugal', 39.3557, -9.3395,
  'https://www.bukubaki.com/alojamentos',
  '+351-967-138-917',
  'Sibling site — Bukubaki Eco Surf Resort. See anchor row id 11136.',
  'Bungalow: ground-floor forest unit for 4 (accessible bungalow available); open double + bunk; private bath; kitchenette; terrace with pool view. Same materials/concept as treehouses.',
  'From €128/night room-only (May 2026). PAIPD-accessible bungalow on property.',
  '2026-05-21', '2026-05-21', 'private_commercial', 8, 1, '4', '1 Double, 1 Bunk', '1', 'Year-round',
  128, 128, 128,
  '{"2026":{"currency":"EUR","from_rate_eur":128,"meal_plan":"room_only","pool_view":true}}'::jsonb,
  'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'upscale', 'Ground bungalow; kitchenette; pool view terrace; accessible option.'
),
(
  '04267af0-1eb0-4fae-be23-506051ffb2ff'::uuid,
  'published', 'Yes', 'Yes',
  'Bukubaki Eco Surf Resort', 'Treehouse Wide',
  'bukubaki-eco-surf-resort', 'Glamping Resort', 'Treehouse',
  'Sage', 'web_research_bukubaki_alojamentos_2026_05', 'Portugal', NULL, 'Peniche',
  'Rua do Juncal 6, Mte. Mendo, 2525-331, Portugal', 39.3557, -9.3395,
  'https://www.bukubaki.com/alojamentos',
  '+351-967-138-917',
  'Sibling site — Bukubaki Eco Surf Resort. See anchor row id 11136.',
  'Treehouse Wide: large suspended treehouse for up to 6 — open double room, twin room (joinable), double sofa bed; private bath; full kitchenette with microwave; terrace loungers; A/C.',
  'From €195/night room-only (May 2026).',
  '2026-05-21', '2026-05-21', 'private_commercial', 8, 1, '6', '1 Double, 2 Twin, Sofa bed', '1', 'Year-round',
  195, 195, 195,
  '{"2026":{"currency":"EUR","from_rate_eur":195,"meal_plan":"room_only"}}'::jsonb,
  'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'upscale', 'Large treehouse; sofa bed; microwave; private bath; terrace.'
),
(
  '04267af0-1eb0-4fae-be23-506051ffb2ff'::uuid,
  'published', 'Yes', 'Yes',
  'Bukubaki Eco Surf Resort', 'Sharing Villa',
  'bukubaki-eco-surf-resort', 'Glamping Resort', 'Cabin',
  'Sage', 'web_research_bukubaki_alojamentos_2026_05', 'Portugal', NULL, 'Peniche',
  'Rua do Juncal 6, Mte. Mendo, 2525-331, Portugal', 39.3557, -9.3395,
  'https://www.bukubaki.com/alojamentos',
  '+351-967-138-917',
  'Sibling site — Bukubaki Eco Surf Resort. See anchor row id 11136.',
  'Sharing Villa: shared accommodation for up to 12 — two bunk rooms, shared lounge, shared kitchen (oven, stove, fridge), two shared showers, terrace. Book by bed from €34/night.',
  'Minimum 2 nights when booking one person; additional beds require separate booking or contact.',
  '2026-05-21', '2026-05-21', 'private_commercial', 8, 1, '12', 'Bunks', '2', 'Year-round',
  34, 34, 34,
  '{"2026":{"currency":"EUR","from_rate_eur":34,"rate_basis":"per_bed","meal_plan":"room_only","min_nights_one_guest":2}}'::jsonb,
  'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'upscale', 'Shared villa; bunk rooms; shared kitchen and baths; per-bed pricing.'
),
(
  '04267af0-1eb0-4fae-be23-506051ffb2ff'::uuid,
  'published', 'Yes', 'Yes',
  'Bukubaki Eco Surf Resort', 'Sharing Villa - Deluxe',
  'bukubaki-eco-surf-resort', 'Glamping Resort', 'Cabin',
  'Sage', 'web_research_bukubaki_alojamentos_2026_05', 'Portugal', NULL, 'Peniche',
  'Rua do Juncal 6, Mte. Mendo, 2525-331, Portugal', 39.3557, -9.3395,
  'https://www.bukubaki.com/alojamentos',
  '+351-967-138-917',
  'Sibling site — Bukubaki Eco Surf Resort. See anchor row id 11136.',
  'Sharing Villa - Deluxe: private wing attached to Sharing Villa for up to 4 — mezzanine open double, bunk with two singles; private bathroom; kitchenette; A/C; more privacy than shared villa.',
  'From €92/night room-only (May 2026).',
  '2026-05-21', '2026-05-21', 'private_commercial', 8, 1, '4', '1 Double, 1 Bunk', '1', 'Year-round',
  92, 92, 92,
  '{"2026":{"currency":"EUR","from_rate_eur":92,"meal_plan":"room_only"}}'::jsonb,
  'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'upscale', 'Deluxe wing; private bath; kitchenette; A/C; attached to Sharing Villa.'
);

UPDATE public.all_glamping_properties SET
  property_id = '04267af0-1eb0-4fae-be23-506051ffb2ff'::uuid,
  description = 'Sibling site — Bukubaki Eco Surf Resort (Peniche, Portugal). See anchor row id 11136 (Canadian Room Comfort).',
  phone_number = '+351-967-138-917',
  country = 'Portugal',
  state = NULL,
  city = 'Peniche',
  address = 'Rua do Juncal 6, Mte. Mendo, 2525-331, Portugal',
  lat = 39.3557,
  lon = -9.3395,
  property_total_sites = 8,
  is_glamping_property = 'Yes',
  is_open = 'Yes',
  property_type = 'Glamping Resort',
  slug = 'bukubaki-eco-surf-resort',
  land_operator_category = 'private_commercial',
  glamping_service_tier = 'upscale',
  property_family_friendly = 'Yes',
  setting_forest = 'Yes',
  setting_coastal = 'Yes',
  activities_hiking = 'Yes',
  activities_surfing = 'Yes',
  unit_wifi = 'Yes',
  operating_season_months = 'Year-round',
  discovery_source = 'web_research_bukubaki_alojamentos_2026_05',
  research_status = 'published'
WHERE property_name = 'Bukubaki Eco Surf Resort' AND id <> 11136;
