-- Nevada published glamping: site-level enrichment (May 2026).
-- Sources:
--   Tarantula Ranch — ResNexus B3F72B7A-F2FA-4231-B60D-2E88B01E00AC, deathvalley.camp
--   Vegas Glamping — vegasglamping.com unit pages (phone booking; no public ADR)
--   Mustang Monument — mustangmonument.com/resort/luxury-tipis, safari-cottages

-- =============================================================================
-- Mustang Monument (Wells NV): correct all-inclusive ADR + descriptions
-- =============================================================================

UPDATE public.all_glamping_properties SET
  property_name = 'Mustang Monument',
  property_type = 'Glamping Resort',
  property_total_sites = 2,
  quantity_of_units = 10,
  unit_capacity = '2',
  operating_season_months = 'Seasonal (verify dates with operator)',
  unit_private_bathroom = 'Yes',
  unit_shower = 'Yes',
  unit_wifi = 'Yes',
  property_food_on_site = 'Yes',
  property_family_friendly = 'Yes',
  setting_desert = 'Yes',
  activities_wildlife_watching = 'Yes',
  activities_hiking = 'Yes',
  description = $$Mustang Monument — luxury conservation ranch and "American safari" on a vast private reserve near Wells, NV (~900 sq mi). Two accommodation categories: Luxury Tipis (300 sq ft, leather furnishings, custom beds) and Safari Cottages (designer décor, deck views, en-suite bath). All-inclusive stays include meals, soft beverages, and house wine; guided mustang and landscape experiences. Non-smoking property. Book: mustangmonument.com / Booking@MustangMonument.com.$$,
  unit_description = $$Luxury Tipis: ~300 sq ft tipis with hardwood floors, leather/plush seating, and custom-made beds; outdoor safari experience with resort-level comfort.$$,
  notes = COALESCE(notes, '') || E'\n\nRate correction (May 2026): Operator lists Luxury Tipis at $2,400/night all-inclusive (meals, soft drinks, house wine; excludes tax/service). Prior Sage ADR $99 was incorrect.',
  discovery_source = 'web_research_mustangmonument_2026_05',
  date_updated = '2026-05-18',
  rate_avg_retail_daily_rate = 2400,
  rate_summer_weekday = 2400,
  rate_summer_weekend = 2400,
  rate_unit_rates_by_year = '{"2026":{"all_inclusive":{"weekday":2400,"weekend":2400,"note":"mustangmonument.com Luxury Tipis page May 2026"}}}'::jsonb,
  amenities_raw = 'All-inclusive meals, soft beverages, house wine; 300 sq ft tipi; custom beds; hardwood floors; mustang experiences.'
WHERE id = 9907;

UPDATE public.all_glamping_properties SET
  property_name = 'Mustang Monument',
  property_type = 'Glamping Resort',
  property_total_sites = 2,
  quantity_of_units = 10,
  unit_capacity = '4',
  operating_season_months = 'Seasonal (verify dates with operator)',
  unit_private_bathroom = 'Yes',
  unit_shower = 'Yes',
  unit_wifi = 'Yes',
  property_food_on_site = 'Yes',
  property_family_friendly = 'Yes',
  setting_desert = 'Yes',
  activities_wildlife_watching = 'Yes',
  activities_hiking = 'Yes',
  description = $$Mustang Monument — luxury conservation ranch and "American safari" on a vast private reserve near Wells, NV. Safari Cottages offer chic designer décor, romantic furnishings, open floor plans, and en-suite bathrooms with deck views. All-inclusive nightly rate includes meals, soft beverages, and house wine. Book: mustangmonument.com.$$,
  unit_description = $$Safari Cottages: open-plan cottages with en-suite bathroom, designer décor, private deck overlooking the landscape; all-inclusive resort programming.$$,
  notes = COALESCE(notes, '') || E'\n\nSite enrichment (May 2026): Operator lists Safari Cottages at $2,600/night all-inclusive (meals, soft drinks, house wine; excludes tax/service).',
  discovery_source = 'web_research_mustangmonument_2026_05',
  date_updated = '2026-05-18',
  rate_avg_retail_daily_rate = 2600,
  rate_summer_weekday = 2600,
  rate_summer_weekend = 2600,
  rate_unit_rates_by_year = '{"2026":{"all_inclusive":{"weekday":2600,"weekend":2600,"note":"mustangmonument.com Safari Cottages page May 2026"}}}'::jsonb,
  amenities_raw = 'All-inclusive meals, soft beverages, house wine; en-suite bath; designer cottage; deck; non-smoking property.'
WHERE id = 10495;

-- =============================================================================
-- Vegas Glamping (Nelson area NV): 7 named safari/bell tents
-- =============================================================================

UPDATE public.all_glamping_properties SET
  property_name = 'Vegas Glamping',
  site_name = 'Canyon Safari Tent',
  slug = 'vegas-glamping-nv',
  city = 'Nelson',
  state = 'NV',
  zip_code = '89046',
  lat = 35.7074,
  lon = -114.8731,
  address = 'Near Nelson, NV (Eldorado Canyon; host directions at check-in)',
  phone_number = '+1-702-521-6642',
  url = 'https://vegasglamping.com/our-destination/safari-tent/',
  is_open = 'Yes',
  research_status = 'published',
  is_glamping_property = 'Yes',
  property_type = 'Glamping Resort',
  unit_type = 'Safari Tent',
  property_total_sites = 7,
  quantity_of_units = 1,
  unit_capacity = '3',
  minimum_nights = '1',
  operating_season_months = 'Year-round (check-in by appointment 3–9 PM)',
  unit_private_bathroom = 'Yes',
  unit_shower = 'Yes',
  unit_wifi = 'Yes',
  unit_pets = 'Yes',
  unit_campfires = 'Yes',
  property_family_friendly = 'Yes',
  setting_desert = 'Yes',
  activities_hiking = 'Yes',
  activities_wildlife_watching = 'Yes',
  description = $$Vegas Glamping — luxury desert safari tents near Nelson, NV (~1 hr from Las Vegas Strip), minutes from Eldorado ghost town and off-road trails. Seven distinct tent experiences (safari tents and bell tents) with stargazing, campfires, optional Jeep rentals and Colorado River kayak add-ons. Phone/email booking only (no online rate calendar). Check-in 3–9 PM by appointment.$$,
  unit_description = $$Canyon Safari Tent: queen bed + optional premium cot (max 3 guests); secluded outdoor shower; canyon views. Marketing page: vegasglamping.com/our-destination/safari-tent/$$,
  notes = COALESCE(notes, '') || E'\n\nSite enrichment (May 2026): 7 bookable tent types on vegasglamping.com. No public nightly ADR — call/text 702-521-6642. Henderson address on file is operator contact; property is near Nelson/Eldorado Canyon.',
  amenities_raw = 'Safari tents; outdoor shower (unit-specific); Wi‑Fi (solar-dependent); pets allowed with policy; fire pits; stargazing; complimentary desert activities.',
  discovery_source = 'web_research_vegasglamping_2026_05',
  date_updated = '2026-05-18',
  land_operator_category = 'private_commercial'
WHERE id = 11650;

INSERT INTO public.all_glamping_properties (
  property_id, research_status, is_glamping_property, is_open,
  property_name, site_name, slug, property_type, unit_type,
  source, discovery_source, country, state, city,
  address, zip_code, lat, lon, url, phone_number,
  description, unit_description, notes,
  date_added, date_updated, land_operator_category,
  property_total_sites, quantity_of_units, unit_capacity,
  unit_private_bathroom, unit_shower, unit_wifi, unit_pets, unit_campfires,
  setting_desert, activities_hiking, activities_wildlife_watching, amenities_raw
) VALUES
(
  'a1945707-91b3-4bb5-b71a-fef68e433e80'::uuid,
  'published', 'Yes', 'Yes',
  'Vegas Glamping', 'King Suite Safari Tent',
  'vegas-glamping-nv', 'Glamping Resort', 'Safari Tent',
  'Sage', 'web_research_vegasglamping_2026_05', 'United States', 'NV', 'Nelson',
  'Near Nelson, NV (Eldorado Canyon; host directions at check-in)', '89046', 35.7074, -114.8731,
  'https://vegasglamping.com/our-destination/southern-italy/',
  '+1-702-521-6642',
  $$Sibling site — Vegas Glamping (Nelson NV area). See anchor row id 11650.$$,
  $$King Suite Safari Tent: largest safari tent; sleeps 4 (max 6) with queen beds and living room area; ideal for families/groups. Page slug southern-italy on operator site.$$,
  $$No public ADR — phone booking 702-521-6642.$$,
  '2026-05-18', '2026-05-18', 'private_commercial',
  7, 1, '6',
  'Yes', 'Yes', 'Yes', 'Yes', 'Yes',
  'Yes', 'Yes', 'Yes',
  'Group safari tent; living room; queen beds; shared or private bath per operator assignment.'
),
(
  'a1945707-91b3-4bb5-b71a-fef68e433e80'::uuid,
  'published', 'Yes', 'Yes',
  'Vegas Glamping', 'Desert Den',
  'vegas-glamping-nv', 'Glamping Resort', 'Safari Tent',
  'Sage', 'web_research_vegasglamping_2026_05', 'United States', 'NV', 'Nelson',
  'Near Nelson, NV (Eldorado Canyon; host directions at check-in)', '89046', 35.7074, -114.8731,
  'https://vegasglamping.com/our-destination/australia/',
  '+1-702-521-6642',
  $$Sibling site — Vegas Glamping.$$,
  $$Desert Den: most private hillside safari tent; twin cots (max 2 guests); private deck and fire pit; shared bathhouse a short walk.$$,
  $$No public ADR — phone booking.$$,
  '2026-05-18', '2026-05-18', 'private_commercial',
  7, 1, '2',
  'No', 'Yes', 'Yes', 'Yes', 'Yes',
  'Yes', 'Yes', 'Yes',
  'Twin cots; private deck; fire pit; shared bathhouse.'
),
(
  'a1945707-91b3-4bb5-b71a-fef68e433e80'::uuid,
  'published', 'Yes', 'Yes',
  'Vegas Glamping', 'Desert Oasis',
  'vegas-glamping-nv', 'Glamping Resort', 'Safari Tent',
  'Sage', 'web_research_vegasglamping_2026_05', 'United States', 'NV', 'Nelson',
  'Near Nelson, NV (Eldorado Canyon; host directions at check-in)', '89046', 35.7074, -114.8731,
  'https://vegasglamping.com/our-destination/desert-oasis-tent/',
  '+1-702-521-6642',
  $$Sibling site — Vegas Glamping.$$,
  $$Desert Oasis: queen bed + twin cot option (max 3); private outdoor shower and bath behind tent; sunrise/sunset views.$$,
  $$No public ADR — phone booking.$$,
  '2026-05-18', '2026-05-18', 'private_commercial',
  7, 1, '3',
  'Yes', 'Yes', 'Yes', 'Yes', 'Yes',
  'Yes', 'Yes', 'Yes',
  'Private outdoor shower; queen + optional twin.'
),
(
  'a1945707-91b3-4bb5-b71a-fef68e433e80'::uuid,
  'published', 'Yes', 'Yes',
  'Vegas Glamping', 'Star Gazer',
  'vegas-glamping-nv', 'Glamping Resort', 'Bell Tent',
  'Sage', 'web_research_vegasglamping_2026_05', 'United States', 'NV', 'Nelson',
  'Near Nelson, NV (Eldorado Canyon; host directions at check-in)', '89046', 35.7074, -114.8731,
  'https://vegasglamping.com/our-destination/queen-suite',
  '+1-702-521-6642',
  $$Sibling site — Vegas Glamping.$$,
  $$Star Gazer Bell Tent: max 3 guests; stargazing-focused bell tent; shared outdoor bath ~5-minute walk.$$,
  $$No public ADR — phone booking.$$,
  '2026-05-18', '2026-05-18', 'private_commercial',
  7, 1, '3',
  'No', 'Yes', 'Yes', 'Yes', 'Yes',
  'Yes', 'Yes', 'Yes',
  'Bell tent; shared bath; stargazing.'
),
(
  'a1945707-91b3-4bb5-b71a-fef68e433e80'::uuid,
  'published', 'Yes', 'Yes',
  'Vegas Glamping', 'Queen Safari Tent',
  'vegas-glamping-nv', 'Glamping Resort', 'Safari Tent',
  'Sage', 'web_research_vegasglamping_2026_05', 'United States', 'NV', 'Nelson',
  'Near Nelson, NV (Eldorado Canyon; host directions at check-in)', '89046', 35.7074, -114.8731,
  'https://vegasglamping.com/our-destination/queen-safari-tent-las-vegas',
  '+1-702-521-6642',
  $$Sibling site — Vegas Glamping.$$,
  $$Queen Safari Tent: 2 guests standard (max 3); shared outdoor bath/shower with one other tent.$$,
  $$No public ADR — phone booking.$$,
  '2026-05-18', '2026-05-18', 'private_commercial',
  7, 1, '3',
  'No', 'Yes', 'Yes', 'Yes', 'Yes',
  'Yes', 'Yes', 'Yes',
  'Safari tent; shared bath with one other unit.'
),
(
  'a1945707-91b3-4bb5-b71a-fef68e433e80'::uuid,
  'published', 'Yes', 'Yes',
  'Vegas Glamping', 'Sunrise Safari Tent',
  'vegas-glamping-nv', 'Glamping Resort', 'Safari Tent',
  'Sage', 'web_research_vegasglamping_2026_05', 'United States', 'NV', 'Nelson',
  'Near Nelson, NV (Eldorado Canyon; host directions at check-in)', '89046', 35.7074, -114.8731,
  'https://vegasglamping.com/our-destination/sunrise-safari-tent/',
  '+1-702-521-6642',
  $$Sibling site — Vegas Glamping.$$,
  $$Sunrise Safari Tent: max 4 guests; shared outdoor shower with one other tent; spacious layout for small groups.$$,
  $$No public ADR — phone booking.$$,
  '2026-05-18', '2026-05-18', 'private_commercial',
  7, 1, '4',
  'No', 'Yes', 'Yes', 'Yes', 'Yes',
  'Yes', 'Yes', 'Yes',
  'Safari tent; max 4; shared shower.'
);

-- =============================================================================
-- Tarantula Ranch (Amargosa Valley NV): 16 ResNexus inventory rows
-- =============================================================================

UPDATE public.all_glamping_properties SET
  property_name = 'Tarantula Ranch',
  site_name = 'The Bottling Room',
  slug = 'tarantula-ranch-amargosa-valley-nv',
  url = 'https://resnexus.com/resnexus/reservations/book/B3F72B7A-F2FA-4231-B60D-2E88B01E00AC/',
  phone_number = '+1-775-295-9463',
  research_status = 'published',
  property_type = 'Glamping Resort',
  unit_type = 'Cabin',
  property_total_sites = 16,
  quantity_of_units = 1,
  unit_capacity = '2',
  unit_wifi = 'Yes',
  unit_pets = 'Yes',
  unit_shower = 'Yes',
  unit_campfires = 'Yes',
  property_family_friendly = 'Yes',
  setting_desert = 'Yes',
  activities_wildlife_watching = 'Yes',
  description = $$Tarantula Ranch — vineyard ranch glamping ~20 minutes from Death Valley National Park (east entrance), Amargosa Valley NV (5065 Cook Road). ResNexus inventory: The Bottling Room, glamping sites (vintage Burro/teardrop-style units; Site 1 includes EV charger), RV site, and wine-named tent/van campsites. Shared outdoor kitchen, showers, Wi‑Fi, dark skies; pet-friendly. Book: deathvalley.camp / ResNexus.$$,
  unit_description = $$The Bottling Room: standalone ranch room/suite on the vineyard property (verify bed count in ResNexus).$$,
  notes = COALESCE(notes, '') || E'\n\nResNexus enrichment (May 2026): 16 bookable unit types. Sample Standard Rate 2026-05-18→19 (1 night): Glamping Site 2 $96.30; Glamping Site 11 $80.25; RV Site $53.50; Zinfandel tent/van $26.75. Occupied units — re-quote in engine.',
  discovery_source = 'web_research_tarantula_resnexus_2026_05',
  date_updated = '2026-05-18',
  land_operator_category = 'private_commercial',
  amenities_raw = 'Vineyard ranch; outdoor kitchen; showers; Wi‑Fi; EV charger on Site 1; tent/van sites; RV site.'
WHERE id = 12089;

INSERT INTO public.all_glamping_properties (
  property_id, research_status, is_glamping_property, is_open,
  property_name, site_name, slug, property_type, unit_type,
  source, discovery_source, country, state, city,
  address, zip_code, lat, lon, url, phone_number,
  description, unit_description, notes,
  date_added, date_updated, land_operator_category,
  property_total_sites, quantity_of_units, unit_capacity,
  rate_avg_retail_daily_rate, rate_unit_rates_by_year,
  unit_wifi, unit_pets, unit_shower, unit_campfires,
  setting_desert, activities_wildlife_watching, amenities_raw
) VALUES
(
  '6ac68a51-7b3f-49d0-b10d-6365f53986a2'::uuid,
  'published', 'Yes', 'Yes',
  'Tarantula Ranch', 'Glamping Site 1 {EV Charger}',
  'tarantula-ranch-amargosa-valley-nv', 'Glamping Resort', 'Vintage Trailer',
  'Sage', 'web_research_tarantula_resnexus_2026_05', 'United States', 'NV', 'Amargosa Valley',
  '5065 Cook Road, Amargosa Valley, NV 89020', '89020', 36.4361, -116.8702,
  'https://resnexus.com/resnexus/reservations/book/B3F72B7A-F2FA-4231-B60D-2E88B01E00AC/',
  '+1-775-295-9463',
  $$Sibling site — Tarantula Ranch. See anchor id 12089.$$,
  $$Glamping Site 1: vintage glamping unit with EV charger; Burro/teardrop-style site on vineyard ranch.$$,
  $$ResNexus rate not captured on 2026-05-18 sample (occupied).$$,
  '2026-05-18', '2026-05-18', 'private_commercial',
  16, 1, '2', NULL, NULL,
  'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes',
  'EV charger; vintage glamping site.'
),
(
  '6ac68a51-7b3f-49d0-b10d-6365f53986a2'::uuid,
  'published', 'Yes', 'Yes',
  'Tarantula Ranch', 'Glamping Site 2',
  'tarantula-ranch-amargosa-valley-nv', 'Glamping Resort', 'Vintage Trailer',
  'Sage', 'web_research_tarantula_resnexus_2026_05', 'United States', 'NV', 'Amargosa Valley',
  '5065 Cook Road, Amargosa Valley, NV 89020', '89020', 36.4361, -116.8702,
  'https://resnexus.com/resnexus/reservations/book/B3F72B7A-F2FA-4231-B60D-2E88B01E00AC/',
  '+1-775-295-9463',
  $$Sibling site — Tarantula Ranch.$$,
  $$Glamping Site 2: vintage Burro/teardrop-style glamping site.$$,
  $$ResNexus Standard Rate sample: $96.30/night (2026-05-18→19).$$,
  '2026-05-18', '2026-05-18', 'private_commercial',
  16, 1, '2', 96.30,
  '{"2026":{"standard":{"weekday":96.30,"weekend":96.30,"note":"ResNexus sample 2026-05-18, 1 night"}}}'::jsonb,
  'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes',
  'Vintage glamping site.'
),
(
  '6ac68a51-7b3f-49d0-b10d-6365f53986a2'::uuid,
  'published', 'Yes', 'Yes',
  'Tarantula Ranch', 'Glamping Site 3',
  'tarantula-ranch-amargosa-valley-nv', 'Glamping Resort', 'Vintage Trailer',
  'Sage', 'web_research_tarantula_resnexus_2026_05', 'United States', 'NV', 'Amargosa Valley',
  '5065 Cook Road, Amargosa Valley, NV 89020', '89020', 36.4361, -116.8702,
  'https://resnexus.com/resnexus/reservations/book/B3F72B7A-F2FA-4231-B60D-2E88B01E00AC/',
  '+1-775-295-9463',
  $$Sibling site — Tarantula Ranch.$$,
  $$Glamping Site 3: vintage glamping site.$$,
  $$ResNexus Standard Rate tier ~$96.30/night (same class as Site 2; verify calendar).$$,
  '2026-05-18', '2026-05-18', 'private_commercial',
  16, 1, '2', 96.30,
  '{"2026":{"standard":{"weekday":96.30,"weekend":96.30,"note":"ResNexus tier match Site 2, May 2026"}}}'::jsonb,
  'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes',
  'Vintage glamping site.'
),
(
  '6ac68a51-7b3f-49d0-b10d-6365f53986a2'::uuid,
  'published', 'Yes', 'Yes',
  'Tarantula Ranch', 'Glamping Site 4',
  'tarantula-ranch-amargosa-valley-nv', 'Glamping Resort', 'Vintage Trailer',
  'Sage', 'web_research_tarantula_resnexus_2026_05', 'United States', 'NV', 'Amargosa Valley',
  '5065 Cook Road, Amargosa Valley, NV 89020', '89020', 36.4361, -116.8702,
  'https://resnexus.com/resnexus/reservations/book/B3F72B7A-F2FA-4231-B60D-2E88B01E00AC/',
  '+1-775-295-9463',
  $$Sibling site — Tarantula Ranch.$$,
  $$Glamping Site 4.$$,
  $$ResNexus tier ~$96.30/night (verify).$$,
  '2026-05-18', '2026-05-18', 'private_commercial',
  16, 1, '2', 96.30, NULL,
  'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Vintage glamping site.'
),
(
  '6ac68a51-7b3f-49d0-b10d-6365f53986a2'::uuid,
  'published', 'Yes', 'Yes',
  'Tarantula Ranch', 'Glamping Site 5',
  'tarantula-ranch-amargosa-valley-nv', 'Glamping Resort', 'Vintage Trailer',
  'Sage', 'web_research_tarantula_resnexus_2026_05', 'United States', 'NV', 'Amargosa Valley',
  '5065 Cook Road, Amargosa Valley, NV 89020', '89020', 36.4361, -116.8702,
  'https://resnexus.com/resnexus/reservations/book/B3F72B7A-F2FA-4231-B60D-2E88B01E00AC/',
  '+1-775-295-9463',
  $$Sibling site — Tarantula Ranch.$$,
  $$Glamping Site 5.$$,
  $$ResNexus tier ~$96.30/night (verify).$$,
  '2026-05-18', '2026-05-18', 'private_commercial',
  16, 1, '2', 96.30, NULL,
  'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Vintage glamping site.'
),
(
  '6ac68a51-7b3f-49d0-b10d-6365f53986a2'::uuid,
  'published', 'Yes', 'Yes',
  'Tarantula Ranch', 'Glamping Site 6',
  'tarantula-ranch-amargosa-valley-nv', 'Glamping Resort', 'Vintage Trailer',
  'Sage', 'web_research_tarantula_resnexus_2026_05', 'United States', 'NV', 'Amargosa Valley',
  '5065 Cook Road, Amargosa Valley, NV 89020', '89020', 36.4361, -116.8702,
  'https://resnexus.com/resnexus/reservations/book/B3F72B7A-F2FA-4231-B60D-2E88B01E00AC/',
  '+1-775-295-9463',
  $$Sibling site — Tarantula Ranch.$$,
  $$Glamping Site 6.$$,
  $$ResNexus tier ~$96.30/night (verify).$$,
  '2026-05-18', '2026-05-18', 'private_commercial',
  16, 1, '2', 96.30, NULL,
  'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Vintage glamping site.'
),
(
  '6ac68a51-7b3f-49d0-b10d-6365f53986a2'::uuid,
  'published', 'Yes', 'Yes',
  'Tarantula Ranch', 'Glamping Site 9',
  'tarantula-ranch-amargosa-valley-nv', 'Glamping Resort', 'Vintage Trailer',
  'Sage', 'web_research_tarantula_resnexus_2026_05', 'United States', 'NV', 'Amargosa Valley',
  '5065 Cook Road, Amargosa Valley, NV 89020', '89020', 36.4361, -116.8702,
  'https://resnexus.com/resnexus/reservations/book/B3F72B7A-F2FA-4231-B60D-2E88B01E00AC/',
  '+1-775-295-9463',
  $$Sibling site — Tarantula Ranch.$$,
  $$Glamping Site 9 (no Sites 7–8 in ResNexus catalog).$$,
  $$ResNexus tier ~$96.30/night (verify).$$,
  '2026-05-18', '2026-05-18', 'private_commercial',
  16, 1, '2', 96.30, NULL,
  'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Vintage glamping site.'
),
(
  '6ac68a51-7b3f-49d0-b10d-6365f53986a2'::uuid,
  'published', 'Yes', 'Yes',
  'Tarantula Ranch', 'Glamping Site 10',
  'tarantula-ranch-amargosa-valley-nv', 'Glamping Resort', 'Vintage Trailer',
  'Sage', 'web_research_tarantula_resnexus_2026_05', 'United States', 'NV', 'Amargosa Valley',
  '5065 Cook Road, Amargosa Valley, NV 89020', '89020', 36.4361, -116.8702,
  'https://resnexus.com/resnexus/reservations/book/B3F72B7A-F2FA-4231-B60D-2E88B01E00AC/',
  '+1-775-295-9463',
  $$Sibling site — Tarantula Ranch.$$,
  $$Glamping Site 10.$$,
  $$ResNexus tier ~$96.30/night (verify).$$,
  '2026-05-18', '2026-05-18', 'private_commercial',
  16, 1, '2', 96.30, NULL,
  'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Vintage glamping site.'
),
(
  '6ac68a51-7b3f-49d0-b10d-6365f53986a2'::uuid,
  'published', 'Yes', 'Yes',
  'Tarantula Ranch', 'Glamping Site 11',
  'tarantula-ranch-amargosa-valley-nv', 'Glamping Resort', 'Vintage Trailer',
  'Sage', 'web_research_tarantula_resnexus_2026_05', 'United States', 'NV', 'Amargosa Valley',
  '5065 Cook Road, Amargosa Valley, NV 89020', '89020', 36.4361, -116.8702,
  'https://resnexus.com/resnexus/reservations/book/B3F72B7A-F2FA-4231-B60D-2E88B01E00AC/',
  '+1-775-295-9463',
  $$Sibling site — Tarantula Ranch.$$,
  $$Glamping Site 11: lower-priced glamping tier on ranch.$$,
  $$ResNexus Standard Rate sample: $80.25/night (2026-05-18→19).$$,
  '2026-05-18', '2026-05-18', 'private_commercial',
  16, 1, '2', 80.25,
  '{"2026":{"standard":{"weekday":80.25,"weekend":80.25,"note":"ResNexus sample 2026-05-18"}}}'::jsonb,
  'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Vintage glamping site.'
),
(
  '6ac68a51-7b3f-49d0-b10d-6365f53986a2'::uuid,
  'published', 'Yes', 'Yes',
  'Tarantula Ranch', 'RV Site',
  'tarantula-ranch-amargosa-valley-nv', 'Glamping Resort', 'RV Site',
  'Sage', 'web_research_tarantula_resnexus_2026_05', 'United States', 'NV', 'Amargosa Valley',
  '5065 Cook Road, Amargosa Valley, NV 89020', '89020', 36.4361, -116.8702,
  'https://resnexus.com/resnexus/reservations/book/B3F72B7A-F2FA-4231-B60D-2E88B01E00AC/',
  '+1-775-295-9463',
  $$Sibling site — Tarantula Ranch.$$,
  $$RV Site: full-hookup or standard RV pad on ranch (verify length/hookups in ResNexus).$$,
  $$ResNexus Standard Rate sample: $53.50/night (2026-05-18→19).$$,
  '2026-05-18', '2026-05-18', 'private_commercial',
  16, 1, '4', 53.50,
  '{"2026":{"standard":{"weekday":53.50,"weekend":53.50,"note":"ResNexus sample 2026-05-18"}}}'::jsonb,
  'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'RV site on vineyard ranch.'
),
(
  '6ac68a51-7b3f-49d0-b10d-6365f53986a2'::uuid,
  'published', 'Yes', 'Yes',
  'Tarantula Ranch', 'Barbera- Tent/Van Camping',
  'tarantula-ranch-amargosa-valley-nv', 'Glamping Resort', 'Tent Site',
  'Sage', 'web_research_tarantula_resnexus_2026_05', 'United States', 'NV', 'Amargosa Valley',
  '5065 Cook Road, Amargosa Valley, NV 89020', '89020', 36.4361, -116.8702,
  'https://resnexus.com/resnexus/reservations/book/B3F72B7A-F2FA-4231-B60D-2E88B01E00AC/',
  '+1-775-295-9463',
  $$Sibling site — Tarantula Ranch.$$,
  $$Barbera: tent or van camping pad (wine-varietal named site).$$,
  $$ResNexus tent/van tier ~$26.75/night (match Zinfandel sample; verify).$$,
  '2026-05-18', '2026-05-18', 'private_commercial',
  16, 1, '4', 26.75, NULL,
  'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Tent/van site; bring own rig.'
),
(
  '6ac68a51-7b3f-49d0-b10d-6365f53986a2'::uuid,
  'published', 'Yes', 'Yes',
  'Tarantula Ranch', 'Chardonnay- Tent/Van Camping',
  'tarantula-ranch-amargosa-valley-nv', 'Glamping Resort', 'Tent Site',
  'Sage', 'web_research_tarantula_resnexus_2026_05', 'United States', 'NV', 'Amargosa Valley',
  '5065 Cook Road, Amargosa Valley, NV 89020', '89020', 36.4361, -116.8702,
  'https://resnexus.com/resnexus/reservations/book/B3F72B7A-F2FA-4231-B60D-2E88B01E00AC/',
  '+1-775-295-9463',
  $$Sibling site — Tarantula Ranch.$$,
  $$Chardonnay: tent/van camping pad.$$,
  $$ResNexus tent/van tier ~$26.75/night (verify).$$,
  '2026-05-18', '2026-05-18', 'private_commercial',
  16, 1, '4', 26.75, NULL,
  'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Tent/van site.'
),
(
  '6ac68a51-7b3f-49d0-b10d-6365f53986a2'::uuid,
  'published', 'Yes', 'Yes',
  'Tarantula Ranch', 'Cabernet- Tent/Van Camping',
  'tarantula-ranch-amargosa-valley-nv', 'Glamping Resort', 'Tent Site',
  'Sage', 'web_research_tarantula_resnexus_2026_05', 'United States', 'NV', 'Amargosa Valley',
  '5065 Cook Road, Amargosa Valley, NV 89020', '89020', 36.4361, -116.8702,
  'https://resnexus.com/resnexus/reservations/book/B3F72B7A-F2FA-4231-B60D-2E88B01E00AC/',
  '+1-775-295-9463',
  $$Sibling site — Tarantula Ranch.$$,
  $$Cabernet: tent/van camping pad.$$,
  $$ResNexus tent/van tier ~$26.75/night (verify).$$,
  '2026-05-18', '2026-05-18', 'private_commercial',
  16, 1, '4', 26.75, NULL,
  'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Tent/van site.'
),
(
  '6ac68a51-7b3f-49d0-b10d-6365f53986a2'::uuid,
  'published', 'Yes', 'Yes',
  'Tarantula Ranch', 'Merlot- Tent/Van Camping',
  'tarantula-ranch-amargosa-valley-nv', 'Glamping Resort', 'Tent Site',
  'Sage', 'web_research_tarantula_resnexus_2026_05', 'United States', 'NV', 'Amargosa Valley',
  '5065 Cook Road, Amargosa Valley, NV 89020', '89020', 36.4361, -116.8702,
  'https://resnexus.com/resnexus/reservations/book/B3F72B7A-F2FA-4231-B60D-2E88B01E00AC/',
  '+1-775-295-9463',
  $$Sibling site — Tarantula Ranch.$$,
  $$Merlot: tent/van camping pad.$$,
  $$ResNexus tent/van tier ~$26.75/night (verify).$$,
  '2026-05-18', '2026-05-18', 'private_commercial',
  16, 1, '4', 26.75, NULL,
  'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Tent/van site.'
),
(
  '6ac68a51-7b3f-49d0-b10d-6365f53986a2'::uuid,
  'published', 'Yes', 'Yes',
  'Tarantula Ranch', 'Zinfandel- Tent/Van Camping',
  'tarantula-ranch-amargosa-valley-nv', 'Glamping Resort', 'Tent Site',
  'Sage', 'web_research_tarantula_resnexus_2026_05', 'United States', 'NV', 'Amargosa Valley',
  '5065 Cook Road, Amargosa Valley, NV 89020', '89020', 36.4361, -116.8702,
  'https://resnexus.com/resnexus/reservations/book/B3F72B7A-F2FA-4231-B60D-2E88B01E00AC/',
  '+1-775-295-9463',
  $$Sibling site — Tarantula Ranch.$$,
  $$Zinfandel: tent or van camping pad.$$,
  $$ResNexus Standard Rate sample: $26.75/night (2026-05-18→19).$$,
  '2026-05-18', '2026-05-18', 'private_commercial',
  16, 1, '4', 26.75,
  '{"2026":{"standard":{"weekday":26.75,"weekend":26.75,"note":"ResNexus sample 2026-05-18"}}}'::jsonb,
  'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Tent/van site.'
);

-- Backfill ResNexus sample ADRs (ensure numeric column populated after multi-row INSERT)
UPDATE public.all_glamping_properties SET
  rate_avg_retail_daily_rate = 96.30,
  rate_unit_rates_by_year = COALESCE(rate_unit_rates_by_year, '{"2026":{"standard":{"weekday":96.30,"weekend":96.30,"note":"ResNexus tier May 2026"}}}'::jsonb)
WHERE property_name = 'Tarantula Ranch'
  AND site_name IN ('Glamping Site 2','Glamping Site 3','Glamping Site 4','Glamping Site 5','Glamping Site 6','Glamping Site 9','Glamping Site 10');

UPDATE public.all_glamping_properties SET
  rate_avg_retail_daily_rate = 80.25,
  rate_unit_rates_by_year = COALESCE(rate_unit_rates_by_year, '{"2026":{"standard":{"weekday":80.25,"weekend":80.25,"note":"ResNexus sample 2026-05-18"}}}'::jsonb)
WHERE property_name = 'Tarantula Ranch' AND site_name = 'Glamping Site 11';

UPDATE public.all_glamping_properties SET
  rate_avg_retail_daily_rate = 53.50,
  rate_unit_rates_by_year = COALESCE(rate_unit_rates_by_year, '{"2026":{"standard":{"weekday":53.50,"weekend":53.50,"note":"ResNexus sample 2026-05-18"}}}'::jsonb)
WHERE property_name = 'Tarantula Ranch' AND site_name = 'RV Site';

UPDATE public.all_glamping_properties SET
  rate_avg_retail_daily_rate = 26.75,
  rate_unit_rates_by_year = COALESCE(rate_unit_rates_by_year, '{"2026":{"standard":{"weekday":26.75,"weekend":26.75,"note":"ResNexus sample 2026-05-18"}}}'::jsonb)
WHERE property_name = 'Tarantula Ranch' AND site_name LIKE '%Tent/Van Camping';

REFRESH MATERIALIZED VIEW public.unified_comps;
