-- Strawberry Park Hot Springs (Steamboat Springs CO): 7 lodging site rows from strawberryhotsprings.com/lodging + Checkfront (May 2026).
-- Checkfront host: strawberry-hot-springs.manage.na1.bookingplatform.app (category IDs on lodging page).

UPDATE public.all_glamping_properties SET
  property_name = 'Strawberry Park Hot Springs',
  site_name = 'Train Caboose',
  url = 'https://strawberryhotsprings.com/lodging/',
  unit_type = 'Caboose',
  property_total_sites = 7,
  quantity_of_units = 1,
  unit_capacity = '2',
  minimum_nights = '2',
  operating_season_months = 'Year-round lodging; pool access daily sunrise–midnight for overnight guests',
  unit_private_bathroom = 'Yes',
  unit_shower = 'Yes',
  unit_full_kitchen = 'No',
  unit_kitchenette = 'No',
  unit_wifi = 'No',
  unit_pets = 'No',
  unit_campfires = 'No',
  unit_picnic_table = 'No',
  unit_patio = 'No',
  unit_gas_fireplace = 'Yes',
  unit_electricity = 'Yes',
  property_hot_tub = 'Yes',
  property_family_friendly = 'Yes',
  setting_hot_spring = 'Yes',
  setting_mountainous = 'Yes',
  setting_forest = 'Yes',
  setting_swimming_hole = 'Yes',
  activities_swimming = 'Yes',
  activities_hiking = 'Yes',
  activities_wildlife_watching = 'Yes',
  description = $$Strawberry Park Hot Springs — natural geothermal mineral pools along Hot Springs Creek, ~7 miles from downtown Steamboat Springs CO (44200 County Road 36). Seven rustic overnight lodging types (train caboose, cabins, covered wagons, tent & vehicle camping) each include pool access: check-in 5pm, checkout 11am, daily soaking sunrise–midnight. Off-grid property: no Wi‑Fi; shared central bathhouse (showers, flush toilets) for most units; no pets, RVs, campfires, or parties. Reservations open ~90–120 days ahead via Checkfront. Nov 1–May 1: Routt County traction law (4×4 + snow tires or chains).$$,
  unit_description = $$Renovated train caboose — most comfortable on-site lodging. Gas fireplace; private bathroom with shower; lights; full-size Murphy bed and sofa. Linens provided for two. Max 2 guests; one caboose on property — book early.$$,
  notes = COALESCE(notes, '') || E'\n\nSite enrichment (May 2026): 7 bookable lodging SKUs from strawberryhotsprings.com/lodging + Checkfront Droplet widgets (category IDs 3529, 3718, 3524, 3525, 3526, 3528, 3527). Nightly rates sample from booking engine May 2026 (USD, per night, +taxes/fees if any). Weekend/holiday minimum nights may apply per operator.',
  amenities_raw = 'Lodging includes hot springs pool access. Caboose: private bath/shower, gas fireplace, Murphy bed, sofa, linens for 2. Property: central bathhouse, changing cabin, massage/watsu, picnic areas, propane grills (select units), walk-to sites, clothing-optional pools after dark.',
  discovery_source = 'web_research_strawberryhotsprings_checkfront_2026_05',
  date_updated = '2026-05-18',
  land_operator_category = 'private_commercial',
  rate_avg_retail_daily_rate = 240,
  rate_summer_weekday = 240,
  rate_summer_weekend = 240,
  rate_winter_weekday = 240,
  rate_winter_weekend = 240,
  rate_unit_rates_by_year = '{"2026":{"checkfront_nightly":{"weekday":240,"weekend":240,"note":"Category 3529 sample May 2026; exclusive of taxes/fees"}}}'::jsonb
WHERE id = 11659;

INSERT INTO public.all_glamping_properties (
  property_id,
  research_status, is_glamping_property, is_open,
  property_name, site_name, slug, property_type, unit_type,
  source, discovery_source, country, state, city,
  address, zip_code, lat, lon, url, phone_number,
  description, unit_description, notes,
  date_added, date_updated, land_operator_category,
  property_total_sites, quantity_of_units, unit_capacity, minimum_nights,
  rate_avg_retail_daily_rate, rate_summer_weekday, rate_summer_weekend,
  rate_winter_weekday, rate_winter_weekend,
  rate_unit_rates_by_year,
  unit_private_bathroom, unit_shower, unit_full_kitchen, unit_wifi,
  unit_pets, unit_campfires, unit_picnic_table, unit_gas_fireplace, unit_electricity,
  property_hot_tub, property_family_friendly,
  setting_hot_spring, setting_mountainous, setting_forest, setting_swimming_hole,
  activities_swimming, activities_hiking, activities_wildlife_watching,
  amenities_raw
) VALUES
(
  'a3457bc3-69fc-4530-890f-bbd821a31557',
  'published', 'Yes', 'Yes',
  'Strawberry Park Hot Springs', 'Rustic Retreat Cabin',
  'strawberry-park-hot-springs-steamboat-springs-co', 'Glamping', 'Cabin',
  'Sage', 'web_research_strawberryhotsprings_checkfront_2026_05', 'United States', 'CO', 'Steamboat Springs',
  '44200 County Road 36', '80487', 40.7265, -106.8950,
  'https://strawberryhotsprings.com/lodging/',
  '(970) 879-0342',
  $$Sibling site — Strawberry Park Hot Springs. See anchor row id 11659.$$,
  $$Recently renovated two-story rustic cabin with one full-size mattress, lights, gas fireplace, and gas grill. Outhouse on site; access to central bathhouse with showers and flush toilets. Bring own bedding; max 2 guests.$$,
  $$Checkfront category 3718. $200/night sample May 2026.$$,
  '2026-05-18', '2026-05-18', 'private_commercial',
  7, 1, '2', '2',
  200, 200, 200, 200, 200,
  '{"2026":{"checkfront_nightly":{"weekday":200,"weekend":200,"note":"Category 3718"}}}'::jsonb,
  'No', 'Yes', 'No', 'No',
  'No', 'No', 'No', 'Yes', 'Yes',
  'Yes', 'Yes',
  'Yes', 'Yes', 'Yes', 'Yes',
  'Yes', 'Yes', 'Yes',
  'Two-story cabin; outhouse; shared bathhouse; gas grill; no linens provided.'
),
(
  'a3457bc3-69fc-4530-890f-bbd821a31557',
  'published', 'Yes', 'Yes',
  'Strawberry Park Hot Springs', 'Large Rustic Cabin',
  'strawberry-park-hot-springs-steamboat-springs-co', 'Glamping', 'Cabin',
  'Sage', 'web_research_strawberryhotsprings_checkfront_2026_05', 'United States', 'CO', 'Steamboat Springs',
  '44200 County Road 36', '80487', 40.7265, -106.8950,
  'https://strawberryhotsprings.com/lodging/',
  '(970) 879-0342',
  $$Sibling site — Strawberry Park Hot Springs. See anchor row id 11659.$$,
  $$Two-story rustic cabin with one full-size futon and one single futon, lights, gas fireplace, and gas grill. Includes outhouse; central bathhouse access. Bring own bedding; max 2 guests.$$,
  $$Checkfront category 3524. $160/night sample May 2026.$$,
  '2026-05-18', '2026-05-18', 'private_commercial',
  7, 1, '2', '2',
  160, 160, 160, 160, 160,
  '{"2026":{"checkfront_nightly":{"weekday":160,"weekend":160,"note":"Category 3524"}}}'::jsonb,
  'No', 'Yes', 'No', 'No',
  'No', 'No', 'No', 'Yes', 'Yes',
  'Yes', 'Yes',
  'Yes', 'Yes', 'Yes', 'Yes',
  'Yes', 'Yes', 'Yes',
  'Two-story cabin; full + single futon; outhouse; shared bathhouse; gas grill.'
),
(
  'a3457bc3-69fc-4530-890f-bbd821a31557',
  'published', 'Yes', 'Yes',
  'Strawberry Park Hot Springs', 'Small Rustic Cabin',
  'strawberry-park-hot-springs-steamboat-springs-co', 'Glamping', 'Cabin',
  'Sage', 'web_research_strawberryhotsprings_checkfront_2026_05', 'United States', 'CO', 'Steamboat Springs',
  '44200 County Road 36', '80487', 40.7265, -106.8950,
  'https://strawberryhotsprings.com/lodging/',
  '(970) 879-0342',
  $$Sibling site — Strawberry Park Hot Springs. See anchor row id 11659.$$,
  $$Simple one-room cabin with double futon, light, gas fireplace, and gas grill. Central bathhouse with showers and flush toilets (no in-cabin running water). Bring own bedding; max 2 guests. Operator sells multiple small cabins as one inventory SKU.$$,
  $$Checkfront category 3525. $145/night sample May 2026.$$,
  '2026-05-18', '2026-05-18', 'private_commercial',
  7, 1, '2', '2',
  145, 145, 145, 145, 145,
  '{"2026":{"checkfront_nightly":{"weekday":145,"weekend":145,"note":"Category 3525"}}}'::jsonb,
  'No', 'Yes', 'No', 'No',
  'No', 'No', 'No', 'Yes', 'No',
  'Yes', 'Yes',
  'Yes', 'Yes', 'Yes', 'Yes',
  'Yes', 'Yes', 'Yes',
  'One-room cabin; double futon; shared bathhouse; no electricity in cabin per property FAQ.'
),
(
  'a3457bc3-69fc-4530-890f-bbd821a31557',
  'published', 'Yes', 'Yes',
  'Strawberry Park Hot Springs', 'Covered Wagon',
  'strawberry-park-hot-springs-steamboat-springs-co', 'Glamping', 'Covered Wagon',
  'Sage', 'web_research_strawberryhotsprings_checkfront_2026_05', 'United States', 'CO', 'Steamboat Springs',
  '44200 County Road 36', '80487', 40.7265, -106.8950,
  'https://strawberryhotsprings.com/lodging/',
  '(970) 879-0342',
  $$Sibling site — Strawberry Park Hot Springs. See anchor row id 11659.$$,
  $$Walk-to covered wagon near tent sites and pools. Full-size mattress; bring bedding and weather-appropriate gear. Propane grill and picnic table; no light or heat. Summer season only (May 1 – Oct 31). Max 2 guests per operator policy.$$,
  $$Checkfront category 3526. $130/night sample May 2026. Summer only.$$,
  '2026-05-18', '2026-05-18', 'private_commercial',
  7, 1, '2', '2',
  130, 130, 130, NULL, NULL,
  '{"2026":{"checkfront_nightly":{"weekday":130,"weekend":130,"season":"May 1 – Oct 31","note":"Category 3526"}}}'::jsonb,
  'No', 'Yes', 'No', 'No',
  'No', 'No', 'Yes', 'No', 'No',
  'Yes', 'Yes',
  'Yes', 'Yes', 'Yes', 'Yes',
  'Yes', 'Yes', 'Yes',
  'Walk-to wagon; propane grill; picnic table; summer only; shared bathhouse.'
),
(
  'a3457bc3-69fc-4530-890f-bbd821a31557',
  'published', 'Yes', 'Yes',
  'Strawberry Park Hot Springs', 'Tent Site',
  'strawberry-park-hot-springs-steamboat-springs-co', 'Glamping', 'Tent',
  'Sage', 'web_research_strawberryhotsprings_checkfront_2026_05', 'United States', 'CO', 'Steamboat Springs',
  '44200 County Road 36', '80487', 40.7265, -106.8950,
  'https://strawberryhotsprings.com/lodging/',
  '(970) 879-0342',
  $$Sibling site — Strawberry Park Hot Springs. See anchor row id 11659.$$,
  $$Walk-to tent site 100–300 yards along the creek below the pools. Bring own tent and camping gear. Propane grill and picnic table; no campfires. Summer only (May 1 – Oct 31). Shared bathhouse.$$,
  $$Checkfront category 3528. $120/night sample May 2026. Summer only.$$,
  '2026-05-18', '2026-05-18', 'private_commercial',
  7, 1, '2', '2',
  120, 120, 120, NULL, NULL,
  '{"2026":{"checkfront_nightly":{"weekday":120,"weekend":120,"season":"May 1 – Oct 31","note":"Category 3528"}}}'::jsonb,
  'No', 'Yes', 'No', 'No',
  'No', 'No', 'Yes', 'No', 'No',
  'Yes', 'Yes',
  'Yes', 'Yes', 'Yes', 'Yes',
  'Yes', 'Yes', 'Yes',
  'Walk-to tent camping; propane grill; picnic table; no campfires; summer only.'
),
(
  'a3457bc3-69fc-4530-890f-bbd821a31557',
  'published', 'Yes', 'Yes',
  'Strawberry Park Hot Springs', 'Vehicle Camping Site',
  'strawberry-park-hot-springs-steamboat-springs-co', 'Glamping', 'Campsite',
  'Sage', 'web_research_strawberryhotsprings_checkfront_2026_05', 'United States', 'CO', 'Steamboat Springs',
  '44200 County Road 36', '80487', 40.7265, -106.8950,
  'https://strawberryhotsprings.com/lodging/',
  '(970) 879-0342',
  $$Sibling site — Strawberry Park Hot Springs. See anchor row id 11659.$$,
  $$Single vehicle-accessible camping area (standard cars only — no RVs). Tent or car camping with own gear; no campfires. Availability weather-dependent. Shared bathhouse; pool access per overnight lodging rules.$$,
  $$Checkfront category 3527. $120/night sample May 2026.$$,
  '2026-05-18', '2026-05-18', 'private_commercial',
  7, 1, '2', '2',
  120, 120, 120, 120, 120,
  '{"2026":{"checkfront_nightly":{"weekday":120,"weekend":120,"note":"Category 3527"}}}'::jsonb,
  'No', 'Yes', 'No', 'No',
  'No', 'No', 'No', 'No', 'No',
  'Yes', 'Yes',
  'Yes', 'Yes', 'Yes', 'Yes',
  'Yes', 'Yes', 'Yes',
  'Vehicle access campsite; no RVs; no campfires; bring own gear.'
);
