-- Cedar Pass Lodge (Badlands NP, Interior SD): 7 cabin/cottage site types from staybadlands.com + officialbookings S005993 (May 2026).
-- Rates: Synxis/KBE Standard Daily Rate sample night 2026-08-12 (exclusive of taxes/fees per booking engine).

UPDATE public.all_glamping_properties SET
  property_name = 'Cedar Pass Lodge',
  site_name = '1 King ADA Cabin',
  url = 'https://staybadlands.com/stay/',
  unit_type = 'Cabin',
  property_total_sites = 23,
  quantity_of_units = 1,
  unit_capacity = '2',
  operating_season_months = 'Apr 15 – Oct 15 (2026 season per booking engine)',
  unit_private_bathroom = 'Yes',
  unit_shower = 'Yes',
  unit_full_kitchen = 'No',
  unit_kitchenette = 'No',
  unit_wifi = 'No',
  unit_pets = 'No',
  unit_campfires = 'No',
  unit_picnic_table = 'Yes',
  unit_patio = 'Yes',
  unit_air_conditioning = 'Yes',
  unit_ada_accessibility = 'Yes',
  property_restaurant = 'Yes',
  property_food_on_site = 'Yes',
  property_family_friendly = 'Yes',
  setting_desert = 'Yes',
  setting_canyon = 'Yes',
  activities_hiking = 'Yes',
  activities_wildlife_watching = 'Yes',
  activities_scenic_drives = 'Yes',
  activities_historic_sightseeing = 'Yes',
  description = $$Cedar Pass Lodge — the only in-park lodging at Badlands National Park (20681 SD Highway 240, Interior SD). ~23 eco-friendly cabins and cottages (renovated 2013) with handcrafted lodgepole pine furniture, front/back porches, and modern amenities. On-site Cedar Pass Restaurant, Ben Reifel Visitor Center nearby, campground adjacent. Season typically Apr 15–Oct 15. Book via Seekda/KBE (property S005993) or staybadlands.com; 855-765-0737.$$,
  unit_description = $$ADA cabin (non-duplex) with 1 king bed, microwave, coffee maker, TV with Dish Network.$$,
  notes = COALESCE(notes, '') || E'\n\nSite enrichment (May 2026): 7 cabin SKUs from s005993.officialbookings.com (KBE) + staybadlands.com. ~23 total cabins on property; one row per bookable unit type. Rates exclusive of taxes/fees.',
  amenities_raw = 'Park lodge: restaurant, free parking, visitor center access, hiking/scenic drives. Cabin: microwave, coffee maker, Dish Network TV, A/C & heat, lodgepole pine furniture, front/back porch chairs, picnic table, toiletries.',
  discovery_source = 'web_research_staybadlands_officialbookings_2026_05',
  date_updated = '2026-05-18',
  land_operator_category = 'federal_public',
  rate_avg_retail_daily_rate = 269,
  rate_summer_weekday = 269,
  rate_summer_weekend = 269,
  rate_unit_rates_by_year = '{"2026":{"standard_daily_rate":{"weekday":269,"weekend":269,"note":"KBE sample 2026-08-12; exclusive of taxes/fees; +SD lodging taxes"}}}'::jsonb
WHERE id = 11677;

INSERT INTO public.all_glamping_properties (  property_id,
  research_status, is_glamping_property, is_open,
  property_name, site_name, slug, property_type, unit_type,
  source, discovery_source, country, state, city,
  address, zip_code, lat, lon, url, phone_number,
  description, unit_description, notes,
  date_added, date_updated, land_operator_category,
  property_total_sites, quantity_of_units, unit_capacity,
  rate_avg_retail_daily_rate, rate_summer_weekday, rate_summer_weekend,
  rate_unit_rates_by_year,
  unit_private_bathroom, unit_shower, unit_full_kitchen, unit_kitchenette,
  unit_pets, unit_picnic_table, unit_patio, unit_air_conditioning, unit_ada_accessibility,
  property_restaurant, property_food_on_site, property_family_friendly,
  setting_desert, setting_canyon,
  activities_hiking, activities_wildlife_watching, activities_scenic_drives, activities_historic_sightseeing,
  amenities_raw) VALUES (
  '8a56a8e9-fdc0-42f3-84da-a4214cbc3110',
  'published', 'Yes', 'Yes',
  'Cedar Pass Lodge', '1 King Duplex ADA Cabin',
  'cedar-pass-lodge-interior-sd', 'Glamping', 'Cabin',
  'Sage', 'web_research_staybadlands_officialbookings_2026_05', 'United States', 'SD', 'Interior',
  '20681 SD Highway 240', '57750', 43.855, -101.999,
  'https://staybadlands.com/stay/',
  '(855) 765-0737',
  $$Sibling site — Cedar Pass Lodge (Badlands NP). See anchor row id 11677.$$,
  $$ADA duplex cabin with 1 king bed, daybed, microwave, coffee maker, TV with Dish Network. Synxis room code 1KDA.$$,
  $$https://s005993.officialbookings.com/?activeBookingEngine=KBE&propertyCode=S005993&currencyCode=USD&language=en&priceType=asInPricelist&priceTimeBase=stay SKU 1KDA. $269/night sample Aug 2026 (excl. tax).$$,
  '2026-05-18', '2026-05-18', 'federal_public',
  23, 1, '2',
  269, 269, 269, '{"2026":{"standard_daily_rate":{"weekday":269,"weekend":269,"note":"KBE sample 2026-08-12; exclusive of taxes/fees"}}}'::jsonb,
  'Yes', 'Yes', 'No', 'No',
  'No', 'Yes', 'Yes', 'Yes', 'Yes',
  'Yes', 'Yes', 'Yes',
  'Yes', 'Yes',
  'Yes', 'Yes', 'Yes', 'Yes',
  'King bed; daybed; ADA; microwave; coffee maker; satellite TV; porches; picnic table.'
);

INSERT INTO public.all_glamping_properties (  property_id,
  research_status, is_glamping_property, is_open,
  property_name, site_name, slug, property_type, unit_type,
  source, discovery_source, country, state, city,
  address, zip_code, lat, lon, url, phone_number,
  description, unit_description, notes,
  date_added, date_updated, land_operator_category,
  property_total_sites, quantity_of_units, unit_capacity,
  rate_avg_retail_daily_rate, rate_summer_weekday, rate_summer_weekend,
  rate_unit_rates_by_year,
  unit_private_bathroom, unit_shower, unit_full_kitchen, unit_kitchenette,
  unit_pets, unit_picnic_table, unit_patio, unit_air_conditioning, unit_ada_accessibility,
  property_restaurant, property_food_on_site, property_family_friendly,
  setting_desert, setting_canyon,
  activities_hiking, activities_wildlife_watching, activities_scenic_drives, activities_historic_sightseeing,
  amenities_raw) VALUES (
  '8a56a8e9-fdc0-42f3-84da-a4214cbc3110',
  'published', 'Yes', 'Yes',
  'Cedar Pass Lodge', '2 Queen + Futon ADA Cabin',
  'cedar-pass-lodge-interior-sd', 'Glamping', 'Cabin',
  'Sage', 'web_research_staybadlands_officialbookings_2026_05', 'United States', 'SD', 'Interior',
  '20681 SD Highway 240', '57750', 43.855, -101.999,
  'https://staybadlands.com/stay/',
  '(855) 765-0737',
  $$Sibling site — Cedar Pass Lodge (Badlands NP). See anchor row id 11677.$$,
  $$ADA cabin with 2 queen beds, 1 futon, microwave, coffee maker, TV with Dish Network. Synxis room code 2QFA.$$,
  $$https://s005993.officialbookings.com/?activeBookingEngine=KBE&propertyCode=S005993&currencyCode=USD&language=en&priceType=asInPricelist&priceTimeBase=stay SKU 2QFA. $269/night sample Aug 2026 (excl. tax).$$,
  '2026-05-18', '2026-05-18', 'federal_public',
  23, 1, '5',
  269, 269, 269, '{"2026":{"standard_daily_rate":{"weekday":269,"weekend":269,"note":"KBE sample 2026-08-12; exclusive of taxes/fees"}}}'::jsonb,
  'Yes', 'Yes', 'No', 'No',
  'No', 'Yes', 'Yes', 'Yes', 'Yes',
  'Yes', 'Yes', 'Yes',
  'Yes', 'Yes',
  'Yes', 'Yes', 'Yes', 'Yes',
  '2 queen beds; futon; ADA; microwave; coffee maker; satellite TV; porches.'
);

INSERT INTO public.all_glamping_properties (  property_id,
  research_status, is_glamping_property, is_open,
  property_name, site_name, slug, property_type, unit_type,
  source, discovery_source, country, state, city,
  address, zip_code, lat, lon, url, phone_number,
  description, unit_description, notes,
  date_added, date_updated, land_operator_category,
  property_total_sites, quantity_of_units, unit_capacity,
  rate_avg_retail_daily_rate, rate_summer_weekday, rate_summer_weekend,
  rate_unit_rates_by_year,
  unit_private_bathroom, unit_shower, unit_full_kitchen, unit_kitchenette,
  unit_pets, unit_picnic_table, unit_patio, unit_air_conditioning, unit_ada_accessibility,
  property_restaurant, property_food_on_site, property_family_friendly,
  setting_desert, setting_canyon,
  activities_hiking, activities_wildlife_watching, activities_scenic_drives, activities_historic_sightseeing,
  amenities_raw) VALUES (
  '8a56a8e9-fdc0-42f3-84da-a4214cbc3110',
  'published', 'Yes', 'Yes',
  'Cedar Pass Lodge', '2 Queen + Futon Cabin',
  'cedar-pass-lodge-interior-sd', 'Glamping', 'Cabin',
  'Sage', 'web_research_staybadlands_officialbookings_2026_05', 'United States', 'SD', 'Interior',
  '20681 SD Highway 240', '57750', 43.855, -101.999,
  'https://staybadlands.com/stay/',
  '(855) 765-0737',
  $$Sibling site — Cedar Pass Lodge (Badlands NP). See anchor row id 11677.$$,
  $$Cabin with 2 queen beds, 1 futon, microwave, coffee maker, TV with Dish Network. Synxis room code 2QFT.$$,
  $$https://s005993.officialbookings.com/?activeBookingEngine=KBE&propertyCode=S005993&currencyCode=USD&language=en&priceType=asInPricelist&priceTimeBase=stay SKU 2QFT. No rate returned for sample dates — check live calendar.$$,
  '2026-05-18', '2026-05-18', 'federal_public',
  23, NULL, '5',
  NULL, NULL, NULL, NULL,
  'Yes', 'Yes', 'No', 'No',
  'No', 'Yes', 'Yes', 'Yes', 'No',
  'Yes', 'Yes', 'Yes',
  'Yes', 'Yes',
  'Yes', 'Yes', 'Yes', 'Yes',
  '2 queen beds; futon; microwave; coffee maker; satellite TV; porches; picnic table.'
);

INSERT INTO public.all_glamping_properties (  property_id,
  research_status, is_glamping_property, is_open,
  property_name, site_name, slug, property_type, unit_type,
  source, discovery_source, country, state, city,
  address, zip_code, lat, lon, url, phone_number,
  description, unit_description, notes,
  date_added, date_updated, land_operator_category,
  property_total_sites, quantity_of_units, unit_capacity,
  rate_avg_retail_daily_rate, rate_summer_weekday, rate_summer_weekend,
  rate_unit_rates_by_year,
  unit_private_bathroom, unit_shower, unit_full_kitchen, unit_kitchenette,
  unit_pets, unit_picnic_table, unit_patio, unit_air_conditioning, unit_ada_accessibility,
  property_restaurant, property_food_on_site, property_family_friendly,
  setting_desert, setting_canyon,
  activities_hiking, activities_wildlife_watching, activities_scenic_drives, activities_historic_sightseeing,
  amenities_raw) VALUES (
  '8a56a8e9-fdc0-42f3-84da-a4214cbc3110',
  'published', 'Yes', 'Yes',
  'Cedar Pass Lodge', '2 Queen Kitchen Cottage',
  'cedar-pass-lodge-interior-sd', 'Glamping', 'Cottage',
  'Sage', 'web_research_staybadlands_officialbookings_2026_05', 'United States', 'SD', 'Interior',
  '20681 SD Highway 240', '57750', 43.855, -101.999,
  'https://staybadlands.com/stay/',
  '(855) 765-0737',
  $$Sibling site — Cedar Pass Lodge (Badlands NP). See anchor row id 11677.$$,
  $$Cottage with 2 queen beds, queen pull-out sofa, 2 bedrooms, full kitchen (stove, cookware, utensils, dinnerware), living/dining room, microwave, coffee maker, toaster, TV with Dish Network. Synxis room code 2QKC.$$,
  $$https://s005993.officialbookings.com/?activeBookingEngine=KBE&propertyCode=S005993&currencyCode=USD&language=en&priceType=asInPricelist&priceTimeBase=stay SKU 2QKC. No rate returned for sample dates — check live calendar.$$,
  '2026-05-18', '2026-05-18', 'federal_public',
  23, NULL, '6',
  NULL, NULL, NULL, NULL,
  'Yes', 'Yes', 'Yes', 'No',
  'No', 'Yes', 'Yes', 'Yes', 'No',
  'Yes', 'Yes', 'Yes',
  'Yes', 'Yes',
  'Yes', 'Yes', 'Yes', 'Yes',
  'Full kitchen; 2 queen beds; sofa bed; 2 bedrooms; living/dining room; microwave; toaster; satellite TV.'
);

INSERT INTO public.all_glamping_properties (  property_id,
  research_status, is_glamping_property, is_open,
  property_name, site_name, slug, property_type, unit_type,
  source, discovery_source, country, state, city,
  address, zip_code, lat, lon, url, phone_number,
  description, unit_description, notes,
  date_added, date_updated, land_operator_category,
  property_total_sites, quantity_of_units, unit_capacity,
  rate_avg_retail_daily_rate, rate_summer_weekday, rate_summer_weekend,
  rate_unit_rates_by_year,
  unit_private_bathroom, unit_shower, unit_full_kitchen, unit_kitchenette,
  unit_pets, unit_picnic_table, unit_patio, unit_air_conditioning, unit_ada_accessibility,
  property_restaurant, property_food_on_site, property_family_friendly,
  setting_desert, setting_canyon,
  activities_hiking, activities_wildlife_watching, activities_scenic_drives, activities_historic_sightseeing,
  amenities_raw) VALUES (
  '8a56a8e9-fdc0-42f3-84da-a4214cbc3110',
  'published', 'Yes', 'Yes',
  'Cedar Pass Lodge', '2 Queen Cabin',
  'cedar-pass-lodge-interior-sd', 'Glamping', 'Cabin',
  'Sage', 'web_research_staybadlands_officialbookings_2026_05', 'United States', 'SD', 'Interior',
  '20681 SD Highway 240', '57750', 43.855, -101.999,
  'https://staybadlands.com/stay/',
  '(855) 765-0737',
  $$Sibling site — Cedar Pass Lodge (Badlands NP). See anchor row id 11677.$$,
  $$Cabin with 2 queen beds, microwave, coffee maker, TV with Dish Network. Synxis room code 2QNS.$$,
  $$https://s005993.officialbookings.com/?activeBookingEngine=KBE&propertyCode=S005993&currencyCode=USD&language=en&priceType=asInPricelist&priceTimeBase=stay SKU 2QNS. $269/night sample Aug 2026 (excl. tax).$$,
  '2026-05-18', '2026-05-18', 'federal_public',
  23, 5, '5',
  269, 269, 269, '{"2026":{"standard_daily_rate":{"weekday":269,"weekend":269,"note":"KBE sample 2026-08-12; exclusive of taxes/fees"}}}'::jsonb,
  'Yes', 'Yes', 'No', 'No',
  'No', 'Yes', 'Yes', 'Yes', 'No',
  'Yes', 'Yes', 'Yes',
  'Yes', 'Yes',
  'Yes', 'Yes', 'Yes', 'Yes',
  '2 queen beds; microwave; coffee maker; satellite TV; porches; picnic table.'
);

INSERT INTO public.all_glamping_properties (  property_id,
  research_status, is_glamping_property, is_open,
  property_name, site_name, slug, property_type, unit_type,
  source, discovery_source, country, state, city,
  address, zip_code, lat, lon, url, phone_number,
  description, unit_description, notes,
  date_added, date_updated, land_operator_category,
  property_total_sites, quantity_of_units, unit_capacity,
  rate_avg_retail_daily_rate, rate_summer_weekday, rate_summer_weekend,
  rate_unit_rates_by_year,
  unit_private_bathroom, unit_shower, unit_full_kitchen, unit_kitchenette,
  unit_pets, unit_picnic_table, unit_patio, unit_air_conditioning, unit_ada_accessibility,
  property_restaurant, property_food_on_site, property_family_friendly,
  setting_desert, setting_canyon,
  activities_hiking, activities_wildlife_watching, activities_scenic_drives, activities_historic_sightseeing,
  amenities_raw) VALUES (
  '8a56a8e9-fdc0-42f3-84da-a4214cbc3110',
  'published', 'Yes', 'Yes',
  'Cedar Pass Lodge', '1 King Duplex Cabin',
  'cedar-pass-lodge-interior-sd', 'Glamping', 'Cabin',
  'Sage', 'web_research_staybadlands_officialbookings_2026_05', 'United States', 'SD', 'Interior',
  '20681 SD Highway 240', '57750', 43.855, -101.999,
  'https://staybadlands.com/stay/',
  '(855) 765-0737',
  $$Sibling site — Cedar Pass Lodge (Badlands NP). See anchor row id 11677.$$,
  $$Duplex cabin with 1 king bed, daybed, microwave, coffee maker, TV with Dish Network. Synxis room code KDPX.$$,
  $$https://s005993.officialbookings.com/?activeBookingEngine=KBE&propertyCode=S005993&currencyCode=USD&language=en&priceType=asInPricelist&priceTimeBase=stay SKU KDPX. $269/night sample Aug 2026 (excl. tax).$$,
  '2026-05-18', '2026-05-18', 'federal_public',
  23, 5, '3',
  269, 269, 269, '{"2026":{"standard_daily_rate":{"weekday":269,"weekend":269,"note":"KBE sample 2026-08-12; exclusive of taxes/fees"}}}'::jsonb,
  'Yes', 'Yes', 'No', 'No',
  'No', 'Yes', 'Yes', 'Yes', 'No',
  'Yes', 'Yes', 'Yes',
  'Yes', 'Yes',
  'Yes', 'Yes', 'Yes', 'Yes',
  'King bed; daybed; microwave; coffee maker; satellite TV; porches.'
);

