-- Natura Wilderness Resort (NS): live property enrichment + 4 named tent site rows.
-- Sources: naturawilderness.com, naturawilderness.ca/our-tents.html, glamping.html (May 2026).

UPDATE public.all_glamping_properties SET
  property_name = 'Natura Wilderness Resort',
  site_name = 'Apple Tent',
  url = 'https://www.naturawilderness.com/',
  city = 'Ellershouse',
  state = 'NS',
  country = 'Canada',
  address = '50 Lynch Road',
  zip_code = 'B0N 1L0',
  lat = 44.9448588,
  lon = -64.0069757,
  phone_number = '+1-902-410-5718',
  is_open = 'Yes',
  research_status = 'published',
  property_type = 'Glamping Resort',
  unit_type = 'Safari Tent',
  property_total_sites = 4,
  quantity_of_units = 1,
  unit_capacity = '4',
  minimum_nights = '2',
  operating_season_months = 'May 22 – Oct 31 (seasonal)',
  season_open_month = 5,
  season_close_month = 10,
  unit_private_bathroom = 'Yes',
  unit_shower = 'Yes',
  unit_pets = 'Yes',
  unit_campfires = 'Yes',
  unit_wifi = 'No',
  unit_picnic_table = 'Yes',
  property_family_friendly = 'Yes',
  property_food_on_site = 'Yes',
  setting_forest = 'Yes',
  setting_coastal = 'Yes',
  activities_hiking = 'Yes',
  activities_wildlife_watching = 'Yes',
  description = $$NATURA Wilderness Resort — private forest glamping near Halifax and the Annapolis Valley (50 Lynch Road, Ellershouse NS). Four spaced canvas glamping tents (Apple, Cherry, Pine, Birch) with real beds, linens, private washrooms, cook decks, fire pits, and no Wi‑Fi by design. Seasonal operation; book via naturawilderness.ca/book.html (Checkfront).$$,
  unit_description = $$Apple Tent: open-air shower stall and private flush toilet in an outhouse-style building; sunny/sunrise setting near the access road; closest to tree swing and barnyard; dog-friendly (sleeps 2 included, up to 4 with cots).$$,
  notes = COALESCE(notes, '') || E'\n\nSite enrichment (May 2026): replaced SaltWire placeholder URL with operator site. Booking: https://naturawilderness.ca/book.html. Rates not published on marketing site—verify in Checkfront. Extra adults $25/night; children 17 and under free.',
  amenities_raw = 'Included: queen bed/linens/towels, private washroom + hot shower, cook deck w/ stove & cookware, coffee/tea/condiments/drinking water, cooler + ice, solar lights + phone charging, fire pit + starter wood + deck seating. Add-ons: breakfast baskets, dinner kits, wine/flowers, s''mores/firewood. No Wi‑Fi.',
  discovery_source = 'web_research_natura_site_2026_05',
  date_updated = '2026-05-18',
  land_operator_category = 'private_commercial'
WHERE id = 11845;

INSERT INTO public.all_glamping_properties (
  research_status, is_glamping_property, is_open,
  property_name, site_name, slug, property_type, unit_type,
  source, discovery_source, country, state, city,
  address, zip_code, lat, lon, url, phone_number,
  description, unit_description, notes,
  date_added, date_updated, land_operator_category,
  property_total_sites, quantity_of_units, unit_capacity, minimum_nights,
  operating_season_months, season_open_month, season_close_month,
  unit_private_bathroom, unit_shower, unit_pets, unit_campfires, unit_wifi,
  unit_picnic_table, unit_ada_accessibility,
  property_family_friendly, property_food_on_site,
  setting_forest, setting_coastal, activities_hiking, activities_wildlife_watching,
  amenities_raw
) VALUES
(
  'published', 'Yes', 'Yes',
  'Natura Wilderness Resort', 'Cherry Tent',
  'natura-wilderness-resort-newport-corner-ns', 'Glamping Resort', 'Safari Tent',
  'Sage', 'web_research_natura_site_2026_05', 'Canada', 'NS', 'Ellershouse',
  '50 Lynch Road', 'B0N 1L0', 44.9448588, -64.0069757,
  'https://naturawilderness.ca/book.html', '+1-902-410-5718',
  $$Sibling site — NATURA Wilderness Resort (Ellershouse NS). See anchor row id 11845.$$,
  $$Cherry Tent: quieter private setting; full bathroom ~50 ft away up stairs (“loo with a view”); more tucked away than Apple; dog-friendly; sleeps 2 included, up to 4 with cots.$$,
  $$Bathroom access involves stairs. Book via Checkfront widget on book.html.$$,
  '2026-05-18', '2026-05-18', 'private_commercial',
  4, 1, '4', '2', 'May 22 – Oct 31 (seasonal)', 5, 10,
  'Yes', 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes',
  'Private washroom w/ shower; cook deck; fire pit; no Wi‑Fi.'
),
(
  'published', 'Yes', 'Yes',
  'Natura Wilderness Resort', 'Pine Tent (Accessible)',
  'natura-wilderness-resort-newport-corner-ns', 'Glamping Resort', 'Safari Tent',
  'Sage', 'web_research_natura_site_2026_05', 'Canada', 'NS', 'Ellershouse',
  '50 Lynch Road', 'B0N 1L0', 44.9448588, -64.0069757,
  'https://naturawilderness.ca/book.html', '+1-902-410-5718',
  $$Sibling site — NATURA Wilderness Resort (Ellershouse NS).$$,
  $$Pine Tent: ramp + wheelchair-accessible bathroom connected by deck; most accessible option; calm wooded setting; dog-friendly; sleeps 2 included, up to 4 with cots.$$,
  $$Best choice for mobility needs. Book via Checkfront.$$,
  '2026-05-18', '2026-05-18', 'private_commercial',
  4, 1, '4', '2', 'May 22 – Oct 31 (seasonal)', 5, 10,
  'Yes', 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes',
  'Accessible ramp + accessible bath/shower; cook deck; fire pit.'
),
(
  'published', 'Yes', 'Yes',
  'Natura Wilderness Resort', 'Birch Tent',
  'natura-wilderness-resort-newport-corner-ns', 'Glamping Resort', 'Safari Tent',
  'Sage', 'web_research_natura_site_2026_05', 'Canada', 'NS', 'Ellershouse',
  '50 Lynch Road', 'B0N 1L0', 44.9448588, -64.0069757,
  'https://naturawilderness.ca/book.html', '+1-902-410-5718',
  $$Sibling site — NATURA Wilderness Resort (Ellershouse NS).$$,
  $$Birch Tent: secluded wooded setting; full private bathroom a few steps from deck; among the most private sites on property; dog-friendly; sleeps 2 included, up to 4 with cots.$$,
  $$En-suite-style bath very close to tent. Book via Checkfront.$$,
  '2026-05-18', '2026-05-18', 'private_commercial',
  4, 1, '4', '2', 'May 22 – Oct 31 (seasonal)', 5, 10,
  'Yes', 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes',
  'Private washroom steps from tent; cook deck; fire pit.'
);
