-- Ouachita Wilde (Mena AR): property enrichment + 3 ResNexus site rows.
-- Sources: ResNexus book engine A699365C-E037-4019-A7CB-04ECD6099F79, ouachitawilde.com (May 2026).

UPDATE public.all_glamping_properties SET
  property_name = 'Ouachita Wilde',
  site_name = 'Mountain View Dome',
  url = 'https://resnexus.com/resnexus/reservations/book/A699365C-E037-4019-A7CB-04ECD6099F79',
  city = 'Mena',
  state = 'AR',
  country = 'United States',
  address = '185 Polk County Road 167',
  zip_code = '71953',
  lat = 34.575,
  lon = -94.208,
  phone_number = '+1-479-243-8500',
  is_open = 'Yes',
  research_status = 'published',
  is_glamping_property = 'Yes',
  property_type = 'Glamping Resort',
  unit_type = 'Geodesic Dome',
  property_total_sites = 3,
  quantity_of_units = 1,
  unit_capacity = '4',
  operating_season_months = 'Year-round (heat & A/C on units per operator)',
  unit_private_bathroom = 'No',
  unit_shower = 'Yes',
  unit_kitchenette = 'Yes',
  unit_air_conditioning = 'Yes',
  unit_campfires = 'Yes',
  unit_pets = 'Yes',
  property_family_friendly = 'Yes',
  setting_forest = 'Yes',
  setting_mountainous = 'Yes',
  activities_hiking = 'Yes',
  activities_wildlife_watching = 'Yes',
  description = $$Ouachita Wilde — safari-wall tent and geodesic dome glamping on ~27 wooded acres in the Ouachita Mountains near Mena AR (185 Polk County Road 167). Three bookable units on ResNexus: Mountain View Dome plus two safari tents (The Forest Hideout, Treehouse Safari Tent). Safari tents share a modern ridge-top bathhouse with tankless hot water; units include heat/A/C, plush bedding, decks/patios, and outdoor fire/BBQ amenities. Book: resnexus.com link on property row.$$,
  unit_description = $$Mountain View Dome: geodesic dome with mountain views; climate-controlled; premium unit on the property (higher nightly rate than safari tents). Verify bed layout and bath access in ResNexus listing.$$,
  notes = COALESCE(notes, '') || E'\n\nSite enrichment (May 2026): ResNexus inventory (3 units). Sample Standard Rate 2026-05-18→19: Mountain View Dome $145/night; Forest Hideout & Treehouse Safari Tent $125/night (+taxes/fees). Marketing: https://www.ouachitawilde.com/',
  amenities_raw = 'Property: Ouachita Mountains, 27 acres, shared modern bathhouse (family-style private stalls, walk-in tiled shower, tankless hot water). Safari tents: heat/A/C, memory-foam bedding, mini fridge, coffee maker, BBQ, fire pit seating, hammock (Forest Hideout).',
  discovery_source = 'web_research_ouachita_wilde_resnexus_2026_05',
  date_updated = '2026-05-18',
  land_operator_category = 'private_commercial',
  rate_avg_retail_daily_rate = 145,
  rate_summer_weekday = 145,
  rate_summer_weekend = 145,
  rate_unit_rates_by_year = '{"2026":{"standard":{"weekday":145,"weekend":145,"note":"ResNexus Standard Rate sample 2026-05-18, 1 night"}}}'::jsonb
WHERE id = 11877;

INSERT INTO public.all_glamping_properties (
  property_id,
  research_status, is_glamping_property, is_open,
  property_name, site_name, slug, property_type, unit_type,
  source, discovery_source, country, state, city,
  address, zip_code, lat, lon, url, phone_number,
  description, unit_description, notes,
  date_added, date_updated, land_operator_category,
  property_total_sites, quantity_of_units, unit_capacity,
  rate_avg_retail_daily_rate, rate_summer_weekday, rate_summer_weekend,
  rate_unit_rates_by_year,
  unit_private_bathroom, unit_shower, unit_kitchenette,
  unit_air_conditioning, unit_campfires, unit_pets,
  setting_forest, setting_mountainous, activities_hiking, activities_wildlife_watching,
  amenities_raw
) VALUES
(
  '08a93e36-c9c7-4bce-b74c-64afeac27b60',
  'published', 'Yes', 'Yes',
  'Ouachita Wilde', 'The Forest Hideout',
  'ouachita-wilde-mena-ar', 'Glamping Resort', 'Safari Tent',
  'Sage', 'web_research_ouachita_wilde_resnexus_2026_05', 'United States', 'AR', 'Mena',
  '185 Polk County Road 167', '71953', 34.575, -94.208,
  'https://resnexus.com/resnexus/reservations/book/A699365C-E037-4019-A7CB-04ECD6099F79',
  '+1-479-243-8500',
  $$Sibling site — Ouachita Wilde (Mena AR). See anchor row id 11877.$$,
  $$The Forest Hideout: cozy safari tent on a ridge inside the tree line with mountain views. Two queen memory-foam beds plus futon sofa; table/chairs; drip coffee maker, mini fridge, and outlet; heat & A/C. Outdoor BBQ, fire pit (seating for 4), and hammock. Shared modern bathhouse at top of ridge (private stalls, walk-in tiled shower, tankless hot water). Kitchen kit: pot/skillet, utensils, plates & silverware (4), insulated cups, dish soap/towel/sponge.$$,
  $$ResNexus Standard Rate sample: $125/night (2026-05-18→19, 1 night). Sleeps up to ~6 with futon.$$,
  '2026-05-18', '2026-05-18', 'private_commercial',
  3, 1, '6',
  125, 125, 125,
  '{"2026":{"standard":{"weekday":125,"weekend":125,"note":"ResNexus sample 2026-05-18"}}}'::jsonb,
  'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes',
  'Yes', 'Yes', 'Yes', 'Yes',
  'Shared bathhouse; 2 queen beds + futon; BBQ; fire pit; hammock; mini fridge.'
),
(
  '08a93e36-c9c7-4bce-b74c-64afeac27b60',
  'published', 'Yes', 'Yes',
  'Ouachita Wilde', 'Treehouse Safari Tent',
  'ouachita-wilde-mena-ar', 'Glamping Resort', 'Safari Tent',
  'Sage', 'web_research_ouachita_wilde_resnexus_2026_05', 'United States', 'AR', 'Mena',
  '185 Polk County Road 167', '71953', 34.575, -94.208,
  'https://resnexus.com/resnexus/reservations/book/A699365C-E037-4019-A7CB-04ECD6099F79',
  '+1-479-243-8500',
  $$Sibling site — Ouachita Wilde (Mena AR).$$,
  $$Treehouse Safari Tent: elevated safari-wall tent on the 27-acre Ouachita Wilde property; climate-controlled glamping with plush bedding and outdoor living space. Shares the ridge-top luxury bathhouse with The Forest Hideout. Verify bed count and site-specific amenities in ResNexus listing.$$,
  $$ResNexus Standard Rate sample: $125/night (2026-05-18→19, 1 night).$$,
  '2026-05-18', '2026-05-18', 'private_commercial',
  3, 1, '4',
  125, 125, 125,
  '{"2026":{"standard":{"weekday":125,"weekend":125,"note":"ResNexus sample 2026-05-18"}}}'::jsonb,
  'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes',
  'Yes', 'Yes', 'Yes', 'Yes',
  'Shared bathhouse; safari tent; heat & A/C per operator.'
);
