-- Treebox (Ohio Amish Country): property + 9 named site rows from treeboxstays.com (May 2026).
-- Sources: treeboxstays.com/Accommodations/, ResNexus book engine CAB96178-8231-4598-84EE-69D44EEFDD5E.

-- Shared property_id for all Treebox site rows (multi-campus: Dundee, Dover, Walnut Creek, Winesburg OH).
-- property_total_sites = 9 bookable units on operator site.

INSERT INTO public.all_glamping_properties (
  property_id,
  research_status,
  is_glamping_property,
  is_open,
  property_name,
  site_name,
  slug,
  property_type,
  unit_type,
  source,
  discovery_source,
  country,
  state,
  city,
  address,
  zip_code,
  lat,
  lon,
  url,
  phone_number,
  description,
  unit_description,
  notes,
  date_added,
  date_updated,
  land_operator_category,
  property_total_sites,
  quantity_of_units,
  unit_capacity,
  minimum_nights,
  operating_season_months,
  unit_private_bathroom,
  unit_shower,
  unit_full_kitchen,
  unit_kitchenette,
  unit_wifi,
  unit_pets,
  unit_campfires,
  unit_hot_tub,
  property_hot_tub,
  property_family_friendly,
  setting_forest,
  activities_hiking,
  activities_wildlife_watching,
  amenities_raw
) VALUES
(
  'c4e8f2a1-7b3d-4f9e-a156-0b2e4d8c9f31'::uuid,
  'published',
  'Yes',
  'Yes',
  'Treebox',
  'Meraki House',
  'treebox-ohio',
  'Glamping',
  'Cabin',
  'Sage',
  'web_research_treeboxstays_2026_05',
  'United States',
  'OH',
  'Dover',
  '2375 Private Road 5800',
  '44624',
  40.5206,
  -81.4774,
  'https://www.treeboxstays.com/Accommodations/merakihouse.html',
  '+1-330-275-3572',
  $$Treebox — Ohio's treehouse village and modern cabin getaways in Amish Country (operator HQ 2375 Private Road 5800, Dundee OH). Nine distinct bookable units across Dover, Walnut Creek, and Winesburg: Meraki House and Orchard House (cabins), five Treehouse Village retreats (Treehouse Lodge, The Arrow, The Box, The Sky Loft, The Shack), and two Forest Haven shipping-container suites (Ela, Otium). Book direct via treeboxstays.com / ResNexus. Policies: 2-night weekend minimum; pets allowed on most units except Meraki House and Orchard House; Wi‑Fi at Meraki and Orchard; limited Wi‑Fi at Treehouse Village; no Wi‑Fi at Forest Havens.$$,
  $$Meraki House (Dover OH): entire-house rental (not shared with other groups). Nightly rate varies by guest count and dates per ResNexus. Check-in 4 PM, check-out 10 AM. Fast Wi‑Fi. Non-refundable deposit per operator policy. No pets.$$,
  $$ResNexus subscriber CAB96178-8231-4598-84EE-69D44EEFDD5E. Rates dynamic on booking calendar — verify before publishing ADR.$$,
  '2026-05-18',
  '2026-05-18',
  'private_commercial',
  9,
  1,
  '10',
  '2',
  'Year-round; 2-night minimum on weekends; 3-night minimum some holiday weekends',
  'Yes',
  'Yes',
  'Yes',
  'No',
  'Yes',
  'No',
  'Yes',
  'Yes',
  'Yes',
  'Yes',
  'Yes',
  'Yes',
  'Yes',
  'Per operator: full kitchen, private bath, gas fire pit, Wi‑Fi, luxury linens; entire-house booking.'
),
(
  'c4e8f2a1-7b3d-4f9e-a156-0b2e4d8c9f31'::uuid,
  'published', 'Yes', 'Yes',
  'Treebox', 'Orchard House',
  'treebox-ohio', 'Glamping', 'Cabin',
  'Sage', 'web_research_treeboxstays_2026_05', 'United States', 'OH', 'Walnut Creek',
  '2375 Private Road 5800', '44624', 40.1717, -81.8572,
  'https://www.treeboxstays.com/Accommodations/The-Dwell-House.html',
  '+1-330-275-3572',
  $$Sibling site — Treebox (Ohio). See anchor Meraki House row (property_id c4e8f2a1-7b3d-4f9e-a156-0b2e4d8c9f31).$$,
  $$Orchard House (Walnut Creek OH): cabin built for rest and gathering; sleeps 10–12 with master suite (king), soaking tub with view, and shared spaces. Check-in 4 PM, check-out 11 AM. Fast Wi‑Fi. No pets.$$,
  $$Operator lists as Orchard House (page The-Dwell-House.html). 30-day cancellation window for Orchard per Treebox policies.$$,
  '2026-05-18', '2026-05-18', 'private_commercial',
  9, 1, '12', '2', 'Year-round',
  'Yes', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes',
  'Large group cabin; master suite; soaking tub; Wi‑Fi.'
),
(
  'c4e8f2a1-7b3d-4f9e-a156-0b2e4d8c9f31'::uuid,
  'published', 'Yes', 'Yes',
  'Treebox', 'Treehouse Lodge',
  'treebox-ohio', 'Glamping', 'Treehouse',
  'Sage', 'web_research_treeboxstays_2026_05', 'United States', 'OH', 'Winesburg',
  '2375 Private Road 5800', '44624', 40.4944, -81.7244,
  'https://www.treeboxstays.com/Accommodations/Treehouse-Village.html',
  '+1-330-275-3572',
  $$Sibling site — Treebox Treehouse Village (Winesburg OH).$$,
  $$Treehouse Lodge: modern group treehouse with central gas fireplace, handcrafted couches, full kitchen, gas grill, 2 baths, 3 bedrooms with six queen beds. Pet fee $50. 30-day change/cancel window.$$,
  $$Listed on Treehouse-Village.html ResNexus widget (unit id 5).$$,
  '2026-05-18', '2026-05-18', 'private_commercial',
  9, 1, '12', '2', 'Year-round',
  'Yes', 'Yes', 'Yes', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes',
  'Group treehouse; 6 queen beds; kitchen; gas fireplace; limited Wi‑Fi.'
),
(
  'c4e8f2a1-7b3d-4f9e-a156-0b2e4d8c9f31'::uuid,
  'published', 'Yes', 'Yes',
  'Treebox', 'The Arrow',
  'treebox-ohio', 'Glamping', 'Treehouse',
  'Sage', 'web_research_treeboxstays_2026_05', 'United States', 'OH', 'Winesburg',
  '2375 Private Road 5800', '44624', 40.4945, -81.7245,
  'https://www.treeboxstays.com/Accommodations/Treehouse-Village.html',
  '+1-330-275-3572',
  $$Sibling site — Treebox Treehouse Village (Winesburg OH).$$,
  $$The Arrow: classic A-frame treehouse for couples; claw-foot bathtub highlight. Romantic getaway.$$,
  $$ResNexus unit id 1 on Treehouse-Village.html.$$,
  '2026-05-18', '2026-05-18', 'private_commercial',
  9, 1, '2', '2', 'Year-round',
  'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes', 'Yes', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes',
  'A-frame treehouse; claw-foot tub; couples.'
),
(
  'c4e8f2a1-7b3d-4f9e-a156-0b2e4d8c9f31'::uuid,
  'published', 'Yes', 'Yes',
  'Treebox', 'The Box',
  'treebox-ohio', 'Glamping', 'Tiny Home',
  'Sage', 'web_research_treeboxstays_2026_05', 'United States', 'OH', 'Winesburg',
  '2375 Private Road 5800', '44624', 40.4946, -81.7246,
  'https://www.treeboxstays.com/Accommodations/Treehouse-Village.html',
  '+1-330-275-3572',
  $$Sibling site — Treebox Treehouse Village (Winesburg OH).$$,
  $$The Box: shipping container set in the trees — minimalist modern retreat in nature.$$,
  $$ResNexus unit id 2.$$,
  '2026-05-18', '2026-05-18', 'private_commercial',
  9, 1, '2', '2', 'Year-round',
  'Yes', 'Yes', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes',
  'Container cabin in treetops; minimalist design.'
),
(
  'c4e8f2a1-7b3d-4f9e-a156-0b2e4d8c9f31'::uuid,
  'published', 'Yes', 'Yes',
  'Treebox', 'The Sky Loft',
  'treebox-ohio', 'Glamping', 'Treehouse',
  'Sage', 'web_research_treeboxstays_2026_05', 'United States', 'OH', 'Winesburg',
  '2375 Private Road 5800', '44624', 40.4947, -81.7247,
  'https://www.treeboxstays.com/Accommodations/Treehouse-Village.html',
  '+1-330-275-3572',
  $$Sibling site — Treebox Treehouse Village (Winesburg OH).$$,
  $$The Sky Loft: treetop hideaway with modern decor — cozy couples retreat high in the canopy.$$,
  $$ResNexus unit id 3.$$,
  '2026-05-18', '2026-05-18', 'private_commercial',
  9, 1, '2', '2', 'Year-round',
  'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes', 'Yes', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes',
  'Elevated treehouse loft; couples.'
),
(
  'c4e8f2a1-7b3d-4f9e-a156-0b2e4d8c9f31'::uuid,
  'published', 'Yes', 'Yes',
  'Treebox', 'The Shack',
  'treebox-ohio', 'Glamping', 'Treehouse',
  'Sage', 'web_research_treeboxstays_2026_05', 'United States', 'OH', 'Winesburg',
  '2375 Private Road 5800', '44624', 40.4948, -81.7248,
  'https://www.treeboxstays.com/Accommodations/Treehouse-Village.html',
  '+1-330-275-3572',
  $$Sibling site — Treebox Treehouse Village (Winesburg OH).$$,
  $$The Shack: treehouse with sleeping/lounging loft; classic cabin-in-the-woods feel.$$,
  $$ResNexus unit id 4.$$,
  '2026-05-18', '2026-05-18', 'private_commercial',
  9, 1, '4', '2', 'Year-round',
  'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes', 'Yes', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes',
  'Treehouse with loft; rustic woods setting.'
),
(
  'c4e8f2a1-7b3d-4f9e-a156-0b2e4d8c9f31'::uuid,
  'published', 'Yes', 'Yes',
  'Treebox', 'Forest Haven - Ela',
  'treebox-ohio', 'Glamping', 'Tiny Home',
  'Sage', 'web_research_treeboxstays_2026_05', 'United States', 'OH', 'Walnut Creek',
  '2375 Private Road 5800', '44624', 40.1718, -81.8573,
  'https://www.treeboxstays.com/forest-havens/ForestHavenEla.html',
  '+1-330-275-3572',
  $$Sibling site — Treebox Forest Havens (Walnut Creek OH).$$,
  $$Forest Haven - Ela: shipping container suite in a forest clearing; outdoor lounge, gas fire pit, outdoor shower and soaking tub; nature-inspired interior with luxury linens. No Wi‑Fi.$$,
  $$ResNexus bookRoomID 18. Pet fee $30 on smaller units per policies.$$,
  '2026-05-18', '2026-05-18', 'private_commercial',
  9, 1, '2', '2', 'Year-round',
  'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes',
  'Container glamping; outdoor soaking tub; fire pit; no Wi‑Fi.'
),
(
  'c4e8f2a1-7b3d-4f9e-a156-0b2e4d8c9f31'::uuid,
  'published', 'Yes', 'Yes',
  'Treebox', 'Forest Haven - Otium',
  'treebox-ohio', 'Glamping', 'Tiny Home',
  'Sage', 'web_research_treeboxstays_2026_05', 'United States', 'OH', 'Walnut Creek',
  '2375 Private Road 5800', '44624', 40.1719, -81.8574,
  'https://www.treeboxstays.com/forest-havens/ForestHavenOtium.html',
  '+1-330-275-3572',
  $$Sibling site — Treebox Forest Havens (Walnut Creek OH).$$,
  $$Forest Haven - Otium: second shipping-container forest suite; outdoor lounging, gas fire pit, outdoor shower and soaking tub; peaceful wooded clearing. No Wi‑Fi.$$,
  $$ResNexus unit id 22.$$,
  '2026-05-18', '2026-05-18', 'private_commercial',
  9, 1, '2', '2', 'Year-round',
  'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes',
  'Container glamping; outdoor soaking tub; fire pit; no Wi‑Fi.'
);

REFRESH MATERIALIZED VIEW public.unified_comps;
