-- Savannah Sunset Resort and Spa: site inventory from Six Flags reservations engine (May 2026)
-- Sources: reservations.sixflags.com/savannahsunset/availability.asp; sixflags.com/greatadventure/savannahsunset
-- Enriches anchor row id 12184; inserts 8 sibling suite-category rows (9 bookable types).
-- Brand: Six Flags

INSERT INTO public.glamping_brands (slug, display_name, brand_tier, legacy_chain_key, website_url)
VALUES ('six-flags', 'Six Flags', 'standalone', 'six flags', 'https://www.sixflags.com/')
ON CONFLICT (slug) DO UPDATE SET display_name = EXCLUDED.display_name, updated_at = now();

UPDATE public.all_glamping_properties SET
  property_id = '7dc970da-15e8-4d42-bed5-672276bbb0ac'::uuid,
  brand_id = (SELECT id FROM public.glamping_brands WHERE slug = 'six-flags'),
  site_name = 'Couples Glamping Suite Safari View',
  slug = 'savannah-sunset-resort-and-spa-jackson-nj',
  property_type = 'Glamping Resort',
  unit_type = 'Suite',
  source = 'Sage',
  discovery_source = 'web_research_savannah_sunset_sixflags_2026_05',
  country = 'United States',
  state = 'NJ',
  city = 'Jackson',
  address = 'Six Flags Wild Safari, 1 Six Flags Blvd, Jackson, NJ 08527',
  zip_code = '08527',
  lat = 40.138,
  lon = -74.440,
  url = 'https://reservations.sixflags.com/savannahsunset/availability.asp',
  phone_number = '+1-732-928-2000',
  research_status = 'published',
  is_glamping_property = 'Yes',
  is_open = 'Yes',
  property_total_sites = 9,
  quantity_of_units = 1,
  unit_capacity = '2',
  minimum_nights = '2',
  operating_season_months = 'May–November (verify annual calendar)',
  unit_private_bathroom = 'Yes',
  unit_shower = 'Yes',
  unit_kitchenette = 'Yes',
  unit_wifi = 'Yes',
  unit_air_conditioning = 'Yes',
  unit_campfires = 'Yes',
  unit_hot_tub = 'No',
  property_family_friendly = 'Yes',
  setting_forest = 'Yes',
  activities_wildlife_watching = 'Yes',
  land_operator_category = 'private_commercial',
  date_updated = '2026-05-21',
  description = $$Savannah Sunset Resort and Spa — Six Flags Great Adventure luxury glamping within the 350-acre Wild Safari (1,200+ animals). Nine bookable glamping suite categories with private baths, safari-view and accessible options, restaurant/bar, spa, fire pits, and package stays including multi-park admission, breakfast, giraffe feeding, and Wild Safari tours. 2-night minimum; season typically May–November.$$,
  unit_description = $$Couples Glamping Suite Safari View: 2 guests; one king bed; safari views; non-smoking; dorm-size refrigerator, microwave, in-room safe; private bathroom; West African-inspired décor.$$,
  notes = COALESCE(notes, '') || E'\n\nSite enrichment (May 2026): reservations.sixflags.com/savannahsunset/availability.asp. Sample stay 2026-06-20–06-22, 2 adults, 2-night package. Brand Six Flags. Contact: savannahsunset@sixflags.com. Re-quote rates for travel dates.',
  amenities_raw = 'King bed; safari view; private bathroom; refrigerator; microwave; in-room safe; non-smoking; package includes park tickets, breakfast, giraffe feeding per Six Flags packages.',
  rate_avg_retail_daily_rate = 849,
  rate_summer_weekday = 849,
  rate_summer_weekend = 849,
  rate_unit_rates_by_year = '{"2026":{"sample_dates":"2026-06-20_to_2026-06-22","currency":"USD","guests":2,"nights":2,"nightly_usd":849,"package_total_usd":1698,"booking_url":"https://reservations.sixflags.com/savannahsunset/availability.asp"}}'::jsonb
WHERE id = 12184;

INSERT INTO public.all_glamping_properties (
  property_id, brand_id, research_status, is_glamping_property, is_open,
  property_name, site_name, slug, property_type, unit_type,
  source, discovery_source, country, state, city,
  address, zip_code, lat, lon, url, phone_number,
  description, unit_description, notes,
  date_added, date_updated, land_operator_category,
  property_total_sites, quantity_of_units, unit_capacity, minimum_nights,
  operating_season_months,
  rate_avg_retail_daily_rate, rate_summer_weekday, rate_summer_weekend,
  rate_unit_rates_by_year,
  unit_private_bathroom, unit_shower, unit_kitchenette, unit_wifi,
  unit_air_conditioning, unit_campfires, unit_hot_tub,
  property_family_friendly, setting_forest, activities_wildlife_watching, amenities_raw
) VALUES
(
  '7dc970da-15e8-4d42-bed5-672276bbb0ac'::uuid,
  (SELECT id FROM public.glamping_brands WHERE slug = 'six-flags'),
  'published', 'Yes', 'Yes',
  'Savannah Sunset Resort and Spa', 'Couples Glamping Suite- Safari View Accessible',
  'savannah-sunset-resort-and-spa-jackson-nj', 'Glamping Resort', 'Suite',
  'Sage', 'web_research_savannah_sunset_sixflags_2026_05', 'United States', 'NJ', 'Jackson',
  'Six Flags Wild Safari, 1 Six Flags Blvd, Jackson, NJ 08527', '08527', 40.138, -74.440,
  'https://reservations.sixflags.com/savannahsunset/availability.asp', '+1-732-928-2000',
  'Sibling site — Savannah Sunset (Jackson NJ). See anchor row id 12184.',
  'Couples Glamping Suite- Safari View Accessible: 2 guests; accessible room; one king bed; safari views; refrigerator, microwave, safe; private bathroom.',
  'Sample 2026-06-20–22: $849/night, $1,698 package (2 nights, 2 adults).',
  '2026-05-21', '2026-05-21', 'private_commercial', 9, 1, '2', '2', 'May–November (verify annual calendar)',
  849, 849, 849,
  '{"2026":{"sample_dates":"2026-06-20_to_2026-06-22","nightly_usd":849,"package_total_usd":1698}}'::jsonb,
  'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'Yes',
  'Accessible; king bed; safari view; private bath; fridge; microwave; safe.'
),
(
  '7dc970da-15e8-4d42-bed5-672276bbb0ac'::uuid,
  (SELECT id FROM public.glamping_brands WHERE slug = 'six-flags'),
  'published', 'Yes', 'Yes',
  'Savannah Sunset Resort and Spa', 'Family Glamping Suite With 1 King, 1 Queen/Trundle',
  'savannah-sunset-resort-and-spa-jackson-nj', 'Glamping Resort', 'Suite',
  'Sage', 'web_research_savannah_sunset_sixflags_2026_05', 'United States', 'NJ', 'Jackson',
  'Six Flags Wild Safari, 1 Six Flags Blvd, Jackson, NJ 08527', '08527', 40.138, -74.440,
  'https://reservations.sixflags.com/savannahsunset/availability.asp', '+1-732-928-2000',
  'Sibling site — Savannah Sunset (Jackson NJ). See anchor row id 12184.',
  'Family Glamping Suite With 1 King, 1 Queen/Trundle: up to 5 guests; one king and one queen/twin trundle; refrigerator, microwave, safe; private bathroom.',
  'Booking engine short title: Family Glamping Suite.',
  '2026-05-21', '2026-05-21', 'private_commercial', 9, 1, '5', '2', 'May–November (verify annual calendar)',
  899, 899, 899,
  '{"2026":{"sample_dates":"2026-06-20_to_2026-06-22","nightly_usd":899,"package_total_usd":1798}}'::jsonb,
  'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'Yes',
  'King bed; queen/trundle; private bath; fridge; microwave; safe; sleeps 5.'
),
(
  '7dc970da-15e8-4d42-bed5-672276bbb0ac'::uuid,
  (SELECT id FROM public.glamping_brands WHERE slug = 'six-flags'),
  'published', 'Yes', 'Yes',
  'Savannah Sunset Resort and Spa', 'Family Glamping Suite- Accessible',
  'savannah-sunset-resort-and-spa-jackson-nj', 'Glamping Resort', 'Suite',
  'Sage', 'web_research_savannah_sunset_sixflags_2026_05', 'United States', 'NJ', 'Jackson',
  'Six Flags Wild Safari, 1 Six Flags Blvd, Jackson, NJ 08527', '08527', 40.138, -74.440,
  'https://reservations.sixflags.com/savannahsunset/availability.asp', '+1-732-928-2000',
  'Sibling site — Savannah Sunset (Jackson NJ). See anchor row id 12184.',
  'Family Glamping Suite- Accessible: accessible room; one king and two twin beds; private bathroom; refrigerator, microwave, safe.',
  'Booking engine short title: Family Glamping Suite Accessible.',
  '2026-05-21', '2026-05-21', 'private_commercial', 9, 1, '4', '2', 'May–November (verify annual calendar)',
  899, 899, 899,
  '{"2026":{"sample_dates":"2026-06-20_to_2026-06-22","nightly_usd":899,"package_total_usd":1798}}'::jsonb,
  'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'Yes',
  'Accessible; king; two twins; private bath; fridge; microwave; safe.'
),
(
  '7dc970da-15e8-4d42-bed5-672276bbb0ac'::uuid,
  (SELECT id FROM public.glamping_brands WHERE slug = 'six-flags'),
  'published', 'Yes', 'Yes',
  'Savannah Sunset Resort and Spa', 'Family Glamping Suite with Veranda 2 Twin',
  'savannah-sunset-resort-and-spa-jackson-nj', 'Glamping Resort', 'Suite',
  'Sage', 'web_research_savannah_sunset_sixflags_2026_05', 'United States', 'NJ', 'Jackson',
  'Six Flags Wild Safari, 1 Six Flags Blvd, Jackson, NJ 08527', '08527', 40.138, -74.440,
  'https://reservations.sixflags.com/savannahsunset/availability.asp', '+1-732-928-2000',
  'Sibling site — Savannah Sunset (Jackson NJ). See anchor row id 12184.',
  'Family Glamping Suite with Veranda 2 Twin: up to 6 guests; veranda; one king, two twins, pullout queen; private bathroom; refrigerator, microwave, safe.',
  'Sample 2026-06-20–22: $999/night, $1,998 package.',
  '2026-05-21', '2026-05-21', 'private_commercial', 9, 1, '6', '2', 'May–November (verify annual calendar)',
  999, 999, 999,
  '{"2026":{"sample_dates":"2026-06-20_to_2026-06-22","nightly_usd":999,"package_total_usd":1998}}'::jsonb,
  'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'Yes',
  'Veranda; king; two twins; pullout queen; private bath; sleeps 6.'
),
(
  '7dc970da-15e8-4d42-bed5-672276bbb0ac'::uuid,
  (SELECT id FROM public.glamping_brands WHERE slug = 'six-flags'),
  'published', 'Yes', 'Yes',
  'Savannah Sunset Resort and Spa', 'Family Glamping Suite- Safari View 1 King, 1 Queen/Trundle',
  'savannah-sunset-resort-and-spa-jackson-nj', 'Glamping Resort', 'Suite',
  'Sage', 'web_research_savannah_sunset_sixflags_2026_05', 'United States', 'NJ', 'Jackson',
  'Six Flags Wild Safari, 1 Six Flags Blvd, Jackson, NJ 08527', '08527', 40.138, -74.440,
  'https://reservations.sixflags.com/savannahsunset/availability.asp', '+1-732-928-2000',
  'Sibling site — Savannah Sunset (Jackson NJ). See anchor row id 12184.',
  'Family Glamping Suite- Safari View 1 King, 1 Queen/Trundle: up to 6 guests; safari view; one king and queen/twin trundle; private bathroom; refrigerator, microwave, safe.',
  'Booking engine short title: Family Glamping Suite - Safari View.',
  '2026-05-21', '2026-05-21', 'private_commercial', 9, 1, '6', '2', 'May–November (verify annual calendar)',
  1099, 1099, 1099,
  '{"2026":{"sample_dates":"2026-06-20_to_2026-06-22","nightly_usd":1099,"package_total_usd":2198}}'::jsonb,
  'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'Yes',
  'Safari view; king; queen/trundle; private bath; sleeps 6.'
),
(
  '7dc970da-15e8-4d42-bed5-672276bbb0ac'::uuid,
  (SELECT id FROM public.glamping_brands WHERE slug = 'six-flags'),
  'published', 'Yes', 'Yes',
  'Savannah Sunset Resort and Spa', 'Family Glamping Suite With 1 King, 2 Twins',
  'savannah-sunset-resort-and-spa-jackson-nj', 'Glamping Resort', 'Suite',
  'Sage', 'web_research_savannah_sunset_sixflags_2026_05', 'United States', 'NJ', 'Jackson',
  'Six Flags Wild Safari, 1 Six Flags Blvd, Jackson, NJ 08527', '08527', 40.138, -74.440,
  'https://reservations.sixflags.com/savannahsunset/availability.asp', '+1-732-928-2000',
  'Sibling site — Savannah Sunset (Jackson NJ). See anchor row id 12184.',
  'Family Glamping Suite With 1 King, 2 Twins: up to 6 guests; one king, two twin beds, pullout queen; private bathroom; refrigerator, microwave, safe.',
  'No rate returned on sample dates 2026-06-20–22; inferred tier $899/night (standard family) — re-quote.',
  '2026-05-21', '2026-05-21', 'private_commercial', 9, 1, '6', '2', 'May–November (verify annual calendar)',
  899, 899, 899,
  '{"2026":{"sample_dates":"2026-06-20_to_2026-06-22","nightly_usd":null,"inferred_nightly_usd":899,"note":"Sold out or no quote on sample dates"}}'::jsonb,
  'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'Yes',
  'King; two twins; pullout queen; private bath; sleeps 6.'
),
(
  '7dc970da-15e8-4d42-bed5-672276bbb0ac'::uuid,
  (SELECT id FROM public.glamping_brands WHERE slug = 'six-flags'),
  'published', 'Yes', 'Yes',
  'Savannah Sunset Resort and Spa', 'Family Glamping Suite- Safari View 1 King / 2 Twin',
  'savannah-sunset-resort-and-spa-jackson-nj', 'Glamping Resort', 'Suite',
  'Sage', 'web_research_savannah_sunset_sixflags_2026_05', 'United States', 'NJ', 'Jackson',
  'Six Flags Wild Safari, 1 Six Flags Blvd, Jackson, NJ 08527', '08527', 40.138, -74.440,
  'https://reservations.sixflags.com/savannahsunset/availability.asp', '+1-732-928-2000',
  'Sibling site — Savannah Sunset (Jackson NJ). See anchor row id 12184.',
  'Family Glamping Suite- Safari View 1 King / 2 Twin: up to 6 guests; safari view; one king, two twins, pullout queen; private bathroom; refrigerator, microwave, safe.',
  'No rate on sample dates; inferred $1,099/night (safari-view family tier) — re-quote.',
  '2026-05-21', '2026-05-21', 'private_commercial', 9, 1, '6', '2', 'May–November (verify annual calendar)',
  1099, 1099, 1099,
  '{"2026":{"sample_dates":"2026-06-20_to_2026-06-22","nightly_usd":null,"inferred_nightly_usd":1099}}'::jsonb,
  'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'Yes',
  'Safari view; king; two twins; pullout queen; private bath; sleeps 6.'
),
(
  '7dc970da-15e8-4d42-bed5-672276bbb0ac'::uuid,
  (SELECT id FROM public.glamping_brands WHERE slug = 'six-flags'),
  'published', 'Yes', 'Yes',
  'Savannah Sunset Resort and Spa', 'Family Glamping Suite- Safari View Accessible',
  'savannah-sunset-resort-and-spa-jackson-nj', 'Glamping Resort', 'Suite',
  'Sage', 'web_research_savannah_sunset_sixflags_2026_05', 'United States', 'NJ', 'Jackson',
  'Six Flags Wild Safari, 1 Six Flags Blvd, Jackson, NJ 08527', '08527', 40.138, -74.440,
  'https://reservations.sixflags.com/savannahsunset/availability.asp', '+1-732-928-2000',
  'Sibling site — Savannah Sunset (Jackson NJ). See anchor row id 12184.',
  'Family Glamping Suite- Safari View Accessible: up to 6 guests; safari view; accessible; two king beds and pullout queen; private bathroom; refrigerator, microwave, safe.',
  'No rate on sample dates; inferred $1,099/night — re-quote.',
  '2026-05-21', '2026-05-21', 'private_commercial', 9, 1, '6', '2', 'May–November (verify annual calendar)',
  1099, 1099, 1099,
  '{"2026":{"sample_dates":"2026-06-20_to_2026-06-22","nightly_usd":null,"inferred_nightly_usd":1099}}'::jsonb,
  'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'Yes',
  'Safari view; accessible; two kings; pullout queen; private bath; sleeps 6.'
);

UPDATE public.all_glamping_properties SET
  brand_id = (SELECT id FROM public.glamping_brands WHERE slug = 'six-flags'),
  property_id = '7dc970da-15e8-4d42-bed5-672276bbb0ac'::uuid,
  description = 'Sibling site — Savannah Sunset Resort and Spa (Jackson NJ). See anchor row id 12184.',
  url = 'https://reservations.sixflags.com/savannahsunset/availability.asp',
  phone_number = '+1-732-928-2000',
  country = 'United States',
  state = 'NJ',
  city = 'Jackson',
  address = 'Six Flags Wild Safari, 1 Six Flags Blvd, Jackson, NJ 08527',
  zip_code = '08527',
  lat = 40.138,
  lon = -74.440,
  property_total_sites = 9,
  quantity_of_units = 1,
  minimum_nights = '2',
  is_glamping_property = 'Yes',
  is_open = 'Yes',
  property_type = 'Glamping Resort',
  unit_type = 'Suite',
  slug = 'savannah-sunset-resort-and-spa-jackson-nj',
  land_operator_category = 'private_commercial',
  property_family_friendly = 'Yes',
  setting_forest = 'Yes',
  activities_wildlife_watching = 'Yes',
  unit_private_bathroom = 'Yes',
  unit_shower = 'Yes',
  unit_kitchenette = 'Yes',
  unit_wifi = 'Yes',
  unit_air_conditioning = 'Yes',
  unit_campfires = 'Yes',
  operating_season_months = 'May–November (verify annual calendar)',
  discovery_source = 'web_research_savannah_sunset_sixflags_2026_05',
  research_status = 'published'
WHERE property_name = 'Savannah Sunset Resort and Spa' AND id <> 12184;
