-- Blue Bell Lodge (Custer SD): property enrichment + 8 cabin site-type rows.
-- Sources: custerresorts.com GraphQL cabinsEntries + cabin detail pages (.md), Synxis Hotel=20178 (May 2026).

UPDATE public.all_glamping_properties SET
  property_name = 'Blue Bell Lodge',
  site_name = 'Bakerville Cabin',
  url = 'https://www.custerresorts.com/lodging/cabins/blue-bell/housekeeping-cabin-h3dc-bakerville-cabin',
  city = 'Custer',
  state = 'SD',
  country = 'United States',
  address = '13079 Blue Bell Road',
  zip_code = '57730',
  lat = 43.712,
  lon = -103.448,
  phone_number = '+1-605-255-4531',
  is_open = 'Yes',
  research_status = 'published',
  is_glamping_property = 'Yes',
  property_type = 'Glamping',
  unit_type = 'Cabin',
  property_total_sites = 30,
  quantity_of_units = 2,
  unit_capacity = '8',
  operating_season_months = 'Seasonal May–October (verify exact open/close dates in Synxis; dining May–Oct per operator)',
  unit_private_bathroom = 'Yes',
  unit_shower = 'Yes',
  unit_full_kitchen = 'Yes',
  unit_kitchenette = 'No',
  unit_wifi = 'No',
  unit_pets = 'Yes',
  unit_campfires = 'Yes',
  unit_picnic_table = 'Yes',
  unit_patio = 'Yes',
  unit_air_conditioning = 'Yes',
  unit_ada_accessibility = 'No',
  property_restaurant = 'Yes',
  property_food_on_site = 'Yes',
  property_general_store = 'Yes',
  property_family_friendly = 'Yes',
  setting_forest = 'Yes',
  setting_mountainous = 'Yes',
  activities_hiking = 'Yes',
  activities_wildlife_watching = 'Yes',
  activities_horseback_riding = 'Yes',
  activities_scenic_drives = 'Yes',
  activities_historic_sightseeing = 'Yes',
  description = $$Blue Bell Lodge — log-cabin ranch hideaway in Custer State Park Resort (13079 Blue Bell Road, Custer SD), north of French Creek on the Wildlife Loop near the horse camp. ~30 housekeeping and log cabins in a private loop with outdoor fire pits, seasonal Western dining, Blue Bell Store (gifts, gas, essentials), trail rides, and nightly hayride & chuck wagon cookout. Book cabins via Synxis (Hotel 20178) or 888-875-0001.$$,
  unit_description = $$Bakerville Cabin (QN/DBL/DBL/Sofa): two-bedroom housekeeping cabin with full kitchen, living area, covered private deck, fire pit, and picnic table; sleeps up to 8 (1 queen, 2 full beds, sofa sleeper). Two identical units (H3DC). Pet-friendly on request when booking by phone.$$,
  notes = COALESCE(notes, '') || E'\n\nSite enrichment (May 2026): 8 cabin types via custerresorts.com/lodging/cabins?lodge=blue-bell + cabin detail pages. Published nightly rates on operator site (excludes taxes/fees). Synxis booking: https://be.synxis.com/?Hotel=20178&Chain=7774. Property marketing: https://www.custerresorts.com/plan-your-trip/blue-bell-lodge. Reservations: 888-875-0001.',
  amenities_raw = 'Property: ~30 cabins, Blue Bell dining room & lounge (May–Oct), Blue Bell Store, horses/chuckwagon, hayride & cookout, Wildlife Loop access. Cabin: full kitchen (stove/oven, microwave, fridge/freezer, cookware), HVAC, flat-screen TV, hair dryer, fire pit, picnic table, covered deck; 1 full bath.',
  discovery_source = 'web_research_custerresorts_synxis_2026_05',
  date_updated = '2026-05-18',
  land_operator_category = 'state_park',
  rate_avg_retail_daily_rate = 385,
  rate_summer_weekday = 385,
  rate_summer_weekend = 385,
  rate_unit_rates_by_year = '{"2026":{"summer":{"weekday":385,"weekend":385,"note":"custerresorts.com published nightly rate May 2026; +taxes/fees"}}}'::jsonb
WHERE id = 11675;

INSERT INTO public.all_glamping_properties (
  property_id,
  research_status, is_glamping_property, is_open,
  property_name, site_name, slug, property_type, unit_type,
  source, discovery_source, country, state, city,
  address, zip_code, lat, lon, url, phone_number,
  description, unit_description, notes,
  date_added, date_updated, land_operator_category,
  property_total_sites, quantity_of_units, unit_capacity,
  rate_avg_retail_daily_rate, rate_summer_weekday, rate_summer_weekend,
  rate_unit_rates_by_year,
  unit_private_bathroom, unit_shower, unit_full_kitchen, unit_kitchenette,
  unit_pets, unit_campfires, unit_picnic_table, unit_patio, unit_air_conditioning, unit_ada_accessibility,
  property_restaurant, property_food_on_site, property_general_store, property_family_friendly,
  setting_forest, setting_mountainous,
  activities_hiking, activities_wildlife_watching, activities_horseback_riding,
  activities_scenic_drives, activities_historic_sightseeing,
  amenities_raw
) VALUES
(
  '66951380-6c2b-41a4-9c62-b8e2db331608',
  'published', 'Yes', 'Yes',
  'Blue Bell Lodge', 'Bison Cabin',
  'blue-bell-lodge-custer-sd', 'Glamping', 'Cabin',
  'Sage', 'web_research_custerresorts_synxis_2026_05', 'United States', 'SD', 'Custer',
  '13079 Blue Bell Road', '57730', 43.712, -103.448,
  'https://www.custerresorts.com/lodging/cabins/blue-bell/log-cabin-ada-s2dh-bison-cabin',
  '+1-605-255-4531',
  $$Sibling site — Blue Bell Lodge (Custer State Park). See anchor row id 11675.$$,
  $$Bison Cabin (DBL/DBL, ADA): accessible log cabin with kitchenette, private deck, fire pit; sleeps 4 (2 double beds). Two units (S2DH). Pet-friendly on request when booking by phone.$$,
  $$Synxis room=S2DH. Published rate $342/night (May 2026).$$,
  '2026-05-18', '2026-05-18', 'state_park',
  30, 2, '4',
  342, 342, 342,
  '{"2026":{"summer":{"weekday":342,"weekend":342,"note":"custerresorts.com May 2026; +taxes/fees"}}}'::jsonb,
  'Yes', 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes',
  'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes',
  'ADA log cabin; kitchenette; deck; fire pit; 1 full bath.'
),
(
  '66951380-6c2b-41a4-9c62-b8e2db331608',
  'published', 'Yes', 'Yes',
  'Blue Bell Lodge', 'Camp Narrows Cabin',
  'blue-bell-lodge-custer-sd', 'Glamping', 'Cabin',
  'Sage', 'web_research_custerresorts_synxis_2026_05', 'United States', 'SD', 'Custer',
  '13079 Blue Bell Road', '57730', 43.712, -103.448,
  'https://www.custerresorts.com/lodging/cabins/blue-bell/housekeeping-cabin-h1dc-camp-narrows-cabin',
  '+1-605-255-4531',
  $$Sibling site — Blue Bell Lodge (Custer State Park).$$,
  $$Camp Narrows Cabin (QN/Sofa): compact housekeeping cabin with kitchenette; queen bed and sofa sleeper; sleeps 4 (H1DC). Pet-friendly on request.$$,
  $$Synxis room=H1DC. Published rate $261/night (May 2026).$$,
  '2026-05-18', '2026-05-18', 'state_park',
  30, 1, '4',
  261, 261, 261,
  '{"2026":{"summer":{"weekday":261,"weekend":261,"note":"custerresorts.com May 2026; +taxes/fees"}}}'::jsonb,
  'Yes', 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'No',
  'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes',
  'Kitchenette; fire pit; 1 full bath.'
),
(
  '66951380-6c2b-41a4-9c62-b8e2db331608',
  'published', 'Yes', 'Yes',
  'Blue Bell Lodge', 'Commissioner''s Cabin',
  'blue-bell-lodge-custer-sd', 'Glamping', 'Cabin',
  'Sage', 'web_research_custerresorts_synxis_2026_05', 'United States', 'SD', 'Custer',
  '13079 Blue Bell Road', '57730', 43.712, -103.448,
  'https://www.custerresorts.com/lodging/cabins/blue-bell/commissioners',
  '+1-605-255-4531',
  $$Sibling site — Blue Bell Lodge (Custer State Park).$$,
  $$Commissioner's Cabin (QN/DBL/DBL/Sofa): two-bedroom cabin with full kitchen, porch, fire pit; sleeps 8. Not pet-friendly (COMM).$$,
  $$Synxis room=COMM. Published rate $442/night (May 2026).$$,
  '2026-05-18', '2026-05-18', 'state_park',
  30, 1, '8',
  442, 442, 442,
  '{"2026":{"summer":{"weekday":442,"weekend":442,"note":"custerresorts.com May 2026; +taxes/fees"}}}'::jsonb,
  'Yes', 'Yes', 'Yes', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'No',
  'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes',
  'Full kitchen; porch; not pet-friendly.'
),
(
  '66951380-6c2b-41a4-9c62-b8e2db331608',
  'published', 'Yes', 'Yes',
  'Blue Bell Lodge', 'Honeymoon Cabin',
  'blue-bell-lodge-custer-sd', 'Glamping', 'Cabin',
  'Sage', 'web_research_custerresorts_synxis_2026_05', 'United States', 'SD', 'Custer',
  '13079 Blue Bell Road', '57730', 43.712, -103.448,
  'https://www.custerresorts.com/lodging/cabins/blue-bell/honeymoon-cabin-king-sofa-s1ks',
  '+1-605-255-4531',
  $$Sibling site — Blue Bell Lodge (Custer State Park).$$,
  $$Honeymoon Cabin (King): couples cabin with king bed, kitchenette, private deck, fire pit; sleeps 2 (S1KS). Not pet-friendly.$$,
  $$Synxis room=S1KS. Published rate $379/night (May 2026).$$,
  '2026-05-18', '2026-05-18', 'state_park',
  30, 1, '2',
  379, 379, 379,
  '{"2026":{"summer":{"weekday":379,"weekend":379,"note":"custerresorts.com May 2026; +taxes/fees"}}}'::jsonb,
  'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'No',
  'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes',
  'King bed; kitchenette; private deck; not pet-friendly.'
),
(
  '66951380-6c2b-41a4-9c62-b8e2db331608',
  'published', 'Yes', 'Yes',
  'Blue Bell Lodge', 'Ponderosa Cabin',
  'blue-bell-lodge-custer-sd', 'Glamping', 'Cabin',
  'Sage', 'web_research_custerresorts_synxis_2026_05', 'United States', 'SD', 'Custer',
  '13079 Blue Bell Road', '57730', 43.712, -103.448,
  'https://www.custerresorts.com/lodging/cabins/blue-bell/ponderosa',
  '+1-605-255-4531',
  $$Sibling site — Blue Bell Lodge (Custer State Park).$$,
  $$Ponderosa Cabin (Specialty Group Cabin): large reunion/group cabin with full kitchen, private deck and patio; 11 beds, 5 baths; sleeps up to 24 (POND). Not pet-friendly. Rollaway/pack-n-play on request.$$,
  $$Synxis room=POND. Published rate $1,650/night (May 2026). Spring Sale may discount reunion cabins—verify on operator site.$$,
  '2026-05-18', '2026-05-18', 'state_park',
  30, 1, '24',
  1650, 1650, 1650,
  '{"2026":{"summer":{"weekday":1650,"weekend":1650,"note":"custerresorts.com May 2026; +taxes/fees"}}}'::jsonb,
  'Yes', 'Yes', 'Yes', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'No',
  'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes',
  'Group/reunion cabin; 5 baths; full kitchen; deck & patio.'
),
(
  '66951380-6c2b-41a4-9c62-b8e2db331608',
  'published', 'Yes', 'Yes',
  'Blue Bell Lodge', 'Robber''s Roost Cabin',
  'blue-bell-lodge-custer-sd', 'Glamping', 'Cabin',
  'Sage', 'web_research_custerresorts_synxis_2026_05', 'United States', 'SD', 'Custer',
  '13079 Blue Bell Road', '57730', 43.712, -103.448,
  'https://www.custerresorts.com/lodging/cabins/blue-bell/housekeeping-cabin-h2db-robbers-roost-cabin',
  '+1-605-255-4531',
  $$Sibling site — Blue Bell Lodge (Custer State Park).$$,
  $$Robber's Roost Cabin (QN/QN/Sofa): two queen bedrooms plus sofa sleeper, kitchenette, porch, fire pit; sleeps 6 (H2DB). Pet-friendly on request.$$,
  $$Synxis room=H2DB. Published rate $292/night (May 2026).$$,
  '2026-05-18', '2026-05-18', 'state_park',
  30, 1, '6',
  292, 292, 292,
  '{"2026":{"summer":{"weekday":292,"weekend":292,"note":"custerresorts.com May 2026; +taxes/fees"}}}'::jsonb,
  'Yes', 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'No',
  'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes',
  'Kitchenette; porch; 2 queen beds + sofa.'
),
(
  '66951380-6c2b-41a4-9c62-b8e2db331608',
  'published', 'Yes', 'Yes',
  'Blue Bell Lodge', 'Rose Quartz Cabin',
  'blue-bell-lodge-custer-sd', 'Glamping', 'Cabin',
  'Sage', 'web_research_custerresorts_synxis_2026_05', 'United States', 'SD', 'Custer',
  '13079 Blue Bell Road', '57730', 43.712, -103.448,
  'https://www.custerresorts.com/lodging/cabins/blue-bell/log-cabin-s2d-rose-quartz-cabin',
  '+1-605-255-4531',
  $$Sibling site — Blue Bell Lodge (Custer State Park).$$,
  $$Rose Quartz Cabin (QN/QN): log cabin with two queen beds, kitchenette, private deck, fire pit; sleeps 4 (S2D). Pet-friendly on request.$$,
  $$Synxis room=S2D. Published rate $342/night (May 2026).$$,
  '2026-05-18', '2026-05-18', 'state_park',
  30, 1, '4',
  342, 342, 342,
  '{"2026":{"summer":{"weekday":342,"weekend":342,"note":"custerresorts.com May 2026; +taxes/fees"}}}'::jsonb,
  'Yes', 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'No',
  'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes',
  'Log cabin; kitchenette; private deck.'
);
