-- Three Camel Lodge: site inventory from threecamellodge.com (May 2026)
-- Sources: accomodations FAQ, 3-day/2-night journey pricing (Nomadic Expeditions); AFAR from-rate
-- Enriches anchor row id 12195; inserts 2 sibling ger-category rows (40 gers, 3 types).

UPDATE public.all_glamping_properties SET
  property_id = '72ba9ebe-554b-4950-96cf-3db77e3cdc22'::uuid,
  site_name = 'Deluxe Ger',
  slug = 'three-camel-lodge-gobi-mn',
  property_type = 'Glamping Resort',
  unit_type = 'Yurt',
  source = 'Sage',
  discovery_source = 'web_research_three_camel_lodge_2026_05',
  country = 'Mongolia',
  state = 'Ömnögovi',
  city = 'Dalanzadgad',
  address = 'Gobi Altai Mountains, South Gobi, Mongolia',
  lat = 43.730,
  lon = 103.430,
  url = 'https://www.threecamellodge.com/accomodations/',
  phone_number = '+1-800-998-6634',
  research_status = 'published',
  is_glamping_property = 'Yes',
  is_open = 'Yes',
  property_total_sites = 40,
  quantity_of_units = 1,
  unit_capacity = '2',
  unit_bed = '1 King or 2 Twins',
  minimum_nights = '2',
  operating_season_months = 'May; Jun–Oct; Oct 12–Nov 30 (journey seasons)',
  unit_private_bathroom = 'Yes',
  unit_shower = 'Yes',
  unit_wifi = 'Yes',
  unit_campfires = 'Yes',
  unit_hot_tub = 'No',
  property_family_friendly = 'Yes',
  setting_desert = 'Yes',
  setting_mountainous = 'Yes',
  activities_wildlife_watching = 'Yes',
  activities_hiking = 'Yes',
  activities_scenic_drives = 'Yes',
  land_operator_category = 'private_commercial',
  glamping_service_tier = 'luxury',
  date_updated = '2026-05-21',
  description = $$Three Camel Lodge — luxury ger camp in Mongolia's Gobi Altai (South Gobi), 40 handmade gers with wool carpets, camel-hair blankets, wood stoves, and stone en-suite baths. Nomadic Expeditions journeys include 4x4 excursions to Khongoryn Els dunes, Flaming Cliffs dinosaur sites, and ancient petroglyphs; lodge spa, Bulagtai Restaurant, Thirsty Camel Bar, stables, and stargazing. Beyond Green sustainable property; 100% Mongolian staff. Fly via Ulaanbaatar to Dalanzadgad.$$,
  unit_description = $$Deluxe Ger: spacious layout with king or two twin beds and en-suite bathroom. Wool carpets, hand-painted Mongolian furniture, wood stove or electric heat, solar LED lighting. Default category on published land packages.$$,
  notes = COALESCE(notes, '') || E'\n\nSite enrichment (May 2026): threecamellodge.com/accomodations + 3-day/2-night journey. Sample land rate $2,885/person for 2 nights (Jun–Oct, 2–3 guests) ≈ $1,443/night/person package equivalent. AFAR cites from ~$2,425/night/person for 2-night stay. Domestic UB–Dalanzadgad airfare ~$380 extra.',
  amenities_raw = 'Luxury ger; king or twins; wool carpets; camel-hair blankets; hand-carved furniture; wood stove; electric heat; solar LED; stone en-suite bath; spa; restaurant; bar; guided Gobi excursions; stargazing.',
  rate_avg_retail_daily_rate = 1443,
  rate_summer_weekday = 1443,
  rate_summer_weekend = 1443,
  rate_unit_rates_by_year = '{"2026":{"sample_journey":"3_days_2_nights","season":"Jun_to_Oct_11","guests":"2-3","land_per_person_usd":2885,"nights":2,"nightly_equiv_per_person_usd":1443,"afar_from_rate_per_night_pp":2425,"domestic_airfare_usd":380,"booking":"Nomadic Expeditions via threecamellodge.com"}}'::jsonb
WHERE id = 12195;

INSERT INTO public.all_glamping_properties (
  property_id, research_status, is_glamping_property, is_open,
  property_name, site_name, slug, property_type, unit_type,
  source, discovery_source, country, state, city,
  address, lat, lon, url, phone_number,
  description, unit_description, notes,
  date_added, date_updated, land_operator_category,
  property_total_sites, quantity_of_units, unit_capacity, unit_bed, minimum_nights,
  operating_season_months,
  rate_avg_retail_daily_rate, rate_summer_weekday, rate_summer_weekend,
  rate_unit_rates_by_year,
  unit_private_bathroom, unit_shower, unit_wifi, unit_campfires,
  property_family_friendly, setting_desert, setting_mountainous,
  activities_wildlife_watching, activities_hiking, activities_scenic_drives,
  glamping_service_tier, amenities_raw
) VALUES
(
  '72ba9ebe-554b-4950-96cf-3db77e3cdc22'::uuid,
  'published', 'Yes', 'Yes',
  'Three Camel Lodge', 'Chinggis Khan Ger',
  'three-camel-lodge-gobi-mn', 'Glamping Resort', 'Yurt',
  'Sage', 'web_research_three_camel_lodge_2026_05', 'Mongolia', 'Ömnögovi', 'Dalanzadgad',
  'Gobi Altai Mountains, South Gobi, Mongolia', 43.730, 103.430,
  'https://www.threecamellodge.com/accomodations/',
  '+1-800-998-6634',
  'Sibling site — Three Camel Lodge (South Gobi MN). See anchor row id 12195 (Deluxe Ger).',
  'Chinggis Khan Ger: king bedroom, private bathroom, relaxation area, and large living space for guests wanting extra room beyond Deluxe gers.',
  'Premium ger category per lodge FAQ. Land package pricing typically based on Deluxe Ger — request upgrade when booking.',
  '2026-05-21', '2026-05-21', 'private_commercial',
  40, 1, '2', '1 King', '2', 'May; Jun–Oct; Oct 12–Nov 30 (journey seasons)',
  1443, 1443, 1443,
  '{"2026":{"category":"Chinggis Khan Ger","note":"Premium category; land rates quoted on Deluxe Ger basis"}}'::jsonb,
  'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes',
  'luxury', 'King bedroom; large living space; relaxation area; private bath; wood stove; solar lighting; stone bathroom.'
),
(
  '72ba9ebe-554b-4950-96cf-3db77e3cdc22'::uuid,
  'published', 'Yes', 'Yes',
  'Three Camel Lodge', 'Khubilai Khan Ger',
  'three-camel-lodge-gobi-mn', 'Glamping Resort', 'Yurt',
  'Sage', 'web_research_three_camel_lodge_2026_05', 'Mongolia', 'Ömnögovi', 'Dalanzadgad',
  'Gobi Altai Mountains, South Gobi, Mongolia', 43.730, 103.430,
  'https://www.threecamellodge.com/accomodations/',
  '+1-800-998-6634',
  'Sibling site — Three Camel Lodge (South Gobi MN). See anchor row id 12195.',
  'Khubilai Khan Ger: family ger with two separate bedrooms connected by a bathroom; king bed plus two twins in second bedroom. Ideal for families or small groups.',
  '2-night journey land rate sample (Jun–Oct): $2,955/person (3 guests) or $2,275/person (4 guests).',
  '2026-05-21', '2026-05-21', 'private_commercial',
  40, 1, '4', '1 King + 2 Twins', '2', 'May; Jun–Oct; Oct 12–Nov 30 (journey seasons)',
  1478, 1478, 1478,
  '{"2026":{"category":"Khubilai Khan 2BR Family Ger","land_per_person_3_guests_usd":2955,"land_per_person_4_guests_usd":2275,"nights":2,"nightly_equiv_3_guests_usd":1478,"nightly_equiv_4_guests_usd":1138}}'::jsonb,
  'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes',
  'luxury', 'Two-bedroom family ger; king + twins; connected bath; wood stove; solar LED; family Gobi packages.'
);

UPDATE public.all_glamping_properties SET
  property_id = '72ba9ebe-554b-4950-96cf-3db77e3cdc22'::uuid,
  description = 'Sibling site — Three Camel Lodge (South Gobi MN). See anchor row id 12195 (Deluxe Ger).',
  url = 'https://www.threecamellodge.com/accomodations/',
  phone_number = '+1-800-998-6634',
  country = 'Mongolia',
  state = 'Ömnögovi',
  city = 'Dalanzadgad',
  address = 'Gobi Altai Mountains, South Gobi, Mongolia',
  lat = 43.730,
  lon = 103.430,
  property_total_sites = 40,
  quantity_of_units = 1,
  minimum_nights = '2',
  is_glamping_property = 'Yes',
  is_open = 'Yes',
  property_type = 'Glamping Resort',
  unit_type = 'Yurt',
  slug = 'three-camel-lodge-gobi-mn',
  land_operator_category = 'private_commercial',
  glamping_service_tier = 'luxury',
  property_family_friendly = 'Yes',
  setting_desert = 'Yes',
  setting_mountainous = 'Yes',
  activities_wildlife_watching = 'Yes',
  activities_hiking = 'Yes',
  activities_scenic_drives = 'Yes',
  unit_private_bathroom = 'Yes',
  unit_shower = 'Yes',
  unit_wifi = 'Yes',
  unit_campfires = 'Yes',
  operating_season_months = 'May; Jun–Oct; Oct 12–Nov 30 (journey seasons)',
  discovery_source = 'web_research_three_camel_lodge_2026_05',
  research_status = 'published'
WHERE property_name = 'Three Camel Lodge' AND id <> 12195;
