-- Eureka Yurts and Cabins (Eureka Springs AR): property enrichment + 2 named yurt site rows.
-- Sources: eurekayurts.com, MotoPress Hotel Booking listings (May 2026).

UPDATE public.all_glamping_properties SET
  property_name = 'Eureka Yurts and Cabins',
  site_name = 'Pine View Yurt',
  url = 'https://eurekayurts.com/',
  city = 'Eureka Springs',
  state = 'AR',
  country = 'United States',
  address = '191 Bear Ridge Rd',
  zip_code = '72631',
  lat = 36.395,
  lon = -93.782,
  phone_number = '+1-479-358-6485',
  is_open = 'Yes',
  research_status = 'published',
  is_glamping_property = 'Yes',
  property_type = 'Glamping Resort',
  unit_type = 'Yurt',
  property_total_sites = 2,
  quantity_of_units = 1,
  unit_capacity = '2',
  minimum_nights = '2',
  operating_season_months = 'Year-round (verify holiday closures on operator calendar)',
  unit_private_bathroom = 'Yes',
  unit_shower = 'Yes',
  unit_kitchenette = 'Yes',
  unit_hot_tub = 'Yes',
  unit_air_conditioning = 'Yes',
  unit_wifi = 'Yes',
  property_family_friendly = 'No',
  setting_forest = 'Yes',
  activities_hiking = 'Yes',
  activities_wildlife_watching = 'Yes',
  description = $$Eureka Yurts and Cabins — two large western red cedar yurts (~475 sq ft each) on 32 wooded acres in Eureka Springs West AR (191 Bear Ridge Rd). Each yurt has a king bed, full kitchen, private bath with walk-in shower, climate control, private deck hot tub, and forest views; book direct via MotoPress on eurekayurts.com. Operator notes proximity to Leatherwood Wilderness bike trails and Beaver Lake; brand name references future cabin builds—only yurts are listed for booking as of May 2026.$$,
  unit_description = $$Pine View Yurt: private western cedar yurt with forest views, oversized deck and hot tub, open-floor-plan studio layout, king bed (sleeps 2), 475 sq ft.$$,
  notes = COALESCE(notes, '') || E'\n\nSite enrichment (May 2026): MotoPress listings on eurekayurts.com. Starting price $380 for 2 nights (+taxes/fees) per unit ≈ $190/night; 2-night minimum; check-in 3pm / check-out 10am. Contact: Reservations@EurekaYurts.com.',
  amenities_raw = 'Per operator: A/C & heat, king bed, full kitchen (induction cooktop, dishwasher, microwave/convection oven, refrigerator, coffee/toaster/blender), private bathroom w/ large walk-in shower, toiletries, iron, smart TV, Wi‑Fi, ceiling fan, private deck hot tub. Property: 32 acres, secluded forest setting.',
  discovery_source = 'web_research_eurekayurts_site_2026_05',
  date_updated = '2026-05-18',
  land_operator_category = 'private_commercial',
  rate_avg_retail_daily_rate = 190,
  rate_summer_weekday = 190,
  rate_summer_weekend = 190,
  rate_unit_rates_by_year = '{"2026":{"package":{"two_night_total":380,"implied_nightly":190,"note":"+taxes/fees; MotoPress starting price May 2026"}}}'::jsonb
WHERE id = 11879;

INSERT INTO public.all_glamping_properties (
  property_id,
  research_status, is_glamping_property, is_open,
  property_name, site_name, slug, property_type, unit_type,
  source, discovery_source, country, state, city,
  address, zip_code, lat, lon, url, phone_number,
  description, unit_description, notes,
  date_added, date_updated, land_operator_category,
  property_total_sites, quantity_of_units, unit_capacity, minimum_nights,
  operating_season_months,
  rate_avg_retail_daily_rate, rate_summer_weekday, rate_summer_weekend,
  rate_unit_rates_by_year,
  unit_private_bathroom, unit_shower, unit_kitchenette, unit_hot_tub,
  unit_air_conditioning, unit_wifi,
  setting_forest, activities_hiking, activities_wildlife_watching,
  amenities_raw
) VALUES (
  '19d8505d-8904-4c06-bdb0-2edbbb6392c2',
  'published', 'Yes', 'Yes',
  'Eureka Yurts and Cabins', 'White Oak Yurt',
  'eureka-yurts-and-cabins-eureka-springs-ar', 'Glamping Resort', 'Yurt',
  'Sage', 'web_research_eurekayurts_site_2026_05', 'United States', 'AR', 'Eureka Springs',
  '191 Bear Ridge Rd', '72631', 36.395, -93.782,
  'https://eurekayurts.com/accommodation/white-oak-yurt/',
  '+1-479-358-6485',
  $$Sibling site — Eureka Yurts and Cabins (Eureka Springs AR). See anchor row id 11879.$$,
  $$White Oak Yurt: cedar yurt opened Aug 2019; forest and holler views, large deck with private hot tub, king bed (sleeps 2), 475 sq ft, same amenity package as Pine View.$$,
  $$MotoPress room type id 1387. Starting price $380 for 2 nights (+taxes/fees) ≈ $190/night (May 2026).$$,
  '2026-05-18', '2026-05-18', 'private_commercial',
  2, 1, '2', '2', 'Year-round (see property row)',
  190, 190, 190,
  '{"2026":{"package":{"two_night_total":380,"implied_nightly":190,"note":"+taxes/fees; MotoPress starting price May 2026"}}}'::jsonb,
  'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes',
  'Yes', 'Yes', 'Yes',
  'Full kitchen, private bath, deck hot tub, Wi‑Fi, king bed.'
);
