-- Longitude 131°: site inventory from longitude131.com.au/stay (May 2026)
-- Sources: stay pages (Luxury Tent, Premium View, Dune Pavilion), AFAR Hotels We Love (Apr 2026)
-- Enriches anchor row id 12189; inserts 2 sibling category rows (16 tented pavilions total).

UPDATE public.all_glamping_properties SET
  property_id = 'a8c4e2b1-6f3d-4a9e-b2c1-7d8e4f5a6b0c'::uuid,
  site_name = 'Luxury Tent',
  slug = 'longitude-131-uluru-nt-au',
  property_type = 'Glamping Resort',
  unit_type = 'Safari Tent',
  source = 'Sage',
  discovery_source = 'web_research_longitude131_site_2026_05',
  country = 'Australia',
  state = 'NT',
  city = 'Yulara',
  address = 'Near Uluru-Kata Tjuta National Park, Northern Territory, Australia',
  zip_code = '0872',
  lat = -25.240,
  lon = 131.050,
  url = 'https://longitude131.com.au/stay/luxury-tent/',
  phone_number = '+61-2-9918-4355',
  research_status = 'published',
  is_glamping_property = 'Yes',
  is_open = 'Yes',
  property_total_sites = 16,
  quantity_of_units = 1,
  unit_capacity = '3',
  minimum_nights = '3',
  operating_season_months = 'Year-round',
  unit_private_bathroom = 'Yes',
  unit_shower = 'Yes',
  unit_kitchenette = 'No',
  unit_wifi = 'No',
  unit_air_conditioning = 'Yes',
  unit_campfires = 'Yes',
  unit_hot_tub = 'No',
  property_family_friendly = 'Yes',
  setting_desert = 'Yes',
  activities_stargazing = 'Yes',
  activities_wildlife_watching = 'Yes',
  land_operator_category = 'private_commercial',
  date_updated = '2026-05-21',
  description = $$Longitude 131° — Baillie/Beckons luxury tented camp in Australia's Red Centre (Uluru-Kata Tjuta), with sixteen tented pavilions among ancient dunes. Floor-to-ceiling glass, First Nations artworks, custom furnishings, balcony daybeds, feature fireplaces, and outdoor swags for sleeping under the stars. Children aged 10+ welcome. Three published room categories: Luxury Tent, Luxury Tent Premium View, and the two-bedroom Dune Pavilion (sole address with Uluru and Kata Tjuta on one horizon).$$,
  unit_description = $$Luxury Tent: canopied pavilion with floor-to-ceiling glass framing desert and Uluru views; king or twin beds; ensuite rain shower; balcony daybed; feature fireplace; 63m² indoor/outdoor living. Sleeps 1–2 in bedding (max 3 with rollaway).$$,
  notes = COALESCE(notes, '') || E'\n\nSite enrichment (May 2026): longitude131.com.au/stay. AFAR cites rates from ~USD $3,161/night (Apr 2026). Classic Longitude packages typically 3+ nights. Reservations via Beckons (+61 2 9918 4355).',
  amenities_raw = 'Floor-to-ceiling glass; king or twin beds; ensuite rain shower; balcony daybed; feature fireplace; First Nations artworks; outdoor swag/star bed; 63m² living space.',
  rate_avg_retail_daily_rate = 3161,
  rate_summer_weekday = 3161,
  rate_summer_weekend = 3161,
  rate_unit_rates_by_year = '{"2026":{"standard":{"base_nightly":3161,"currency":"USD","included_guests":2,"note":"AFAR Hotels We Love Apr 2026 from-rate; confirm AUD/nightly in Beckons booking engine"}}}'::jsonb
WHERE id = 12189;

INSERT INTO public.all_glamping_properties (
  property_id, research_status, is_glamping_property, is_open,
  property_name, site_name, slug, property_type, unit_type,
  source, discovery_source, country, state, city,
  address, zip_code, lat, lon, url, phone_number,
  description, unit_description, notes,
  date_added, date_updated, land_operator_category,
  property_total_sites, quantity_of_units, unit_capacity, minimum_nights,
  operating_season_months,
  rate_avg_retail_daily_rate, rate_summer_weekday, rate_summer_weekend,
  rate_unit_rates_by_year,
  unit_private_bathroom, unit_shower, unit_kitchenette, unit_wifi,
  unit_air_conditioning, unit_campfires, unit_hot_tub,
  property_family_friendly, setting_desert, activities_stargazing, activities_wildlife_watching,
  amenities_raw
) VALUES
(
  'a8c4e2b1-6f3d-4a9e-b2c1-7d8e4f5a6b0c'::uuid,
  'published', 'Yes', 'Yes',
  'Longitude 131°', 'Luxury Tent Premium View',
  'longitude-131-uluru-nt-au', 'Glamping Resort', 'Safari Tent',
  'Sage', 'web_research_longitude131_site_2026_05', 'Australia', 'NT', 'Yulara',
  'Near Uluru-Kata Tjuta National Park, Northern Territory, Australia', '0872',
  -25.240, 131.050,
  'https://longitude131.com.au/stay/luxury-tent-premium-view/',
  '+61-2-9918-4355',
  'Sibling site — Longitude 131° (Uluru-Kata Tjuta NT). See anchor row id 12189.',
  'Luxury Tent Premium View: uninterrupted Uluru sightlines from king bed to balcony; First Nations artworks; feature fireplace; ensuite rain shower; balcony daybed, armchairs, fireplace; 63m² indoor/outdoor living. Sleeps 1–2 (max 3 with rollaway).',
  'Premium View category on Beckons stay page; premium Uluru-facing tent inventory within 16 pavilions. ADR not published online — re-quote in Beckons engine.',
  '2026-05-21', '2026-05-21', 'private_commercial',
  16, 1, '3', '3', 'Year-round',
  NULL, NULL, NULL,
  NULL,
  'Yes', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No',
  'Yes', 'Yes', 'Yes', 'Yes',
  'Uninterrupted Uluru views; king bed; ensuite rain shower; balcony daybed; feature fireplace; floor-to-ceiling glass; First Nations art; 63m².'
),
(
  'a8c4e2b1-6f3d-4a9e-b2c1-7d8e4f5a6b0c'::uuid,
  'published', 'Yes', 'Yes',
  'Longitude 131°', 'Dune Pavilion',
  'longitude-131-uluru-nt-au', 'Glamping Resort', 'Villa',
  'Sage', 'web_research_longitude131_site_2026_05', 'Australia', 'NT', 'Yulara',
  'Near Uluru-Kata Tjuta National Park, Northern Territory, Australia', '0872',
  -25.240, 131.050,
  'https://longitude131.com.au/stay/dune-pavilion/',
  '+61-2-9918-4355',
  'Sibling site — Longitude 131° (Uluru-Kata Tjuta NT). See anchor row id 12189.',
  'Dune Pavilion: modern desert homestead — only Australian stay with Uluru and Kata Tjuta on the same horizon. Two king bedrooms each with ensuite (deep tub + rain shower); separate living/sleeping pavilions; EcoSmart fireplaces; outdoor lounges; private plunge pool; commissioned artworks; 153m² indoor/outdoor. Sleeps 2–4 (max 5 with rollaway).',
  'AFAR notes outdoor stargazing beds and plunge pool. Single Dune Pavilion inventory type (1 of 16 pavilions). ADR not published online — re-quote in Beckons engine.',
  '2026-05-21', '2026-05-21', 'private_commercial',
  16, 1, '5', '3', 'Year-round',
  NULL, NULL, NULL,
  NULL,
  'Yes', 'Yes', 'No', 'No', 'Yes', 'Yes', 'Yes',
  'Yes', 'Yes', 'Yes', 'Yes',
  'Two king bedrooms + ensuites; private plunge pool; deep bathtubs; rain showers; EcoSmart fireplaces; Uluru + Kata Tjuta views; outdoor lounges; 153m²; outdoor star beds (AFAR).'
);

UPDATE public.all_glamping_properties SET
  description = 'Sibling site — Longitude 131° (Uluru-Kata Tjuta NT). See anchor row id 12189.',
  url = 'https://longitude131.com.au/stay/',
  phone_number = '+61-2-9918-4355',
  country = 'Australia',
  state = 'NT',
  city = 'Yulara',
  address = 'Near Uluru-Kata Tjuta National Park, Northern Territory, Australia',
  zip_code = '0872',
  lat = -25.240,
  lon = 131.050,
  property_total_sites = 16,
  quantity_of_units = 1,
  is_glamping_property = 'Yes',
  is_open = 'Yes',
  property_type = 'Glamping Resort',
  slug = 'longitude-131-uluru-nt-au',
  land_operator_category = 'private_commercial',
  property_family_friendly = 'Yes',
  setting_desert = 'Yes',
  activities_stargazing = 'Yes',
  activities_wildlife_watching = 'Yes',
  minimum_nights = '3'
WHERE property_name = 'Longitude 131°' AND id <> 12189;
