-- Sal Salis: site inventory from salsalis.com.au + Newbook booking (May 2026)
-- Sources: accommodation page, make-a-booking Newbook (May 2026), AFAR Hotels We Love (Apr 2026)
-- Enriches anchor row id 12192; inserts 2 sibling tent category rows (15 tents total).

UPDATE public.all_glamping_properties SET
  property_id = '535f346b-0116-48d3-bb38-c1de022fb858'::uuid,
  site_name = 'King Wilderness Tent',
  slug = 'sal-salis-exmouth-wa-au',
  property_type = 'Glamping Resort',
  unit_type = 'Safari Tent',
  source = 'Sage',
  discovery_source = 'web_research_sal_salis_newbook_2026_05',
  country = 'Australia',
  state = 'WA',
  city = 'Exmouth',
  address = 'Cape Range National Park, Yardie Creek Road, North West Cape, Exmouth WA 6707',
  zip_code = '6707',
  lat = -21.930,
  lon = 113.980,
  url = 'https://www.salsalis.com.au/make-a-booking/',
  phone_number = '+61-8-9949-1776',
  research_status = 'published',
  is_glamping_property = 'Yes',
  is_open = 'Yes',
  property_total_sites = 15,
  quantity_of_units = 1,
  unit_capacity = '2',
  minimum_nights = '3',
  operating_season_months = 'Apr-Oct (peak); verify seasonal calendar',
  unit_private_bathroom = 'Yes',
  unit_shower = 'Yes',
  unit_kitchenette = 'No',
  unit_wifi = 'No',
  unit_air_conditioning = 'No',
  unit_campfires = 'No',
  unit_hot_tub = 'No',
  property_family_friendly = 'Yes',
  setting_coastal = 'Yes',
  setting_beach = 'Yes',
  setting_desert = 'Yes',
  activities_wildlife_watching = 'Yes',
  activities_hiking = 'Yes',
  activities_canoeing_kayaking = 'Yes',
  land_operator_category = 'private_commercial',
  date_updated = '2026-05-21',
  description = $$Sal Salis Ningaloo Reef — fifteen eco-luxury wilderness tents on the dunes of Cape Range National Park, steps from Ningaloo Reef (Exmouth, Western Australia). Pared-back safari tents with en suite bathrooms, hammock decks, and Indian Ocean views. All-inclusive: meals, open bar, guided snorkelling and gorge walks, Learmonth airport transfers, kayaks/SUP, and national park fees. Seasonal whale sharks and humpbacks (May–Oct). Operated by Journey Beyond.$$,
  unit_description = $$King Wilderness Tent: standard wilderness safari tent for 2 adults; comfortable bed, eco-ensuite bathroom, drinking water, daily housekeeping; private deck with hammock; ocean ~50 metres away. Newbook category "King Wilderness Tent".$$,
  notes = COALESCE(notes, '') || E'\n\nSite enrichment (May 2026): salsalis.com.au/make-a-booking (Newbook). Live sample from 08 Jun 2026 (3-night min, 2A): AUD 2,700/night (Everyday) or 2,980 (Fully Flex). FAQ lists AUD 1,580/night reference. AFAR from-rate ~USD 750 (Apr 2026). info@salsalis.com.au.',
  amenities_raw = 'King bed; eco-ensuite; hammock deck; ocean views; all-inclusive meals & bar; guided snorkelling & gorge walks; airport transfers; snorkel/kayak/SUP; national park fees; whale shark season.',
  rate_avg_retail_daily_rate = 1755,
  rate_summer_weekday = 1755,
  rate_summer_weekend = 1755,
  rate_unit_rates_by_year = '{"2026":{"sample_dates":"2026-06-08_arrival_3_night_min","currency":"AUD","guests":2,"categories":["King Wilderness Tent"],"everyday_aud":2700,"fully_flex_aud":2980,"usd_approx_everyday":1755,"usd_approx_fully_flex":1937,"faq_reference_aud":1580,"afar_from_rate_usd":750,"note":"Newbook May 2026; USD approx AUD×0.65"}}'::jsonb
WHERE id = 12192;

INSERT INTO public.all_glamping_properties (
  property_id, research_status, is_glamping_property, is_open,
  property_name, site_name, slug, property_type, unit_type,
  source, discovery_source, country, state, city,
  address, zip_code, lat, lon, url, phone_number,
  description, unit_description, notes,
  date_added, date_updated, land_operator_category,
  property_total_sites, quantity_of_units, unit_capacity, minimum_nights,
  operating_season_months,
  rate_avg_retail_daily_rate, rate_summer_weekday, rate_summer_weekend,
  rate_unit_rates_by_year,
  unit_private_bathroom, unit_shower, unit_kitchenette, unit_wifi,
  unit_air_conditioning, unit_campfires, unit_hot_tub,
  property_family_friendly, setting_coastal, setting_beach, setting_desert,
  activities_wildlife_watching, activities_hiking, activities_canoeing_kayaking,
  amenities_raw
) VALUES
(
  '535f346b-0116-48d3-bb38-c1de022fb858'::uuid,
  'published', 'Yes', 'Yes',
  'Sal Salis', 'King/Twin Wilderness Tent',
  'sal-salis-exmouth-wa-au', 'Glamping Resort', 'Safari Tent',
  'Sage', 'web_research_sal_salis_newbook_2026_05', 'Australia', 'WA', 'Exmouth',
  'Cape Range National Park, Yardie Creek Road, North West Cape, Exmouth WA 6707', '6707',
  -21.930, 113.980,
  'https://www.salsalis.com.au/make-a-booking/',
  '+61-8-9949-1776',
  'Sibling site — Sal Salis (Exmouth WA). See anchor row id 12192.',
  'King/Twin Wilderness Tent: wilderness safari tent with king or twin bed configuration for 2 adults; eco-ensuite, hammock deck, dunes-side setting on Ningaloo.',
  'Newbook category; re-quote in booking engine for travel dates (3-night minimum often applies).',
  '2026-05-21', '2026-05-21', 'private_commercial',
  15, 1, '2', '3', 'Apr-Oct (peak); verify seasonal calendar',
  NULL, NULL, NULL,
  '{"2026":{"note":"King/Twin Wilderness Tent — availability/pricing via Newbook; not sampled for Jun 2026 in scrape"}}'::jsonb,
  'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No',
  'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes',
  'King or twin beds; eco-ensuite; hammock deck; all-inclusive package; reef access.'
),
(
  '535f346b-0116-48d3-bb38-c1de022fb858'::uuid,
  'published', 'Yes', 'Yes',
  'Sal Salis', 'Honeymoon Wilderness Tent',
  'sal-salis-exmouth-wa-au', 'Glamping Resort', 'Safari Tent',
  'Sage', 'web_research_sal_salis_newbook_2026_05', 'Australia', 'WA', 'Exmouth',
  'Cape Range National Park, Yardie Creek Road, North West Cape, Exmouth WA 6707', '6707',
  -21.930, 113.980,
  'https://www.salsalis.com.au/make-a-booking/',
  '+61-8-9949-1776',
  'Sibling site — Sal Salis (Exmouth WA). See anchor row id 12192.',
  'Honeymoon Wilderness Tent: premium secluded tent with double hammock, bed canopy/net, and private beach outlook; most romantic site per Sal Salis accommodation page.',
  'Premium tier; re-quote ADR in Newbook for travel dates.',
  '2026-05-21', '2026-05-21', 'private_commercial',
  15, 1, '2', '3', 'Apr-Oct (peak); verify seasonal calendar',
  NULL, NULL, NULL,
  NULL,
  'Yes', 'Yes', 'No', 'No', 'No', 'No', 'No',
  'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes',
  'Double hammock; bed net; secluded; private beach outlook; all-inclusive; eco-ensuite.'
);

UPDATE public.all_glamping_properties SET
  description = 'Sibling site — Sal Salis (Exmouth WA). See anchor row id 12192.',
  url = 'https://www.salsalis.com.au/make-a-booking/',
  phone_number = '+61-8-9949-1776',
  country = 'Australia',
  state = 'WA',
  city = 'Exmouth',
  address = 'Cape Range National Park, Yardie Creek Road, North West Cape, Exmouth WA 6707',
  zip_code = '6707',
  lat = -21.930,
  lon = 113.980,
  property_total_sites = 15,
  quantity_of_units = 1,
  minimum_nights = '3',
  is_glamping_property = 'Yes',
  is_open = 'Yes',
  property_type = 'Glamping Resort',
  slug = 'sal-salis-exmouth-wa-au',
  land_operator_category = 'private_commercial',
  property_family_friendly = 'Yes',
  setting_coastal = 'Yes',
  setting_beach = 'Yes',
  setting_desert = 'Yes',
  activities_wildlife_watching = 'Yes',
  activities_hiking = 'Yes',
  activities_canoeing_kayaking = 'Yes',
  unit_private_bathroom = 'Yes',
  unit_shower = 'Yes',
  unit_wifi = 'No'
WHERE property_name = 'Sal Salis' AND id <> 12192;
