-- Nayara Tented Camp: site inventory from nayaratentedcamp.com/stay + LHW booking (May 2026)
-- Sources: stay page, booking step-2 (Aug 16–17, 2026, 2 adults USD), AFAR Hotels We Love (Apr 2026)
-- Enriches anchor row id 12191; inserts 4 sibling category rows (37 tents total on property).

UPDATE public.all_glamping_properties SET
  property_id = 'e339ee56-db9c-4f71-aaa2-3c5b9934a62f'::uuid,
  site_name = 'Nayara Tent',
  slug = 'nayara-tented-camp-la-fortuna-cr',
  property_type = 'Glamping Resort',
  unit_type = 'Safari Tent',
  source = 'Sage',
  discovery_source = 'web_research_nayara_site_booking_2026_05',
  country = 'Costa Rica',
  state = 'Alajuela',
  city = 'La Fortuna',
  address = 'Arenal Natura Ecological Park, La Fortuna, Alajuela, Costa Rica',
  zip_code = '21007',
  lat = 10.470,
  lon = -84.700,
  url = 'https://nayaratentedcamp.com/stay/#/',
  phone_number = '+506-2479-1600',
  research_status = 'published',
  is_glamping_property = 'Yes',
  is_open = 'Yes',
  property_total_sites = 37,
  quantity_of_units = 1,
  unit_capacity = '4',
  minimum_nights = '1',
  operating_season_months = 'Year-round',
  unit_private_bathroom = 'Yes',
  unit_shower = 'Yes',
  unit_kitchenette = 'No',
  unit_wifi = 'Yes',
  unit_air_conditioning = 'Yes',
  unit_campfires = 'No',
  unit_hot_tub = 'Yes',
  property_family_friendly = 'Yes',
  setting_forest = 'Yes',
  setting_hot_spring = 'Yes',
  setting_mountainous = 'Yes',
  activities_wildlife_watching = 'Yes',
  activities_hiking = 'Yes',
  land_operator_category = 'private_commercial',
  date_updated = '2026-05-21',
  description = $$Nayara Tented Camp — 37 safari-style tents on a 62-acre rewilded rainforest estate in Costa Rica's Arenal region, facing the active Arenal volcano. Hot-spring-fed private plunge pools, king beds, deep soaking tubs, indoor/outdoor showers, and butler service; sister property to Nayara Gardens and Nayara Springs on the same estate. Leading Hotels of the World. Categories: Nayara Tent, Family Tent, Grand Tent, and two Private Residences (Casa Paloma, Casa Dana).$$,
  unit_description = $$Nayara Tent: stilted rainforest pavilion maximizing volcano views; king bed plus two daybeds (sleeps 4 / 2 adults + 2 children); 157.9 m² (1,700 sq ft); private plunge pool fed by mineral hot springs; outdoor shower; outdoor living and sitting space; mini bar; exquisitely appointed master suite.$$,
  notes = COALESCE(notes, '') || E'\n\nSite enrichment (May 2026): nayaratentedcamp.com/stay + LHW booking. Live sample Aug 16–17, 2026 (2 adults, USD excl. taxes): $1,392 / $1,450 / $1,465 per night. AFAR from-rate ~$1,221 (Apr 2026). reservations@nayararesorts.com; +506 2479 1600.',
  amenities_raw = 'King bed; 2 daybeds; sleeps 4; 1,700 sq ft; hot-spring plunge pool; outdoor shower; outdoor living area; mini bar; volcano views; butler service.',
  rate_avg_retail_daily_rate = 1392,
  rate_summer_weekday = 1392,
  rate_summer_weekend = 1450,
  rate_unit_rates_by_year = '{"2026":{"sample_dates":"2026-08-16_to_2026-08-17","currency":"USD","guests":2,"excluding_taxes":true,"tiers":[{"nightly":1392,"note":"Leaders Club / lowest displayed"},{"nightly":1450},{"nightly":1465}],"afar_from_rate":1221,"note":"LHW booking engine May 2026; AFAR Hotels We Love Apr 2026 from-rate"}}'::jsonb
WHERE id = 12191;

INSERT INTO public.all_glamping_properties (
  property_id, research_status, is_glamping_property, is_open,
  property_name, site_name, slug, property_type, unit_type,
  source, discovery_source, country, state, city,
  address, zip_code, lat, lon, url, phone_number,
  description, unit_description, notes,
  date_added, date_updated, land_operator_category,
  property_total_sites, quantity_of_units, unit_capacity, minimum_nights,
  operating_season_months,
  rate_avg_retail_daily_rate, rate_summer_weekday, rate_summer_weekend,
  rate_unit_rates_by_year,
  unit_private_bathroom, unit_shower, unit_kitchenette, unit_wifi,
  unit_air_conditioning, unit_campfires, unit_hot_tub,
  property_family_friendly, setting_forest, setting_hot_spring, setting_mountainous,
  activities_wildlife_watching, activities_hiking, amenities_raw
) VALUES
(
  'e339ee56-db9c-4f71-aaa2-3c5b9934a62f'::uuid,
  'published', 'Yes', 'Yes',
  'Nayara Tented Camp', 'Family Tent',
  'nayara-tented-camp-la-fortuna-cr', 'Glamping Resort', 'Safari Tent',
  'Sage', 'web_research_nayara_site_booking_2026_05', 'Costa Rica', 'Alajuela', 'La Fortuna',
  'Arenal Natura Ecological Park, La Fortuna, Alajuela, Costa Rica', '21007',
  10.470, -84.700,
  'https://nayaratentedcamp.com/stay/#/',
  '+506-2479-1600',
  'Sibling site — Nayara Tented Camp (La Fortuna CR). See anchor row id 12191.',
  'Family Tent: two connected tents (king bed tent + two-queen tent) with shared outdoor living space and private plunge pool; sleeps 6; 265.7 m² (2,860 sq ft); max 6 adults or couple with 2 children + baby crib.',
  'LHW booking sample Aug 16–17, 2026: $2,394 / $2,505 / $2,520 USD per night (2 adults, excl. taxes).',
  '2026-05-21', '2026-05-21', 'private_commercial',
  37, 1, '6', '1', 'Year-round',
  2394, 2394, 2505,
  '{"2026":{"sample_dates":"2026-08-16_to_2026-08-17","currency":"USD","guests":2,"excluding_taxes":true,"tiers":[{"nightly":2394},{"nightly":2505},{"nightly":2520}]}}'::jsonb,
  'Yes', 'Yes', 'No', 'Yes', 'Yes', 'No', 'Yes',
  'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes',
  '2 tents (king + 2 queens); shared plunge pool; outdoor living; 2,860 sq ft; sleeps 6; hot springs; volcano views.'
),
(
  'e339ee56-db9c-4f71-aaa2-3c5b9934a62f'::uuid,
  'published', 'Yes', 'Yes',
  'Nayara Tented Camp', 'Grand Tent',
  'nayara-tented-camp-la-fortuna-cr', 'Glamping Resort', 'Villa',
  'Sage', 'web_research_nayara_site_booking_2026_05', 'Costa Rica', 'Alajuela', 'La Fortuna',
  'Arenal Natura Ecological Park, La Fortuna, Alajuela, Costa Rica', '21007',
  10.470, -84.700,
  'https://nayaratentedcamp.com/stay/#/',
  '+506-2479-1600',
  'Sibling site — Nayara Tented Camp (La Fortuna CR). See anchor row id 12191.',
  'Grand Tent: primary tent with king bed and two daybeds plus ground-level room with two queen beds; fully equipped kitchen, dining, indoor/outdoor lounges; oversized infinity pool with Arenal volcano panorama. Sleeps 4 adults + 2 children or 2 adults + 4 children.',
  'Not listed in LHW online booking for sampled Aug 2026 dates — contact reservations for ADR and availability.',
  '2026-05-21', '2026-05-21', 'private_commercial',
  37, 1, '6', '1', 'Year-round',
  NULL, NULL, NULL, NULL,
  'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'Yes',
  'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes',
  'King + daybeds; 2 queen ground-level room; full kitchen; infinity pool; indoor/outdoor lounge; volcano views.'
),
(
  'e339ee56-db9c-4f71-aaa2-3c5b9934a62f'::uuid,
  'published', 'Yes', 'Yes',
  'Nayara Tented Camp', 'Casa Paloma',
  'nayara-tented-camp-la-fortuna-cr', 'Glamping Resort', 'Villa',
  'Sage', 'web_research_nayara_site_booking_2026_05', 'Costa Rica', 'Alajuela', 'La Fortuna',
  'Arenal Natura Ecological Park, La Fortuna, Alajuela, Costa Rica', '21007',
  10.470, -84.700,
  'https://nayaratentedcamp.com/stay/#/',
  '+506-2479-1600',
  'Sibling site — Nayara Tented Camp (La Fortuna CR). See anchor row id 12191.',
  'Casa Paloma Private Residence: two family-tent units sharing a villa — 2 king beds and 4 queen beds total; full kitchen, living/dining, fire pit, oversized hot-spring infinity pool, volcano views; personal concierge. Up to 12 adults or two families with children (2 baby cribs).',
  'One of two on-property Private Residences (with Casa Dana). Book via reservations — not in LHW online engine for sampled dates.',
  '2026-05-21', '2026-05-21', 'private_commercial',
  37, 1, '12', '1', 'Year-round',
  NULL, NULL, NULL, NULL,
  'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes',
  'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes',
  'Private residence; 2 family tents; 2 kings + 4 queens; full kitchen; fire pit; infinity pool; concierge; volcano views.'
),
(
  'e339ee56-db9c-4f71-aaa2-3c5b9934a62f'::uuid,
  'published', 'Yes', 'Yes',
  'Nayara Tented Camp', 'Casa Dana',
  'nayara-tented-camp-la-fortuna-cr', 'Glamping Resort', 'Villa',
  'Sage', 'web_research_nayara_site_booking_2026_05', 'Costa Rica', 'Alajuela', 'La Fortuna',
  'Arenal Natura Ecological Park, La Fortuna, Alajuela, Costa Rica', '21007',
  10.470, -84.700,
  'https://nayaratentedcamp.com/stay/#/',
  '+506-2479-1600',
  'Sibling site — Nayara Tented Camp (La Fortuna CR). See anchor row id 12191.',
  'Casa Dana Private Residence: two family-tent units sharing a villa — 2 king beds and 4 queen beds total; full kitchen, living/dining, fire pit, oversized hot-spring infinity pool, volcano views; personal concierge. Up to 12 adults or two families with children (2 baby cribs).',
  'One of two on-property Private Residences (with Casa Paloma). Book via reservations — not in LHW online engine for sampled dates.',
  '2026-05-21', '2026-05-21', 'private_commercial',
  37, 1, '12', '1', 'Year-round',
  NULL, NULL, NULL, NULL,
  'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes',
  'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes',
  'Private residence; 2 family tents; 2 kings + 4 queens; full kitchen; fire pit; infinity pool; concierge; volcano views.'
);

UPDATE public.all_glamping_properties SET
  description = 'Sibling site — Nayara Tented Camp (La Fortuna CR). See anchor row id 12191.',
  url = 'https://nayaratentedcamp.com/stay/#/',
  phone_number = '+506-2479-1600',
  country = 'Costa Rica',
  state = 'Alajuela',
  city = 'La Fortuna',
  address = 'Arenal Natura Ecological Park, La Fortuna, Alajuela, Costa Rica',
  zip_code = '21007',
  lat = 10.470,
  lon = -84.700,
  property_total_sites = 37,
  quantity_of_units = 1,
  is_glamping_property = 'Yes',
  is_open = 'Yes',
  property_type = 'Glamping Resort',
  slug = 'nayara-tented-camp-la-fortuna-cr',
  land_operator_category = 'private_commercial',
  property_family_friendly = 'Yes',
  setting_forest = 'Yes',
  setting_hot_spring = 'Yes',
  setting_mountainous = 'Yes',
  activities_wildlife_watching = 'Yes',
  activities_hiking = 'Yes',
  unit_private_bathroom = 'Yes',
  unit_shower = 'Yes',
  unit_wifi = 'Yes',
  unit_air_conditioning = 'Yes',
  unit_hot_tub = 'Yes'
WHERE property_name = 'Nayara Tented Camp' AND id <> 12191;
