-- Spring Ranch Campground (Fairfield NE): property enrichment + 5 bookable stay rows.
-- Sources: springranchcampground.com/the-stays/, unit pages, ReservationKey 88259 (May 2026).

UPDATE public.all_glamping_properties SET
  property_name = 'Spring Ranch Campground',
  site_name = 'The Great Medicine Road Yurt',
  url = 'https://v2.reservationkey.com/88259/reserve/c',
  city = 'Fairfield',
  state = 'NE',
  country = 'United States',
  address = '30551 Road D',
  zip_code = '68938',
  lat = 40.432,
  lon = -98.146,
  phone_number = '+1-402-726-2282',
  is_open = 'Yes',
  research_status = 'published',
  is_glamping_property = 'Yes',
  property_type = 'Glamping Resort',
  unit_type = 'Yurt',
  property_total_sites = 5,
  quantity_of_units = 1,
  unit_capacity = '6',
  minimum_nights = '1',
  operating_season_months = 'Year-round (verify seasonal closures on operator calendar)',
  unit_private_bathroom = 'Yes',
  unit_shower = 'Yes',
  unit_kitchenette = 'Yes',
  unit_air_conditioning = 'Yes',
  unit_campfires = 'Yes',
  unit_wifi = 'No',
  unit_pets = 'Yes',
  property_family_friendly = 'Yes',
  setting_forest = 'Yes',
  setting_lake = 'Yes',
  activities_swimming = 'Yes',
  activities_fishing = 'Yes',
  activities_hiking = 'Yes',
  description = $$Spring Ranch Campground — private glamping ranch on ~240 acres along the Little Blue River near Fairfield NE (30551 Road D). Five bookable glamping stays on ReservationKey: two luxury yurts, two Conestoga-style covered wagons with en-suite baths, and a lofted cabin. Property amenities include private pond (swimming, dock fishing, water trampoline), creek, zipline, hiking, and optional chef-prepared meals; no on-site Wi‑Fi (available a short walk uphill). Entire-property buyouts available for large groups.$$,
  unit_description = $$The Great Medicine Road Yurt: luxury yurt with queen bed, double bed, and twin lofted beds (sleeps 6+ adults). Full kitchen with full-size fridge; private en-suite bath; A/C & heat; patio with fire pit, grill, and picnic table; in-room coffee/tea and drinking water. Optional tent/cot add-ons for kids under the stars.$$,
  notes = COALESCE(notes, '') || E'\n\nSite enrichment (May 2026): Marketing https://www.springranchcampground.com/the-stays/ + unit FAQs. Booking: https://v2.reservationkey.com/88259/reserve/c. Standard rate $375/night up to 6 guests (+$25/person/night extra per operator). Check-in 3pm / check-out 11am.',
  amenities_raw = 'Full kitchen, private bath w/ shower, A/C & heat, USB outlets, fire pit w/ grill, picnic table, linens/toiletries provided, s''mores kit, no property Wi‑Fi.',
  discovery_source = 'web_research_spring_ranch_site_rk_2026_05',
  date_updated = '2026-05-18',
  land_operator_category = 'private_commercial',
  rate_avg_retail_daily_rate = 375,
  rate_summer_weekday = 375,
  rate_summer_weekend = 375,
  rate_unit_rates_by_year = '{"2026":{"standard":{"base_nightly":375,"included_guests":6,"extra_guest":25,"note":"Operator published rate; +taxes/fees"}}}'::jsonb
WHERE id = 11871;

INSERT INTO public.all_glamping_properties (
  property_id,
  research_status, is_glamping_property, is_open,
  property_name, site_name, slug, property_type, unit_type,
  source, discovery_source, country, state, city,
  address, zip_code, lat, lon, url, phone_number,
  description, unit_description, notes,
  date_added, date_updated, land_operator_category,
  property_total_sites, quantity_of_units, unit_capacity, minimum_nights,
  rate_avg_retail_daily_rate, rate_summer_weekday, rate_summer_weekend,
  rate_unit_rates_by_year,
  unit_private_bathroom, unit_shower, unit_kitchenette,
  unit_air_conditioning, unit_campfires, unit_wifi, unit_pets,
  setting_forest, setting_lake, activities_swimming, activities_fishing, activities_hiking,
  amenities_raw
) VALUES
(
  'a2ebd9fb-e929-43ad-b8b6-127de6770c42',
  'published', 'Yes', 'Yes',
  'Spring Ranch Campground', 'The Great Migration Yurt',
  'spring-ranch-campground-fairfield-ne', 'Glamping Resort', 'Yurt',
  'Sage', 'web_research_spring_ranch_site_rk_2026_05', 'United States', 'NE', 'Fairfield',
  '30551 Road D', '68938', 40.432, -98.146,
  'https://v2.reservationkey.com/88259/reserve/c',
  '+1-402-726-2282',
  $$Sibling site — Spring Ranch Campground (Fairfield NE). See anchor row id 11871.$$,
  $$The Great Migration Yurt: rustic-luxe yurt with queen bed and two lofted queen mattress pads (sleeps 4 adults). Full kitchen w/ full-size fridge; private en-suite bath; A/C & heat; handmade canoe ceiling light; patio/fire pit amenities per property standards.$$,
  $$Marketing: /camping-in-nebraska-great-migration-yurt/. Standard rate $375/night up to 4 guests (+$25/person/night extra).$$,
  '2026-05-18', '2026-05-18', 'private_commercial',
  5, 1, '4', '1',
  375, 375, 375,
  '{"2026":{"standard":{"base_nightly":375,"included_guests":4,"extra_guest":25}}}'::jsonb,
  'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'Yes',
  'Yes', 'Yes', 'Yes', 'Yes', 'Yes',
  'Full kitchen, private bath, A/C & heat, sleeps 4 adults.'
),
(
  'a2ebd9fb-e929-43ad-b8b6-127de6770c42',
  'published', 'Yes', 'Yes',
  'Spring Ranch Campground', 'The Wagoneer Wagon',
  'spring-ranch-campground-fairfield-ne', 'Glamping Resort', 'Covered Wagon',
  'Sage', 'web_research_spring_ranch_site_rk_2026_05', 'United States', 'NE', 'Fairfield',
  '30551 Road D', '68938', 40.432, -98.146,
  'https://v2.reservationkey.com/88259/reserve/c',
  '+1-402-726-2282',
  $$Sibling site — Spring Ranch Campground (Fairfield NE).$$,
  $$The Wagoneer Wagon: Conestoga-style wagon with queen bed, wagon-wheel table & chairs, private en-suite shower bath, mini fridge, microwave, Keurig, A/C & heat, USB outlets. Outdoor grilling utensils in exterior box; private patio w/ Adirondack chairs, fire pit & grill. Linens & toiletries provided.$$,
  $$ReservationKey unit: Wagoneer Wagon. Standard rate $250/night for 2 guests (+$25/person/night extra). Sleeps 2 adults.$$,
  '2026-05-18', '2026-05-18', 'private_commercial',
  5, 1, '2', '1',
  250, 250, 250,
  '{"2026":{"standard":{"base_nightly":250,"included_guests":2,"extra_guest":25}}}'::jsonb,
  'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'Yes',
  'Yes', 'Yes', 'Yes', 'Yes', 'Yes',
  'Queen bed; en-suite bath; mini kitchen; fire pit & grill; s''mores kit.'
),
(
  'a2ebd9fb-e929-43ad-b8b6-127de6770c42',
  'published', 'Yes', 'Yes',
  'Spring Ranch Campground', 'The Pawnee Wagon',
  'spring-ranch-campground-fairfield-ne', 'Glamping Resort', 'Covered Wagon',
  'Sage', 'web_research_spring_ranch_site_rk_2026_05', 'United States', 'NE', 'Fairfield',
  '30551 Road D', '68938', 40.432, -98.146,
  'https://v2.reservationkey.com/88259/reserve/c',
  '+1-402-726-2282',
  $$Sibling site — Spring Ranch Campground (Fairfield NE). Listed as "Pioneer Wagon" on /the-stays/; book as Pawnee Wagon on ReservationKey.$$,
  $$The Pawnee Wagon: covered wagon with queen bed, bunk beds, wagon-wheel table & chairs, private en-suite shower bath, mini fridge, microwave, Keurig, A/C & heat. Outdoor grill box; patio w/ Adirondack chairs & fire pit. Bring own plates/utensils for dining.$$,
  $$ReservationKey: Pawnee Wagon. Standard rate $250/night for 2 guests (+$25/person/night). Sleeps 4 (queen + bunk).$$,
  '2026-05-18', '2026-05-18', 'private_commercial',
  5, 1, '4', '1',
  250, 250, 250,
  '{"2026":{"standard":{"base_nightly":250,"included_guests":2,"extra_guest":25}}}'::jsonb,
  'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'Yes',
  'Yes', 'Yes', 'Yes', 'Yes', 'Yes',
  'Queen + bunk beds; en-suite bath; mini kitchen; fire pit.'
),
(
  'a2ebd9fb-e929-43ad-b8b6-127de6770c42',
  'published', 'Yes', 'Yes',
  'Spring Ranch Campground', 'The Cabin',
  'spring-ranch-campground-fairfield-ne', 'Glamping Resort', 'Cabin',
  'Sage', 'web_research_spring_ranch_site_rk_2026_05', 'United States', 'NE', 'Fairfield',
  '30551 Road D', '68938', 40.432, -98.146,
  'https://v2.reservationkey.com/88259/reserve/c',
  '+1-402-726-2282',
  $$Sibling site — Spring Ranch Campground (Fairfield NE).$$,
  $$The Cabin: lofted queen bed (guests bring sleeping bags/bedding for loft), pull-out sleeper sofa & downstairs sitting area, kitchenette w/ gas stove & sink, microwave, Keurig, private bath w/ shower, A/C & heat.$$,
  $$ReservationKey: Cabin. Standard rate $250/night for 2 guests (+$25/person/night extra). Marketing page lists sleeps 4.$$,
  '2026-05-18', '2026-05-18', 'private_commercial',
  5, 1, '4', '1',
  250, 250, 250,
  '{"2026":{"standard":{"base_nightly":250,"included_guests":2,"extra_guest":25}}}'::jsonb,
  'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'Yes',
  'Yes', 'Yes', 'Yes', 'Yes', 'Yes',
  'Loft queen + sleeper sofa; gas kitchenette; private bath.'
);
