-- Serenity Ridge (Mill Spring NC): property enrichment + 8 named on-site lodging rows.
-- Sources: serenityridgenc.com/lodging and per-unit pages (May 2026); Houfy host
--   serenity-ridgecabins nightly ranges (excl. fees/taxes) for rate anchors.

UPDATE public.all_glamping_properties SET
  property_name = 'Serenity Ridge',
  site_name = 'Glamping Yurt',
  slug = 'serenity-ridge-mill-spring-nc',
  url = 'https://www.serenityridgenc.com/glamping-yurt',
  address = '444 Delind Drive',
  city = 'Mill Spring',
  state = 'NC',
  zip_code = '28756',
  country = 'United States',
  lat = 35.3785,
  lon = -82.298,
  phone_number = '+1-828-333-7185',
  is_open = 'Yes',
  research_status = 'published',
  is_glamping_property = 'Yes',
  property_type = 'Glamping Resort',
  unit_type = 'Yurt',
  property_total_sites = 8,
  quantity_of_units = 1,
  unit_capacity = '2',
  minimum_nights = '2',
  operating_season_months = 'Year-round on-site lodging (wedding-season peak; verify OwnerRez calendar)',
  unit_private_bathroom = 'Yes',
  unit_shower = 'Yes',
  unit_bathtub = 'Yes',
  unit_kitchenette = 'Yes',
  unit_wifi = 'Yes',
  unit_hot_tub = 'No',
  unit_campfires = 'Yes',
  unit_pets = 'Yes',
  property_family_friendly = 'Yes',
  property_food_on_site = 'Yes',
  setting_forest = 'Yes',
  setting_mountainous = 'Yes',
  setting_lake = 'Yes',
  activities_hiking = 'Yes',
  activities_wildlife_watching = 'Yes',
  activities_stargazing = 'Yes',
  description = $$Serenity Ridge — Blue Ridge foothills wedding venue and on-site lodging on ~25 private acres in Mill Spring NC (444 Delind Drive), ~3 mi from Lake Lure. Eight rentable units sleep up to 36 guests: six wooded tiny-home cabins (A–F), Hilltop House, and a luxury glamping yurt. Shared Fire Pavilion, hiking trails, creek/spring, and pet-friendly grounds.$$,
  unit_description = $$Glamping Yurt: king bed under skylight; full kitchen; dining and living area with DirecTV + Smart TV; spa bathroom with double vanity, rain shower, and soaking tub. Romantic couples stay near the celebration spaces.$$,
  notes = COALESCE(notes, '') || E'\n\nSite enrichment (May 2026): serenityridgenc.com/lodging + unit pages. Houfy serenity-ridgecabins lists yurt $215–$331/night excl. fees/taxes (used as summer rate anchors). Booking via OwnerRez widget on operator site.',
  amenities_raw = 'King bed, skylight, full kitchen, spa bath (soaking tub, rain shower, double vanity), DirecTV, Smart TV; property Fire Pavilion, trails, pet-friendly.',
  discovery_source = 'web_research_serenityridgenc_2026_05',
  date_updated = '2026-05-18',
  land_operator_category = 'private_commercial',
  rate_avg_retail_daily_rate = 273,
  rate_summer_weekday = 215,
  rate_summer_weekend = 331,
  rate_unit_rates_by_year = '{"2026":{"summer":{"weekday":215,"weekend":331,"source":"houfy.com host serenity-ridgecabins range excl fees"}}}'::jsonb
WHERE id = 11582;

INSERT INTO public.all_glamping_properties (
  property_id,
  research_status, is_glamping_property, is_open,
  property_name, site_name, slug, property_type, unit_type,
  source, discovery_source, country, state, city,
  address, zip_code, lat, lon, url, phone_number,
  description, unit_description, notes,
  date_added, date_updated, land_operator_category,
  property_total_sites, quantity_of_units, unit_capacity,
  rate_avg_retail_daily_rate, rate_summer_weekday, rate_summer_weekend,
  rate_unit_rates_by_year,
  unit_private_bathroom, unit_shower, unit_kitchenette, unit_hot_tub,
  unit_wifi, unit_campfires, unit_pets, unit_charcoal_grill,
  property_family_friendly, property_food_on_site,
  setting_forest, setting_mountainous, setting_lake,
  activities_hiking, activities_wildlife_watching, activities_stargazing,
  amenities_raw
) VALUES
(
  '7aaa5233-9e19-49fd-8568-a7e4f9410b50',
  'published', 'Yes', 'Yes',
  'Serenity Ridge', 'Hilltop House',
  'serenity-ridge-mill-spring-nc', 'Glamping Resort', 'Lodge',
  'Sage', 'web_research_serenityridgenc_2026_05', 'United States', 'NC', 'Mill Spring',
  '444 Delind Drive', '28756', 35.3785, -82.298,
  'https://www.serenityridgenc.com/hilltop-house',
  '+1-828-333-7185',
  $$Sibling site — Serenity Ridge (Mill Spring NC). See anchor Glamping Yurt row id 11582.$$,
  $$Hilltop House: sleeps 10 in 4 bedrooms (main king + ensuite; guest king; two rooms with queen + twin). 2.5 baths; full kitchen; living room with gas fireplace; Smart TVs; mountain-view hot tub; XL wrap porch; screened porch with gas grill; washer/dryer; outdoor gas fire pit.$$,
  $$Houfy $573–$882/night excl. fees/taxes. Best for bridal party / close family per operator lodging page.$$,
  '2026-05-18', '2026-05-18', 'private_commercial',
  8, 1, '10', 728, 573, 882,
  '{"2026":{"summer":{"weekday":573,"weekend":882,"source":"houfy.com"}}}'::jsonb,
  'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes',
  'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes',
  'Hot tub, gas fireplace, gas fire pit, porch grill, 4BR/2.5BA, WiFi, Smart TVs, washer/dryer.'
),
(
  '7aaa5233-9e19-49fd-8568-a7e4f9410b50',
  'published', 'Yes', 'Yes',
  'Serenity Ridge', 'Cabin A',
  'serenity-ridge-mill-spring-nc', 'Glamping Resort', 'Tiny Home',
  'Sage', 'web_research_serenityridgenc_2026_05', 'United States', 'NC', 'Mill Spring',
  '444 Delind Drive', '28756', 35.3785, -82.298,
  'https://www.serenityridgenc.com/cabin-a',
  '+1-828-333-7185',
  $$Sibling site — Serenity Ridge (Mill Spring NC).$$,
  $$Cabin A: tiny home in the woods; sleeps 4 (main queen + loft queen). Full kitchen; living area with electric fireplace; DirecTV + Smart TV; private hot tub; screened porch; charcoal grill; washer/dryer in bedroom; drip coffee maker.$$,
  $$Houfy $143–$220/night excl. fees/taxes. Walk-in shower bath.$$,
  '2026-05-18', '2026-05-18', 'private_commercial',
  8, 1, '4', 182, 143, 220,
  '{"2026":{"summer":{"weekday":143,"weekend":220,"source":"houfy.com"}}}'::jsonb,
  'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes',
  'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes',
  'Private hot tub, screened porch, electric fireplace, WiFi, DirecTV, W/D.'
),
(
  '7aaa5233-9e19-49fd-8568-a7e4f9410b50',
  'published', 'Yes', 'Yes',
  'Serenity Ridge', 'Cabin B',
  'serenity-ridge-mill-spring-nc', 'Glamping Resort', 'Tiny Home',
  'Sage', 'web_research_serenityridgenc_2026_05', 'United States', 'NC', 'Mill Spring',
  '444 Delind Drive', '28756', 35.3785, -82.298,
  'https://www.serenityridgenc.com/cabin-b',
  '+1-828-333-7185',
  $$Sibling site — Serenity Ridge (Mill Spring NC).$$,
  $$Cabin B: wooded tiny home; sleeps 4 (main queen + loft queen). Full kitchen; electric fireplace; DirecTV + Smart TV; private hot tub; screened porch entry; washer/dryer; drip coffee maker.$$,
  $$Houfy $143–$220/night. Tub bath.$$,
  '2026-05-18', '2026-05-18', 'private_commercial',
  8, 1, '4', 182, 143, 220,
  '{"2026":{"summer":{"weekday":143,"weekend":220}}}'::jsonb,
  'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes',
  'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes',
  'Hot tub, screened porch, fireplace, WiFi, DirecTV, W/D.'
),
(
  '7aaa5233-9e19-49fd-8568-a7e4f9410b50',
  'published', 'Yes', 'Yes',
  'Serenity Ridge', 'Cabin C',
  'serenity-ridge-mill-spring-nc', 'Glamping Resort', 'Tiny Home',
  'Sage', 'web_research_serenityridgenc_2026_05', 'United States', 'NC', 'Mill Spring',
  '444 Delind Drive', '28756', 35.3785, -82.298,
  'https://www.serenityridgenc.com/cabin-c',
  '+1-828-333-7185',
  $$Sibling site — Serenity Ridge (Mill Spring NC).$$,
  $$Cabin C: hilltop tiny home; sleeps 4 (main queen + loft queen). Full kitchen; electric fireplace; DirecTV + Smart TV; private outdoor hot tub; screened porch; charcoal grill; washer/dryer.$$,
  $$Houfy $143–$220/night. Tub bath.$$,
  '2026-05-18', '2026-05-18', 'private_commercial',
  8, 1, '4', 182, 143, 220,
  '{"2026":{"summer":{"weekday":143,"weekend":220}}}'::jsonb,
  'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes',
  'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes',
  'Hilltop setting; hot tub, screened porch, charcoal grill, W/D.'
),
(
  '7aaa5233-9e19-49fd-8568-a7e4f9410b50',
  'published', 'Yes', 'Yes',
  'Serenity Ridge', 'Cabin D',
  'serenity-ridge-mill-spring-nc', 'Glamping Resort', 'Tiny Home',
  'Sage', 'web_research_serenityridgenc_2026_05', 'United States', 'NC', 'Mill Spring',
  '444 Delind Drive', '28756', 35.3785, -82.298,
  'https://www.serenityridgenc.com/cabin-d',
  '+1-828-333-7185',
  $$Sibling site — Serenity Ridge (Mill Spring NC).$$,
  $$Cabin D: wooded tiny home; sleeps 4 (main queen + loft queen). Full kitchen; electric fireplace; DirecTV + Smart TV; private hot tub; screened porch; charcoal grill; washer/dryer. Walk-in shower bath.$$,
  $$Houfy $143–$220/night.$$,
  '2026-05-18', '2026-05-18', 'private_commercial',
  8, 1, '4', 182, 143, 220,
  '{"2026":{"summer":{"weekday":143,"weekend":220}}}'::jsonb,
  'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes',
  'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes',
  'Wooded cabin; hot tub, screened porch, W/D.'
),
(
  '7aaa5233-9e19-49fd-8568-a7e4f9410b50',
  'published', 'Yes', 'Yes',
  'Serenity Ridge', 'Cabin E',
  'serenity-ridge-mill-spring-nc', 'Glamping Resort', 'Tiny Home',
  'Sage', 'web_research_serenityridgenc_2026_05', 'United States', 'NC', 'Mill Spring',
  '444 Delind Drive', '28756', 35.3785, -82.298,
  'https://www.serenityridgenc.com/cabin-e',
  '+1-828-333-7185',
  $$Sibling site — Serenity Ridge (Mill Spring NC).$$,
  $$Cabin E: quiet-hill tiny home; sleeps 4 (main queen + loft queen). Full kitchen; electric fireplace; DirecTV + Smart TV; private hot tub; screened porch; charcoal grill; washer/dryer. Walk-in shower.$$,
  $$Houfy $143–$220/night. Operator notes ideal for families.$$,
  '2026-05-18', '2026-05-18', 'private_commercial',
  8, 1, '4', 182, 143, 220,
  '{"2026":{"summer":{"weekday":143,"weekend":220}}}'::jsonb,
  'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes',
  'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes',
  'Family-friendly cabin; hot tub, screened porch, grill, W/D.'
),
(
  '7aaa5233-9e19-49fd-8568-a7e4f9410b50',
  'published', 'Yes', 'Yes',
  'Serenity Ridge', 'Cabin F',
  'serenity-ridge-mill-spring-nc', 'Glamping Resort', 'Tiny Home',
  'Sage', 'web_research_serenityridgenc_2026_05', 'United States', 'NC', 'Mill Spring',
  '444 Delind Drive', '28756', 35.3785, -82.298,
  'https://www.serenityridgenc.com/cabin-f',
  '+1-828-333-7185',
  $$Sibling site — Serenity Ridge (Mill Spring NC).$$,
  $$Cabin F: tiny home among the trees; sleeps 4 (main queen + loft queen). Full kitchen; electric fireplace; DirecTV + Smart TV; private hot tub; screened porch; charcoal grill; washer/dryer. Tub bath.$$,
  $$Houfy $143–$220/night.$$,
  '2026-05-18', '2026-05-18', 'private_commercial',
  8, 1, '4', 182, 143, 220,
  '{"2026":{"summer":{"weekday":143,"weekend":220}}}'::jsonb,
  'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes',
  'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes',
  'Wooded retreat; hot tub, screened porch, charcoal grill, W/D.'
);
