-- Four Seasons Tented Camp Golden Triangle: site inventory from fourseasons.com (May 2026)
-- Sources: accommodations index + category detail pages; AFAR Hotels We Love from-rate $2,655 (Apr 2026)
-- Enriches anchor row id 12188; inserts 3 sibling category rows (15 tents + 1 Explorer's Lodge = 16 units).

UPDATE public.all_glamping_properties SET
  property_id = '0137d9b1-ad12-4c7a-b72e-98b019684d48'::uuid,
  brand_id = (SELECT id FROM public.glamping_brands WHERE slug = 'four-seasons'),
  site_name = 'Golden Triangle Tent',
  slug = 'four-seasons-tented-camp-golden-triangle-chiang-rai-th',
  property_type = 'Glamping Resort',
  unit_type = 'Safari Tent',
  source = 'Sage',
  discovery_source = 'web_research_fs_golden_triangle_2026_05',
  country = 'Thailand',
  state = 'Chiang Rai',
  city = 'Chiang Rai',
  address = 'Ruak River, Golden Triangle, Chiang Rai, Thailand',
  lat = 20.350,
  lon = 100.080,
  url = 'https://www.fourseasons.com/goldentriangle/accommodations/tent/golden-triangle-tent/',
  phone_number = '+66-53-910-200',
  research_status = 'published',
  is_glamping_property = 'Yes',
  is_open = 'Yes',
  property_total_sites = 16,
  quantity_of_units = 1,
  unit_capacity = '3',
  minimum_nights = '1',
  operating_season_months = 'Year-round',
  unit_private_bathroom = 'Yes',
  unit_shower = 'Yes',
  unit_kitchenette = 'No',
  unit_wifi = 'Yes',
  unit_hot_tub = 'Yes',
  property_family_friendly = 'Yes',
  setting_forest = 'Yes',
  activities_wildlife_watching = 'Yes',
  land_operator_category = 'private_commercial',
  date_updated = '2026-05-21',
  description = $$Four Seasons Tented Camp Golden Triangle — luxury glamping in Chiang Rai where Thailand, Laos, and Myanmar meet, reached by longtail boat on the Ruak River. Fifteen Bill Bensley–designed safari tents on raised platforms in bamboo jungle, plus one two-bedroom Explorer's Lodge. Elephant encounters, river excursions, spa, open-air dining, and Camp Peak sunset experiences. Featured amenities: premium Wi-Fi, spa, 24-hour in-room dining, multilingual concierge.$$,
  unit_description = $$Golden Triangle Tent: king bed plus mattress with bedding; 54 m² (581 sq ft) at various camp locations; up to 3 guests. Full bath in living area, outdoor rain shower, custom private wooden tub on deck. Views of Ruak River or jungle and Myanmar mountains. Safari-style hardwood/bamboo/leather décor; each tent unique.$$,
  notes = COALESCE(notes, '') || E'\n\nSite enrichment (May 2026): fourseasons.com/goldentriangle/accommodations. 15 tents + Explorer''s Lodge per property copy. AFAR from-rate ~$2,655/night (Apr 2026). Guests 9+ only; children 9–18 at adult rate — contact resort. Re-quote ADR in FS booker.',
  amenities_raw = 'King bed; 581 sq ft; full bath; outdoor rain shower; custom wooden tub on deck; river or jungle views; private bar; Nespresso; in-tent safe; premium Wi-Fi; bathrobes; twice-daily housekeeping.',
  rate_avg_retail_daily_rate = 2655,
  rate_summer_weekday = 2655,
  rate_summer_weekend = 2655,
  rate_unit_rates_by_year = '{"2026":{"source":"AFAR_Hotels_We_Love_Apr_2026","currency":"USD","afar_from_rate":2655,"note":"Category ADRs vary in FS booker; 15 physical tents in this category type across camp"}}'::jsonb
WHERE id = 12188;

INSERT INTO public.all_glamping_properties (
  property_id, brand_id, research_status, is_glamping_property, is_open,
  property_name, site_name, slug, property_type, unit_type,
  source, discovery_source, country, state, city,
  address, lat, lon, url, phone_number,
  description, unit_description, notes,
  date_added, date_updated, land_operator_category,
  property_total_sites, quantity_of_units, unit_capacity, minimum_nights,
  operating_season_months,
  rate_avg_retail_daily_rate, rate_summer_weekday, rate_summer_weekend,
  rate_unit_rates_by_year,
  unit_private_bathroom, unit_shower, unit_kitchenette, unit_wifi,
  unit_hot_tub, property_family_friendly, setting_forest,
  activities_wildlife_watching, amenities_raw
) VALUES
(
  '0137d9b1-ad12-4c7a-b72e-98b019684d48'::uuid,
  (SELECT id FROM public.glamping_brands WHERE slug = 'four-seasons'),
  'published', 'Yes', 'Yes',
  'Four Seasons Tented Camp Golden Triangle', 'Mekong Tent',
  'four-seasons-tented-camp-golden-triangle-chiang-rai-th', 'Glamping Resort', 'Safari Tent',
  'Sage', 'web_research_fs_golden_triangle_2026_05', 'Thailand', 'Chiang Rai', 'Chiang Rai',
  'Ruak River, Golden Triangle, Chiang Rai, Thailand', 20.350, 100.080,
  'https://www.fourseasons.com/goldentriangle/accommodations/tent/mekong-tent/',
  '+66-53-910-200',
  'Sibling site — Four Seasons Tented Camp Golden Triangle. See anchor row id 12188.',
  'Mekong Tent: king or two twin beds plus extra bed; 54 m² along hillside; up to 3 guests. Full bath and outdoor rain shower. Ruak River and Myanmar mountain views; river-view deck with coffee table and chairs.',
  'Hillside tent category. AFAR from-rate ~$2,655/night — re-quote in FS booker.',
  '2026-05-21', '2026-05-21', 'private_commercial', 16, 1, '3', '1', 'Year-round',
  2655, 2655, 2655,
  '{"2026":{"afar_from_rate":2655,"category":"Mekong Tent"}}'::jsonb,
  'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes', 'Yes', 'Yes',
  'King or twins; extra bed; 581 sq ft; river views; outdoor rain shower; private bar; Nespresso; premium Wi-Fi.'
),
(
  '0137d9b1-ad12-4c7a-b72e-98b019684d48'::uuid,
  (SELECT id FROM public.glamping_brands WHERE slug = 'four-seasons'),
  'published', 'Yes', 'Yes',
  'Four Seasons Tented Camp Golden Triangle', 'Bamboo Tent',
  'four-seasons-tented-camp-golden-triangle-chiang-rai-th', 'Glamping Resort', 'Safari Tent',
  'Sage', 'web_research_fs_golden_triangle_2026_05', 'Thailand', 'Chiang Rai', 'Chiang Rai',
  'Ruak River, Golden Triangle, Chiang Rai, Thailand', 20.350, 100.080,
  'https://www.fourseasons.com/goldentriangle/accommodations/tent/bamboo-tent/',
  '+66-53-910-200',
  'Sibling site — Four Seasons Tented Camp Golden Triangle. See anchor row id 12188.',
  'Bamboo Tent: king or two twin beds plus mattress with bedding; 54 m² along hillside; up to 3 guests. Full bath and outdoor rain shower. Jungle and Myanmar mountain views; bed with sheer white net and private terrace.',
  'Hillside jungle-view category. AFAR from-rate ~$2,655/night — re-quote in FS booker.',
  '2026-05-21', '2026-05-21', 'private_commercial', 16, 1, '3', '1', 'Year-round',
  2655, 2655, 2655,
  '{"2026":{"afar_from_rate":2655,"category":"Bamboo Tent"}}'::jsonb,
  'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes', 'Yes', 'Yes',
  'King or twins; 581 sq ft; jungle views; mosquito net canopy bed; private terrace; outdoor rain shower; premium Wi-Fi.'
),
(
  '0137d9b1-ad12-4c7a-b72e-98b019684d48'::uuid,
  (SELECT id FROM public.glamping_brands WHERE slug = 'four-seasons'),
  'published', 'Yes', 'Yes',
  'Four Seasons Tented Camp Golden Triangle', 'Explorer''s Lodge',
  'four-seasons-tented-camp-golden-triangle-chiang-rai-th', 'Glamping Resort', 'Lodge',
  'Sage', 'web_research_fs_golden_triangle_2026_05', 'Thailand', 'Chiang Rai', 'Chiang Rai',
  'Ruak River, Golden Triangle, Chiang Rai, Thailand', 20.350, 100.080,
  'https://www.fourseasons.com/goldentriangle/accommodations/lodges/explorers-lodge/',
  '+66-53-910-200',
  'Sibling site — Four Seasons Tented Camp Golden Triangle. See anchor row id 12188.',
  'Explorer''s Lodge: two-bedroom lodge at far end of camp; one king and two twins; up to 6 guests; 232 m². Ensuite bath, shower, and tub in each room; private infinity pool on deck overlooking bamboo jungle. Private BBQ dinners and movies under the stars available.',
  'Only lodge inventory (1 unit). Premium category — re-quote ADR in FS booker.',
  '2026-05-21', '2026-05-21', 'private_commercial', 16, 1, '6', '1', 'Year-round',
  2655, 2655, 2655,
  '{"2026":{"afar_from_rate":2655,"category":"Explorer''s Lodge","size_sqm":232,"private_pool":true}}'::jsonb,
  'Yes', 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes',
  'Two bedrooms; king + twins; private pool; 232 sq m; jungle views; handcrafted tub; premium Wi-Fi; private bar.'
);

UPDATE public.all_glamping_properties SET
  brand_id = (SELECT id FROM public.glamping_brands WHERE slug = 'four-seasons'),
  property_id = '0137d9b1-ad12-4c7a-b72e-98b019684d48'::uuid,
  description = 'Sibling site — Four Seasons Tented Camp Golden Triangle (Chiang Rai TH). See anchor row id 12188.',
  phone_number = '+66-53-910-200',
  country = 'Thailand',
  state = 'Chiang Rai',
  city = 'Chiang Rai',
  address = 'Ruak River, Golden Triangle, Chiang Rai, Thailand',
  lat = 20.350,
  lon = 100.080,
  property_total_sites = 16,
  quantity_of_units = 1,
  minimum_nights = '1',
  is_glamping_property = 'Yes',
  is_open = 'Yes',
  property_type = 'Glamping Resort',
  slug = 'four-seasons-tented-camp-golden-triangle-chiang-rai-th',
  land_operator_category = 'private_commercial',
  property_family_friendly = 'Yes',
  setting_forest = 'Yes',
  activities_wildlife_watching = 'Yes',
  unit_private_bathroom = 'Yes',
  unit_shower = 'Yes',
  unit_wifi = 'Yes',
  unit_kitchenette = 'No',
  operating_season_months = 'Year-round',
  discovery_source = 'web_research_fs_golden_triangle_2026_05',
  research_status = 'published'
WHERE property_name = 'Four Seasons Tented Camp Golden Triangle' AND id <> 12188;
