-- Al Maha, a Luxury Collection Desert Resort & Spa: site inventory from marriott.com (May 2026)
-- Sources: rooms/overview pages, rateListMenu.mi (DXBAM, May 21–22 2026, 2 adults), AFAR Hotels We Love (Apr 2026)
-- Enriches anchor row id 12185; inserts 4 sibling villa category rows (42 villas total).

INSERT INTO public.glamping_brands (slug, display_name, brand_tier, legacy_chain_key, website_url, notes)
VALUES (
  'marriott',
  'Marriott',
  'portfolio',
  'marriott',
  'https://www.marriott.com/',
  'Marriott International / Marriott Bonvoy; includes Luxury Collection properties such as Al Maha (DXBAM).'
)
ON CONFLICT (slug) DO UPDATE SET
  display_name = EXCLUDED.display_name,
  brand_tier = EXCLUDED.brand_tier,
  legacy_chain_key = EXCLUDED.legacy_chain_key,
  website_url = EXCLUDED.website_url,
  notes = EXCLUDED.notes,
  updated_at = now();

UPDATE public.all_glamping_properties SET
  property_id = 'ad64ad4c-4b01-4156-92d2-08f52a309ae6'::uuid,
  brand_id = (SELECT id FROM public.glamping_brands WHERE slug = 'marriott'),
  site_name = 'Bedouin Villa King',
  slug = 'al-maha-luxury-collection-dubai-ae',
  property_type = 'Glamping Resort',
  unit_type = 'Safari Tent',
  source = 'Sage',
  discovery_source = 'web_research_al_maha_marriott_booking_2026_05',
  country = 'United Arab Emirates',
  state = NULL,
  city = 'Dubai Desert Conservation Reserve',
  address = 'Dubai Desert Conservation Reserve, Dubai - Al Ain Road, Dubai, UAE',
  zip_code = '118887',
  lat = 24.850,
  lon = 55.550,
  url = 'https://www.marriott.com/en-us/hotels/dxbam-al-maha-a-luxury-collection-desert-resort-and-spa-dubai/rooms/',
  phone_number = '+971-4-8329900',
  research_status = 'published',
  is_glamping_property = 'Yes',
  is_open = 'Yes',
  property_total_sites = 42,
  quantity_of_units = 1,
  unit_capacity = '2',
  minimum_nights = '1',
  operating_season_months = 'Year-round',
  unit_private_bathroom = 'Yes',
  unit_shower = 'Yes',
  unit_kitchenette = 'No',
  unit_wifi = 'Yes',
  unit_air_conditioning = 'Yes',
  unit_campfires = 'No',
  unit_hot_tub = 'Yes',
  property_family_friendly = 'Yes',
  setting_desert = 'Yes',
  activities_wildlife_watching = 'Yes',
  activities_hiking = 'Yes',
  land_operator_category = 'private_commercial',
  date_updated = '2026-05-21',
  description = $$Al Maha, a Luxury Collection Desert Resort & Spa — Bedouin-inspired luxury villas in the Dubai Desert Conservation Reserve (42 individual villas: Bedouin, Royal, Emirates, and Presidential). Private plunge pools, handcrafted Arabian décor, fine dining, Timeless Spa, and desert experiences (falconry, camel rides, wildlife drives). UAE's largest free-roaming Arabian oryx herd on site. Marriott Bonvoy / Luxury Collection.$$,
  unit_description = $$Bedouin Villa King: 1-bedroom villa, 1 king bed, private pool; authentic Arabian furnishings and desert views; bookable as 1 Bedroom Villa, 1 King, Private pool on Marriott.$$,
  notes = COALESCE(notes, '') || E'\n\nSite enrichment (May 2026): marriott.com DXBAM rateListMenu. Sample May 21–22, 2026, 2 adults (AED): from 1,510/night (breakfast); full board + 2 desert activities non-member 3,250/night (~USD 886 at 3.67). AFAR from-rate ~$500 (Apr 2026).',
  amenities_raw = 'King bed; private plunge pool; handcrafted Arabian décor; indoor/outdoor living; mini fridge; coffee/tea maker; desert views; spa; fine dining; wildlife (oryx, gazelles).',
  rate_avg_retail_daily_rate = 411,
  rate_summer_weekday = 411,
  rate_summer_weekend = 411,
  rate_unit_rates_by_year = '{"2026":{"sample_dates":"2026-05-21_to_2026-05-22","currency":"AED","guests":2,"property_code":"DXBAM","lowest_aed":1510,"full_board_non_member_aed":3250,"usd_approx_lowest":411,"usd_approx_full_board":886,"afar_from_rate_usd":500,"note":"Marriott rateListMenu May 2026; USD approx AED/3.67"}}'::jsonb
WHERE id = 12185;

INSERT INTO public.all_glamping_properties (
  property_id, brand_id, research_status, is_glamping_property, is_open,
  property_name, site_name, slug, property_type, unit_type,
  source, discovery_source, country, state, city,
  address, zip_code, lat, lon, url, phone_number,
  description, unit_description, notes,
  date_added, date_updated, land_operator_category,
  property_total_sites, quantity_of_units, unit_capacity, minimum_nights,
  operating_season_months,
  rate_avg_retail_daily_rate, rate_summer_weekday, rate_summer_weekend,
  rate_unit_rates_by_year,
  unit_private_bathroom, unit_shower, unit_kitchenette, unit_wifi,
  unit_air_conditioning, unit_campfires, unit_hot_tub,
  property_family_friendly, setting_desert,
  activities_wildlife_watching, activities_hiking, amenities_raw
) VALUES
(
  'ad64ad4c-4b01-4156-92d2-08f52a309ae6'::uuid,
  (SELECT id FROM public.glamping_brands WHERE slug = 'marriott'),
  'published', 'Yes', 'Yes',
  'Al Maha', 'Bedouin Villa Twin',
  'al-maha-luxury-collection-dubai-ae', 'Glamping Resort', 'Safari Tent',
  'Sage', 'web_research_al_maha_marriott_booking_2026_05', 'United Arab Emirates', NULL, 'Dubai Desert Conservation Reserve',
  'Dubai Desert Conservation Reserve, Dubai - Al Ain Road, Dubai, UAE', '118887',
  24.850, 55.550,
  'https://www.marriott.com/en-us/hotels/dxbam-al-maha-a-luxury-collection-desert-resort-and-spa-dubai/rooms/',
  '+971-4-8329900',
  'Sibling site — Al Maha (Dubai AE). See anchor row id 12185.',
  'Bedouin Villa Twin: 1-bedroom villa, 2 twin beds, private pool; same Bedouin category with twin bedding configuration.',
  'Marriott May 21–22, 2026: from 1,510 AED/night; full board non-member 3,255 AED (~USD 887).',
  '2026-05-21', '2026-05-21', 'private_commercial',
  42, 1, '2', '1', 'Year-round',
  411, 411, 411,
  '{"2026":{"sample_dates":"2026-05-21_to_2026-05-22","currency":"AED","lowest_aed":1510,"full_board_non_member_aed":3255,"usd_approx_lowest":411,"usd_approx_full_board":887}}'::jsonb,
  'Yes', 'Yes', 'No', 'Yes', 'Yes', 'No', 'Yes',
  'Yes', 'Yes', 'Yes', 'Yes',
  '2 twin beds; private pool; Arabian décor; desert wildlife views.'
),
(
  'ad64ad4c-4b01-4156-92d2-08f52a309ae6'::uuid,
  (SELECT id FROM public.glamping_brands WHERE slug = 'marriott'),
  'published', 'Yes', 'Yes',
  'Al Maha', 'Royal Villa',
  'al-maha-luxury-collection-dubai-ae', 'Glamping Resort', 'Villa',
  'Sage', 'web_research_al_maha_marriott_booking_2026_05', 'United Arab Emirates', NULL, 'Dubai Desert Conservation Reserve',
  'Dubai Desert Conservation Reserve, Dubai - Al Ain Road, Dubai, UAE', '118887',
  24.850, 55.550,
  'https://www.marriott.com/en-us/hotels/dxbam-al-maha-a-luxury-collection-desert-resort-and-spa-dubai/rooms/',
  '+971-4-8329900',
  'Sibling site — Al Maha (Dubai AE). See anchor row id 12185.',
  'Royal Villa: 2-bedroom villa — bedroom 1 king, bedroom 2 two twins; private pool; expanded living for families or groups.',
  'Marriott May 21–22, 2026: from 5,200 AED/night (Timeless Desert Serenity); full board non-member 6,500 AED (~USD 1,771).',
  '2026-05-21', '2026-05-21', 'private_commercial',
  42, 1, '4', '1', 'Year-round',
  1417, 1417, 1417,
  '{"2026":{"sample_dates":"2026-05-21_to_2026-05-22","currency":"AED","lowest_aed":5200,"full_board_non_member_aed":6500,"usd_approx_lowest":1417,"usd_approx_full_board":1771}}'::jsonb,
  'Yes', 'Yes', 'No', 'Yes', 'Yes', 'No', 'Yes',
  'Yes', 'Yes', 'Yes', 'Yes',
  '2 bedrooms; king + twins; private pool; premium desert villa.'
),
(
  'ad64ad4c-4b01-4156-92d2-08f52a309ae6'::uuid,
  (SELECT id FROM public.glamping_brands WHERE slug = 'marriott'),
  'published', 'Yes', 'Yes',
  'Al Maha', 'Emirates Villa',
  'al-maha-luxury-collection-dubai-ae', 'Glamping Resort', 'Villa',
  'Sage', 'web_research_al_maha_marriott_booking_2026_05', 'United Arab Emirates', NULL, 'Dubai Desert Conservation Reserve',
  'Dubai Desert Conservation Reserve, Dubai - Al Ain Road, Dubai, UAE', '118887',
  24.850, 55.550,
  'https://www.marriott.com/en-us/hotels/dxbam-al-maha-a-luxury-collection-desert-resort-and-spa-dubai/rooms/',
  '+971-4-8329900',
  'Sibling site — Al Maha (Dubai AE). See anchor row id 12185.',
  'Emirates Villa: 2-bedroom signature villa — bedroom 1 king, bedroom 2 two twins; private pool; premium tier alongside Royal on Marriott inventory.',
  'Re-quote ADR in Marriott booker for travel dates; floor plan matches 2 Bedroom Villa on site.',
  '2026-05-21', '2026-05-21', 'private_commercial',
  42, 1, '4', '1', 'Year-round',
  NULL, NULL, NULL,
  '{"2026":{"sample_dates":"2026-05-21_to_2026-05-22","note":"Emirates Villa listed on overview; expand rates in rateListMenu for specific date"}}'::jsonb,
  'Yes', 'Yes', 'No', 'Yes', 'Yes', 'No', 'Yes',
  'Yes', 'Yes', 'Yes', 'Yes',
  '2 bedrooms; king + twins; private pool; signature villa tier.'
),
(
  'ad64ad4c-4b01-4156-92d2-08f52a309ae6'::uuid,
  (SELECT id FROM public.glamping_brands WHERE slug = 'marriott'),
  'published', 'Yes', 'Yes',
  'Al Maha', 'Presidential Villa',
  'al-maha-luxury-collection-dubai-ae', 'Glamping Resort', 'Villa',
  'Sage', 'web_research_al_maha_marriott_booking_2026_05', 'United Arab Emirates', NULL, 'Dubai Desert Conservation Reserve',
  'Dubai Desert Conservation Reserve, Dubai - Al Ain Road, Dubai, UAE', '118887',
  24.850, 55.550,
  'https://www.marriott.com/en-us/hotels/dxbam-al-maha-a-luxury-collection-desert-resort-and-spa-dubai/rooms/',
  '+971-4-8329900',
  'Sibling site — Al Maha (Dubai AE). See anchor row id 12185.',
  'Presidential Villa: three-bedroom ultimate desert escape; custom super king beds, handcrafted décor; max occupancy 6 per Marriott FAQ.',
  'Premium tier — contact resort or expand Marriott booker for dated ADR.',
  '2026-05-21', '2026-05-21', 'private_commercial',
  42, 1, '6', '1', 'Year-round',
  NULL, NULL, NULL,
  NULL,
  'Yes', 'Yes', 'No', 'Yes', 'Yes', 'No', 'Yes',
  'Yes', 'Yes', 'Yes', 'Yes',
  '3 bedrooms; sleeps up to 6; private pool; top-tier villa.'
);

UPDATE public.all_glamping_properties SET
  brand_id = (SELECT id FROM public.glamping_brands WHERE slug = 'marriott'),
  description = 'Sibling site — Al Maha (Dubai AE). See anchor row id 12185.',
  url = 'https://www.marriott.com/en-us/hotels/dxbam-al-maha-a-luxury-collection-desert-resort-and-spa-dubai/rooms/',
  phone_number = '+971-4-8329900',
  country = 'United Arab Emirates',
  city = 'Dubai Desert Conservation Reserve',
  address = 'Dubai Desert Conservation Reserve, Dubai - Al Ain Road, Dubai, UAE',
  zip_code = '118887',
  lat = 24.850,
  lon = 55.550,
  property_total_sites = 42,
  quantity_of_units = 1,
  is_glamping_property = 'Yes',
  is_open = 'Yes',
  property_type = 'Glamping Resort',
  slug = 'al-maha-luxury-collection-dubai-ae',
  land_operator_category = 'private_commercial',
  property_family_friendly = 'Yes',
  setting_desert = 'Yes',
  activities_wildlife_watching = 'Yes',
  activities_hiking = 'Yes',
  unit_private_bathroom = 'Yes',
  unit_shower = 'Yes',
  unit_wifi = 'Yes',
  unit_air_conditioning = 'Yes',
  unit_hot_tub = 'Yes'
WHERE property_name = 'Al Maha' AND id <> 12185;
