-- andBeyond Punakha River Lodge: site inventory from andbeyond.com (May 2026)
-- Sources: lodge page, rate pages (tented suite, river house, family suite); AFAR from ~$890
-- Enriches anchor row id 12186; inserts 2 sibling rows (6 tented suites + 2 villas = 8 units).

INSERT INTO public.glamping_brands (slug, display_name, brand_tier, legacy_chain_key, website_url)
VALUES ('andbeyond', 'andBeyond', 'standalone', 'andbeyond', 'https://www.andbeyond.com/')
ON CONFLICT (slug) DO UPDATE SET display_name = EXCLUDED.display_name, updated_at = now();

UPDATE public.all_glamping_properties SET
  property_id = 'eccee0a7-2b94-45d0-aa50-c6763bae8515'::uuid,
  brand_id = (SELECT id FROM public.glamping_brands WHERE slug = 'andbeyond'),
  site_name = 'Tented Suite',
  slug = 'andbeyond-punakha-river-lodge-punakha-bt',
  property_type = 'Glamping Resort',
  unit_type = 'Safari Tent',
  source = 'Sage',
  discovery_source = 'web_research_andbeyond_punakha_2026_05',
  country = 'Bhutan',
  state = 'Punakha',
  city = 'Punakha',
  address = 'Mo Chhu River, Punakha Valley, Bhutan',
  lat = 27.590,
  lon = 89.860,
  url = 'https://www.andbeyond.com/rates/punakha-river-lodge-tented-suite-rate/',
  phone_number = '+1-800-998-6634',
  research_status = 'published',
  is_glamping_property = 'Yes',
  is_open = 'Yes',
  property_total_sites = 8,
  quantity_of_units = 6,
  unit_capacity = '2',
  unit_bed = '1 King',
  minimum_nights = '1',
  operating_season_months = 'Year-round (seasonal rate bands)',
  unit_private_bathroom = 'Yes',
  unit_shower = 'Yes',
  unit_wifi = 'Yes',
  unit_hot_tub = 'Yes',
  property_family_friendly = 'Yes',
  setting_forest = 'Yes',
  setting_mountainous = 'Yes',
  activities_hiking = 'Yes',
  activities_wildlife_watching = 'Yes',
  activities_scenic_drives = 'Yes',
  land_operator_category = 'private_commercial',
  glamping_service_tier = 'luxury',
  date_updated = '2026-05-21',
  description = $$andBeyond Punakha River Lodge — first andBeyond lodge in Asia on the Mo Chhu River in Bhutan's Punakha Valley (rice fields, forest, Himalaya views). Eight accommodations: six safari-style Tented Suites on Bhutanese timber platforms, one River House villa, and one two-bedroom Family Suite. All-inclusive meals, house wines/spirits, spa, yoga pavilion, hot stone bath, and valley experiences (dzongs, rafting, biking, culture). Beyond Green sustainable property; SDF visa fee separate.$$,
  unit_description = $$Tented Suite: six canvas-and-wood suites suspended from traditional Bhutanese timber structures with privacy-focused positioning. King bed, hardwood floors, lounge with velvet seating and bone-inlay drinks trolley; brass-panel soaking tub beneath skylight; morning cappuccino via wooden hatch. Maximum two adults (children ≤5 may share with two adults).$$,
  notes = COALESCE(notes, '') || E'\n\nSite enrichment (May 2026): andbeyond.com rate pages. All-inclusive 2026 from USD 953/suite/night (single, Jun–Aug) or USD 1,210/night (double, 2 guests). AFAR from ~$890. I Prefer / Beyond Green. SDF payable at visa.',
  amenities_raw = 'Safari-style tented suite; king bed; hardwood floors; lounge; brass soaking tub; skylight bath; timber platform; cappuccino hatch; three meals; house wines; yoga; biking; archery; cooking class; spa (treatments extra).',
  rate_avg_retail_daily_rate = 953,
  rate_summer_weekday = 953,
  rate_summer_weekend = 953,
  rate_unit_rates_by_year = '{"2026":{"currency":"USD","all_inclusive":true,"from_rate_single_usd":953,"double_2_guests_low_season_usd":1210,"double_2_guests_high_season_usd":1477,"afar_from_rate_usd":890,"units":6,"booking_url":"https://www.andbeyond.com/rates/punakha-river-lodge-tented-suite-rate/"}}'::jsonb
WHERE id = 12186;

INSERT INTO public.all_glamping_properties (
  property_id, brand_id, research_status, is_glamping_property, is_open,
  property_name, site_name, slug, property_type, unit_type,
  source, discovery_source, country, state, city,
  address, lat, lon, url, phone_number,
  description, unit_description, notes,
  date_added, date_updated, land_operator_category,
  property_total_sites, quantity_of_units, unit_capacity, unit_bed, minimum_nights,
  operating_season_months,
  rate_avg_retail_daily_rate, rate_summer_weekday, rate_summer_weekend,
  rate_unit_rates_by_year,
  unit_private_bathroom, unit_shower, unit_wifi, unit_hot_tub,
  property_family_friendly, setting_forest, setting_mountainous,
  activities_hiking, activities_wildlife_watching, activities_scenic_drives,
  glamping_service_tier, amenities_raw
) VALUES
(
  'eccee0a7-2b94-45d0-aa50-c6763bae8515'::uuid,
  (SELECT id FROM public.glamping_brands WHERE slug = 'andbeyond'),
  'published', 'Yes', 'Yes',
  'andBeyond Punakha River Lodge', 'One-Bedroom Villa - River House',
  'andbeyond-punakha-river-lodge-punakha-bt', 'Glamping Resort', 'Villa',
  'Sage', 'web_research_andbeyond_punakha_2026_05', 'Bhutan', 'Punakha', 'Punakha',
  'Mo Chhu River, Punakha Valley, Bhutan', 27.590, 89.860,
  'https://www.andbeyond.com/rates/punakha-river-lodge-river-suite-rate/',
  '+1-800-998-6634',
  'Sibling site — andBeyond Punakha River Lodge. See anchor row id 12186 (Tented Suite).',
  'One-Bedroom Villa – River House: exclusive private villa along a perennial stream with uninterrupted river and Himalayan views; two levels with spacious lounge and bedroom; private pool. Couples; max two adults.',
  '2026 all-inclusive from USD 1,285/night single (Jun–Aug); USD 1,565/night double (2 guests).',
  '2026-05-21', '2026-05-21', 'private_commercial',
  8, 1, '2', '1 King', '1', 'Year-round (seasonal rate bands)',
  1285, 1285, 1285,
  '{"2026":{"all_inclusive":true,"from_rate_single_usd":1285,"double_2_guests_low_season_usd":1565,"double_2_guests_high_season_usd":1957,"units":1}}'::jsonb,
  'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes',
  'luxury', 'Private pool; two-level villa; river views; lounge; ensuite; all-inclusive meals and house wines.'
),
(
  'eccee0a7-2b94-45d0-aa50-c6763bae8515'::uuid,
  (SELECT id FROM public.glamping_brands WHERE slug = 'andbeyond'),
  'published', 'Yes', 'Yes',
  'andBeyond Punakha River Lodge', 'Two-Bedroom Villa - Family Suite',
  'andbeyond-punakha-river-lodge-punakha-bt', 'Glamping Resort', 'Villa',
  'Sage', 'web_research_andbeyond_punakha_2026_05', 'Bhutan', 'Punakha', 'Punakha',
  'Mo Chhu River, Punakha Valley, Bhutan', 27.590, 89.860,
  'https://www.andbeyond.com/rates/punakha-river-lodge-family-suite-rate/',
  '+1-800-998-6634',
  'Sibling site — andBeyond Punakha River Lodge. See anchor row id 12186.',
  'Two-Bedroom Villa – Family Suite: two interconnected suites with separate ensuite bathrooms, private decks, and al fresco showers; private pool and shared living spaces. Up to four adults; flexible child occupancy per lodge policy.',
  '2026 from USD 3,456/night (4 adults, Jun–Aug); USD 2,358/night (2 adults).',
  '2026-05-21', '2026-05-21', 'private_commercial',
  8, 1, '4', '2 Bedrooms', '1', 'Year-round (seasonal rate bands)',
  3456, 3456, 3456,
  '{"2026":{"all_inclusive":true,"from_rate_4_adults_usd":3456,"rate_2_adults_low_season_usd":2358,"rate_3_adults_low_season_usd":2907,"units":1,"max_adults":4}}'::jsonb,
  'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes',
  'luxury', 'Two-bedroom villa; private pool; interconnected suites; al fresco shower; family occupancy; all-inclusive.'
);

UPDATE public.all_glamping_properties SET
  brand_id = (SELECT id FROM public.glamping_brands WHERE slug = 'andbeyond'),
  property_id = 'eccee0a7-2b94-45d0-aa50-c6763bae8515'::uuid,
  description = 'Sibling site — andBeyond Punakha River Lodge (Punakha, Bhutan). See anchor row id 12186 (Tented Suite).',
  phone_number = '+1-800-998-6634',
  country = 'Bhutan',
  state = 'Punakha',
  city = 'Punakha',
  address = 'Mo Chhu River, Punakha Valley, Bhutan',
  lat = 27.590,
  lon = 89.860,
  property_total_sites = 8,
  minimum_nights = '1',
  is_glamping_property = 'Yes',
  is_open = 'Yes',
  property_type = 'Glamping Resort',
  slug = 'andbeyond-punakha-river-lodge-punakha-bt',
  land_operator_category = 'private_commercial',
  glamping_service_tier = 'luxury',
  property_family_friendly = 'Yes',
  setting_forest = 'Yes',
  setting_mountainous = 'Yes',
  activities_hiking = 'Yes',
  activities_wildlife_watching = 'Yes',
  activities_scenic_drives = 'Yes',
  unit_private_bathroom = 'Yes',
  unit_shower = 'Yes',
  unit_wifi = 'Yes',
  operating_season_months = 'Year-round (seasonal rate bands)',
  discovery_source = 'web_research_andbeyond_punakha_2026_05',
  research_status = 'published'
WHERE property_name = 'andBeyond Punakha River Lodge' AND id <> 12186;
