-- ============================================================================
-- Sage AI: add draft_content + source columns to reports
--
-- Lets the build_feasibility_brief tool write a structured draft into the
-- reports product without clobbering the real report_url/dropbox_url columns.
-- The admin app can then decide whether to promote the draft to a final
-- report.
--
-- Apply with:
--   psql $DATABASE_URL -f scripts/migrations/sage-ai-reports-draft-content.sql
-- or via the Supabase SQL editor.
-- ============================================================================

ALTER TABLE reports
  ADD COLUMN IF NOT EXISTS draft_content JSONB,
  ADD COLUMN IF NOT EXISTS source        TEXT
    CHECK (source IS NULL OR source IN ('manual', 'sage_ai', 'upload', 'import'));

CREATE INDEX IF NOT EXISTS idx_reports_source
  ON reports(source)
  WHERE source IS NOT NULL;

COMMENT ON COLUMN reports.draft_content IS
  'Structured draft content (e.g. generated by Sage AI build_feasibility_brief). NULL for finalized reports.';

COMMENT ON COLUMN reports.source IS
  'Origin of the report row: manual/sage_ai/upload/import. NULL for legacy rows.';
