INSERT INTO public.all_glamping_properties (
  property_id, research_status, is_glamping_property, is_open,
  property_name, site_name, slug, property_type, unit_type,
  source, discovery_source, country, state, city,
  address, zip_code, lat, lon, url, phone_number,
  description, unit_description, notes,
  date_added, date_updated, land_operator_category,
  property_total_sites, quantity_of_units, unit_capacity, minimum_nights,
  rate_avg_retail_daily_rate, rate_summer_weekday, rate_summer_weekend,
  rate_unit_rates_by_year,
  unit_wifi, unit_pets, unit_shower, unit_private_bathroom, unit_campfires,
  unit_hot_tub, unit_kitchenette, unit_air_conditioning,
  property_family_friendly, setting_forest, activities_wildlife_watching,
  amenities_raw
) VALUES
('1eed22fc-916f-4748-8fee-f9f0716ede7b'::uuid,
  'in_progress', 'Yes', 'Yes',
  'Eureka Springs Treehouses', '2. Four Mystic Cottages of Hogsveil',
  'eureka-springs-treehouses-ar', 'Glamping Resort', 'Cabin',
  'Sage', 'web_research_estreehouses_thinkreservations_2026_05', 'United States', 'AR', 'Eureka Springs',
  '3018 E Van Buren, Eureka Springs, AR 72632', '72632', 36.3964, -93.737,
  'https://secure.thinkreservations.com/estreehouses/reservations/availability',
  '+1-479-253-9493',
  'Sibling site — Eureka Springs Treehouses (Eureka Springs AR). See anchor row id 32.',
  'Second four-pack Mystic Cottage block at Hogsveil sister property.',
  'ThinkReservations calendar row; 2-night minimum on many units; re-quote ADR in engine.',
  '2026-05-20', '2026-05-20', 'private_commercial',
  24, 1, '2',
  '2',
  NULL, NULL, NULL,
  NULL,
  'No', NULL, 'Yes', 'Yes', 'Yes',
  'No', 'No', 'No',
  'Yes', 'Yes', 'Yes',
  'Jacuzzi; fireplace; seasonal A/C; kitchenette; king bed; cable/DVD; deck/patio.')
;