/**
 * Feasibility-brief templates used by the build_feasibility_brief tool.
 *
 * Each template defines:
 *   - an id exposed to the model
 *   - a short display label
 *   - an ordered list of sections to populate
 *   - a default prompt hint appended to each section
 *
 * Keep these templates small — the model fills the content. The template
 * is mainly a structure + disclaimer contract so the output is predictable.
 */

export type ReportTemplateId = 'glamping_feasibility' | 'market_snapshot';

export interface ReportSectionSpec {
  key: string;
  title: string;
  guidance: string;
}

export interface ReportTemplate {
  id: ReportTemplateId;
  label: string;
  sections: ReportSectionSpec[];
  disclaimer: string;
}

export const REPORT_TEMPLATES: ReportTemplate[] = [
  {
    id: 'glamping_feasibility',
    label: 'Glamping Feasibility Brief (short)',
    disclaimer:
      'Draft generated by Sage AI from available database and research context. Review and validate before sharing externally.',
    sections: [
      {
        key: 'market_overview',
        title: 'Market Overview',
        guidance:
          'Summarize current glamping supply in the target city/state (counts by unit type, notable operators). Cite Sage database and any external research.',
      },
      {
        key: 'demand_signals',
        title: 'Demand Signals',
        guidance:
          'Use county-population data and proximity to attractions (ski resorts, national parks, major cities) to infer demand. Note visitor stats when available.',
      },
      {
        key: 'comparable_operators',
        title: 'Comparable Operators',
        guidance:
          'List 3-6 operators serving the same market or offering a similar unit mix. Include price points and amenity highlights when known.',
      },
      {
        key: 'risks',
        title: 'Risks & Open Questions',
        guidance:
          'List gaps in the data, seasonality concerns, permitting/zoning uncertainties, and questions the team should validate before committing.',
      },
      {
        key: 'recommended_next_steps',
        title: 'Recommended Next Steps',
        guidance:
          '3-5 concrete next steps (e.g. on-site visit, permit research, competitor interviews).',
      },
    ],
  },
  {
    id: 'market_snapshot',
    label: 'Market Snapshot (very short)',
    disclaimer:
      'One-page snapshot. Not a substitute for a full feasibility study.',
    sections: [
      {
        key: 'supply_summary',
        title: 'Supply Summary',
        guidance:
          'Total properties + top operators in the target market, pulled from Sage database.',
      },
      {
        key: 'demand_summary',
        title: 'Demand Summary',
        guidance:
          'Key demand drivers: population, tourism anchors, proximity to airports/cities.',
      },
      {
        key: 'highlights',
        title: 'Highlights',
        guidance:
          'Three bullets: strongest signal, biggest risk, one surprising fact.',
      },
    ],
  },
];

export function getReportTemplate(
  id: ReportTemplateId
): ReportTemplate | null {
  return REPORT_TEMPLATES.find((t) => t.id === id) ?? null;
}
