-- SQL script to add manually_reviewed column and insert new glamping properties
-- This will keep ALL existing data and add the new properties from csv/new-properties/new-glamping-properties.csv
--
-- Usage:
--   Run this SQL in your Supabase SQL Editor

-- Step 1: Add manually_reviewed column with default value 'No'
ALTER TABLE "sage-glamping-data" 
ADD COLUMN IF NOT EXISTS manually_reviewed TEXT DEFAULT 'No';

-- Add check constraint to ensure only 'Yes' or 'No' values
ALTER TABLE "sage-glamping-data"
ADD CONSTRAINT manually_reviewed_check 
CHECK (manually_reviewed IN ('Yes', 'No'))
NOT VALID;

-- Validate the constraint (this ensures existing NULL values don't cause issues)
ALTER TABLE "sage-glamping-data"
VALIDATE CONSTRAINT manually_reviewed_check;

-- Update any existing NULL values to 'No'
UPDATE "sage-glamping-data"
SET manually_reviewed = 'No'
WHERE manually_reviewed IS NULL;

-- Add comment to document the column
COMMENT ON COLUMN "sage-glamping-data".manually_reviewed IS 
'Indicates whether this property has been manually reviewed for accuracy. Values: Yes, No. Default: No';

-- Create index for faster querying by review status
CREATE INDEX IF NOT EXISTS idx_sage_glamping_data_manually_reviewed 
ON "sage-glamping-data" (manually_reviewed);

-- Step 2: Insert new glamping properties from CSV
-- Note: Adjust these INSERT statements based on your actual CSV data
-- The following is based on the columns in your CSV file

INSERT INTO "sage-glamping-data" (
  property_name, site_name, unit_type, address, city, state, country, url,
  __of_locations, fall_weekday, fall_weekend, spring_weekday, spring_weekend,
  summer_weekday, summer_weekend, winter_weekday, winter_weekend,
  campfires, cooking_equipment, description, getting_there, hot_tub___sauna,
  lat, laundry, lon, occupancy_rate_2024, operating_season__months_,
  pets, picnic_table, playground, property_type, property__total_sites,
  quantity_of_units, rv___accommodates_slideout, rv___parking, rv___surface_type,
  rv___surface_level, rv___vehicle_length, rv___vehicles__class_a_rvs,
  rv___vehicles__class_b_rvs, rv___vehicles__class_c_rvs, rv___vehicles__fifth_wheels,
  rv___vehicles__toy_hauler, revpar_2024, retail_daily_rate__fees__2024,
  sage___p__amenity__food_on_site, pool, restaurant, waterfront,
  private_bathroom, shower, source, toilet, trash, unit_capacity, water, wifi,
  year_site_opened, zip_code, manually_reviewed
) VALUES

-- Collective Yellowstone
('Collective Yellowstone', 'Safari Tent', 'Safari Tent', 'Moonlight Basin', 'Big Sky', 'MT', 'USA', 'https://www.collectiveretreats.com/retreats/collective-yellowstone/', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Yes', NULL, 'Luxury glamping retreat in Big Sky''s Moonlight Basin. Canvas tents with plush king beds, wood-burning stoves, and private en suite bathrooms. Situated on a freshwater pond surrounded by mountains.', NULL, NULL, 45.2847, NULL, -111.3681, NULL, '4-6', NULL, NULL, NULL, 'Glamping Resort', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Yes', NULL, NULL, NULL, 'Yes', 'Yes', 'Web Research 2025', 'Yes', NULL, '2', 'Yes', 'Yes', NULL, '59716', 'No'),

-- Triple G's Resort  
('Triple G''s Resort', NULL, '2-4', '13951 US Highway 2 East', 'Essex', 'MT', 'USA', 'https://www.triplegsresort.com/', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Yes', NULL, 'Glamping resort located 15 minutes east of Glacier National Park''s west entrance. Features cabins (available year-round), GeoDomes, and Sky Domes (seasonal, mid-May to early November). Amenities include full restaurant and bar (The Tavern, open 5pm-10pm), communal fire pits, and proximity to outdoor activities like hiking and fishing. Pet-friendly with non-refundable pet fee. Self-check-in with instructions emailed to guests. One-time cleaning fees apply per unit.', NULL, NULL, 48.374562, NULL, -113.686523, NULL, '5-11', 'Yes', NULL, NULL, 'Glamping Resort', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Yes', NULL, 'Yes', 'Yes', 'Yes', 'Yes', 'Web Research 2025', 'Yes', NULL, NULL, 'Yes', 'Yes', NULL, '59916', 'No'),

-- Cedar Bloom Farm
('Cedar Bloom Farm', 'A-Frame Cabin', 'Cabin', NULL, 'Cave Junction', 'OR', 'USA', 'https://www.cedarbloomfarm.com/', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Yes', 'Glamping farm on 99 acres along the Illinois River. Features hand-built tiny A-frame cabins, geodesic domes, communal kitchen, sauna, and outdoor showers.', NULL, NULL, 42.1629, NULL, -123.6481, NULL, '12', NULL, NULL, NULL, 'Glamping Farm', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Yes', 'Web Research 2025', 'Yes', NULL, '2-4', 'Yes', NULL, NULL, '97523', 'No'),

-- Clear Sky Resorts
('Clear Sky Resorts', 'Sky Dome', 'Dome', 'Scenic Byway 12', 'Cannonville', 'UT', 'USA', 'https://brycecanyon.clearskyresorts.com/', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Luxury glass-domed glamping resort on 80-acre private canyon, 15 minutes from Bryce Canyon National Park. Features 5-star mattresses, luxury linens, private designer bathrooms with rainfall showers, and climate control.', NULL, NULL, 37.5667, NULL, -112.0500, NULL, '12', NULL, NULL, NULL, 'Glamping Resort', 25, 25, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Yes', 'Yes', 'Web Research 2025', 'Yes', NULL, '2-4', 'Yes', 'Yes', 2024, '84718', 'No'),

-- Outpost X
('Outpost X', 'Cave Unit', 'Cave', NULL, 'Beryl', 'UT', 'USA', 'https://outpost-x.com/', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Yes', NULL, 'Unique sci-fi themed glamping experience on 100-acre playa. Features cave units, Zen Domes, and Viking Tents. Includes X-Spa with hot tubs, sauna, cold plunge, Cantina, and sand cruisers. Located 30 minutes west of Cedar City, 1.5 hours from Zion National Park.', NULL, NULL, 37.9000, NULL, -113.6500, NULL, '12', NULL, NULL, NULL, 'Glamping Resort', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Yes', NULL, NULL, NULL, NULL, 'Yes', 'Web Research 2025', 'Yes', NULL, '2-4', 'Yes', NULL, NULL, '84714', 'No'),

-- North Shore Camping Company
('North Shore Camping Company', 'Furnished Wall Tent', 'Tent', NULL, 'Beaver Bay', 'MN', 'USA', 'https://www.northshorecampingco.com/', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Yes', 'Glamping experience along the North Shore of Lake Superior. Features 30 furnished wall tents on wooden platforms nestled in forested hills. Includes beds, bedding, cookware, and access to modern bathrooms and showers at Base Lodge.', NULL, NULL, 47.2581, NULL, -91.3000, NULL, '10', 'Yes', NULL, NULL, 'Glamping Resort', 30, 30, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Yes', 'Web Research 2025', 'Yes', NULL, '2-4', 'Yes', NULL, 2024, '55601', 'No'),

-- Outdoors Elevated
('Outdoors Elevated', 'Royal Tent', 'Safari Tent', NULL, 'Uinta Mountains', 'UT', 'USA', 'https://theoutdoorselevated.net/', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Luxury glamping accommodations in the Uinta Mountains. Features Royal and Grand Tents with in-suite bathrooms, accommodating 2-8 guests. Offers Traditional Tents for value-oriented experience. Activities include snowmobile rentals, guided backcountry skiing, zip-line tours, off-road Can-Am tours, and mountain bike tours.', NULL, NULL, 40.7000, NULL, -110.8000, NULL, '12', NULL, NULL, NULL, 'Glamping Resort', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Yes', 'Yes', 'Web Research 2025 - Utah Focus', 'Yes', NULL, '2-8', 'Yes', NULL, 'No'),

-- Zen Zion Glamping Domes
('Zen Zion Glamping Domes', 'River Dome', 'Dome', '2200 US-89', 'Glendale', 'UT', 'USA', 'https://www.visitzenzion.com/', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Yes', 'Yes', 'Luxury glamping domes near Zion National Park. Features two geodesic domes (River Dome and Evergreen Dome), each climate-controlled with kitchenette, full bathroom, and private outdoor space with BBQ and fire pit. Virgin River runs through property. Shared pavilion with seating, BBQ, and hot tub. Pet-friendly.', NULL, NULL, 37.3000, NULL, -112.6000, NULL, '12', 'Yes', NULL, NULL, 'Glamping Resort', 2, 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Yes', NULL, NULL, NULL, 'Yes', 'Yes', 'Web Research 2025 - Utah Focus', 'Yes', NULL, 2, 'Yes', 'Yes', 2024, '84729', 'No'),

-- Onera Fredericksburg
('Onera Fredericksburg', 'Treehouse', 'Treehouse', '173 Basse Lane', 'Fredericksburg', 'TX', 'USA', 'https://stayonera.com/', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Yes', NULL, 'Luxury glamping resort in Texas Hill Country. Features treehouses, safari tents, and geodesic domes. Treehouses include private outdoor soaking tubs, elevated decks, heating and air conditioning, Wi-Fi, private bathrooms, and efficiency kitchens. Communal facilities include pool, barrel sauna, jacuzzi spa, and oak grove tree deck. Expanded Fall 2025 with 23 new treehouse units, bringing total to 35.', NULL, NULL, 30.2750, NULL, -98.8714, NULL, '12', NULL, NULL, NULL, 'Glamping Resort', 35, 35, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Yes', 'Yes', NULL, 'Yes', 'Yes', 'Yes', NULL, 'Treehouse', 'Web Research 2025 - Texas Focus', NULL, '2-4', 'Treehouse', 'Yes', NULL, '78624', 'No'),

-- Onera Wimberley
('Onera Wimberley', 'Treehouse', 'Treehouse', '801 Buttercup Lane', 'Wimberley', 'TX', 'USA', 'https://stayonera.com/locations/wimberley/', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Yes', NULL, 'Luxury glamping resort on 20 acres, 45 minutes south of Austin. Features 28 custom-designed units including 12 Spyglass treehouses and 16 Greenhouse units, each with private hot tubs, efficiency kitchens, private decks, and walk-in rain showers. Amenities include heated infinity pool, communal hot tub, lounge area, walking trails, and event venue. Opened September 2024.', NULL, NULL, 29.9970, NULL, -98.0910, NULL, '12', NULL, NULL, NULL, 'Glamping Resort', 28, 28, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Yes', 'Yes', NULL, 'Yes', 'Yes', 'Yes', NULL, 'Treehouse', 'Web Research 2025 - Texas Focus', NULL, '2-4', 'Treehouse', 'Yes', 2024, '78676', 'No'),

-- Summit Big Bend  
('Summit Big Bend', 'Cave Room', 'Cave', '2500 N Lone Star Mine Rd', 'Terlingua', 'TX', 'USA', 'https://summitbigbend.com/', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Yes', NULL, 'Unique glamping resort between Big Bend National and State Parks. Features luxury cave rooms (only cave hotel suites in Texas), stargazing domes, and stargazer deluxe suites. Cave rooms offer modern luxuries in natural setting. Domes feature clear ceiling portals for night sky views. Located in world''s largest Dark Sky Reserve.', NULL, NULL, 29.3219, NULL, -103.6172, NULL, '12', NULL, NULL, NULL, 'Glamping Resort', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Yes', NULL, NULL, 'Yes', NULL, 'Yes', 'Yes', 'Web Research 2025 - Texas Focus', 'Yes', NULL, '2-4', 'Yes', 'Yes', NULL, '79852', 'No'),

-- Camp Elena
('Camp Elena', 'Safari Tent', 'Safari Tent', '40 ET Road', 'Terlingua', 'TX', 'USA', 'https://www.campelena.com/', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Yes', NULL, 'Luxury glamping retreat less than 10 miles from Big Bend National Park. Features safari-style tents with king-size beds, en suite kitchens, full bathrooms, and private decks overlooking Chisos and Christmas Mountains. Emphasizes sustainability with solar energy and eco-friendly amenities. Offers in-tent massages and off-road Jeep tours. Located in world''s largest Dark Sky Reserve.', NULL, NULL, 29.32879, NULL, -103.61887, NULL, '12', NULL, NULL, NULL, 'Glamping Resort', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Yes', NULL, NULL, 'Yes', NULL, 'Yes', 'Yes', 'Web Research 2025 - Texas Focus', 'Yes', NULL, '2-4', 'Yes', 'Yes', NULL, '79852', 'No'),

-- Talula Mesa Glamping Resort
('Talula Mesa Glamping Resort', 'Grand Tent', 'Safari Tent', '6517 Shaw Dr', 'Marble Falls', 'TX', 'USA', 'https://www.talulamesa.com/', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Yes', NULL, 'Luxury glamping resort with stunning views of Lake Travis and Texas Hill Country. Features Grand Tents with king-sized beds, queen lofts, and expansive glass walls, plus Mini Aztec Tents. Each tent includes hot tub, hammock, and access to activities like paddleboarding, kayaking, and hiking. Approximately 55 minutes from downtown Austin.', NULL, NULL, 30.5775, NULL, -98.2750, NULL, '12', NULL, NULL, NULL, 'Glamping Resort', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Yes', 'Yes', NULL, 'Yes', 'Yes', 'Yes', 'Yes', 'Grand Tent', 'Web Research 2025 - Texas Focus', NULL, '2-4', 'Safari Tent', 'Yes', NULL, '78654', 'No'),

-- Walden Retreats
('Walden Retreats', 'Safari Tent', 'Safari Tent', '1388 Gipson Road', 'Johnson City', 'TX', 'USA', 'https://waldenretreats.com/', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Yes', NULL, 'Luxury glamping destination on 96 acres along Pedernales River. Features 15 luxury safari tents with mini-split heating and air conditioning, private bathrooms with claw-foot tubs and outdoor showers, king-size beds with Casper mattresses, full kitchens with refrigerators, and wrap-around decks with gas grills. Activities include fishing, canoeing, swimming in Pedernales River. Located 1 hour west of Austin, 1 hour north of San Antonio.', NULL, NULL, 30.3047196, NULL, -98.4750148, NULL, '12', NULL, NULL, NULL, 'Glamping Resort', 15, 15, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Yes', NULL, 'Yes', 'Safari Tent', 'Web Research 2025 - Texas Focus', 'TX', '2-4', 'Safari Tent', 'https://waldenretreats.com/', 'Yes', 'Yes', NULL, '78636', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'https://waldenretreats.com/', 'No'),

-- Space Cowboys
('Space Cowboys', 'Mirrored Space Pod', 'Dome', '52975 TX-118', 'Terlingua', 'TX', 'USA', 'https://bookspacecowboys.com/', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Yes', NULL, 'Unique glamping destination near Big Bend National Park featuring mirrored space pods with panoramic views of desert and night sky. Pods equipped with memory foam beds, air conditioning, mini-fridges, and private terraces with fire pits. Located in world''s largest Dark Sky Reserve. Pet-friendly.', NULL, NULL, 29.406256, NULL, -103.507802, NULL, '12', 'Yes', NULL, NULL, 'Glamping Resort', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Yes', NULL, NULL, 'Yes', NULL, 'Yes', 'Yes', 'Web Research 2025 - Texas Focus', 'Yes', NULL, 2, 'Yes', 'Yes', NULL, '79852', 'No'),

-- Hart's Camp
('Hart''s Camp', 'Airstream', 'Airstream', '33315-B Cape Kiwanda Drive', 'Pacific City', 'OR', 'USA', 'https://www.hartscamp.com/', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Yes', NULL, 'Coastal glamping camp just short walk from beach and Pelican Brewpub. Features unique Airstreams equipped with queen bed or bunk-style beds, bathroom, fully-equipped kitchenette, air conditioning, and private outdoor space with Adirondack chairs, fire pit, picnic table, and gas grill. Also offers cozy cottages and coastal cabins. Located near Cape Kiwanda.', NULL, NULL, 45.214943, NULL, -123.968914, NULL, '12', NULL, NULL, NULL, 'Glamping Resort', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Yes', NULL, NULL, 'Yes', NULL, 'Yes', 'Yes', 'Yes', 'Web Research 2025 - Oregon Focus', 'OR', 'Yes', 'Airstream', 'https://www.hartscamp.com/', 'Yes', 'Yes', NULL, '97135', 'No'),

-- Sheltered Nook on Tillamook Bay
('Sheltered Nook on Tillamook Bay', 'Tiny Home', 'Cabin', '7882 Warren Street', 'Bay City', 'OR', 'USA', 'https://www.shelterednook.com/', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Yes', NULL, 'Unique lodging offering village of tiny homes near Tillamook Bay. Each tiny home features full bedroom, upper loft bedroom, full kitchen, bathroom with shower, living room, dining area, and small porch. Amenities include Smart TVs, cable and streaming services, and Wi-Fi. Nestled in wooded area providing cozy retreat after exploring nearby beaches and hiking trails.', NULL, NULL, 45.51353, NULL, -123.88255, NULL, '12', NULL, NULL, NULL, 'Glamping Resort', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Yes', NULL, NULL, 'Yes', NULL, 'Yes', 'Yes', 'Web Research 2025 - Oregon Focus', 'Yes', NULL, '2-4', 'Yes', 'Yes', NULL, '97107', 'No'),

-- Crater Lake Resort
('Crater Lake Resort', NULL, '2-4', '50711 Crater Lake Highway', 'Chiloquin', 'OR', 'USA', 'Safari Tent', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Yes', NULL, 'Glamping resort approximately 30 miles from Crater Lake National Park. Offers glamping tents among various accommodations. Located along OR-62 with views of Upper Klamath Lake. Guests can enjoy fishing, kayaking, and exploring the Klamath Basin. Convenient base for visiting Crater Lake.', NULL, NULL, 42.6849614, NULL, -121.9730338, NULL, '5-10', NULL, NULL, NULL, 'Glamping Resort', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Yes', NULL, NULL, 'Yes', NULL, 'Yes', 'Yes', 'Safari Tent', 'OR', 'Yes', NULL, 'https://www.craterlakeresort.com/', 'Yes', 'Yes', NULL, '97624', 'No'),

-- Mt. Hood Tiny House Village
('Mt. Hood Tiny House Village', 'Tiny House', 'Cabin', '65000 E. Hwy 26', 'Welches', 'OR', 'USA', 'https://www.mthoodtinyhouse.com/', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Yes', NULL, 'Unique glamping site near Mount Hood featuring collection of tiny houses, each with unique personality and charm. Each tiny house ranges from 175 to 260 square feet. Amenities include free Wi-Fi, free parking, kitchen facilities, heating, air conditioning, TV, washer, dryer, hot tub, indoor fireplace, private entrance, BBQ grill, patio or balcony, and garden or backyard. Close to Mount Hood''s recreational activities including skiing, hiking, and mountain biking.', NULL, NULL, 45.35944, NULL, -121.99701, NULL, '12', NULL, NULL, NULL, 'Glamping Resort', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Yes', 'Yes', NULL, 'Yes', 'Yes', 'Yes', NULL, 'Tiny House', 'Web Research 2025 - Oregon Focus', NULL, '2-4', 'Cabin', 'Yes', NULL, '97067', 'No'),

-- Green Rock Retreat
('Green Rock Retreat', 'Safari Tent', 'Safari Tent', '15580 SW Forest Service Rd 5480', 'Culver', 'OR', 'USA', 'https://www.greenrockretreat.com/', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Yes', NULL, 'Spiritual retreat center on 50-acre sanctuary perched on rim of Crooked River Gorge, approximately 30 miles north of Bend. Family-owned, off-grid yoga sanctuary running entirely on solar power. Features seven luxury platform tents with private outdoor bathrooms, gas fireplaces, and large windows with breathtaking views. Amenities include private outdoor showers and bathrooms, flushing toilets, gas fireplace, fans and lighting, camping stovetop and tea kettle, organic linens and comforters, private deck with outdoor seating. Also features labyrinth, sacred tipi, communal splash pool, multi-purpose barn studio, energy vortex, prayer tree, fully equipped communal outdoor kitchen, Yoga Barn with attached bathroom, yoga deck, and yurt. Private hiking trails lead to 500-foot-tall overlook of Crooked River. Sober property (no alcohol).', NULL, NULL, 44.5020, NULL, -121.1900, NULL, '5-10', NULL, NULL, NULL, 'Glamping Resort', 7, 7, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Yes', NULL, 'Yes', 'Web Research 2025 - Oregon Focus', 'OR', 'Yes', 'Safari Tent', 'https://www.greenrockretreat.com/', 'Yes', 'No', NULL, '97734', 'No'),

-- Alpine Airstream Glamping
('Alpine Airstream Glamping', NULL, '2-4', NULL, 'Ashford', 'WA', 'USA', 'Airstream', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Yes', NULL, 'Luxury glamping Airstream on nearly half acre of Douglas fir forest near Nisqually River, close to Mount Rainier National Park. Features 25-foot Airstream with fully equipped kitchen, plush queen-sized bed, convertible sofa bed, covered hot tub, fire pit, BBQ grill, central air conditioning, HDTV with Fire TV, and separate shower and toilet. Access to Nisqually River.', NULL, NULL, 46.7584, NULL, -122.0216, NULL, '5-10', NULL, NULL, NULL, 'Glamping Resort', 1, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Yes', 'Yes', NULL, 'Yes', 'Yes', 'Yes', 'Airstream', 'WA', 'Yes', NULL, 'https://visitrainier.com/alpine-airstream-glamping/', 'Yes', 'Yes', NULL, '98304', 'No'),

-- Stargazer Dome
('Stargazer Dome', 'Dome', 'Dome', '2678 Highway 7', 'Mineral', 'WA', 'USA', 'https://visitrainier.com/the-stargazer-dome/', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Yes', NULL, 'Luxury two-story geodome near Mount Rainier National Park. Features well-equipped kitchen, bathroom, indoor electric fireplace, king-size bed, and private patio with fire pit. Outdoor stargazing patio offers stunning night sky views. Mountain and valley views. EV charger available. Minimum two-night stay.', NULL, NULL, 46.71387, NULL, -122.20716, NULL, '12', NULL, NULL, NULL, 'Glamping Resort', 1, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Yes', NULL, 'Yes', 'Web Research 2025 - Washington Focus', 'WA', 'Yes', 'Dome', 'https://visitrainier.com/the-stargazer-dome/', 'Yes', 'Yes', NULL, '98355', 'No'),

-- Angel of the Winds RV Resort
('Angel of the Winds RV Resort', 'Yurt', 'Yurt', '25525 Dahl Rd', 'Arlington', NULL, 'USA', 'https://rvwinds.com/', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Yes', NULL, 'Luxury RV resort offering eight luxury yurts. Each yurt features kitchenette (refrigerator and microwave), full bathroom, queen-size bed, queen-size pull-out sofa, air conditioning, heating, and ceiling fan with sky-view window. Resort amenities include clubhouse, pool, and dog park. Private parking spaces for each yurt.', NULL, NULL, 48.226520, NULL, -122.223000, NULL, '12', 'Yes', NULL, NULL, 'Glamping Resort', 8, 8, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Yes', 'Yes', 'Yes', 'Yurt', 'Web Research 2025 - Washington Focus', 'WA', '2-4', 'Yurt', 'https://rvwinds.com/', 'Yes', 'Yes', NULL, '98223', 'No'),

-- The Hill - Olympic Peninsula Glamping
('The Hill - Olympic Peninsula Glamping', 'Safari Tent', 'Safari Tent', NULL, 'Port Angeles', 'WA', 'USA', 'https://www.olympicpeninsulaglamping.com/', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Yes', NULL, 'Secluded glamping site perched atop clearing in Olympic National Park foothills, just south of Port Angeles. Features breathtaking views of Strait of Juan de Fuca. Conveniently located within short drive of many Olympic Peninsula attractions. Amenities include solar panels for charging phones and lighting, propane-powered heaters inside tent and on deck, Jetboil stove, French press, and coffee. Spacious parking pad accommodates up to two vehicles.', NULL, NULL, 48.1180, NULL, -123.4300, NULL, '5-10', NULL, NULL, NULL, 'Glamping Resort', 1, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Yes', NULL, 'Yes', 'Web Research 2025 - Washington Focus', 'WA', 'Yes', 'Safari Tent', 'https://www.olympicpeninsulaglamping.com/', 'Yes', 'No', NULL, '98362', 'No'),

-- Iron & Vine Luxury Treehouse
('Iron & Vine Luxury Treehouse', 'Treehouse', 'Treehouse', NULL, 'Ashford', 'WA', 'USA', 'https://ironandvinetreehouse.com/', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Yes', NULL, 'Luxury two-story treehouse nestled among towering fir trees near Mount Rainier National Park. Features fully functional kitchen, living area with fireplace and flat-screen TV, bathroom with waterfall shower, sleeping loft with queen-sized bed, suspended net loft for relaxation, and private deck. Accommodates up to 2 guests with sofa sleeper for third guest if needed. Not suitable for children under 13 due to steep staircase.', NULL, NULL, 46.7584, NULL, -122.0216, NULL, '5-10', NULL, NULL, NULL, 'Glamping Resort', 1, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Yes', NULL, 'Yes', 'Web Research 2025 - Washington Focus', 'WA', 'Yes', 'Treehouse', 'https://ironandvinetreehouse.com/', 'Yes', 'Yes', NULL, '98304', 'No'),

-- Alexander's Lodge Yurts
('Alexander''s Lodge Yurts', 'Yurt', 'Yurt', '37515 State Route 706 E', 'Ashford', 'WA', 'USA', 'https://alexanderslodge.com/', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Yes', NULL, 'Lodge near Nisqually Entrance of Mount Rainier National Park. Features two small rustic yurts with access to shared bath. Lodge grounds include trout pond, patio, and trail through property. No televisions in yurts.', NULL, NULL, 46.752477, NULL, -121.937292, NULL, '5-10', NULL, NULL, NULL, 'Glamping Resort', 2, 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Yes', NULL, 'Yes', 'Web Research 2025 - Washington Focus', 'WA', 'Yes', 'Yurt', 'https://alexanderslodge.com/', 'Yes', 'Yes', NULL, '98304', 'No'),

-- Darla the Glamping Trailer
('Darla the Glamping Trailer', 'Airstream', 'Airstream', NULL, 'Ashford', 'WA', 'USA', 'https://ashfordlodge.co/', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Yes', NULL, 'Vintage 1955 Westerner camping trailer located at Ashford Lodge, approximately 6 miles from Nisqually Entrance to Mount Rainier National Park. Features vintage decor, string lights, hammock, picnic table, lounge chairs, kitchenette, cozy flannel sheets, and outhouse. Shared hot tub available. Part of Ashford Lodge collection including Layla and Lois the Lo-Liner.', NULL, NULL, 46.7584413, NULL, -122.0309408, NULL, '5-10', NULL, NULL, NULL, 'Glamping Resort', 1, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Yes', NULL, 'Yes', 'Web Research 2025 - Washington Focus', 'WA', 'Yes', 'Airstream', 'https://ashfordlodge.co/', 'Yes', 'Yes', NULL, '98304', 'No'),

-- Outdoorsy Hill Country
('Outdoorsy Hill Country', 'Safari Tent', 'Safari Tent', '300 Wilke Trail', 'Stonewall', NULL, 'USA', 'https://hill-country.outdoorsy.com/', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Yes', NULL, 'Luxury glamping retreat opened Spring 2024 near Fredericksburg. Features 22 all-season canvas glamping tents on 32-acre property. Each tent includes king-size bed, climate control, private ensuite bathrooms with rain showers, and wrap-around panoramic decks. Amenities include café, bar, country store, events lodge, hiking trails, and spring-fed lake. Located minutes from Fredericksburg and Texas Wine Trail.', NULL, NULL, 30.199214, NULL, -98.636780, NULL, '12', NULL, NULL, NULL, 'Glamping Resort', 22, 22, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Yes', 'Yes', 'Yes', 'Safari Tent', 'Web Research 2025 - Texas Focus', 'TX', '2-4', 'Safari Tent', 'https://hill-country.outdoorsy.com/', 'Yes', 'Yes', 2024, '78671', 'No'),

-- Geronimo Creek Retreat
('Geronimo Creek Retreat', 'Treehouse', 'Treehouse', '2050 Laubach Rd', 'Seguin', 'TX', 'USA', 'https://www.geronimocreekretreat.com/', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Yes', NULL, 'Unique glamping retreat along spring-fed waters of Geronimo Creek. Features waterfront treehouses, massive teepees, and safari cabins with modern amenities including air conditioning, kitchenettes, and private bathrooms. Treehouses sleep up to 8 guests with full kitchens, fiber internet, Smart TVs, and private decks overlooking creek. Activities include kayaking, paddleboarding, fishing, swimming, game room, hot tub, basketball court, and volleyball court. Located near New Braunfels and Austin.', NULL, NULL, 29.6287034, NULL, -97.9422917, NULL, '12', NULL, NULL, NULL, 'Glamping Resort', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Yes', NULL, 'Yes', 'Yes', 'Yes', 'Web Research 2025 - Texas Focus', 'TX', 'Yes', 'Treehouse', 'https://www.geronimocreekretreat.com/', 'Yes', 'Yes', NULL, '78155', 'No'),

-- SKYE Texas Hill Country Resort
('SKYE Texas Hill Country Resort', 'Dome', 'Dome', '16880 US-87', 'Fredericksburg', NULL, 'USA', 'https://skyetexashillcountry.com/', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Yes', NULL, 'Luxury glamping resort opened March 2024. Features 99-site resort with 12 glamping pods and 36 cabins on 30 acres of remote 250-acre wilderness section. Nature Pods are eco-friendly accommodations with bed, kitchenette, dining table, private bath and shower. Resort amenities include gigabit-speed Wi-Fi, EV charging stations at every site, resort pool and spa, electric cart rentals, general store, sports courts, pet wash stations. Located near Fredericksburg in Texas Hill Country.', NULL, NULL, 30.470089, NULL, -98.998057, NULL, '12', NULL, NULL, NULL, 'Glamping Resort', 99, 12, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Yes', 'Yes', 'Yes', 'Nature Pod', 'Web Research 2025 - Texas Focus', 'TX', '2-4', 'Dome', 'https://skyetexashillcountry.com/', 'Yes', 'Yes', 2024, '78624', 'No'),

-- The Retreat on the Hill
('The Retreat on the Hill', 'Stardome Suite', 'Dome', '4325 Cottonwood Dr', 'Cottonwood Shores', 'TX', 'USA', 'https://theretreatonthehill.com/', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Yes', NULL, 'Luxury glamping destination perched on hilltop overlooking Lakes LBJ and Marble Falls. Features clear bubble domes (Stardome Suite with 360-degree night sky views), safari-style tents, tipis, A-frame houses, and treehouse-style lodgings. Stardome Suite includes private balcony, outdoor star-soaking tub, indoor and outdoor showers, mini-fridge, microwave, coffee maker, and private bathroom. Eagle''s Nest Retreat features luxury safari tent with king-size bed, private restroom, indoor/outdoor shower, and outdoor soaking tub. Private decks and within walking distance to local restaurants.', NULL, NULL, 30.5552, NULL, -98.3267, NULL, '12', NULL, NULL, NULL, 'Glamping Resort', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Yes', 'Yes', NULL, 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Web Research 2025 - Texas Focus', 'Yes', NULL, 2, 'Yes', 'Yes', NULL, '78657', 'No'),

-- Cypress Valley
('Cypress Valley', 'Treehouse', 'Treehouse', '1223 Paleface Ranch Rd S', 'Spicewood', 'TX', 'USA', 'https://www.cypressvalley.com/', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Yes', NULL, 'Unique glamping destination offering luxury treehouses and glamping tents nestled among ancient cypress trees. Features variety of treehouses including Yoki Treehouse (luxury multi-room, sleeps 2-3), The Nest (Swiss Family-style, sleeps up to 6), Lofthaven (romantic aerial yurt with suspension bridge to bathhouse with waterfall tub), and Willow and Juniper (upscale glamping treehouses). Tent Village offers off-grid luxury camping with king beds and private decks. Amenities include private decks, shared restrooms and showers, gas BBQ grills, outdoor games, and seasonal swimming pool. Located approximately 45 minutes from downtown Austin.', NULL, NULL, 30.3000, NULL, -98.1000, NULL, '12', NULL, NULL, NULL, 'Glamping Resort', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Yes', NULL, 'Yes', 'Yes', 'Yes', 'Web Research 2025 - Texas Focus', 'TX', 'Yes', 'Treehouse', 'https://www.cypressvalley.com/', 'Yes', 'Yes', NULL, '78669', 'No'),

-- Safari for the Soul Glamping
('Safari for the Soul Glamping', 'Safari Tent', 'Safari Tent', '9109 RM 1431', 'Marble Falls', 'TX', 'USA', 'http://www.safariforthesoulglamping.com/', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Yes', NULL, 'Luxurious adults-only glamping experience along Colorado River. Features modern Indonesian-inspired safari tents equipped with plush king beds, private hot tubs, and fire pits. Each tent offers riverfront views and access to activities including kayaking, hiking, and stargazing. Located in Texas Hill Country near Marble Falls.', NULL, NULL, 30.5800, NULL, -98.2700, NULL, '12', NULL, NULL, NULL, 'Glamping Resort', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Yes', 'Yes', NULL, 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Web Research 2025 - Texas Focus', 'Yes', NULL, 2, 'Yes', 'Yes', NULL, '78654', 'No'),

-- Collective Hill Country - a Retreat at Montesino Ranch
('Collective Hill Country - a Retreat at Montesino Ranch', NULL, '2', '7431 Fulton Ranch Rd', 'Wimberley', 'TX', 'USA', 'Safari Tent', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Yes', NULL, 'Luxury glamping retreat on Montesino Ranch in Texas Hill Country. Features spacious canvas tents equipped with plush beds featuring high-thread-count linens, en-suite bathrooms with hot showers, and private decks overlooking scenic Montesino Ranch. Offers farm-to-table dining experiences including gourmet breakfasts and multi-course dinners prepared by on-site chefs. Activities include horseback riding, hiking, yoga sessions, wine tasting at nearby vineyards, live sound meditation sessions, and Axe & Arrow Club (archery and tomahawk throwing). Located approximately 45 minutes from Austin and 1 hour from San Antonio.', NULL, NULL, 29.9535492, NULL, -98.0422299, NULL, '12', NULL, NULL, NULL, 'Glamping Resort', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Yes', 'Yes', 'Yes', 'Yes', 'Safari Tent', 'TX', 'Yes', NULL, 'https://www.collectiveretreats.com/retreat/collective-hill-country/', 'Yes', 'Yes', NULL, '78676', 'No'),

-- Spoon Mountain Glamping
('Spoon Mountain Glamping', 'Safari Tent', 'Safari Tent', '210 Masonic Lodge Rd', 'Wimberley', 'TX', 'USA', 'https://www.spoonmountainglamping.com/', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Yes', NULL, 'Luxury glamping experience featuring authentic South African safari tents designed for comfort and relaxation. Features three uniquely decorated tents (Kingfisher - wheelchair-accessible with panoramic Wimberley Valley views, Shaka - bright and airy near communal fire pit, Chisum - masculine decor with earthy wood tones and leather furniture). Each tent includes king-size beds, cozy seating areas, spa-like bathrooms, climate control, Wi-Fi, private decks with soaking tubs, and private pools. Additional amenities include community area with fire pit, games, hot tub, and dry sauna. Located in Wimberley, Texas Hill Country.', NULL, NULL, 29.99957, NULL, -98.08243, NULL, '12', NULL, NULL, NULL, 'Glamping Resort', 3, 3, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Yes', 'Yes', NULL, 'Yes', 'Yes', 'Yes', 'Yes', 'Web Research 2025 - Texas Focus', 'TX', 'Yes', 'Safari Tent', 'https://www.spoonmountainglamping.com/', 'Yes', 'Yes', NULL, '78676', 'No'),

-- Cameron Ranch Glamping - Bastrop
('Cameron Ranch Glamping - Bastrop', 'Dome', 'Dome', '375 S Shore Rd', 'Bastrop', 'TX', 'USA', 'https://cameronranchglamping.com/', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Yes', NULL, 'Luxury glamping accommodations near Austin and Houston. Features designer cabins and geo domes providing unique blend of comfort and nature. Bastrop location includes The Hideaway ÖÖD Mirror House (mirrored cabin), The Bloom ÖÖD Mirror House (mirrored cabin), and Premium Lakefront Cabins (The Magnolia, The Firefly, The Cardinal) with lakefront views. Located near Lake Bastrop, approximately 30 minutes from Austin.', NULL, NULL, 30.13778, NULL, -97.28475, NULL, '12', NULL, NULL, NULL, 'Glamping Resort', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Yes', NULL, 'Yes', 'Yes', 'Yes', 'Web Research 2025 - Texas Focus', 'TX', 'Yes', 'Dome', 'https://cameronranchglamping.com/', 'Yes', 'Yes', NULL, '78602', 'No'),

-- North Texas Jellystone Park
('North Texas Jellystone Park', 'Tipi', 'Tipi', '2301 S Burleson Blvd', 'Burleson', 'TX', 'USA', 'https://www.northtexasjellystone.com/', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Yes', NULL, 'RV park offering unique glamping experience with Glamping Tipis introduced June 2023. Each spacious and luxurious tipi accommodates up to 6-7 guests and includes plush king-size bed, queen/twin bunk beds, futon, heating or air conditioning, mini-fridge, microwave, and dinette set. Outside features private grill and picnic table. Restrooms and showers conveniently located nearby. Located in North Texas near Dallas-Fort Worth area.', NULL, NULL, 32.4948585, NULL, -97.2840868, NULL, '12', 'Yes', NULL, NULL, 'Glamping Resort', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Yes', NULL, 'Yes', 'Yes', 'Yes', 'Web Research 2025 - Texas Focus', 'TX', 'Yes', 'Tipi', 'https://www.northtexasjellystone.com/', 'Yes', 'Yes', NULL, '76028', 'No'),

-- The Glamping Collective
('The Glamping Collective', 'Geo Dome', 'Dome', '2504 Crabtree Mountain Rd', 'Clyde', 'NC', 'USA', 'https://www.theglampingcollective.com/', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Yes', NULL, 'Luxury mountaintop glamping retreat opened early 2023 on 160-acre property. Features Geo Domes, XL Geo Domes, and Glass Cabins, available in standard or ''Luxe'' versions with hot tubs, fire tables, and fireplaces. Each accommodation equipped with modern conveniences and private hot tubs. Property includes five miles of hiking trails, including Sunset Summit Trail leading to mountain''s summit. Located 20 minutes west of Asheville in Blue Ridge Mountains.', NULL, NULL, 35.58799, NULL, -82.86331, NULL, '12', NULL, NULL, NULL, 'Glamping Resort', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Yes', 'Yes', NULL, 'Yes', 'Yes', 'Yes', NULL, 'Geo Dome', 'Web Research 2025 - North Carolina Focus', NULL, '2-4', 'Dome', 'Yes', 2023, '28721', 'No'),

-- AutoCamp Asheville
('AutoCamp Asheville', 'Airstream', 'Airstream', '125 Amberglow Rd', 'Asheville', 'NC', 'USA', 'https://autocamp.com/asheville/', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Yes', NULL, 'Luxury glamping resort set to open March 2026 on 16-acre property along French Broad River. Features 67 accommodations including 55 custom Airstreams, two cabins, and four premium basecamp suites. Amenities include all-season plunge pool, spa, and 5,000-square-foot clubhouse housing lounge, kitchen, and general store. Located near mountain biking trails and breweries. Part of AutoCamp brand.', NULL, NULL, 35.652630, NULL, -82.473260, NULL, '12', NULL, NULL, NULL, 'Glamping Resort', 67, 67, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Yes', 'Yes', NULL, 'Yes', 'Yes', 'Yes', 'Yes', 'Web Research 2025 - North Carolina Focus', 'NC', 'Yes', 'Airstream', 'https://autocamp.com/asheville/', 'Yes', 'Yes', 2026, '28804', 'No'),

-- Tuxedo Falls
('Tuxedo Falls', 'Safari Tent', 'Safari Tent', '100 Twin Creeks Rd', 'Zirconia', 'NC', 'USA', 'https://tuxedofalls.com/', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Yes', NULL, 'Luxury glamping retreat opened July 2025. Features four safari-style tents and two elevated treehouses, each climate-controlled with luxury linens, en suite bathrooms, private decks, kitchenettes, and pizza ovens. Some units offer heated bathroom floors and soaking tubs with scenic views. Property boasts private hiking trails leading to five waterfalls including Tuxedo Falls. Activities include birding, stargazing, and guided fly-fishing excursions. 3,300-square-foot event lodge under construction with food market, breakfast area, activity rooms, and bar.', NULL, NULL, 35.1966, NULL, -82.4796, NULL, '12', NULL, NULL, NULL, 'Glamping Resort', 6, 6, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Yes', NULL, 'Yes', NULL, 'Safari Tent', 'Web Research 2025 - North Carolina Focus', NULL, '2-4', 'Safari Tent', 'https://tuxedofalls.com/', 'Yes', 'Yes', 2025, '28790', 'No'),

-- Sky Ridge Yurts
('Sky Ridge Yurts', 'Yurt', 'Yurt', '200 Sky Ridge Dr', 'Bryson City', 'NC', 'USA', 'https://www.skyridgeyurts.com/', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Yes', NULL, 'Voted No. 1 glamping spot in the U.S. for 2024. Features eight distinct yurts equipped with cooking areas, full baths, heating, and air conditioning, accommodating up to six guests each. Each yurt offers unique design and modern amenities. Located in Great Smoky Mountains region near Bryson City.', NULL, NULL, 35.3334195, NULL, -83.5757228, NULL, '12', NULL, NULL, NULL, 'Glamping Resort', 8, 8, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Yes', NULL, 'Yes', NULL, 'Yurt', 'Web Research 2025 - North Carolina Focus', NULL, '2-6', 'Yurt', 'https://www.skyridgeyurts.com/', 'Yes', 'Yes', NULL, '28713', 'No'),

-- Glamping Wild
('Glamping Wild', 'Dome', 'Dome', '1421 Flatwoods School Rd', 'Creston', 'NC', 'USA', 'https://goglampingwild.com/', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Yes', NULL, 'Luxury glamping retreat in Blue Ridge Mountains. Features luxury geodesic domes with private decks, ensuite bathrooms, and scenic views of Pond Mountain. Each dome equipped with queen-sized Thuma bed, fully equipped kitchenette, private bathroom, and spacious private deck with fire table and herb garden. Dog-friendly options available. On-site activities include hiking trails, wetland preserve, and streamside relaxation areas.', NULL, NULL, 36.46407, NULL, -81.65368, NULL, '12', 'Yes', NULL, NULL, 'Glamping Resort', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Yes', NULL, 'Yes', 'Yes', NULL, 'Web Research 2025 - North Carolina Focus', 'NC', 'Yes', 'Dome', 'https://goglampingwild.com/', 'Yes', 'Yes', NULL, '28615', 'No'),

-- Asheville Glamping
('Asheville Glamping', 'Dome', 'Dome', '20 Spring Cove Rd', 'Asheville', 'NC', 'USA', 'https://www.ashevilleglamping.com/', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Yes', NULL, 'Unique glamping accommodations near Asheville. Features geodesic domes and treehouses including Slide Dome with nine-foot slide and Nest Tree House accessible via suspension bridges. Parkway Dome offers pastoral and mountain views, queen bed, air conditioning, lights and outlets, private fire pit, private outdoor shower, and private waterless toilet. Nest treehouse is adults-only featuring queen bed, small kitchen with refrigerator and sink, Keurig coffee maker, microwave, and private bathroom with shower. Located near Blue Ridge Mountains.', NULL, NULL, 35.6530, NULL, -82.5550, NULL, '12', NULL, NULL, NULL, 'Glamping Resort', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Yes', NULL, 'Yes', 'Yes', NULL, 'Web Research 2025 - North Carolina Focus', 'NC', 'Yes', 'Dome', 'https://www.ashevilleglamping.com/', 'Yes', 'Yes', NULL, '28804', 'No'),

-- Emberglow Outdoor Resort
('Emberglow Outdoor Resort', NULL, '2-4', '95 Pinewood Trl', 'Mill Spring', 'NC', 'USA', 'Treehouse', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Yes', NULL, 'Outdoor resort offering variety of glamping accommodations including luxe treehouses with private decks, full kitchens, and bathrooms, as well as safari tents set against the woods. Also features yurts, vintage campers, and tiny homes. Resort amenities include resort-quality pool, hiking and biking trails, dog park, and free Wi-Fi. Located in western North Carolina.', NULL, NULL, 35.297811, NULL, -82.161944, NULL, '12', 'Yes', NULL, NULL, 'Glamping Resort', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Yes', 'Yes', 'Yes', 'Yes', 'Treehouse', 'NC', 'Yes', NULL, 'https://emberglowoutdoorresort.com/', 'Yes', 'Yes', NULL, '28756', 'No'),

-- Pisgah Glamping at Lake Powhatan
('Pisgah Glamping at Lake Powhatan', 'Canvas Tent', 'Canvas Tent', '375 Wesley Branch Rd', 'Asheville', 'NC', 'USA', 'https://www.pisgah-glamping.com/', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Yes', NULL, 'Luxury glamping experience in Pisgah National Forest, just 10 minutes from downtown Asheville. Features 12 custom-designed, fully furnished canvas platform tents. Each 12'' x 16'' weatherproof canvas wall tent accommodates up to four guests with queen bed with linens, foldable cot, bedside table, fan, and large screened windows. Each site includes front porch with chairs, picnic table, and fire ring with grill. Shared bathroom facilities with hot showers available within Lake Powhatan Campground. Water pumps and power units for charging electronics provided. Short walk to Lake Powhatan for swimming and fishing. Adjacent to Bent Creek Experimental Forest with extensive hiking and mountain biking trails.', NULL, NULL, 35.4816667, NULL, -82.6300, NULL, '4-10', 'Yes', NULL, NULL, 'Glamping Resort', 12, 12, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Yes', NULL, 'Yes', 'Yes', 'Canvas Tent', 'Web Research 2025 - North Carolina Focus', NULL, '2-4', 'Tent', 'https://www.pisgah-glamping.com/', 'Yes', 'Yes', NULL, '28806', 'No'),

-- Yak Eco Camp
('Yak Eco Camp', 'Dome', 'Dome', '186 Meece Rd', 'Rosman', 'NC', 'USA', 'https://yakbrevard.com/', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Yes', NULL, 'Luxury dome glamping in Blue Ridge Mountains near Brevard. Features three fully furnished geodesic domes, each equipped with private kitchens, bathrooms, and HVAC systems. Amenities include stocked trout pond (catch and release only), barrel sauna, and proximity to Pisgah National Forest, DuPont State Forest, and French Broad River. Located 20 minutes from Asheville Airport (AVL) and 32 miles from Biltmore Estate.', NULL, NULL, 35.126991, NULL, -82.827175, NULL, '12', NULL, NULL, NULL, 'Glamping Resort', 3, 3, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Yes', NULL, 'Yes', 'Yes', 'Dome', 'Web Research 2025 - North Carolina Focus', NULL, '2-4', 'Dome', 'https://yakbrevard.com/', 'Yes', 'Yes', NULL, '28772', 'No'),

-- Elk Hollow Resort
('Elk Hollow Resort', 'Safari Tent', 'Safari Tent', '74 Elk Hollow Rd', 'Bryson City', 'NC', 'USA', 'https://elkhollowresort.com/', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Yes', NULL, 'Luxury glamping destination opened October 2025. Features upscale tents nestled in the mountains near Bryson City in Great Smoky Mountains region. Provides serene and comfortable outdoor experience with modern amenities. Located in scenic mountain setting.', NULL, NULL, 35.4222, NULL, -83.4422, NULL, '12', NULL, NULL, NULL, 'Glamping Resort', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Yes', NULL, 'Yes', 'Yes', NULL, 'Web Research 2025 - North Carolina Focus', 'NC', 'Yes', 'Safari Tent', 'https://elkhollowresort.com/', 'Yes', 'Yes', 2025, '28713', 'No'),

-- Paint Rock Farm
('Paint Rock Farm', 'Cabin', 'Cabin', '1295 Paint Rock Rd', 'Hot Springs', 'NC', 'USA', 'https://www.paintrockfarm.com/', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Yes', NULL, 'Glamping resort bordering Pisgah National Forest. Features 11 glamping cabins with memory foam mattresses, fine linens, fire pits, and private decks. Property provides access to hiking, caving, and horseback riding in Pisgah National Forest. Located in Hot Springs, North Carolina.', NULL, NULL, 35.9332, NULL, -82.8910, NULL, '12', NULL, NULL, NULL, 'Glamping Resort', 11, 11, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Yes', NULL, 'Yes', NULL, 'Cabin', 'Web Research 2025 - North Carolina Focus', NULL, '2-4', 'Cabin', 'https://www.paintrockfarm.com/', 'Yes', 'Yes', NULL, '28743', 'No'),

-- Timberline Glamping at Amelia Island
('Timberline Glamping at Amelia Island', 'Dome', 'Dome', '9500 First Coast Highway', 'Fernandina Beach', 'FL', 'USA', 'https://ameliaisland.tlglamping.com/', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Yes', NULL, 'Luxury glamping resort opening mid-to-late March 2025 within Amelia Island State Park. Features six safari-style tents and a 33-foot geodesic dome. Each accommodation includes en suite bathrooms, climate control, and wellness services like saunas and in-accommodation massages. Located on Amelia Island along Atlantic coast.', NULL, NULL, 30.5700, NULL, -81.4500, NULL, '12', NULL, NULL, NULL, 'Glamping Resort', 7, 7, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Yes', NULL, 'Yes', 'Yes', 'Dome', 'Web Research 2025 - Florida Focus', NULL, '2-4', 'Dome', 'https://ameliaisland.tlglamping.com/', 'Yes', 'Yes', 2025, '32034', 'No'),

-- Twin Lakes Camp Resort
('Twin Lakes Camp Resort', 'Safari Tent', 'Safari Tent', '580 Holley King Rd', 'Defuniak Springs', 'FL', 'USA', 'http://www.twinlakescampresort.com/', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Yes', NULL, 'Lakeside glamping resort featuring fully furnished glamping tents with air conditioning, running water, and private bathrooms. Tents equipped with king-size beds and claw-foot tubs with stunning lake views. Also offers luxury cabin suites, tiny homes, and lake houses. Amenities include activity center, laundry facilities, boat and kayak rentals, and pool. Activities include fishing, kayaking, and swimming on adjacent Holley and King Lakes. Located in northwest Florida.', NULL, NULL, 30.7782992, NULL, -86.1809473, NULL, '12', NULL, NULL, NULL, 'Glamping Resort', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Web Research 2025 - Florida Focus', 'FL', 'Yes', 'Safari Tent', 'http://www.twinlakescampresort.com/', 'Yes', 'Yes', NULL, '32433', 'No'),

-- Westgate River Ranch Resort & Rodeo
('Westgate River Ranch Resort & Rodeo', 'Safari Tent', 'Safari Tent', '3200 River Ranch Blvd', 'River Ranch', 'FL', 'USA', 'https://www.westgateresorts.com/hotels/florida/river-ranch/westgate-river-ranch-resort/', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Yes', NULL, 'Voted No. 1 Glamping Spot by USA Today''s 10Best 2023 Readers'' Choice Awards. Offers luxury glamping accommodations including Luxury Glamping Tents, Luxe Teepees, and Luxe Conestoga Wagons. Tents set on platforms, furnished with real beds, air conditioning, heating, and private bathrooms. All-inclusive amenities and entertainment. Activities include horseback riding, airboat rides, and Saturday night rodeo. Located approximately one hour south of Orlando.', NULL, NULL, 27.77042, NULL, -81.21200, NULL, '12', NULL, NULL, NULL, 'Glamping Resort', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Web Research 2025 - Florida Focus', 'FL', 'Yes', 'Safari Tent', 'https://www.westgateresorts.com/hotels/florida/river-ranch/westgate-river-ranch-resort/', 'Yes', 'Yes', NULL, '33867', 'No'),

-- Keystone Heights RV Resort
('Keystone Heights RV Resort', 'Wagon', 'Wagon', '1177 SE Keystone Ave', 'Keystone Heights', 'FL', 'USA', 'https://www.keystoneheightsrv.com/', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Yes', NULL, 'RV resort offering unique covered wagon glamping accommodations. Handcrafted covered wagons by PlainsCraft combine rustic charm with modern comforts. Each wagon includes electricity, heating and air conditioning, private bathroom with vanity and shower, plush bedding, and handcrafted Amish wheels. Built with premium weather-resistant canvas, designed for comfort in every season. Located in north-central Florida.', NULL, NULL, 29.8053, NULL, -82.0607, NULL, '12', NULL, NULL, NULL, 'Glamping Resort', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Yes', NULL, 'Yes', 'Yes', NULL, 'Web Research 2025 - Florida Focus', 'FL', 'Yes', 'Wagon', 'https://www.keystoneheightsrv.com/', 'Yes', 'Yes', NULL, '32656', 'No'),

-- Timberline Glamping at Kissimmee Prairie Preserve
('Timberline Glamping at Kissimmee Prairie Preserve', 'Safari Tent', 'Safari Tent', '33104 NW 192nd Ave', 'Okeechobee', 'FL', 'USA', 'https://kissimmee.tlglamping.com/', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Yes', NULL, 'Glamping experience set to open late December 2025 in internationally recognized Dark Sky Park. Located within Kissimmee Prairie Preserve State Park, ideal for stargazing enthusiasts. Offers unique glamping accommodations in pristine natural setting. Located in central Florida.', NULL, NULL, 27.584069, NULL, -81.045285, NULL, '12', NULL, NULL, NULL, 'Glamping Resort', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Yes', NULL, 'Yes', 'Yes', NULL, 'Web Research 2025 - Florida Focus', 'FL', 'Yes', 'Safari Tent', 'https://kissimmee.tlglamping.com/', 'Yes', 'Yes', 2025, '34972', 'No'),

-- Flamingo Everglades Glamping Tents
('Flamingo Everglades Glamping Tents', 'Safari Tent', 'Safari Tent', '1 Flamingo Lodge Highway', 'Homestead', 'FL', 'USA', 'https://flamingoeverglades.com/', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Yes', NULL, 'Glamping tents located within Everglades National Park at Flamingo. Offers seasonal glamping experiences: Winter Glamping Tents (November 1 - April 30) with fans, electricity, elevated platforms, queen or double beds, linens, lamp with USB connector, fan, power outlets, access to secure bathrooms and separate dining area. Summer Glamping Tents (May 1 - October 31) with fans and electricity, guests bring own bedding and camping gear. Located at southernmost visitor center in Everglades National Park.', NULL, NULL, 25.138935, NULL, -80.925380, NULL, '5-10', NULL, NULL, NULL, 'Glamping Resort', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Yes', NULL, 'Yes', 'Yes', 'Yes', 'Web Research 2025 - Florida Focus', 'FL', 'Yes', 'Safari Tent', 'https://flamingoeverglades.com/', 'Yes', 'Yes', NULL, '33034', 'No'),

-- Timberline Glamping at Collier-Seminole State Park
('Timberline Glamping at Collier-Seminole State Park', 'Safari Tent', 'Safari Tent', '20200 Tamiami Trail East', 'Naples', 'FL', 'USA', 'https://naples.tlglamping.com/', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Yes', NULL, 'Spacious safari tents equipped with modern comforts within Collier-Seminole State Park. Features Deluxe Safari Tent with king-size bed and two sets of bunk beds (accommodates up to 6 guests) and Double Safari Tent with two queen beds (accommodates up to 4 guests). Each tent includes Keurig coffee maker, mini-refrigerator, rugs, lamps, diffuser, electrical outlets, and climate control. Outdoor amenities include hammocks, fire pit with cooking grate, string lights, camp chairs, and picnic table. Located near Naples in southwest Florida.', NULL, NULL, 25.9570, NULL, -81.6080, NULL, '12', NULL, NULL, NULL, 'Glamping Resort', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Yes', NULL, 'Yes', 'Yes', 'Yes', 'Web Research 2025 - Florida Focus', 'FL', 'Yes', 'Safari Tent', 'https://naples.tlglamping.com/', 'Yes', 'Yes', NULL, '34114', 'No'),

-- Safari Wilderness Glamping
('Safari Wilderness Glamping', 'Safari Tent', 'Safari Tent', '10850 Moore Road', 'Lakeland', 'FL', 'USA', 'https://safariwilderness.com/', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Yes', NULL, 'African safari-style glamping experience. Features beautifully appointed safari tents with air conditioning and heating, accommodating up to four individuals. Continental breakfast included. Guests can participate in guided safaris by camel-back, ATV, kayak, or customized vehicle. Unique wildlife viewing and safari experience in central Florida.', NULL, NULL, 28.2389, NULL, -81.9025, NULL, '12', NULL, NULL, NULL, 'Glamping Resort', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Yes', NULL, 'Yes', 'Yes', NULL, 'Web Research 2025 - Florida Focus', 'FL', 'Yes', 'Safari Tent', 'https://safariwilderness.com/', 'Yes', 'Yes', NULL, '33809', 'No'),

-- Shell Camp Florida
('Shell Camp Florida', 'Tent', 'Tent', '4013 SE 19th Place #101', 'Cape Coral', 'FL', 'USA', 'https://www.shellcampflorida.com/', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Yes', NULL, 'Eco-friendly tour company offering 4-day/3-night all-inclusive glamping expeditions on barrier island within Ten Thousand Islands region. Guests engage in activities like seashell collection, fishing, birdwatching, and stargazing. Comfortable accommodations blend glamour with rugged charm of camping. Located in southwest Florida near Ten Thousand Islands.', NULL, NULL, 26.5629, NULL, -81.9495, NULL, '12', NULL, NULL, NULL, 'Glamping Resort', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Yes', NULL, 'Yes', 'Yes', 'Yes', 'Tent', 'Web Research 2025 - Florida Focus', 'FL', '2-4', 'Tent', 'https://www.shellcampflorida.com/', 'Yes', 'Yes', NULL, '33904', 'No'),

-- Clayoquot Wilderness Lodge
('Clayoquot Wilderness Lodge', 'Safari Tent', 'Safari Tent', 'Bedwell River Valley', 'Tofino', 'BC', 'Canada', 'https://clayoquotwildernesslodge.com/', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Yes', NULL, 'Exclusive luxury wilderness lodge accessible only by boat or seaplane. Celebrating 25th season in 2025. Features 25 luxuriously appointed canvas tents along banks of Clayoquot Sound. Each tent includes heated floors, king beds, and cedar rain showers or soaking tubs. Activities include kayaking, horseback riding, hiking, heli-hiking, tidal-zone wildlife tours, and whale-watching tours. Located in Bedwell River Valley, Clayoquot Sound, approximately 30 minutes by boat from Tofino or 45 minutes by seaplane from Vancouver.', NULL, NULL, 49.1536429, NULL, -125.904961, NULL, '5-10', NULL, NULL, NULL, 'Glamping Resort', 25, 25, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Yes', NULL, 'Yes', 'Yes', 'Safari Tent', 'Web Research 2025 - British Columbia Focus', NULL, '2-4', 'Safari Tent', 'https://clayoquotwildernesslodge.com/', 'Yes', 'Yes', NULL, 'V0R 2Z0', 'No'),

-- Rockwater Secret Cove Resort
('Rockwater Secret Cove Resort', 'Tenthouse Suite', 'Safari Tent', '5356 Oles Cove Rd', 'Halfmoon Bay', 'BC', 'Canada', 'https://rockwatersecretcoveresort.com/', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Yes', NULL, 'Luxury oceanfront glamping resort. Features Tenthouse Suites with private verandas, king-size beds, hydro-therapy tubs, rain forest showers, propane fireplaces, and radiant floor heating. Each suite offers stunning ocean views. Guests can enjoy kayaking, spa treatments, and hiking nearby trails. Located on Sunshine Coast.', NULL, NULL, 49.5421238, NULL, -123.9780167, NULL, '12', NULL, NULL, NULL, 'Glamping Resort', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Yes', 'Yes', NULL, 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Web Research 2025 - British Columbia Focus', 'Yes', NULL, 2, 'Yes', 'Yes', NULL, 'V0N 1Y2', 'No'),

-- Siwash Lake Wilderness Resort & Ranch
('Siwash Lake Wilderness Resort & Ranch', 'Safari Tent', 'Safari Tent', 'Eagan Bonaparte Forest Service Rd #3700', 'Thompson-Nicola E', 'BC', 'Canada', 'https://www.siwashlake.com/', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Yes', NULL, 'Ultra-private wilderness resort and ranch offering boutique, high-end accommodations and eco-friendly wilderness adventures. Hosts limited number of guests to ensure exclusivity. Features luxury glamping accommodations in pristine wilderness setting. Activities include horseback riding, whitewater rafting, fly fishing, and mountain biking. Located in Thompson-Nicola region of British Columbia.', NULL, NULL, 51.3040, NULL, -121.3961, NULL, '5-10', NULL, NULL, NULL, 'Glamping Resort', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Yes', NULL, 'Yes', 'Yes', NULL, 'Web Research 2025 - British Columbia Focus', 'BC', 'Yes', 'Safari Tent', 'https://www.siwashlake.com/', 'Yes', 'Yes', NULL, 'V0K 2K2', 'No'),

-- Riverside - A Parkbridge Camping & RV Resort
('Riverside - A Parkbridge Camping & RV Resort', 'Yurt', 'Yurt', '8018 Mons Rd', 'Whistler', 'BC', 'Canada', 'https://www.parkbridge.com/en/resort/resort-detail/riverside', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Yes', NULL, 'Year-round resort offering trendy yurts perched on platforms surrounded by large trees with breathtaking views of mountain peaks and Whistler Valley. Also offers log-constructed Western-cedar cabins. Located between Green Lake and Lost Lake. Near Valley Trail for biking, in-line skating, jogging, or hiking. Located in Whistler, British Columbia.', NULL, NULL, 50.136450, NULL, -122.952060, NULL, '12', NULL, NULL, NULL, 'Glamping Resort', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Yes', NULL, 'Yes', 'Yes', NULL, 'Web Research 2025 - British Columbia Focus', 'BC', 'Yes', 'Yurt', 'https://www.parkbridge.com/en/resort/resort-detail/riverside', 'Yes', 'Yes', NULL, 'V8E 1K6', 'No'),

-- Winderdome Resort
('Winderdome Resort', 'Dome', 'Dome', '1535 Windermere Loop Rd', 'Windermere', 'BC', 'Canada', 'https://winderdome.com/', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Yes', NULL, 'Luxury glamping resort nestled in tranquil forest setting. Features fully serviced, heated, and air-conditioned geodesic dome tents. Each dome offers modern amenities and comfort. Access to private pool available for additional fee. Located directly across from Mount Swansea Recreation Site in Columbia Valley.', NULL, NULL, 50.4740, NULL, -115.9920, NULL, '12', NULL, NULL, NULL, 'Glamping Resort', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Yes', 'Yes', 'Yes', 'Yes', NULL, 'Web Research 2025 - British Columbia Focus', 'BC', 'Yes', 'Dome', 'https://winderdome.com/', 'Yes', 'Yes', NULL, 'V0B 2L1', 'No'),

-- Wild Havens Pop Up Glamping
('Wild Havens Pop Up Glamping', 'Safari Tent', 'Safari Tent', '40330 Government Rd', 'Squamish', 'BC', 'Canada', 'https://www.wildhavens.ca/', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Yes', NULL, 'Pop-up glamping service offering safari-style canvas tents in scenic locations throughout British Columbia from Okanagan to Cariboo. Fully mobile service that can set up tent at designated site of your choosing. Tents fully furnished with real beds and rustic furnishings. Provides glamping experiences in Sea to Sky corridor, Vancouver Island, and South-Central Interior.', NULL, NULL, 49.73996, NULL, -123.13668, NULL, '5-10', NULL, NULL, NULL, 'Glamping Resort', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Yes', NULL, 'Yes', 'Yes', NULL, 'Web Research 2025 - British Columbia Focus', 'BC', 'Yes', 'Safari Tent', 'https://www.wildhavens.ca/', 'Yes', 'Yes', NULL, 'V0N 1T0', 'No'),

-- Boulder Mountain Resort
('Boulder Mountain Resort', 'Dome', 'Dome', '3069 Trans-Canada Hwy', 'Revelstoke', 'BC', 'Canada', 'https://bouldermountainresort.ca/', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Yes', NULL, 'Mountain resort combining rustic charm with luxurious amenities. Features geodesic glamping domes with skylight views, private outdoor firepits, king-size beds, and half bathrooms. Also offers glamping tents. Located in Revelstoke, British Columbia, along Trans-Canada Highway.', NULL, NULL, 50.991180, NULL, -118.263440, NULL, '12', NULL, NULL, NULL, 'Glamping Resort', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Yes', NULL, 'Yes', 'Yes', NULL, 'Web Research 2025 - British Columbia Focus', 'BC', 'Yes', 'Dome', 'https://bouldermountainresort.ca/', 'Yes', 'Yes', NULL, 'V0E 2S0', 'No'),

-- WOODS on Pender
('WOODS on Pender', 'Cabin', 'Cabin', '4709 Canal Road', 'Pender Island', 'BC', 'Canada', 'https://woodsonpender.com/', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Yes', NULL, 'Unique glamping accommodations on Pender Island, short ferry ride from Vancouver. Features stylish accommodations nestled in nature. Located on Pender Island in Gulf Islands, British Columbia.', NULL, NULL, 48.76823, NULL, -123.27494, NULL, '12', NULL, NULL, NULL, 'Glamping Resort', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Yes', NULL, 'Yes', 'Yes', NULL, 'Web Research 2025 - British Columbia Focus', 'BC', 'Yes', 'Cabin', 'https://woodsonpender.com/', 'Yes', 'Yes', NULL, 'V0N 2M1', 'No'),

-- Owl's Perch Treehouse
('Owl''s Perch Treehouse', 'Treehouse', 'Treehouse', '2519 Brule Dr', 'Sooke', 'BC', 'Canada', 'https://eastsooketreehouse.com/', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Yes', NULL, 'Beautifully designed A-frame treehouse perched 30 feet above ground, offering spectacular views of surrounding rainforest and Salish Sea to mountains of Washington state. Features queen-sized bed, small kitchenette, and spacious deck. Nestled among large cedars and giant maple tree. Located on Vancouver Island near Sooke.', NULL, NULL, 48.3917, NULL, -123.7370, NULL, '12', NULL, NULL, NULL, 'Glamping Resort', 1, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Yes', NULL, 'Yes', NULL, 'Treehouse', 'Web Research 2025 - British Columbia Focus', NULL, 2, 'Treehouse', 'https://eastsooketreehouse.com/', 'Yes', 'Yes', NULL, 'V9Z 0X8', 'No'),

-- Free Spirit Spheres
('Free Spirit Spheres', 'Treehouse', 'Treehouse', '420 Horne Lake Rd', 'Qualicum Beach', 'BC', 'Canada', 'https://www.freespiritspheres.com/', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Yes', NULL, 'Unique glamping experience featuring spherical treehouses suspended among trees in coastal rainforest. Offers cozy and surreal escape in nature. Each sphere provides unique accommodation experience. Located on Vancouver Island near Qualicum Beach.', NULL, NULL, 49.3450, NULL, -124.6870, NULL, '12', NULL, NULL, NULL, 'Glamping Resort', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Yes', NULL, 'Yes', 'Yes', NULL, 'Web Research 2025 - British Columbia Focus', 'BC', 'Yes', 'Treehouse', 'https://www.freespiritspheres.com/', 'Yes', 'Yes', NULL, 'V9K 1Z7', 'No'),

-- Akasha Farm Retreat Spa
('Akasha Farm Retreat Spa', 'Dome', 'Dome', '1785 Tyson Rd', 'Sechelt', 'BC', 'Canada', 'https://www.facebook.com/akashafarmretreat', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Yes', NULL, 'Farm retreat spa with agritourism operations. Recently expanded to include three geodesic domes and two A-frame cabins, enhancing luxury glamping offerings. Located in Wilson Creek community within Sechelt on Sunshine Coast.', NULL, NULL, 49.5000, NULL, -123.7000, NULL, '12', NULL, NULL, NULL, 'Glamping Resort', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Yes', NULL, 'Yes', 'Yes', NULL, 'Web Research 2025 - British Columbia Focus', 'BC', 'Yes', 'Dome', 'https://www.facebook.com/akashafarmretreat', 'Yes', 'Yes', NULL, 'V0N 3A0', 'No'),

-- Ruby Lake Resort
('Ruby Lake Resort', 'Cabin', 'Cabin', '15426 Sunshine Coast Hwy', 'Madeira Park', 'BC', 'Canada', 'https://rubylakeresort.com/', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Yes', NULL, 'Luxury glamping accommodations and tiny wood cabins near Caren mountain range. Offers activities including hiking, water sports, yoga, and stargazing. Located on Sunshine Coast near Ruby Lake in Madeira Park.', NULL, NULL, 49.712100, NULL, -123.967332, NULL, '12', NULL, NULL, NULL, 'Glamping Resort', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Yes', NULL, 'Yes', 'Yes', 'Yes', 'Cabin', 'Web Research 2025 - British Columbia Focus', 'BC', '2-4', 'Cabin', 'https://rubylakeresort.com/', 'Yes', 'Yes', NULL, 'V0N 2H1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'No');

-- Show summary of the operation
SELECT 
  COUNT(*) as total_properties,
  COUNT(DISTINCT property_name) as unique_properties,
  COUNT(*) FILTER (WHERE manually_reviewed = 'Yes') as manually_reviewed,
  COUNT(*) FILTER (WHERE manually_reviewed = 'No') as not_reviewed
FROM "sage-glamping-data";
