-- Create the sage-updated table
-- Run this SQL in your Supabase SQL Editor before uploading the CSV

CREATE TABLE IF NOT EXISTS "sage-updated" (
  id BIGSERIAL PRIMARY KEY,
  duplicatenote TEXT,
  source TEXT,
  date_added TEXT,
  date_updated TEXT,
  property_name TEXT,
  site_name TEXT,
  unit_type TEXT,
  property_type TEXT,
  property__total_sites NUMERIC,
  quantity_of_units NUMERIC,
  unit_capacity TEXT,
  year_site_opened NUMERIC,
  operating_season__months_ TEXT,
  __of_locations NUMERIC,
  address TEXT,
  city TEXT,
  state TEXT,
  zip_code TEXT,
  country TEXT,
  occupancy_rate_2024 NUMERIC,
  avg__retail_daily_rate_2024 NUMERIC,
  high_rate_2024 NUMERIC,
  low_rate_2024 NUMERIC,
  retail_daily_rate__fees__2024 NUMERIC,
  revpar_2024 NUMERIC,
  occupancy_rate_2025 NUMERIC,
  retail_daily_rate_ytd NUMERIC,
  retail_daily_rate__fees__ytd NUMERIC,
  high_rate_2025 NUMERIC,
  low_rate_2025 NUMERIC,
  revpar_2025 NUMERIC,
  high_month_2025 TEXT,
  high_avg__occupancy_2025 NUMERIC,
  low_month_2025 TEXT,
  low_avg__occupancy_2025 NUMERIC,
  operating_season__excel_format_ TEXT,
  avg__rate__next_12_months_ NUMERIC,
  high_rate__next_12_months_ NUMERIC,
  low_rate__next_12_months_ NUMERIC,
  winter_weekday NUMERIC,
  winter_weekend NUMERIC,
  spring_weekday NUMERIC,
  spring_weekend NUMERIC,
  summer_weekday NUMERIC,
  summer_weekend NUMERIC,
  fall_weekday NUMERIC,
  fall_weekend NUMERIC,
  url TEXT,
  description TEXT,
  minimum_nights TEXT,
  getting_there TEXT,
  lon NUMERIC,
  lat NUMERIC,
  toilet TEXT,
  hot_tub___sauna TEXT,
  pool TEXT,
  pets TEXT,
  water TEXT,
  shower TEXT,
  trash TEXT,
  cooking_equipment TEXT,
  picnic_table TEXT,
  wifi TEXT,
  laundry TEXT,
  campfires TEXT,
  playground TEXT,
  rv___vehicle_length TEXT,
  rv___parking TEXT,
  rv___accommodates_slideout TEXT,
  rv___surface_type TEXT,
  rv___surface_level TEXT,
  rv___vehicles__fifth_wheels TEXT,
  rv___vehicles__class_a_rvs TEXT,
  rv___vehicles__class_b_rvs TEXT,
  rv___vehicles__class_c_rvs TEXT,
  rv___vehicles__toy_hauler TEXT,
  fishing TEXT,
  surfing TEXT,
  horseback_riding TEXT,
  paddling TEXT,
  climbing TEXT,
  off_roading__ohv_ TEXT,
  boating TEXT,
  swimming TEXT,
  wind_sports TEXT,
  snow_sports TEXT,
  whitewater_paddling TEXT,
  fall_fun TEXT,
  hiking TEXT,
  wildlife_watching TEXT,
  biking TEXT,
  ranch TEXT,
  beach TEXT,
  coastal TEXT,
  suburban TEXT,
  forest TEXT,
  field TEXT,
  wetlands TEXT,
  hot_spring TEXT,
  desert TEXT,
  canyon TEXT,
  waterfall TEXT,
  swimming_hole TEXT,
  lake TEXT,
  cave TEXT,
  redwoods TEXT,
  farm TEXT,
  river__stream__or_creek TEXT,
  mountainous TEXT,
  sage___p__amenity__food_on_site TEXT,
  waterfront TEXT,
  restaurant TEXT,
  dog_park TEXT,
  clubhouse TEXT,
  canoeing___kayaking TEXT,
  alcohol_available TEXT,
  golf_cart_rental TEXT,
  private_bathroom TEXT,
  waterpark TEXT,
  kitchen TEXT,
  patio TEXT,
  electricity TEXT,
  general_store TEXT,
  cable TEXT,
  charcoal_grill TEXT,
  sewer_hook_up TEXT,
  electrical_hook_up TEXT,
  generators_allowed TEXT,
  water_hookup TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable Row Level Security (optional)
ALTER TABLE "sage-updated" ENABLE ROW LEVEL SECURITY;

-- Allow public read access (optional)
CREATE POLICY "Allow public read access" ON "sage-updated"
  FOR SELECT
  USING (true);

-- Create index on coordinates for faster map queries
CREATE INDEX IF NOT EXISTS idx_sage_updated_coordinates ON "sage-updated" (lat, lon) WHERE lat IS NOT NULL AND lon IS NOT NULL;

-- Create index on property name for faster searches
CREATE INDEX IF NOT EXISTS idx_sage_updated_property_name ON "sage-updated" (property_name);

-- Create index on city and state for location-based queries
CREATE INDEX IF NOT EXISTS idx_sage_updated_location ON "sage-updated" (city, state);

