#!/usr/bin/env python3
"""
Script to create a CSV file with new glamping properties that aren't in the existing database.
All properties must have 50%+ glamping units and a business website.
"""

import csv
from datetime import datetime

# Column headers from the existing CSV
headers = [
    '# of Locations', '2024 - Fall Weekday', '2024 - Fall Weekend', '2025 - Spring Weekday',
    '2025 - Spring Weekend', '2025 - Summer Weekday', '2025 - Summer Weekend',
    '2025 - Winter Weekday', '2025 - Winter Weekend', 'Address', 'Campfires', 'City',
    'Cooking equipment', 'Country', 'Description', 'Getting there', 'Hot Tub',
    'INTERNAL NOTES ONLY,', 'Latitude', 'Laundry', 'Longitude', 'Occupancy rate 2023',
    'Occupancy rate 2024', 'Operating Season (months)', 'Pets', 'Picnic Table', 'Playground',
    'Property Name', 'Property Type', 'Property: Total Sites', 'Quantity of Units',
    'RV - Accommodates Slideout', 'RV - Parking', 'RV - Surface Type', 'RV - Surface level',
    'RV - Vehicle Length', 'RV - Vehicles: Class A RVs', 'RV - Vehicles: Class B RVs',
    'RV - Vehicles: Class C RVs', 'RV - Vehicles: Fifth Wheels', 'RV - Vehicles: Toy Hauler',
    'RavPAR 2024', 'Retail Daily Rate 2024', 'Retail Daily Rate(+fees) 2024',
    'SGD - P. Amenity: Food On Site', 'SGD - P. Amenity: Hot Tub / Sauna',
    'SGD - P. Amenity: Pool - Indoor', 'SGD - P. Amenity: Pool - Outdoor',
    'SGD - P. Amenity: Restaurant', 'SGD - P. Amenity: Waterfront',
    'SGD - S. Amenity: Private Bathroom', 'Shower', 'Site Name', 'Source', 'State',
    'Toilet', 'Trash', 'Unit Guest Capacity', 'Unit Type', 'Url', 'Water', 'Wifi',
    'Year Site Opened', 'Zip Code', 'Google Delivery', 'Google Dine In',
    'Google Icon Background Color', 'Google Icon URI', 'Google Live Music', 'Google Menu URI',
    'Google Outdoor Seating', 'Google Phone Number', 'Google Photos', 'Google Photos Count',
    'Google Place Types', 'Google Primary Type', 'Google Primary Type Display Name',
    'Google Rating', 'Google Reservable', 'Google Review Count', 'Google Serves Breakfast',
    'Google Serves Brunch', 'Google Serves Dinner', 'Google Serves Lunch', 'Google Takeout',
    'Google Website URI'
]

# New properties data
properties = [
    {
        'Property Name': 'Under Canvas Yosemite',
        'Site Name': 'Safari Tent',
        'Unit Type': 'Safari Tent',
        'Property Type': 'Glamping Resort',
        'Property: Total Sites': '71',
        'Quantity of Units': '71',
        'Unit Guest Capacity': '2-4',
        'Year Site Opened': '2025',
        'Operating Season (months)': '6',
        '# of Locations': '1',
        'Address': 'Big Oak Flat',
        'City': 'Groveland',
        'State': 'CA',
        'Zip Code': '95321',
        'Country': 'USA',
        'Url': 'https://www.undercanvas.com/camps/yosemite/',
        'Description': 'Luxury glamping resort with 71 safari-inspired tents on 80 acres, 10 minutes from Yosemite National Park. Features plush king beds, ensuite bathrooms, private decks, and in-tent heating.',
        'Latitude': '37.8148796',
        'Longitude': '-120.1089988',
        'Wifi': 'Yes',
        'Water': 'Yes',
        'Shower': 'Yes',
        'Toilet': 'Yes',
        'SGD - S. Amenity: Private Bathroom': 'Yes',
        'SGD - P. Amenity: Restaurant': 'Yes',
        'SGD - P. Amenity: Food On Site': 'Yes',
        'Source': 'Web Research 2025',
        'Date Added': datetime.now().strftime('%Y-%m-%d')
    },
    {
        'Property Name': 'Collective Yellowstone',
        'Site Name': 'Luxury Canvas Tent',
        'Unit Type': 'Safari Tent',
        'Property Type': 'Glamping Resort',
        'Property: Total Sites': '',
        'Quantity of Units': '',
        'Unit Guest Capacity': '2',
        'Year Site Opened': '',
        'Operating Season (months)': '4-6',
        '# of Locations': '1',
        'Address': 'Moonlight Basin',
        'City': 'Big Sky',
        'State': 'MT',
        'Zip Code': '59716',
        'Country': 'USA',
        'Url': 'https://www.collectiveretreats.com/retreats/collective-yellowstone/',
        'Description': 'Luxury glamping retreat in Big Sky\'s Moonlight Basin. Canvas tents with plush king beds, wood-burning stoves, and private en suite bathrooms. Situated on a freshwater pond surrounded by mountains.',
        'Latitude': '45.2847',
        'Longitude': '-111.3681',
        'Wifi': 'Yes',
        'Water': 'Yes',
        'Shower': 'Yes',
        'Toilet': 'Yes',
        'SGD - S. Amenity: Private Bathroom': 'Yes',
        'SGD - P. Amenity: Restaurant': 'Yes',
        'SGD - P. Amenity: Food On Site': 'Yes',
        'Campfires': 'Yes',
        'Source': 'Web Research 2025',
        'Date Added': datetime.now().strftime('%Y-%m-%d')
    },
    {
        'Property Name': 'Cedar Bloom Farm',
        'Site Name': 'A-Frame Cabin',
        'Unit Type': 'Cabin',
        'Property Type': 'Glamping Farm',
        'Property: Total Sites': '',
        'Quantity of Units': '',
        'Unit Guest Capacity': '2-4',
        'Year Site Opened': '',
        'Operating Season (months)': '12',
        '# of Locations': '1',
        'Address': '',
        'City': 'Cave Junction',
        'State': 'OR',
        'Zip Code': '97523',
        'Country': 'USA',
        'Url': 'https://www.cedarbloomfarm.com/',
        'Description': 'Glamping farm on 99 acres along the Illinois River. Features hand-built tiny A-frame cabins, geodesic domes, communal kitchen, sauna, and outdoor showers.',
        'Latitude': '42.1629',
        'Longitude': '-123.6481',
        'Wifi': '',
        'Water': 'Yes',
        'Shower': 'Yes',
        'Toilet': 'Yes',
        'Cooking equipment': 'Yes',
        'Source': 'Web Research 2025',
        'Date Added': datetime.now().strftime('%Y-%m-%d')
    },
    {
        'Property Name': 'Clear Sky Resorts',
        'Site Name': 'Sky Dome',
        'Unit Type': 'Dome',
        'Property Type': 'Glamping Resort',
        'Property: Total Sites': '25',
        'Quantity of Units': '25',
        'Unit Guest Capacity': '2-4',
        'Year Site Opened': '2024',
        'Operating Season (months)': '12',
        '# of Locations': '1',
        'Address': 'Scenic Byway 12',
        'City': 'Cannonville',
        'State': 'UT',
        'Zip Code': '84718',
        'Country': 'USA',
        'Url': 'https://brycecanyon.clearskyresorts.com/',
        'Description': 'Luxury glass-domed glamping resort on 80-acre private canyon, 15 minutes from Bryce Canyon National Park. Features 5-star mattresses, luxury linens, private designer bathrooms with rainfall showers, and climate control.',
        'Latitude': '37.5667',
        'Longitude': '-112.0500',
        'Wifi': 'Yes',
        'Water': 'Yes',
        'Shower': 'Yes',
        'Toilet': 'Yes',
        'SGD - S. Amenity: Private Bathroom': 'Yes',
        'SGD - P. Amenity: Restaurant': 'Yes',
        'SGD - P. Amenity: Food On Site': 'Yes',
        'Source': 'Web Research 2025',
        'Date Added': datetime.now().strftime('%Y-%m-%d')
    },
    {
        'Property Name': 'Backland Luxury Camping',
        'Site Name': 'Luxury Tented Suite',
        'Unit Type': 'Safari Tent',
        'Property Type': 'Glamping Resort',
        'Property: Total Sites': '10',
        'Quantity of Units': '10',
        'Unit Guest Capacity': '2',
        'Year Site Opened': '2025',
        'Operating Season (months)': '12',
        '# of Locations': '1',
        'Address': '',
        'City': 'Williams',
        'State': 'AZ',
        'Zip Code': '86046',
        'Country': 'USA',
        'Url': 'https://www.travelbackland.com/',
        'Description': 'Eco-luxury glamping resort on 160 acres at 7,000-foot elevation, surrounded by Kaibab National Forest. Features 10 climate-controlled tented suites with panoramic windows, king beds, full ensuite bathrooms, and private patios. Some suites feature 16-foot-wide skylights for stargazing.',
        'Latitude': '35.2492',
        'Longitude': '-112.1910',
        'Wifi': 'Yes',
        'Water': 'Yes',
        'Shower': 'Yes',
        'Toilet': 'Yes',
        'SGD - S. Amenity: Private Bathroom': 'Yes',
        'SGD - P. Amenity: Restaurant': 'Yes',
        'SGD - P. Amenity: Food On Site': 'Yes',
        'Campfires': 'Yes',
        'Source': 'Web Research 2025',
        'Date Added': datetime.now().strftime('%Y-%m-%d')
    },
    {
        'Property Name': 'Outpost X',
        'Site Name': 'Cave Unit',
        'Unit Type': 'Cave',
        'Property Type': 'Glamping Resort',
        'Property: Total Sites': '',
        'Quantity of Units': '',
        'Unit Guest Capacity': '2-4',
        'Year Site Opened': '',
        'Operating Season (months)': '12',
        '# of Locations': '1',
        'Address': '',
        'City': 'Beryl',
        'State': 'UT',
        'Zip Code': '84714',
        'Country': 'USA',
        'Url': 'https://outpost-x.com/',
        'Description': 'Unique sci-fi themed glamping experience on 100-acre playa. Features cave units, Zen Domes, and Viking Tents. Includes X-Spa with hot tubs, sauna, cold plunge, Cantina, and sand cruisers. Located 30 minutes west of Cedar City, 1.5 hours from Zion National Park.',
        'Latitude': '37.9000',
        'Longitude': '-113.6500',
        'Wifi': '',
        'Water': 'Yes',
        'Shower': 'Yes',
        'Toilet': 'Yes',
        'SGD - P. Amenity: Hot Tub / Sauna': 'Yes',
        'Campfires': 'Yes',
        'Source': 'Web Research 2025',
        'Date Added': datetime.now().strftime('%Y-%m-%d')
    },
    {
        'Property Name': 'North Shore Camping Company',
        'Site Name': 'Furnished Wall Tent',
        'Unit Type': 'Tent',
        'Property Type': 'Glamping Resort',
        'Property: Total Sites': '30',
        'Quantity of Units': '30',
        'Unit Guest Capacity': '2-4',
        'Year Site Opened': '2024',
        'Operating Season (months)': '10',
        '# of Locations': '1',
        'Address': '',
        'City': 'Beaver Bay',
        'State': 'MN',
        'Zip Code': '55601',
        'Country': 'USA',
        'Url': 'https://www.northshorecampingco.com/',
        'Description': 'Glamping experience along the North Shore of Lake Superior. Features 30 furnished wall tents on wooden platforms nestled in forested hills. Includes beds, bedding, cookware, and access to modern bathrooms and showers at Base Lodge.',
        'Latitude': '47.2581',
        'Longitude': '-91.3000',
        'Wifi': '',
        'Water': 'Yes',
        'Shower': 'Yes',
        'Toilet': 'Yes',
        'Cooking equipment': 'Yes',
        'Pets': 'Yes',
        'Source': 'Web Research 2025',
        'Date Added': datetime.now().strftime('%Y-%m-%d')
    },
    {
        'Property Name': 'Camp Sarika at Amangiri',
        'Site Name': 'Tented Pavilion',
        'Unit Type': 'Safari Tent',
        'Property Type': 'Glamping Resort',
        'Property: Total Sites': '10',
        'Quantity of Units': '10',
        'Unit Guest Capacity': '2',
        'Year Site Opened': '',
        'Operating Season (months)': '12',
        '# of Locations': '1',
        'Address': 'Amangiri 1, Kayenta Rd',
        'City': 'Canyon Point',
        'State': 'UT',
        'Zip Code': '84741',
        'Country': 'USA',
        'Url': 'https://www.aman.com/resorts/amangiri/camp-sarika',
        'Description': 'Ultra-luxury tented retreat in Southern Utah desert. Features 10 spacious pavilions with private heated plunge pools, outdoor terraces, and fire pits. Includes main pavilion with restaurant, lounge, swimming pool, and spa suites. Access to guided hikes, via ferrata climbing, and excursions to nearby national parks.',
        'Latitude': '37.0000',
        'Longitude': '-111.5000',
        'Wifi': 'Yes',
        'Water': 'Yes',
        'Shower': 'Yes',
        'Toilet': 'Yes',
        'SGD - S. Amenity: Private Bathroom': 'Yes',
        'SGD - P. Amenity: Restaurant': 'Yes',
        'SGD - P. Amenity: Food On Site': 'Yes',
        'SGD - P. Amenity: Pool - Outdoor': 'Yes',
        'SGD - P. Amenity: Hot Tub / Sauna': 'Yes',
        'Campfires': 'Yes',
        'Source': 'Web Research 2025 - Utah Focus',
        'Date Added': datetime.now().strftime('%Y-%m-%d')
    },
    {
        'Property Name': 'Outdoors Elevated',
        'Site Name': 'Royal Tent',
        'Unit Type': 'Safari Tent',
        'Property Type': 'Glamping Resort',
        'Property: Total Sites': '',
        'Quantity of Units': '',
        'Unit Guest Capacity': '2-8',
        'Year Site Opened': '',
        'Operating Season (months)': '12',
        '# of Locations': '1',
        'Address': '',
        'City': 'Uinta Mountains',
        'State': 'UT',
        'Zip Code': '',
        'Country': 'USA',
        'Url': 'https://theoutdoorselevated.net/',
        'Description': 'Luxury glamping accommodations in the Uinta Mountains. Features Royal and Grand Tents with in-suite bathrooms, accommodating 2-8 guests. Offers Traditional Tents for value-oriented experience. Activities include snowmobile rentals, guided backcountry skiing, zip-line tours, off-road Can-Am tours, and mountain bike tours.',
        'Latitude': '40.7000',
        'Longitude': '-110.8000',
        'Wifi': '',
        'Water': 'Yes',
        'Shower': 'Yes',
        'Toilet': 'Yes',
        'SGD - S. Amenity: Private Bathroom': 'Yes',
        'Source': 'Web Research 2025 - Utah Focus',
        'Date Added': datetime.now().strftime('%Y-%m-%d')
    },
    {
        'Property Name': 'Zen Zion Glamping Domes',
        'Site Name': 'River Dome',
        'Unit Type': 'Dome',
        'Property Type': 'Glamping Resort',
        'Property: Total Sites': '2',
        'Quantity of Units': '2',
        'Unit Guest Capacity': '2',
        'Year Site Opened': '2024',
        'Operating Season (months)': '12',
        '# of Locations': '1',
        'Address': '2200 US-89',
        'City': 'Glendale',
        'State': 'UT',
        'Zip Code': '84729',
        'Country': 'USA',
        'Url': 'https://www.visitzenzion.com/',
        'Description': 'Luxury glamping domes near Zion National Park. Features two geodesic domes (River Dome and Evergreen Dome), each climate-controlled with kitchenette, full bathroom, and private outdoor space with BBQ and fire pit. Virgin River runs through property. Shared pavilion with seating, BBQ, and hot tub. Pet-friendly.',
        'Latitude': '37.3000',
        'Longitude': '-112.6000',
        'Wifi': 'Yes',
        'Water': 'Yes',
        'Shower': 'Yes',
        'Toilet': 'Yes',
        'SGD - S. Amenity: Private Bathroom': 'Yes',
        'SGD - P. Amenity: Hot Tub / Sauna': 'Yes',
        'Cooking equipment': 'Yes',
        'Campfires': 'Yes',
        'Pets': 'Yes',
        'Source': 'Web Research 2025 - Utah Focus',
        'Date Added': datetime.now().strftime('%Y-%m-%d')
    }
]

def create_csv():
    """Create CSV file with new properties"""
    output_file = 'csv/new-properties/new-glamping-properties.csv'
    
    # Create empty row template with all headers
    def create_empty_row():
        return {header: '' for header in headers}
    
    rows = []
    for prop in properties:
        row = create_empty_row()
        # Fill in known fields
        for key, value in prop.items():
            if key in headers:
                row[key] = value
        rows.append(row)
    
    # Write CSV
    with open(output_file, 'w', encoding='utf-8', newline='') as f:
        writer = csv.DictWriter(f, fieldnames=headers)
        writer.writeheader()
        writer.writerows(rows)
    
    print(f'✅ Created CSV file: {output_file}')
    print(f'   Added {len(properties)} new glamping properties')
    print('\nProperties included:')
    for prop in properties:
        print(f'  - {prop["Property Name"]} ({prop.get("City", "N/A")}, {prop.get("State", "N/A")})')

if __name__ == '__main__':
    create_csv()
