/**
 * Generates queries/amenities_tagging_audit.sql — coverage for structured amenity columns.
 */
import { writeFileSync } from 'fs';
import { ALL_GLAMPING_PROPERTY_COLUMNS } from '../lib/sage-ai/all-glamping-properties-columns';

const COHORT_WHERE = `
  WHERE g.is_glamping_property = 'Yes'
    AND g.research_status = 'published'
    AND (g.land_operator_category IS NULL OR g.land_operator_category = 'private_commercial')
    AND g.country IN ('United States', 'US', 'USA', 'United States of America')
    AND g.property_type = 'Glamping'
    AND lower(btrim(coalesce(g.is_open, ''))) = 'yes'
    AND NOT (coalesce(g.unit_type, '') ~* '\\btent\\s*site')
    AND lower(regexp_replace(coalesce(g.unit_type, ''), '\\s+', ' ', 'g'))
        NOT IN ('vehicles', 'vehicle', 'rv site', 'rv sites')`;

const EXCLUDE_COLS = new Set([
  'unit_type',
  'unit_capacity',
  'unit_sq_ft',
  'unit_description',
  'property_total_sites',
  'property_id',
  'property_name',
  'property_type',
  'property_ota_platforms',
  'activities_raw',
  'amenities_raw',
  'lifestyle_raw',
]);

function categorize(col: string): string | null {
  if (EXCLUDE_COLS.has(col)) return null;
  if (col.startsWith('unit_')) return 'unit';
  if (col.startsWith('property_')) return 'property';
  if (col.startsWith('activities_')) return 'activities';
  if (col.startsWith('setting_') || col === 'river_stream_or_creek') return 'setting';
  if (col.startsWith('rv_')) return 'rv';
  return null;
}

const amenityCols = ALL_GLAMPING_PROPERTY_COLUMNS.filter((c) => categorize(c) !== null);

function fieldBlock(col: string, category: string): string {
  return `
  SELECT
    '${col}' AS field,
    '${category}' AS category,
    COUNT(*)::bigint AS total_rows,
    COUNT(*) FILTER (WHERE lower(btrim(coalesce(${col}::text, ''))) IN ('yes', 'y')) AS yes_rows,
    COUNT(*) FILTER (WHERE lower(btrim(coalesce(${col}::text, ''))) IN ('no', 'n')) AS no_rows,
    COUNT(*) FILTER (WHERE lower(btrim(coalesce(${col}::text, ''))) NOT IN ('yes', 'y', 'no', 'n')) AS gap_rows,
    ROUND(
      100.0 * COUNT(*) FILTER (WHERE lower(btrim(coalesce(${col}::text, ''))) IN ('yes', 'y', 'no', 'n'))
      / NULLIF(COUNT(*), 0),
      1
    ) AS pct_explicit
  FROM cohort`;
}

const coverageUnion = amenityCols
  .map((col) => fieldBlock(col, categorize(col)!))
  .join('\nUNION ALL\n');

const sql = `-- =============================================================================
-- Amenities tagging audit — all_glamping_properties structured flags
-- Generated by scripts/generate-amenities-audit-sql.ts
-- Cohort: published US private-commercial open Glamping (excludes tent sites / RV-only unit types)
-- =============================================================================

-- Cohort size
WITH cohort AS (
  SELECT g.*
  FROM all_glamping_properties g
${COHORT_WHERE}
)
SELECT 'cohort_rows' AS metric, COUNT(*)::bigint AS n FROM cohort
UNION ALL SELECT 'cohort_units', SUM(GREATEST(COALESCE(quantity_of_units, 1), 1))::bigint FROM cohort
UNION ALL SELECT 'distinct_properties', COUNT(DISTINCT property_id)::bigint FROM cohort
UNION ALL SELECT 'rated_rows', COUNT(*)::bigint FROM cohort WHERE rate_avg_retail_daily_rate > 0
UNION ALL SELECT 'rated_units',
  SUM(GREATEST(COALESCE(quantity_of_units, 1), 1)) FILTER (WHERE rate_avg_retail_daily_rate > 0)::bigint
FROM cohort;

-- Per-field coverage (ordered by largest gaps first)
WITH cohort AS (
  SELECT g.*
  FROM all_glamping_properties g
${COHORT_WHERE}
),
coverage AS (
${coverageUnion}
)
SELECT * FROM coverage ORDER BY gap_rows DESC, field;

-- Summary by category
WITH cohort AS (
  SELECT g.*
  FROM all_glamping_properties g
${COHORT_WHERE}
),
coverage AS (
${coverageUnion}
)
SELECT
  category,
  COUNT(*) AS fields,
  SUM(gap_rows) AS total_gap_rows,
  ROUND(AVG(pct_explicit), 1) AS avg_pct_explicit,
  MIN(pct_explicit) AS min_pct_explicit,
  COUNT(*) FILTER (WHERE pct_explicit < 50) AS fields_under_50pct,
  COUNT(*) FILTER (WHERE pct_explicit < 25) AS fields_under_25pct
FROM coverage
GROUP BY category
ORDER BY total_gap_rows DESC;

-- Full-table snapshot (all rows, not just cohort)
WITH base AS (
  SELECT * FROM all_glamping_properties
),
coverage AS (
${amenityCols
  .map((col) => fieldBlock(col, categorize(col)!).replace(/FROM cohort/g, 'FROM base'))
  .join('\nUNION ALL\n')}
)
SELECT
  'all_rows' AS scope,
  COUNT(*)::bigint AS table_rows,
  (SELECT COUNT(DISTINCT property_id) FROM base) AS distinct_properties
FROM base;

WITH base AS (
  SELECT * FROM all_glamping_properties
),
coverage AS (
${amenityCols
  .map((col) => fieldBlock(col, categorize(col)!).replace(/FROM cohort/g, 'FROM base'))
  .join('\nUNION ALL\n')}
)
SELECT category,
  ROUND(AVG(pct_explicit), 1) AS avg_pct_explicit,
  COUNT(*) FILTER (WHERE pct_explicit < 50) AS fields_under_50pct
FROM coverage
GROUP BY category
ORDER BY avg_pct_explicit;

-- Raw text fallbacks
SELECT
  COUNT(*) AS cohort_rows,
  COUNT(*) FILTER (WHERE btrim(coalesce(amenities_raw, '')) <> '') AS rows_with_amenities_raw,
  COUNT(*) FILTER (WHERE btrim(coalesce(activities_raw, '')) <> '') AS rows_with_activities_raw,
  COUNT(*) FILTER (WHERE btrim(coalesce(lifestyle_raw, '')) <> '') AS rows_with_lifestyle_raw
FROM all_glamping_properties g
${COHORT_WHERE};
`;

const outPath = 'queries/amenities_tagging_audit.sql';
writeFileSync(outPath, sql);
console.log(`Wrote ${outPath} (${amenityCols.length} amenity columns)`);
