-- Phase 1 A-Frame reclass USA (2026-07-13)
-- discovery_source note tag: a_frame_reclass_us_2026_07_13
-- Canonical: A-Frame

UPDATE public.all_sage_data SET unit_type = 'A-Frame', date_updated = '2026-07-13', notes = COALESCE(notes || E'\n', '') || '[2026-07-13] Phase 1 A-Frame reclass: unit_type Tiny Home → A-Frame (site_name A-Frames; emigrantcabins.com markets A-frame cabins.) [a_frame_reclass_us_2026_07_13]' WHERE id = 9983 AND unit_type IS DISTINCT FROM 'A-Frame';
UPDATE public.all_sage_data SET unit_type = 'A-Frame', date_updated = '2026-07-13', notes = COALESCE(notes || E'\n', '') || '[2026-07-13] Phase 1 A-Frame reclass: unit_type Safari Tent → A-Frame (site_name is A-Frame; Safari Tent label is a misclass.) [a_frame_reclass_us_2026_07_13]' WHERE id = 10259 AND unit_type IS DISTINCT FROM 'A-Frame';
UPDATE public.all_sage_data SET unit_type = 'A-Frame', date_updated = '2026-07-13', notes = COALESCE(notes || E'\n', '') || '[2026-07-13] Phase 1 A-Frame reclass: unit_type Tiny Home → A-Frame (site_name A-Frame Cabins; palomalakela.com markets A-frame cabins.) [a_frame_reclass_us_2026_07_13]' WHERE id = 9965 AND unit_type IS DISTINCT FROM 'A-Frame';
UPDATE public.all_sage_data SET unit_type = 'A-Frame', date_updated = '2026-07-13', notes = COALESCE(notes || E'\n', '') || '[2026-07-13] Phase 1 A-Frame reclass: unit_type Tiny Home → A-Frame (site_name A-Frame; tobaccoriverranch.com lists A-frame lodging.) [a_frame_reclass_us_2026_07_13]' WHERE id = 9984 AND unit_type IS DISTINCT FROM 'A-Frame';
UPDATE public.all_sage_data SET unit_type = 'A-Frame', date_updated = '2026-07-13', notes = COALESCE(notes || E'\n', '') || '[2026-07-13] Phase 1 A-Frame reclass: unit_type Cabin → A-Frame (site_name A-Frames; bisoncreekranch.com markets A-frame cabins.) [a_frame_reclass_us_2026_07_13]' WHERE id = 10480 AND unit_type IS DISTINCT FROM 'A-Frame';
UPDATE public.all_sage_data SET unit_type = 'A-Frame', date_updated = '2026-07-13', notes = COALESCE(notes || E'\n', '') || '[2026-07-13] Phase 1 A-Frame reclass: unit_type Cabin → A-Frame (site_name A-Frame Cabin; cedarbloomfarm.com markets an A-frame cabin.) [a_frame_reclass_us_2026_07_13]' WHERE id = 10879 AND unit_type IS DISTINCT FROM 'A-Frame';
UPDATE public.all_sage_data SET unit_type = 'A-Frame', date_updated = '2026-07-13', notes = COALESCE(notes || E'\n', '') || '[2026-07-13] Phase 1 A-Frame reclass: unit_type Tiny Home → A-Frame (site_name A-Frame Cabin; treetopiacampground.com markets A-frame cabin.) [a_frame_reclass_us_2026_07_13]' WHERE id = 10028 AND unit_type IS DISTINCT FROM 'A-Frame';
